---
title: "Interactive web application"
subtitle: "Visually explore the WPD dataset"
title-block-banner: true
filters:
  - html-shinyui
format:
  html:
    page-layout: full
---

```{r}
#| include: false
library(shiny)
library(htmltools)
```

```{css}
#| echo: false
.callout {
  margin-top: 0;
}
.control-label {
  font-weight: bold;
}
.irs-with-grid {
  margin: 0 20px;
}
```

::: {.column-screen-inset}

::: {.grid}

::: {.g-col-md-3 .g-col-12}
::: {.callout-note icon=false}

## Plot filters

```{r}
#| echo: false
selectizeInput(inputId = "region", label = "Regions", choices = character(), multiple = TRUE, width = "100%")
selectizeInput(inputId = "country", label = "Countries", choices = character(), multiple = TRUE, width = "100%")
selectizeInput(inputId = "type", label = "Type", choices = character(), multiple = TRUE, width = "100%")
```

:::

::: {.callout-note}

## More information

More information about populist parties and candidates can be found in the [country case notes](./notes.html).

:::
:::

::: {.g-col-md-9 .g-col-12}
::: {.panel-tabset}

## Overall populism

```{r}
#| echo: false
selectizeInput(inputId = "indicator", label = "Populism indicator", choices = character(), width = "100%")
plotOutput("plot_overall", height = "100%")
```

## Compare populism

```{r}
#| echo: false
selectizeInput(inputId = "compare", label = "Compare", choices = character(), width = "100%")
plotOutput("plot_compare", height = "100%")
```

## World populism map

```{r}
#| echo: false
sliderInput(inputId = "period", label = "Time period", value = as.Date(c("1980-01-01", "2020-12-31")), min = as.Date("1980-01-01"), max = as.Date("2020-12-31"), timeFormat = "%b %Y%", width = "100%")
plotOutput("plot_map", height = "100%")
```

:::
:::


:::

:::
