---
title: Argentina
subtitle: |-
  Date range: 1983-2020
  <br>
  Argentina suffered a coup by the military that overthrew the Peronist
  government of Isabel Perón and imposed a military dictatorship. The
  first free elections after the coup took place in 1983 and Raul Alfonsín
  became president until 1989, when he was succeeded by Carlos Menem.
  Populism in Argentina is intrinsically linked to "Peronism", the popular
  movement created in the 1940s by historical populist leader Juan Domingo
  Perón and which survives until today. Except for the Intransigent Party,
  all populist leaders included in the dataset are Peronists.
title-block-banner: yes

---

# Case notes

## Carlos Menem

Carlos Menem is a complicated figure. Most authors agree that he won the
1989 election running a campaign based on the traditional Peronist
discourse articulated around the concepts of "salariazo" and "the
revolution of production" (Burdman, 2008: 10). His platform promised
"welfare state, protection and development of national industry,
nationalization of public services, state regulation and intervention in
the economy, regulation of the financial market, import substitution and
redistribution of income in favor of workers" (*Diario Digital
Conclusión* n.d.) (LRPOSITION = L).

Burdman clearly identifies Menem's platform as populist (Burdman 2008,
8) and Hawkins and Rovira Kaltwasser (2017) argue that his 1989 campaign
indeed showed a Manichean division between the elite and the people. In
this victory speech, for instance, Menem proclaimed his was the victory
of the

> "heroic march of national unity to be protagonist of a historic battle
> that all Argentinians must undertake \... against privileges, against
> vested interests, against speculators and usurers, against those who
> seek that nothing changes so that misery, underdevelopment, poverty
> and hunger continue in the Argentinian Republic" (Menem, 1989b).

Menem also proclaimed that "my only compromise is to achieve the
happiness of the Argentinian people and the greatness of the fatherland"
and cautioned against "playing the game of the vote-grabbing politicians
who do not understand the country" (Menem, 1989a)On this basis, we've
coded his 1989 campaign 3 on OTH_POLCLASS.

Although his platform was clearly leftist and that implied a threat to
big businesses (Fair 2008, 113), in his discourse he emphasised national
unity of all social actors, including businesses: "To every worker, to
every young person, *to every businessman*, to every woman, to every
pensioner, to every soldier, to every child, I say: there is a vacant
place from which to build the future" (Burdman 2008, 14). He also
emphasized the value of property, of hard work and of economic
efficiency that his "Productive revolution" would bring about (Burdman
2008, 12). We have, thus, not found significant evidence that businesses
were seen as an intrinsic part of the elite (OTH_ECONOMIC = 1).

Fair (2011: 2) argues that Menem initiated a timid dialogue with the
military, stressed the need for peace and hinted that he would pardon
the military for the sentences they received for their crimes during the
dictatorship. He later fulfilled this promise. Thus, this group was not
recognised as a main elite opponent (OTH_MILITARY = 1). Burdam (2008:
13) argues that although Menem stressed the need to achieve economic
independence this did not meant, as it did with Perón, freedom from the
dependence vis-à-vis the UK, but simply the modernization of the economy
and the level of production, without addressing who owns the capital.
Borgani (2006, 5) describes the purpose of Menem's foreign policy was
"to improve economic relations with Europe and the United States and to
achieve Argentina\'s economic reinsertion in the world" (OTH_FOREIGN =
1).

Menem rejected accusations of totalitarianism and stressed his
commitment to democracy by arguing that his party, as opposed to the
Radical Party, was the only one holding primary elections to select
their candidate (Menem, 1989a). He claimed that "if there is a
democratic party, a democratic movement, one which respects human rights
and all the liberties, that has been a victim of all forms of violences,
a permanent victim, imprisoned and persecuted and yet holds no grudges
and no hate and aims at national unity, that is the Justicialist Party"
(Menem, 1989a) (LIBDEMNORMS = 1).

Menem had immigrant origins himself. His parents came from Siria, and he
practiced Islam until he decided to convert to Catholicism in his youth.
In fact, during his government, he abolished the legal requirement for
all presidents to profess the Catholic religion to be able to be elected
(Levit 2016). We have found no evidence of a position against immigrants
or ethnic others (OTH_ETHNIC, OTH_IMMIGRANTS = 1).

Carlos Menem had been governor of the province of La Rioja before the
military dictatorship and again throughout the 80's. However, he never
participated in the national government and the Justicialist party only
achieved power again with his government (INC_PARL, INC_PRES, INSIDER =
1). A the leader of the historic Justicialist Party, he nevertheless is
considered charismatic by the scholars that studied him (Burdman 2008)
(CHARISMA = 2).

However, once in government, Menem quickly shifted his economic
discourse and embraced neoliberal policies devoted to control inflation.
This fact has sparked the academic debate on Menem's populism in
government and constitutes a difficult case for our dataset. For those
authors who defend a more substantive definition of populism (Hawkins
and Rovira Kaltwasser, 2017; Levitsky, 2003) Menem should not be
considered populist after 1989. For these authors, neoliberal policies
are considered to be opposed to populism and Menem is portrayed as
betraying his previous populist stance. For authors that define populism
based organizational factors such as personalism, a direct connection
with the people, concentration of power and transgressing liberal
political norms and less on substantive elements (Weyland, 2003: 6,
1996; Wehner, 2004), neoliberalism and populism have a number of
synergies. These include low levels of institutionalization, targeting
unorganized poor, distancing themselves from unions, professional
organizations and business groups and the use of the state to push
through reform against opposition (Weyland, 2003: 2-3). Leaman (1999),
for example, defined Menem as the prime example of "populist
liberalism".

By contrast to these two positions, our definition of populism stresses
discursive distinction between the elite and the people. In this regard,
during Menem's tenure, the elite/people distinction was significantly
blurred. In their analysis of populist discourses, for instance, Hawkins
and Rovira Kaltwasser (2017) find little Manichean discourse between the
elite and the people in his 1995 campaign. Moreover, while Burdam
identified Menem as populist in 1989, by 1995, he argued that

> The antinomies of class (workers-employers), nationalist (national
> autonomy-foreign intervention) and populist (people-power
> bloc-oligarchy) are thus eliminated. There must remain, then, an
> opposition that separates the totality (the community as a whole) from
> an impersonal outside, whose threat is not linked to a concrete enemy,
> but to the potential shortcomings of the community itself. Thus, the
> danger does not lie in the possibility of defeat before an
> antagonistic force that opposes one\'s own identity, but in losing the
> mystique, energy and mobility that will allow national construction.
> (Burdman 2008, 16)

Burdman's interpretation is in line with that of Weyland and Wehner in
arguing that Menem inherited certain stylistic elements of its original
populist discourse when presenting itself as a courageous leader that
attacked the crisis head-on and thus deliver the country from
hyperinflation demonstrating and reinforced his charisma (Weyland, 2003:
4). This author argues that "when the country confronted a deep open
crisis and neoliberals prescribed the shock therapy of drastic market
reform, they relied on the boldness and transgressive tendencies of
neo-populist leaders to carry out this plan of action" (Weyland 2003:
5). Moreover, it was this boldness in the initial crisis what may
explain their downfall as inflation lost importance compared to
unemployment and growth, areas where neoliberal policies fare less well
(Weyland 2003; Wehner, 2004). Wehner (2004: 41) attributes Menem's 1995
reelection to the relatively good results of his neoliberal economic
policies. High inflation had been huge problem during Alfonsín's
government and, although poverty and employment did not improve, Menem's
ability to control inflation was rewarded by the Argentinian voters
(Wehner, 2004: 46). Therefore, being the head of the government,
criticism of the political class was circumscribed to criticising the
inefficiency of parliamentarians in approving the bold reforms that the
country needed (Leaman 1999, 101).

Regarding other types of elites beyond the political class, we also do
not find a strong opposition between ordinary people and an estranged
elite. In government, he had proclaimed an amnesty to military leaders
involved in the dictatorship and promoted close relationships with the
USA in what was known as "relaciones carnales" through, for example,
participating in the invasion OF Kuwait (Botta, 2012: 157). Moreover,
his neoliberal economic discourse became centred around the idea of
"economic stability" and the need to reassure investors to participate
in the Argentina economy (Leaman 1999, 17). Thus, given his lack of
Manichean distinction between any kind of elite and people and his more
pluralist understanding of politics in government, we have ruled against
including Menem in the dataset beyond the 1989 elections.

## Néstor Kirchner, Cristina Fernández de Kirchner, Alberto Fernández

In 2001, Argentina suffered a very strong economic and political crisis
provoked by the "corralito" (which severely restricted people\'s ability
to withdraw cash from banks). Widespread anger against the political
system was summed in the motto \"All of them must go!\" ("¡Que se vayan
todos!") which was widely cried out in rallies, demonstrations and
became a nation-wide saying (Holloway 2002). The election of Néstor
Kirchner in 2003 as president of Argentina can be seen as the political
outcome of that crisis. Néstor ran a campaign based on an opposition to
the "old political class" and the "Fatherland's enemies" (Padoan, 2017:
533; Fernández, 2010: 205). He argued for a radical change in the
political system, the retrieval of the traditional Peronists goals of
"Economic Independency", "Political Sovereignty" and "Social Justice"
(Padoan, 2017: 533) and criticized the Peronists of the 1990s for not
delivering their promises and betraying Perón (Kirchner, 2003)
(OTH_POLCLASS = 3). Néstor condemned harshly the human rights abuses of
the military dictatorship and the presidents before him for not
prosecuting their crimes. Thus, once in government, he revoked the "Law
of Due Obedience" and the "Full Stop law" and renewed the military
leadership because the previous one was seen as part of the
establishment (Fernández, 2010: 202) (OTH_MILITARY = 3).

Economically, Néstor argued forcefully against the neoliberal reforms
that Menem had implemented in the previous decade. Kirchner proclaimed
the need to rethink the economic system and, in his investment speech,
talked about constructing a "National capitalism" (Kirchner, 2003b;
Padoan, 2017: 533). The central issue in his economic and international
policies was the payment of Argentina's debt. Argentina had accrued a
huge debt problem and Néstor's solution consisted mainly on
restructuring it. He famously proclaimed that "the creditors have to
understand that they will only get paid if Argentina performs well"
(Kirchner, 2003b; Fernández, 2010: 206). He managed to restructure 76%
of the debt in 2005 and then his wife and successor Cristina de Kirchner
did it again in 2010 up to 92% (Fernández de Kirchner, 2014). The main
construction of a foreign enemy was done precisely on this point.
Kirchnerism focuses less on attacks on specific foreign others but calls
into question the whole international economic system that promotes
neoliberal policies. Therefore, their attacks are mainly directed
towards international economic institutions such as the IMF and against
the financial elite (both national and international) who is blamed for
pressuring in favor of policies that damage "the people" (Fernández,
2010). In Cristina's presidency this opposition to foreign intervention
was exemplified by the conflict over US judge Thomas Griesa' decision
over the payment of the debt to creditors (OTH_FOREIGN = 3). Due to the
Kirchner's opposition to neo-liberal economic policy and advocacy of
"national capitalism" as its alternative, we've coded them L on
LRPOSITION.

There is no important ethnic other for Kirchnerism and immigrants have
not been identified as the enemy of the people (OTH_ETHNIC = 1,
OTH_IMMIGRANTS = 1). In fact, Cristina has had a welcoming stance
towards immigration (Irigaray, 2014).

Néstor Kirchner was an unknown governor of a province when, in 2003, he
launched his campaign (INSIDER = 1). He was endorsed by exiting
president Eduardo Duhalde, in a move to stop Carlos Menem, who was
running again for the presidency, from winning. He started with a 6%
share in the polls and ended with a 22%. The personality cult around
Kirchner should not be discarded and "Kirchnerism" became the name for
the specific branch of populism developed by Néstor and Cristina.
Moreover, Kirchner won the election with a party coalition (Front for
Victory) and later constructed its party support not just from the
traditional Justicialist Party, but from a very diverse mix of groups,
governors and people from different ideologies. The only unifying figure
of this coalition was Néstor Kirchner himself (Schurman, 2006). Thus, we
have coded CHARISMA 1 for the first election and 2 for the rest.

In the 2007 elections, Néstor Kirchner did not seek re-election and
instead the Front for Victory presented Néstor's wife Cristina Fernández
de Kirchner. Although she held no position in government, since Cristina
was Néstor's wife, a member of the Senate before her 2007 campaign and
participated actively in her husband's political decisions, she can be
considered as belonging to the "inner-circle" of power before running in
2007. Therefore, we have coded her as a 2 on INSIDER. She ruled for two
mandates but could not run for a third in 2015. The Front for Victory
chose David Scioli as its candidate. Scioli had been vice-president
during Néstor's government and governor of the province of Buenos Aires.
Scioli's campaign and personal position as Vice-president, although not
identical, can be considered largely as a continuation of Cristina's
Kirchnerism and his campaign was read as such by the population (Smink,
2015) (INSIDER = 2, CHARISMA = 1).

Scioli lost the election to Mauricio Macri and between 2015 and 2019 the
Peronists were deeply divided into several factions. They were able to
regroup all factions by the 2019 elections under the coalition "Front
for all". In this occasion, Cristina Fernández de Kirchner would run as
vice-president and Alberto Fernández as president. Alberto had been
Chief of the Cabinet of Ministers with both Néstor Kirchner and with
Cristina but resigned in 2008 and since then became a fierce critic of
Cristina's government. He spent nearly 10 years active on the media and
intervening in some minor campaigns until the renewal of the
relationships in time for the 2019 election (Ortiz de Zárate 2019)
(INSIDER = 2). The Front for All also included the "Renewal Front", a
party led by Sergio Massa who also had been part of Cristina's
government but later became a critic and ran on his own platform in
2015. Massa would later become the Peronist candidate in the 2023
elections.

## The Intransigent Party

The Intransigent Party (Partido Instransigente, PI) was a branch of the
Radical Civic Union created and led by Oscar Alende, "a charismatic
ex-governor of Buenos Aires province, the PI was moving somewhat closer
to the Peronists as the second force in Argentina" (Ranis 1986, 31). The
PI has been described as "offering a coherent critique on the \"populist
left\" (Ranis 1986, 31) and obtained its best result in the legislative
elections of 1985. As its foundational document states, their principles
are "popular participation, economic nationalism, social justice and
Latin American integration" (Intransigent Party, 1975: 30). They argued
in favor of an anti-imperialist revolution that would transform
capitalism and liberate the people (Intransigent Party, 1975: 37).
Ferrari describes their platform in the following way:

> In the economic sphere, it postulated \"to wrest the factors of real
> power from the hands of the dominant minorities, with rigorous
> planning of the use of natural and financial resources\" according to
> national objectives and not those of the international monopolies or
> the native oligarchies. In this sense, it encouraged the dissociation
> of the financial system from the foreign exchange market, the
> nationalization of foreign trade, the implementation of a financial
> policy favorable to economic growth and the socialization of wealth
> -with nationalization of the banking system and credit orientation-,
> the reorganization of the public sector, the refinancing of the
> foreign debt and a moratorium, the reduction of inflation and the
> elimination of indexation. This meant transforming the State,
> democratizing economic power towards growth and the defense of popular
> interests. It proposed a free, just and strengthened society, sized on
> a human scale, which would make possible the self-realization of each
> individual. It was anti-oligarchic and anti-imperialist. (Ferrari
> 2017, 27)

We believe these merits a 3 for OTH_POLCLASS, OTH_FINANCIAL,
OTH_FOREIGN.

Although the leftist stance of the party is clear from the previous
description, other sources describe it in more moderate terms: "The PI
emerged as a serious third party with a clearly articulated left-center
platform" (Ranis 1986, 33). Thus, we have decided to code the party as L
in LRPOSITION to reflect a middle point between these positions.

The party also ran on a platform that was very critical with the
military dictatorship and defended democratic participation. According
to one scholar, they proposed to "dismantle the repressive apparatus and
promote unrestricted respect for human rights, promote institutional
forms that ensure popular participation and control (recall of mandates,
right of initiative, popular veto, plebiscite, referendum)" (Ferrari
2017, 27) (MILITARY = 3, LIBDEMNORMS = 1).

The party was created in 1972 and led by Oscar Alende, who had been
governor of Buenos Aires between 1958 and 1962 but did not held any
position of power during the dictatorship (INSIDER = 1, CHARISMA = 3).

## Not included 

Front for a Country in Solidarity (*Frente País Solidario*, FrePaSo) was
a coalition of parties that included Peronists that were critical of
Menem, Frente Grande, the Communist party, the Intransigent party and
Christian democrats. The party obtained good results in 1995 in both the
legislative and the presidential elections. Bordon's rhetoric stressed
the need for a "serious and responsible" political proposal based on the
"work culture" and promised "honesty, austerity and capacity to
recognize when I make a mistake" (Neustadt, 1995). The presidential
candidate abandoned the party the following year. Koessl (2009) argues
that FrePaSo's success was due to the internal problems of the UCR,
Menem's neoliberal policies and the pact between these parties ("Pacto
de Olivos") which gave the impression that there was no political
opposition to the bipartisan system. It is precisely this image as a
political alternative what explains its success but the party's
rhetoric, particularly that of its leader, is difficult to classify as
populist. Thus, we have not added the party in the list.

**References**

Borgani, Clarisa Beatriz. 2006. 'El "discurso de la soberanía" ante un
nuevo proyecto de Estado: el caso de las Islas Malvinas (1989-1995)'. In
. http://sedici.unlp.edu.ar/handle/10915/37428.

Burdman, Javier. 2008. 'La rearticulación identitaria del peronismo a
partir del discurso de Carlos Menem'. *Memoria y Sociedad* 12 (25):
7--20.

*Diario Digital Conclusión*. n.d. 'Carlos Menem: de la revolución
productiva y el salariazo al desguace del Estado y la década
neoliberal', sec. Nacional. Accessed 20 September 2023.
https://www.conclusion.com.ar/politica/carlos-menem-de-la-revolucion-productiva-y-el-salariazo-al-desguace-del-estado-y-la-decada-neoliberal/02/2021/.

Fair, Hernán. 2008. 'El Rol Del Plan de Convertibilidad En La
Articulación de Los Grandes Grupos Empresariales: Un Estudio de Caso Del
Primer Gobierno de Menem'. *Documentos y Aportes En Administración
Pública y Gestión Estatal*, no. 10 (June): 111--56.

Ferrari, Marcela Patricia. 2017. 'La política frentista del peronismo
renovador durante los años ochenta. Las coaliciones con la
centroizquierda'. *Cuadernos del CLAEH* 36 (1): 11--35.
https://doi.org/10.29192/CLAEH.36.1.1.

Holloway, John. 2002. '¡Que Se Vayan Todos!' *Studies in Political
Economy* 69 (1): 157--66.
https://doi.org/10.1080/19187033.2002.11675184.

Leaman, David E. 1999. 'Populist Liberalism as Dominant Ideology:
Competing Ideas and Democracy in Post-Authoritarian Argentina,
1989--1995'. *Studies in Comparative International Development* 34 (3):
98--118. https://doi.org/10.1007/BF02687629.

Levit, Jorge. 2016. 'Religión y Estado: incompatibles'. La Capital. 18
June 2016.
https://www.lacapital.com.ar/opinion/religion-y-estado-incompatibles-n966447.html.

Ortiz de Zárate, Roberto. 2019. 'Biografías Líderes Políticos: Alberto
Fernández'. CIDOB. 1 July 2019.
https://www.cidob.org/biografias_lideres_politicos/america_del_sur/argentina/alberto_fernandez.

Ranis, Peter. 1986. 'The Dilemmas of Democratization in Argentina'.
*Current History* 85 (507): 29--42.

Botta, Paulo (2012) "Argentina e Irán entre 1989 y 1999: Entre las
sombras de los atentados terroristas y el cambio de política exterior
argentina", Araucaria. Revista Iberoamericana de Filosofía, Política y
Humanidades, Vol. 14 (28), pp. 155--178.

Burdam, Javier (2008) "La rearticulación identitaria del peronismo a
partir del discurso de Carlos Menem. Una perspectiva desde los enfoques
de Ernesto Laclau y Slavoj Zizek", Memoria y Sociedad, Vol. 12 (25), pp.
7-20.

Fair, Hernan (2011) "Las relaciones políticas entre el menemismo y las
Fuerzas Armadas. Un análisis histórico-político del período 1989-1995",
Kairos: Revista de temas sociales, Year 15, Vol, 27, May, pp. 1-16.

Fernández Alonso, José Marcelino (2010) "La política hacia las
inversiones extranjeras del gobierno de Néstor Kirchner: tras los rasgos
de un populismo atemperado", Sociedade e Cultura, Vol. 13 (2).

Fernández de Kirchner, Cristina (2014) "Presidential Speech", 19 August:
https://www.youtube.com/watch?v=EYuaPxW5M_I

Hall, Stuart and Martin Jacques (eds.) (1983) The Politics of
Thatcherism (PT), London.

Hawkins, K. A., & Rovira Kaltwasser, C. (2017) "The Ideational Approach
to Populism", Latin American Research Review, 52(4), 513--528.

Intransigent Party (1975) "Aportes Para el Proyecto Nacional", Internal
document.

Irigaray, Juan Ignacio (2014) "Argentina abre las puertas a los
inmigrantes" El Mundo, 16 September:
https://www.elmundo.es/internacional/2014/09/16/541879f5e2704ecf318b459a.html

Kirchner (2003b) "Inaugural Speech", 25 May 2003:
https://www.youtube.com/watch?v=1Zao4M3qXvw

Kirchner, (2003a) "Campaign rally in River Plate", 2 April 2003:
https://www.youtube.com/watch?v=ZZp328XBFxA

Koessl (2009) "Apogeo y derrumbe del FrePaSo. Algunas consideraciones",
Revista del CESLA, Vol. 12, pp. 99-116, July.

Levitsky, Steven. 2003. Transforming Labor-Based Parties in Latin
America: Argentine Peronism in Comparative Perspective. Cambridge:
Cambridge University Press.

Memem, Carlos (1989b) "Menem habla desde el balcón de la Casa Rosada en
1989 (parte I)", Archivo histórico RTA S.E.:
https://www.youtube.com/watch?v=aobgltxzE4w

Menem, Carlos (1989a) "La campaña electoral del PJ y de la UCR, 1989"
Archivo histórico RTA S.E.: https://www.youtube.com/watch?v=v1O16Pcel-4

Neustadt, Bernardo (1995) "Interview with Jose Octavio Bordon":
https://www.youtube.com/watch?v=cka5JbZRsS4

Padoan, Enrico (2017) "The Populist Re-Politicization: Some Lessons from
South America and Southern Europe", The Open Journal of Sociopolitical
Studies, Vol. 10 (2).

Shurman Diego (2006) "Guía práctica para entender la nebulosa del
kirchnerismo" Página 12, 12 February:
https://www.pagina12.com.ar/diario/elpais/1-62987-2006-02-12.html

Smink, Veronica (2015) "Daniel Scioli: el candidato atrapado entre el
kirchnerismo y la autonomía" 20 November:
https://www.bbc.com/mundo/noticias/2015/11/151118_elecciones_argentina_daniel_scioli_vs

Wehner, Leslie (2004) "El neo-populismo de Menem y Fujimori: desde la
primera campaña electoral hasta la reelección", Revista Enfoques, Vol.
2.

Weyland, Kurt (1996) "Neopopulism and Neoliberalism in Latin America:
Unexpected Affinities." Studies in Comparative International Development
(SCID) 31(3): 3--31

Weyland, Kurt (2003) "Neopopulism and Neoliberalism in Latin America:
How Much Affinity?" Paper for Panel on Neopopulism in Latin America:
Conceptual and Theoretical Issues. XXIV International Congress, Latin
American Studies Association. Dallas, TX, 27-29 March.
