---
title: Chile
subtitle: |-
  Date range: 1989-2020.
  <br>
  Chile suffered a military dictatorship at the hands of General Augusto
  Pinochet from 1973 until 1990. In 1988 a referendum was held on whether
  to continue with Pinochet's dictatorship, which was won by the NO. The
  first democratic elections were held in 1989 and Patrio Aylwin, a
  center-left Christian Democrat, became president. Chile has
  traditionally been considered an exception to the succession of populist
  leaders in other Latin American countries. As Drake (1999: 72) argues,
  "populism did not disrupt the transition to democracy or occupy center
  stage". "Centrist and leftist politicians did not want populism to upset
  the new democracy any more than they wanted to disturb macroeconomic
  equilibrium" (Drake, 1999: 72). Thus, none of the big coalition of
  Chilean parties is considered populist by most scholars. However,
  although no populist leader has held the presidency since 1990, there
  are a number of less successful candidates that should be included in
  that category.
title-block-banner: yes

---

# Case notes

## Francisco Javier Errázuriz

Along with the candidates of the right and left, Francisco Javier
Errázuriz, a wealthy businessman that came from a highly influential
family in Chile, claimed to represent the "centre-centre" of politics in
the 1989 presidential election (Drake, 1999: 73). The movement was a
surprise at the time and, not being backed by any party, and he won 15%
of the vote.

Errázuriz appealed an antiparty undercurrent based on "vaguely
nationalistic, reformist, anticorruption, antipolitician platform aimed
at broad segments of the middle classes and unorganized workers" (Drake,
1999: 73). His platform was based on praising the free-market system and
promising social justice (Drake, 1999: 73). He put himself, a wealthy
businessman, as an example of an accomplished life and claimed to be
able to show Chileans the way to the same wealth and wellbeing
(Errázuriz, 1989a). We have coded him 1 for OTH_FOREIGN and
OTH_FINANCIAL.

Errázuriz's discourse, although anti-politician, was conciliatory. He
argued against the polarization of society in two blocks: "do not divide
the country in two sides... we need unity" (Errázuriz, 1989a) and he
claimed that he did not call voters to vote against anybody (Errázuriz,
1989b). He claimed that one of the biggest challenges facing Chile was
the aggressive opposition of the left and right of the country
(LRPOSITION = C). Thus, his criticism of political elites came from a
centre-liberal position that aimed to mobilise the people against the
current state of divisive politics used by politicians (OTH_POLCLASS =
2).

Although he has been later involved in several cases of corruption,
there is nothing in his 1989 campaign that indicates a violation of
liberal democratic norms. In fact, he criticised the violation of human
rights and argued for the protection of civil liberties (Francisco
Errazuriz - Spot de campaña elecciones en Chile 1989 1989) (LIBDEMNORMS
= 1). However, his aim to leave the past behind also means that he did
not condemn the military dictatorship, nor it consider it part of the
establishment (OTH_MILITARY = 1). We have not been able to find any
negative references to either immigrants or ethnic others (OTH_ETHNIC
and OTH_IMMIGRANT = 1). Before running for president, Errázuriz held no
political position and was not involved with any party (INSIDER = 1).
His campaign had been described as a "personalistic effort" (Drake 2012,
81) because it was purely based on his personal figure as a successful
businessman and a man outside of politics (CHARISMA = 3).

## Joaquín Lavín

The Independent Democratic Union (*Unión Demócrata Independiente*, UDI)
was founded in 1982 as one of the parties that defended the military
dictatorship. The party was "inspired by Spanish Franquismo corporatism"
and "its founding leader, Jaime Guzmán, was the political ideologue of
the authoritarian regime" (Luna et al. 2013: 923). The UDI "was born in
the midst of neo-conservatism, and in the context of a conservative turn
within the Catholic Church" (Luna et al. 2013: 929). Moreover, the party
"developed close ties with business interests which partially explains
its electoral performance since 1989 in the upper sectors of the Chilean
society and its financial campaign advantages" (Luna et al. 2013: 924)
but also aimed at attracting the poorer sections of society through the
financing of specific programs targeted to the poor (Luna, 2010: 326).
As a defender of the military establishment and Pinochet's legacy, the
party cannot be considered populist in its first elections. Scholars
agree that it is Joaquin Lavin's leadership which introduces an
"anti-politics discourse" in its campaigns (Silva, 2001; Luna, 2010;
Luna et al. 2013; Cortés and Pelfini, 2017).

Joaquin Lavin's professional evolution follows that of other "Chicago
boys", a group of Chilean economists that studied at the University of
Chicago and then applied their neoliberal policies during the Pinochet
dictatorship (Silva 1991, 368). Lavin studied at Chicago, became dean of
School of Economics at a Chilean University, participated in Pinochet's
administration, became secretary general of the UDI from 1990 to 1994
and acted as mayor of a municipality in the 90s. He did not, however,
participate in the inner circle of Pinochet's government (INSIDER = 1).
The UDI was very much attached to Pinochet's legacy but his arrest in
London in 1988 introduced a change in the political discourse of the
party, which praised the dictatorship less from that point on (Silva,
2001: 28) and crafted a more moderated image for itself (Luna, 2010:
346). The crisis and several cases of corruption in the previous
government gave way to Lavin's anti-political and neo-populist strategy
"expressed in his abhorrence of politics and political parties, and his
inclination to \'technify\' social problems and their solutions" (Silva,
2001: 33). He claimed to be concentrating on the real problems of the
people by addressing particular issues instead crafting large plans and
promised "more action and less politics" (Silva 2001, 33). The party
self-proclaimed itself as the "popular party" in order to enhance its
identification with the people and it proclaimed to overcome the
left-right divide (Cortés and Pelfini, 2017: 67). We have coded 3
OTH_POLCLASS, 1 for OTH_FINANCIAL and 1 for OTH_FOREIGN, and 2 for
CHARISMA since it was Lavin who introduced the novel anti-politics
discourse to an already established party. Without him, the party would
have continued to exist, but it would not have taken its populist
stance.

Neither immigration nor indigenous communities were a central element in
Lavin's campaign, and he has shown itself to be in favor of a better
recognition for the Mapuches (Emol, 2013) and for a regulated open
immigration policy (OTH_IMMIGRANTS = 1, OTH_ETHNIC = 1). I have not
found any indication of Violation of liberal democratic norms. In fact,
when he lost the election, he stood in the balcony of the winner,
Ricardo Lagos, as a way of signaling his commitment to collaborate with
the new government in a friendly manner (Silva, 2001: 35).

Luna et al. (2013) point out that Lavin's candidacy implied a disrupture
in UDI's traditional politics. This disrupture did not continue after
Lavín's failed bids for president. In 2009, the leader of the Alliance
for Chile, was the candidate from the National Renovation, Sebastián
Piñera. In 2013, Evelyn Matthei, a former minister under Piñera's
government and member of UDI, was the candidate of the alliance and
again in 2017 Piñera was presented as the candidate for the right-wing
coalition. Both have explicitly rejected populist rhetoric (Emol, 2013b;
Romainville, 2018) and they are not treated as populist in the
scholarship. Moreover, it is not clear at what point the party did
change its position to a populist one under Lavín. It is perfectly
possible to consider Lavín's anti-political discourse exclusive of the
leader and not of the party. However, considering Lavín's role as the
leader of the party as the leader of the opposition for several years,
we have decided to leave the UDI in the dataset for the 2001 and 2005
legislative elections. However, we have not added the party before or
after Lavín's period.

## Marco Enríquez-Ominami

Marco Enríquez-Ominami, or MEO as he is commonly known, is the son of a
guerrilla warrior killed by the military dictatorship (Prados 2015) and
step-son of a historic leader of the Socialist Party (Schuster y Osorio
2010, 101). His family was forced into exile and when he went back to
Chile, he became known as a TV host and as a movie director. He became a
member of parliament in 2005 for the Socialist Party, which was ruling
at the time. In 2009, the left-wing electoral alliance denied the
possibility of holding primary elections and instead chose former
president Eduardo Frei as their candidate (BCN 2020). Enríquez-Ominami
decided then to run for the presidency as an independent candidate,
where he polled in third place with 20.14%. He had no previous
governmental experience (INSIDER = 1, INC_PARL = 1, INC_PRES = 1). He
later created his own party (The Progressive Party) and ran again three
more times in 2013, 2017 and 2021, although less successfully. The
campaign of MEO was personalist, mediatic, with a strong emotional
speech, based on the closeness to the people and facing its other
contenders whom it identified as \"figures of the past\" (Dosek and
Freidenberg, 2014: 22) (Bunker y Navia 2013, 15) (CHARISMA = 3).

He wished to distance himself from the old political elite, which he
considered that had "kidnapped politics and did not offer a change for
Chile" (Dosek and Freidenberg, 2014: 23). He denounced that millions of
Chileans were "outside of the political process" and campaign to end
that situation (Enríquez-Ominami, 2009). In 2013 he coauthored a book
titled "The economy is not the problem, power is" in which he criticised
the "duopolistic Chile", in reference to the two big parties at the time
(Gumucio Rivas y Enríquez-Ominami 2013, 10). He also stated that "turned
into mafias, political parties care little about triumphing with a
minority of votes cast; they are incapable of understanding abstention
as a form of rejection of the prevailing system" because political
partied had become "feudal oligarchies" (Gumucio Rivas y
Enríquez-Ominami 2013, 13) (OTH_POLCLASS = 3).

MEO ran on a left-wing platform, based on critiquing neoliberal
policies, promising free public education and an increase of the minimum
salary (Manifesto, 2009) but his platform was not radical. He wished to
"raise corporate taxes but lower the income tax" and he "also expressed
an openness to having the state divest itself of a small stake of its
copper Company" (Moffett and Pica, 2009) (Bunker y Navia 2013, 15).
Thus, his main target was the political class but not the economic elite
(LRPOSITION = L, OTH_FINANCIAL = 1). We have also found evidence of
criticism to international institutions when he argued, for instance,
that "Europe\'s old parliamentary democracies have lost sovereignty
\[...\] to the tyrannical rule of the International Monetary Fund, the
World Bank and the European Bank. It matters little the political sign
of the parliamentary majorities, whether they are social-democratic or
right-wing: they all play the same music contained in the Troika\'s
pentagram." (Gumucio Rivas y Enríquez-Ominami 2013, 12) but we have
found little evidence that this was one of his main elements of
campaign, which was centred on criticisng political elites and proposing
political reforms. Thus, we have coded OTH_FOREIGN as 2.

Enríquez-Ominami had a favorable position towards immigration and
indigenous communities in Chile, arguing that "a great deal of the
history of Chile is written together with Mapuches and immigrants" (CNN,
2017). We have therefore coded him 1 for both OTH_IMMIGRANTS and
OTH_ETHNIC. We have not found any reference that could be used to
identify the military as an enemy of the people in MEO's discourse
(OTH_MILITARY = 1).

Enríquez-Ominami proclaimed the need to democratize the country,
regenerate politics, "combat social inequality and promote regional
political unity" (Moffett and Pica, 2009). He also criticised harshly
the Ministers of Economy of Chile saying that his country needed to
"repoliticize to society against the dictatorship of the economists. The
economy in Chile has eaten law and democracy" (Prados 2015). Given his
defense of primary elections and democracy, we have coded him 1 in
LIBDEMNORMS.

## Broad Front 

The Broad Front ("Frente Amplio") is a coalition of left-wing parties
created in 2017 in order to compete in the elections. Its origins can be
traced to the student protests of 2011 and the coalition includes a wide
variety of left and far-left parties with the exception of the Communist
party, which participated in the centre-left coalition (Miranda Orrego
2022, 187; Soto Pimentel 2017, 51; Thielemann 2018, 6). González Le Saux
exposes the Broad Front's vision of the economic and political system in
Chile:

> From Frente Amplio's perspective, the bipartisan logic of compromise
> between the two ruling coalitions has allowed the neoliberal
> model-cemented during the country's 17-year dictatorship under Augusto
> Pinochet (1973-1990)-to continue, with only moderate reforms aimed at
> mitigating its most draconian consequences. Frente Amplio seeks to
> overcome a transitional order characterized by a neoliberal economy,
> export-driven extractivism, and the privatization of social rights in
> the realms of education, health, labor, and social security (González
> Le Saux, 2017).

It is a party that criticises harshly the establishment and wishes a
radical rupture with it: "Frente Amplio is appealing to the novelty and
integrity of its candidates, unpolluted by the links between money and
politics. Against the paternalistic and top-down functioning of
traditional parties, it promotes a participatory style of politics"
(González Le Saux, 2017). The Broad Front, thus, has a "left-wing agenda
of anti-neoliberalism, environmentalism, pro-immigrant and LGBTQI
rights" (González Le Saux, 2017). They claimed to be an alternative to
the "duopoly" of the big traditional Chilean parties, become
"independent from the business power" (Manzano 2017, 171) and
"antagonise the 'politicians from the democratic transition'" (Manzano
2017, 178). He party is clearly identified by scholars as having a
leftist platform and proposing significant reforms (Soto Pimentel 2017,
50) and has been frequently compared with Podemos in Spain (Manzano
2017, 172; Miranda Orrego 2022, 185). We have coded it 3 on OTH_POLCLASS
, OTH_FINANCIAL and FL on LRPOSITION.

The Broad Front's presidential candidate was Beatriz Sánchez, a radio
and TV host that identified herself as "left-wing, but a very democratic
left" and who stresses the importance of discussion as a way of reaching
agreements (The Global Vote, 2017) The party also wanted to deepen
democratic participation by "opening instances of decision and
intervention of the State to binding participation, adapting them to the
particularities as women, as children and young people, as indigenous or
Afro-descendants, as foreigners residing in Chile, as people with
disabilities, as LFTBI community" (Manzano 2017, 179) (LIBDEMNORMS = 1).
Sánchez never held a position in government and did not belong to any
party before 2017 (INSIDER = 1). Since the party was created
independently of Sánchez, had a long tradition on social movements
(Miranda Orrego 2022, 187) and would have existed without her, we have
coded 1 on CHARISMA.

She declared herself as a feminist candidate for the presidency and was
a defender of LGTB rights and abortion (The Global Vote, 2017).
Additionally, she was particularly critical of the sharp inequalities in
Chile: "The concentration of wealth is one of the highest in Latin
America. \[The rich should\] pay fair taxes. I don't want them not to
earn money, but to pay fair taxes." (The Global Vote, 2017).

The army received harsh criticism from Sanchez due to the lack of
governmental control over it (Sanchez, 2016). Moreover, she also argued
against the privileges the army has in comparison with other public
servants such as a better pension scheme or healthcare system (Sanchez,
2016). The reason for this, she argued, was that "there isn't a real
dominion of the Civil power over the military power" and urged to change
that situation (Sanchez, 2016) (MILITARY = 3).

Regarding foreign powers or interests, "the agenda is predominantly
domestic, with relatively little reference made to international affairs
or Chile's role in the world" (The Global Vote, 2017). We have not found
nationalist rhetoric nor the identification of external threats in
Sanchez's discourse (OTH_FOREIGN = 1).

## José Antonio Kast

José Antonio Kast is a lawyer from a prominent political family in
Chile. He was a city councillor, a member of the chamber of deputies for
14 years and secretary general of the UDI. Kast was a well-known figure
of the most conservative current of the UDI and left the party in 2016
in order to run for president in the 2017 campaign on a more right-wing
and populist platform. He has professed many times its admiration for
Bolsonaro's defeat of the "corrupt left" (Tele13, 2018) and is
considered to be a prime example of the populist radical right in Latin
America (Zanotti y Roberts 2021, 36).

Kast was a strong supporter of the dictatorship of Pinochet, saying that
if Pinochet were alive, he would vote for him (Freixas, 2019). He
participated in the campaign for the YES to the dictatorship in the 1988
referendum and his brother, as one of the "Chicago Boys", actively
participated in Pinochet's government. Moreover, he asked for the
liberation of one of the torturers of the dictatorship (Freixas, 2019).
Kast was in favor of increasing military spending, stating that "the
armed forces, in justified cases and as a strictly exceptional measure,
will be able to collaborate in matters of public security when they are
required in order to fight terrorism and drug trafficking. Improvements,
innovation and new powers and attributions require a bigger budget. To
this end, the limits of the use of the Fund created by the Copper
Reserve Law will be revised so that these resources can be used to
increase the available military budget" (The Global Vote, 2017).
(OTH_MILITARY = 1).

Kast is strongly opposed to abortion, feminism, and LGBT rights and
considers the right-wing president, Sebastían Piñera as a "soft right"
for "lack of character" and for giving in to pressures from the
opposition" (Freixas, 2019). He claimed to be placed "to the right of
the right" (Díaz, Rovira Kaltwasser, y Zanotti 2023, 345). After the
2017 election, he created a new party called Republican Action and its
logo clearly references that of the French Front National
(Cooperativa.cl 2018). Stronger law and order measures and authoritarian
tendencies are clear in Kast's platform. As (Díaz, Rovira Kaltwasser,
and Zanotti (2023, 345) argue, "Of the three defining attributes of the
PRR, there is little doubt that authoritarianism is the most important
for Kast and the Partido Republicano". He stated, for example, that "
"we unequivocally reject the so-called 'neo-Marxist postmodernism' that
is beginning to settle in Chilean society through the interested use of
matters such as human rights, gender, sexual orientation, immigration or
the environment. Thus, we regret the use of names such as \...
'homophobic' to those who defend the idea that marriage is between a man
and a woman" (Díaz, Rovira Kaltwasser, y Zanotti 2023, 346). These
authors also identify nativism and populism as fundamental elements of
Kast's platform (Díaz, Rovira Kaltwasser, y Zanotti 2023, 346-47). For
Kast, "the "corrupt elite" is portrayed as an assemblage of powerful
actors who attack the common sense supported by the "pure people" (Díaz,
Rovira Kaltwasser, y Zanotti 2023, 346-47). On economic issues, he is
committed to neoliberal policies (Díaz, Rovira Kaltwasser, y Zanotti
2023, 349) and argues for a small state that is free from "politicking,
privileges, duplicities or useless agencies" (Kast, 2017). Given all the
above we have coded him FR in LRPOSITION, 3 for OTH_POLCLASS, 3 for
LIBDEMNORMS and 1 for OTH_FINANCIAL.

On the relation between Chile and its neighbors, Kast displays a
nationalistic view and identifies physical barriers as the solution to
the long-standing territorial dispute with neighboring Bolivia. Kast
stated that

> we want to reaffirm the autonomy of Chile and its sovereignty that
> must be exercised in every corner of the country. For a long time, we
> have been passive spectators of the communication abuses of our
> neighbors of the northeast and we have not responded with sufficient
> force and decision to the lies of the Bolivian government... Physical
> barriers are required on the Chile-Peru and the Chile-Bolivia border
> to support our police and to help to fight drug trafficking and
> smuggling at the border. In addition, we need to incorporate more
> technology for the detection and prosecution of border crimes" (The
> Global Vote, 2017).

He also criticised Michelle Bachelet, the former Chilean president, for
her role as High Commissioner for Human Rights, as well as the New York
Times and the UN. However, several sources point to the fact that
international others are not as significant for Kast as for other
far-right parties and that the main outgroup are indigenous people
inside the country and (Díaz, Rovira Kaltwasser, y Zanotti 2023, 351;
Zanotti y Roberts 2021, 40) (OTH_FOREIGN = 2).

He is in favor of controlling migration, commenting that "those people
who are going to come must know that as of today, Chile is not ready to
receive all people." (The Global Vote, 2017). "But we must also be
rigorous in controlling our borders and in rejecting illegal immigration
in every event (The Global Vote, 2017). Additionally, Kast has been
criticized for "constructing a hate discourse regarding race, ethnicity
or sexual minorities" (Freixas, 2019) (OTH_ETHNIC = 3, OTHIMMIGRANT =
3).

Although Kast did not participate in the government, he was a prominent
member of the UDI for many years and secretary general of the party
before he decided to run as an independent. We have therefore coded him
as 2 for INSIDER. It is plausible to imagine that other far-right
parties could have emerged in the 2017 elections, but Kast's movement
was based on his personas as he ran as an independent and then founded
the party Republican Action (Díaz, Rovira Kaltwasser, y Zanotti 2023,
356) (CHARISMA = 3).

## Not Included

We have not found sufficient evidence on the Communist Party at this
stage to decide on its inclusion. We have provided below some references
in case a later review of the dataset decides to include it.

## Communist Party / Together we can do more for Chile

There has been extensive debate over whether Communist and/or Socialist
ideologies are similar or dissimilar to populist discourses. Hawkins and
Rovira-Kaltwasser (2017) argue that the combination of Marxism and
populism is common in Chile, being Salvador Allende its prime example.

The Communist Party of Chile is "a revolutionary Party, which fights for
socialism and recognizes the driving role of the working class"
(Communist Party of Chile, 2002) that aims at the "suppression of all
forms of political, economic, social and cultural domination over the
people" (Communist Party of Chile, 2002). Although Marxist parties tend
to downplay their national ties in favor of internationalism while
populist parties are usually more nationalistic, the Chilean Communist
Party aims at combining the two by stating that its inspiration is
"national, patriotic, Latin Americanist and internationalist" (Communist
Party of Chile, 2002). Furthermore, the party is "anti-imperialistic"
and "fights for the self-determination of the peoples and is in
solidarity with all those who fight for their national independence, for
democracy, for socialism and peace." (Communist Party of Chile, 2002).
We have coded 3 for Financial Elite, Foreign Interests and Political
Class and "Far-Left" as its ideology.

Although the Communist party is a revolutionary party and "it's
sustained on the ideas of Marx, Engels and Lenin" (Communist Party of
Chile, 2002), it also proclaims that "because of its tradition and
democratic spirit, it fights for democracy as a form of political
organization of society" and that "its humanistic conception contains
the principles of the Universal Declaration of Human Rights" (Communist
Party of Chile, 2002). I have not found actions carried out by the
Communist Party in this period that imply a violation of LD norms. I
have coded this category as a 2.

The party suffered persecution during the dictatorship and could not
compete in the first elections under its name. Since Allende's
government, the Communist party did not participate in the
administration and was not led by any charismatic leader. Therefore, I
have coded 3 for Military, and 1 for Insider Populism and Personality
Dependent.

In 2005, the party forms an electoral alliance with the Humanist party
called "Together we can do more for Chile" ("Juntos Podemos Más por
Chile") and presented their leader, Tomás Hirsch, as their candidate for
president. There were many ideological similarities between these two
parties and the Communist party remained as the largest party in the
coalition. Moreover, Hirsh campaigned on a progressive left-wing
platform similar to that of the Communist party (Angell and Reig, 2006).
Thus, I have kept the same coding as in the previous elections.

In 2009, 2013 and 2017 parliamentary elections, the Communist Party
became part of the electoral alliance of the "Concertación" and "Nueva
Mayoría" but obtained less than 5% of the votes. For the presidential
elections, the party presented a candidate, supported Bachelet's
candidacy for 2013 and her successors in 2017. Thus, I have not coded
the Communist party for these years. In 2009, "Together we can do more
for Chile" presented Jorge Arrate as their presidential candidate. He
ran on similar ideas to what the party defended before.

**References**

Angell, A. and Reig, R. (2006) "Change or continuity? The Chilean
elections of 2005/2006", Bulletin Latin American Research, Vol. 25 (4),
pp. 481-502.

CNN (2017) "MEO por inmigración: "Buena parte de la historia de Chile se
escribe con mapuches e inmigrantes", 2 October:
<https://www.cnnchile.com/pais/meo-por-inmigracion-buena-parte-de-la-historia-de-chile-se-escribe-con-mapuches-e_20171002/>

Communist Party of Chile (2002) "Estatutos del Partido Comunista de
Chile", October-November:
<http://www.secst.cl/upfiles/documentos/02052016_1122am_57278cd1a8c05.pdf>

Cortés, A. and Pelfini, A. (2017) "El populismo en Chile: ¿tan lejos,
tan cerca?", Izquierdas, 32, March, pp. 58-78.

Dosek, T. and Freidenberg, F. (2014) "Voto hacia nuevos candidatos en
sistemas de partidos (des)institucionalizados: el caso de Marco
Enríquez-Ominami en Chile 2009", Revista SAAP, Vol. 8, No 1, pp.
11-1412.

Drake, P. (1999) "Chile's Populism Reconsidered, 1920s-1990s", in
Conniff, M. (ed.) "Populism in Latin America", London: The University of
Alabama Press.

Emol (2013) "Ministro Lavín: 'El pueblo mapuche merece un
reconocimiento'", 15 January:
https://www.emol.com/noticias/nacional/2013/01/15/579179/ministro-lavin-reconoce-que-es-necesario-ampliar-mesa-de-dialogo-con-indigenas.html

Emol (2013b) "Matthei rechaza el populismo en la campaña y critica
gestión de Bachelet en Enade 2013", Emol.com, 17 October:
https://www.emol.com/noticias/nacional/2013/10/17/625140/matthei.html

Enríquez-Ominami, M. (2009) "2009: Marco anuncia candidatura
presidencial \| Marco Enríquez-Ominami", 26 January:
https://www.youtube.com/watch?v=4iWwaEX4mNI

Errázuriz, F. J. (1989a) "CSA - Campaña Presidencial Francisco Javier
Errazuriz Talavera (Chile 1989)":
https://www.youtube.com/watch?v=E_rGVbPOI2s

Errázuriz, F. J. (1989b) "Franja 1989 Francisco Errázuriz (completo)":
https://www.youtube.com/watch?v=He9W5S5MVNk

Freixas, M. (2019) "José Antonio Kast, el Bolsonaro chileno que lidera
las encuestas presidenciales", Público, 21 January:
https://www.publico.es/internacional/chile-jose-antonio-kast-bolsonaro-chileno-lidera-encuestas-presidenciales.html

González Le Saux, M. (2017) "Broadening Chile\'s Left", NACLA Report on
the Americas; New York Vol. 49, Iss. 3, Fall, pp. 281-283.

Kast, J. A. (2017) "Tweet", 6 November:
https://twitter.com/joseantoniokast/status/927589785484648448

Luna, J. P. (2010) "Segmented Party-Voter Linkages in Latin America: The
Case of the UDI", Journal of Latin American Studies, Vol. 42, No. 2, pp.
325-356.

Luna, J. P., Monestier F. and Rosenblatt, F. (2013) "Religious parties
in Chile: the Christian Democratic Party and the Independent Democratic
Union", Democratization, 20:5, 917-938, DOI:
10.1080/13510347.2013.801258

Manifesto (2009) "Programa; Marco Enríquez-Ominani website":
http://www.marcoenriquezominami.cl/programa-2/

Moffett, M. and Pica, C. (2009) "World News: Chilean Upstart Roils
Elections", Wall Street Journal, Eastern edition; New York, 28 Oct 2009.

Romainville, M. (2018) "Sebastián Piñera: 'El populismo y la corrupción
son formidables enemigos de la democracia'", Semana Económica.com, 14
Abril:
http://semanaeconomica.com/article/legal-y-politica/politica-internacional/283150-sebastian-pinera-el-populismo-y-la-corrupcion-son-formidables-enemigos-de-la-democracia/

Sanchez, B. (2016) "Columna de Beatriz Sánchez: Las Fuerzas Armadas",
Publimetro, 5 May:
https://www.publimetro.cl/cl/columnas/2016/05/05/columna-beatriz-sanchez-fuerzas-armadas.html

Silva, P. (2001) "Towards Technocratic Mass Politics in Chile? The
1999-2000 Elections and the Lavín Phenomenon", European Review of Latin
American and Caribbean Studies / Revista Europea de Estudios
Latinoamericanos y del Caribe, No. 70, pp. 25-39

Tele13 (2018) "José Antonio Kast tras la victoria de Jair Bolsonaro en
Brasil: \"El sentido común sigue triunfando", 28 October:
https://www.t13.cl/noticia/politica/Jose-Antonio-Kast-tras-la-victoria-de-Jair-Bolsonaro-en-Brasil-El-sentido-comun-sigue-triunfando

The Global Vote (2017) "Beatriz Sanchez":
https://www.goodcountry.org/global-vote/elections/chile/candidates/beatriz-sanchez

The Global Vote (2017) "José Antonio Kast":
<https://www.globalvote.org/global-vote/elections/chile/candidates/jose-antonio-kast>

Via X (2013) "Joaquín Lavín justifica política de Longueira sobre
inmigrantes en Cadena Nacional", 20 January:
<https://www.youtube.com/watch?v=DVM_PACQtAc>

BCN. 2020. «Marco Antonio Enríquez-Ominami Gumucio. Reseñas biográficas
parlamentarias de la Biblioteca del Congreso Nacional de Chile (BCN)».
*bcn.cl*.
https://www.bcn.cl/historiapolitica/resenas_parlamentarias/wiki/Marco_Antonio_Enríquez-Ominami_Gumucio
(21 de septiembre de 2023).

Bunker, Kenneth, y Patricio Navia. 2013. «Latin American Political
Outsiders, Revisited: The Case of Marco Enríquez-Ominami in Chile,
2009». *Journal of Politics in Latin America* 5(2): 3-35.

Cooperativa.cl. 2018. «\[Fotos\] Logo del movimiento de Kast es casi
igual al del ultraderechista Frente Nacional francés». *Cooperativa.cl*.
https://cooperativa.cl/noticias/pais/politica/logo-del-movimiento-de-kast-es-casi-igual-al-del-ultraderechista-frente/2018-04-20/172854.html
(21 de septiembre de 2023).

Díaz, Camila, Cristóbal Rovira Kaltwasser, y Lisa Zanotti. 2023. «The
arrival of the populist radical right in Chile : José Antonio Kast and
the "Partido Republicano"». *Journal of Language and Politics* 22(3):
342-59.

Drake, Paul W. 2012. «Chile's Populism Reconsidered, 1920s--1990s». En
*Populism in Latin America*, ed. Michael L Conniff. Tuscaloosa, Ala: The
University Alabama Press.

*Francisco Errazuriz - Spot de campaña elecciones en Chile 1989*. 1989.
https://www.youtube.com/watch?v=8bA2tELLIPg (20 de septiembre de 2023).

Gumucio Rivas, Rafael, y Marco Enríquez-Ominami. 2013. *El problema no
es la economía, es el poder. Un llamado a la reflexión para el proceso
Constituyente*. Santiago de Chile: Self-published.
https://marcoenriquezominami.cl/elproblemanoeslaeconomia/ (21 de
septiembre de 2023).

Manzano, Daniel. 2017. «El Frente Amplio chileno: ¿una interpretación
posmarxista?» *Revista Divergencia* 9.

Miranda Orrego, Juan Pablo. 2022. «El Frente Amplio chileno en punto
cero: Inserción social y perfil de militancias dentro de la nueva
izquierda chilena». *Revista chilena de derecho y ciencia política*
13(1): 180-207.

Prados, Luis. 2015. «"En Chile, la economía se comió la democracia"».
*El País*.
https://elpais.com/internacional/2015/06/16/actualidad/1434491840_212403.html
(21 de septiembre de 2023).

Schuster, Martin, y Rodrigo Osorio. 2010. «Marco Enríquez-Ominami: el
candidato independiente». En *El sismo electoral de 2009: cambio y
continuidad en las preferencias políticas de los chilenos*, Santiago de
Chile: Ediciones Universidad Diego Portales, 99-122.

Silva, Patricio. 1991. «Technocrats and Politics in Chile: From the
Chicago Boys to the CIEPLAN Monks». *Journal of Latin American Studies*
23(2): 385-410.

---------. 2001. «Towards Technocratic Mass Politics in Chile? The
1999-2000 Elections and the "Lavín Phenomenon"». *European Review of
Latin American and Caribbean Studies / Revista Europea de Estudios
Latinoamericanos y del Caribe* 70: 25-39.

Soto Pimentel, Verónica Paz. 2017. «Elecciones presidenciales en Chile
2017 : entre el tradicional duopolio y la propuesta del Frente Amplio».
*Bordes: Revista de política, derecho y sociedad*.
https://ri.conicet.gov.ar/handle/11336/74727 (21 de septiembre de 2023).

Thielemann, Luis. 2018. «¿ Un parto en una funeraria? La formación del
Frente Amplio». *Viento Sur* 156: 5-13.

Zanotti, Lisa, y Kenneth M. Roberts. 2021. «(Aún) la excepción y no la
regla: La derecha populista radical en América Latina». *Revista
Uruguaya de Ciencia Política* 30(1): 23-48.
