---
title: Colombia
subtitle: |-
  -   Date range: 1980-2020
  <br>
  -   Elections included:
  <br>
      -   Presidential: 1990, 2002, 2006, 2018, 2002, 2006, 2018
  <br>
      -   Legislative: 1990, 1991, 2006, 2010, 2014, 2018
  <br>
  -   Not included:
  <br>
      -   Presidential: 1982, 1986, 1994, 1998, 2010, 2014
  <br>
      -   Legislative: 1982, 1986, 1994, 1998, 2002
  <br>
  Colombian politics had been dominated by two main parties, the Liberal
  and the Conservative parties from the mid-XIXth Century as well as by
  the violent conflicts between the state and several guerrillas and
  narcotraffic cartels present in the country.
title-block-banner: yes

---

# Case notes

## Alternative Democracy M-19

The party came out of a peace process between the government of Colombia
and the left-wing guerrilla M-19 that ended in March of 1990. The
guerrilla transformed itself into a party called "Alternative Democracy
M-19". It supported the vote for a Constitutional Assembly that took
place during the legislative elections that same month and then ran for
president in the presidential elections in May of the same year. The
presidential candidate was Carlos Pizarro, the historic leader of M-19,
however, he was assassinated in April of 1990 and had to be quickly
substituted by Antonio Navarro Wolf, his second in command. Navarro came
in third with 12.48% in the presidential elections, which were won by
Liberal Party candidate César Gaviria. However, Alternative Democracy
M-19 was the second most-voted party in the Constitutional Assembly
elections that took place in December of 1990. The new Constitution was
passed in July 1991 and new legislative elections took place in October
of 1991, where the party came in third with 10.28% of the vote.

The main ideology of the party was Marxist (Boudon, 2001: 75) but the
party aimed at reaching a larger section of the electorate by presenting
themselves as "the new political alternative" and "more than a party"
(Villamizar, 1995: 571). The central issue for the party, however, was
not communism, but democracy (Boudon, 2001: 76). Carlos Pizarro, leader
of the M-19 until his assassination, employed populist tropes when he
argued that "what we need to do is create something that attracts the
nonconformists within the traditional parties, the nonconformists within
the private enterprise, the nonconformists within the guerrilla ranks,
the nonconformists within society in general... and which it is capable
of offering proposals to the nation" (quoted in Beccassino, 1989: 110).
The M-19 also heavily criticized Liberal President Gaviria's neoliberal
reforms and the hardline it took with the existing active guerrilla
groups (Boudon, 2001: 81).

Their platform was based on 8 points: "(1) peace and an end to violence,
(2) rejection of corruption and clientelism, (3) constitutional
development toward a "social state of law", (4) an economic policy based
on production and an expanding socioeconomic base, (5) a specific
employment program, (6) a pact to protect the environment, (7) priority
for social programs, and (8) Latin American regional integration" (El
Nuevo Siglo, 1993). Moreover, the party emphasized the need to end
military impunity (Boudon, 2001: 89).

The party was a direct heir of the M-19 movement, a movement that very
explicitly articulated a strong criticism of the "oligarchy" (Caro
Pulido 2020, 104). In their first press release, the M-19 argued that:

> "the Spanish chains broken by Bolivar, today are replaced by the
> gringo dollar. And it is that in the seat of Bolivar, every four years
> the representatives of the murderous oligarchies of the Colombian
> people have taken turns. And the fact is that these exploiters speak
> of a sovereign homeland while they hand it over to the foreign master.
> They speak of a just homeland while the wealth of a privileged few is
> amassed in the anguish of the workers. \[...\] But Bolivar is not with
> them -the oppressors- but with the oppressed. (Caro Pulido 2020, 106).

This rhetoric was constant throughout the existence of the guerrilla. In
a press release in 1985 they argued, for instance, that:

> \"Another intention, anti-popular and immoral, is that of the rulers
> and editorialists of the oligarchy, who seek impunity in a supposed
> defense-abstract, intangible- of the rule of law: To act as if the
> nation were themselves, themselves alone; to mount without impediment
> their big business deals, their great speculations; and to load on the
> back of the people, giving them the character of national, their loans
> with the international banks, obliging the citizen to pay these debts
> which are, in general, the result of embezzlement or illicit\" (M-19,
> November 6, 1985, CEDEMA)." (quoted in Caro Pulido (2020, 106).

We have not found any evidence that indicates a criticism of immigrants
or ethnic others as threats. Therefore, we have coded FL for ideology, 3
for OTH_POLCLASS, OTH_FINANCIAL, OTH_MILITARY, and OTH_FOREIGN, and 1
for every other category.

Judging the violation of liberal-democratic norms of Alternative
Democracy M-19 is very complicated because the party only existed for
two months before the elections and was a direct heir of a guerrilla
group. Under the leadership of both Carlos Pizarro and Antonio Navarro
the M-19 had kidnapped Conservative candidate Antonio Gómez Hurtado in
1988 as a way to pressure the government of Colombia to sign the peace
process and while Pizarro was second in command in 1985, the M-19
assaulted the Justice Palace of Bogotá in an incident that ended with
the burning of the building and the death of 101 people. Of course, the
party stressed the benefits of the peace accord and we have found no
violation of liberal-democratic norms in the two-months run up to the
election but these violations were very common in the recent past and
committed by the party leaders. Thus, we have coded LIBDEMS as 2 in
order to reflect this contradictory evidence.

Neither Carlos Pizarro nor Antonio Navarro had held any governmental
position before the May 1990 presidential elections. However, between
the 7^th^ of August and the 27^th^ of October, Antonio Navarro became
Minister of Healthcare of Colombia invited by President Gaviria. He then
left his position to compete in the December 1990 Constitutional
Assembly elections and was one of the three presidents of the commission
that drafted the new constitution. Camilo González Posso, another member
of Alternative Democracy M-19 substituted Navarro as Minister of
Healthcare. Thus, when the new legislative elections took place in
October 1991, the party still controlled the Ministry of Healthcare
(INSIDER, INC_PARL = 2).

## Álvaro Uribe

Colombia has traditionally been conceived as an unfertile country for
the emergence of populist forces (Dugas, 2003; Giraldo, 2018). Although
Jorge Eliécer Gaitán and Gustavo Rojas Pinilla are considered examples
of populism there is much debate on whether Álvaro Uribe Vélez, the most
influential politician of the twenty first century in Colombia, can be
classified as a populist or not. Uribe did not emphasize the opposition
with the financial elites, was not particularly charismatic and
explicitly rejected populism (Dugas, 2002: 1126). However, he did have a
strong stance against political elites. Uribe had been a member of the
Liberal Party but ran as an independent in the 2002 election under a
platform called "Colombia First". He strongly criticized the political
system at the time, saying in his 100 points manifesto (2002: point 4)
that "I dream with a state that serves the people and not corruption and
politicking" ("politiquería"). This last term is a derogatory way to
refer to politics and it is very present in Uribe's campaign, so much
that one of his promises was to announce a "Referendum against
Corruption and Politicking" as his very first action in government
(Uribe, 2002: point 9). In that same manifesto, he also criticized
pluralism by stating that "pluralism had been transformed into
dispersion and anarchy due to the salaries, the clientelism and the
pension privileges" (Uribe, 2002: point 22). Abad Cisneros also finds
strong presence of a manichean distinction between the people and an
elite "who is communist and betrays the people in service of the FARC"
(Abad Cisneros 2015, 165-66) (OTH_POLCLASS = 3).

Uribe was particularly known for his hard stance on security issues. The
first of his three-pillar-policy was "democratic security" which
involved hardline policies regarding left-wing guerrillas such as the
FARC. He made constant references to the fatherland and aimed to achieve
national unity in the fight against the guerrillas. Uribe clearly
delimitated an "us" vs "them" based on support to his security policies.
He divided society between "the patriots that support the policy of
Democratic Security and the Communists in disguise that wish to sell the
fatherland to the FARC" (Fierro, 2012: 130). He conceded no legitimacy
to the guerrillas and attacked those who did as traitors. The only
legitimate policy was to defeat the armed groups in order to achieve a
country "without guerrillas, without paramilitaries... without drugs"
(Uribe 2002: points 26 and 31). Some of the policies involved "praising
the profession of soldier and policemen" (Uribe 2002: point 28) as well
as paying regular citizens that had undertaken anti-terrorist actions
(Uribe 2002: point 39).

His manifesto clearly states the protection of minority rights and
immigration is not a relevant element in his platform. As a former
governor of one of Colombia's regions and mayor to one of its most
important cities, Uribe was included in previous political settlements
but was a peripheral figure in them. Although he created the new party
and undertook a very personalistic style, the decay of the previous
political system was evident and anti-corruption was a common platform
among several parties in the 2002 election (Duges, 2003: 1126). Uribe
declared a state-of-siege shortly after becoming president which was
condemned by human rights organizations (El País, 2002), has attacked
the press (Fierro, 2014: 139) and has been repeatedly accused of
collaboration with far-right paramilitary groups (El País, 2006).

However, the state-of-siege measure is quite common in Colombian history
and he accepted the Constitutional Court's decisions when they did not
rule in his favor (Dugas, 2003: 1133). Therefore, I have classified him
as 1 on OTH_IMMIGRANTS and OTH_ETHNIC and as 2 on CHARISMA and INSIDER
and LIBDEMNORMS .

On economic issues, Uribe defended orthodox and neoliberal policies
because one of his main "three pillars", "investment trust" was to make
Colombia a secure and attractive place for foreign investment (Uribe,
2002) (OTH_ECONOMIC and OTH_FOREIGN = 1, LRPOSITION = R).

Álvaro Uribe ended his presidency with one of the highest approval rates
in Colombian history and his personality has profoundly marked politics
after him. When he failed to pass a law that could allow him to run for
a third time, Juan Manuel Santos was regarded as his successor. Santos
had been Uribe's Defense Minister and, although he ran a campaign that
was also tough on the FARC, his profile was that of a rich technocrat
that ran on a platform of continuity with Uribe's politics. He argued
that he was the opposite to populism and shortly after his victory he
changed his discourse regarding the guerrillas. He initiated the "peace
dialogues" with the FARC and that made Uribe distance from him. The most
important expression of this conflict was the 2016 referendum on the
Peace Agreement.

Santos' main rival in 2014 and its successor in the presidency in 2018
have both been successors of Uribe under the umbrella of the Democratic
Centre (CD), the party that Uribe founded in 2013 to confront Santos.
The CD is a party regarded my many as right-wing although they
explicitly situate themselves in the center. Uribe's ideas have remained
fairly constant throughout the past 20 years and the CD shares his
programmatic points view, merely adding two more to Uribe's three
pillars (CD website). We have coded this party in the same manner as the
rest of Uribe's government in all legislative elections as it has also
been identified as a populist party that follows Uribe's ideas (León,
Agualimpia, y Barrios 2018, 164).

However, the inclusion of the two presidential candidates of the
Uribismo as populist is less clear. They both owe their popularity to
being related to Uribe, they did not try to distance themselves from him
and their discourses are less anti-elitists, more plural and more
moderate than that of the leader of the CD. These politicians agree with
Uribe on the substantive elements of his discourse but employ to a much
lesser degree his populist strategies. Francisco Panizza (in private
conversation) argued against including them in any populism dataset and
Jorge Giraldo uses the label populist just to refer to the figure of
Álvaro Uribe (Giraldo, 2019). We, too, agree that neither Óscar Zuluaga
nor Iván Duque should be included.

## Gustavo Petro

Petro was part of the M-19 guerrilla movement and later in the
Alternative Democracy M-19. In 2005 this party unified with other
movements and created the "Pole of Democratic Alternative" ("Polo
Democrático Alternativo") and he became a prominent member. With these
two parties Petro had been MP and Senator and ran as the presidential
candidate in 2010. He had not held any position in government previously
(INSIDER = 1, CHARISMA = 1 in 2010). He did not achieve the presidency
in 2010 and left the party shortly after. He then founded his own party,
"Movimiento Progesista" and became mayor of Bogotá. He then ran for
president of Colombia in 2018 under the platform "Humane Colombia"
("Colombia Humana") and then again in 2022, this time winning the
election. Gustavo Petro created the new party and the presidential
coalition and ran on a populist platform based on his personal figure.
His new party and platform would not have existed without him (CHARISMA
= 3 in 2018).

Petro's discourse has been clearly identified as left-populist (González
Figueroa 2018; Grisales 2022; Kajsiu y Grisales 2019). A crucial point
of his discourse is the defence of the \"the poor\", \"the workers\",
\"the peasants\", \"the indigenous people\" and \"the Afros\" (González
Figueroa 2018, 53) and a criticism of elites as estranged from the rest
of the people \"They only know the land from the golf course, they only
know the poor from the maid who every day brings them hot breakfast in
bed, they have had a life of privilege and power, they do not have the
experience, they do not have the capacity, they have never felt what
poverty means, the resistance, the sacrifice\" (González Figueroa 2018,
54). In a TV advertisement in 2018, Petro clearly outlined his populist
discourse: "The first time that a presidential candidate that does not
represent the "politiquería", not the power of the elites, nor the
corrupts who have sacked the country and are now surrounding Duque, may
win the elections" and "it is the first time that a government may be
formed that really works for the people" (Petro, 2018a). Corruption was
the main topic of his discourse and he relates all of Colombia's
problems to it. For example, he stated that "the problem with the
healthcare system is not that we need more money, but corruption"
(Petro, 2018b) (OTH_POLCLASS = 3). He also diluted its ideological
position when he defends that "I was leftist and I do not regret it but
my proposal is not socialist, that did not work, we propose the
development of a democratic capitalism based on granting access to a
rural middle class to productive lands" (Petro, 2018b). However, Petro
was very critical of the huge inequalities of the country and aimed to
distribute wealth extensively. We have therefore coded Petro with L for
LRPOSITION and 2 for OTH_FINANCIAL.

Petro's opinion on the army was dominated by a comment he made in the
campaign in which he said that "those youngsters that cannot study in
university may end \[...\] in the drug cartels or trying to find a job
in the police or the army" (Petro, 2018c). Petro (2018d) rejected the
notion that he hated the military and defended himself by saying that he
gave shelter to the army while mayor of Bogotá. We have followed Petro's
self-description and labelled him as 1 in OTH_MILITARY.

We have found no significant violation of liberal democratic norms nor
against ethnic others of immigrants (LIBDEMNORMS, OTH_ETHNIC,
OTH_IMMIGRANTS = 1). In the campaign, Petro criticized that the
Colombian foreign policy was subordinated to that of the US due to the
money this country provides to Colombia to fight drug cartels (Petro,
2018e). He also argued for Colombia to occupy a more prominent and less
subordinate role in international politics. During the crisis in
Venezuela, Petro called for rallies against any military intervention in
Venezuela by the US (Petro, 2019). Although Petro is clearly critic of
foreign power interests, these are not constructed as the main threat to
the country, so we have labelled him 2 on OTH_FOREIGN.

**References**

Beccassino, A. (1989) "M-19: El heavy metal latino americano", Bogotá:
Fondo Editorial Santodomingo.

Boudon, L. (2001) "Colombia's M-19 Democratic Alliance: A Case Study in
New-Party Self-Destruction", Latin American Perspectives, Vol. 116, 28,
pp. 73-92.

Centro Democrático (website) 'Quiénes somos':
https://www.centrodemocratico.com/?page_id=868

Dugas, J. (2003) "The emergence of Neopopulism in Colombia? The case of
Álvaro Uribe", Third World Quarterly 24(6):1117-1136.

Duque (2018) . https://www.youtube.com/watch?v=bGlVeETH9M8

Duque, I. (2018) Inaugural Speech, 7 August:
https://muse-jhu-edu.gate3.library.lse.ac.uk/article/705728

El Nuevo Siglo (1993) "Article on M-19", 8 March.

El País (2002) "Uribe decreta el estado de excepción en Colombia para
frenar a las FARC", 12 August:
https://elpais.com/diario/2002/08/13/internacional/1029189602_850215.html

El País (2006) "Todo por la autoridad", 26 May:
https://elpais.com/diario/2006/05/28/internacional/1148767216_850215.html

Fierro, M. (2014) "Álvaro uribe vélez populismo y neopopulismo",
Análisis Político, Vol. 27(81), pp. 127-147.

Giraldo, J. (2018) "Populistas a la colombiana", Debate.

Giraldo, J. (2019) "El uribismo: un populismo peligroso" 18 March:
https://www.razonpublica.com/index.php/politica-y-gobierno-temas-27/11843-el-uribismo-un-populismo-peligroso.html

Petro, G. (2018a) "TV advertisement":
https://www.youtube.com/watch?v=7vd2TzvHCJM

Petro, G. (2018b) "Mi propuesta no es socialista, es al contrario, es el
desarollo del capitalism" 29 May:
http://www.wradio.com.co/noticias/actualidad/mi-propuesta-no-es-socialista-es-al-contrario-es-el-desarrollo-del-capitalismo-petro/20180529/nota/3755512.aspx#

Petro, G. (2018c) "Jóvenes terminan de soldados", 19 April:
https://www.pulzo.com/elecciones-2018/respuesta-policias-militares-gustavo-petro-PP472698

Petro, G. (2018d) "Twitter", 21 April:
https://twitter.com/petrogustavo/status/987822827272359938?lang=es

Petro, G. (2018e) "Petro dice que la política internacional de Colombia
es un apéndice de los EEUU" 1 May:
https://www.eldiario.es/politica/Gustavo-Petro-internacional-Colombia-EEUU_0_766773753.html

Petro, G. (2019) "Petro invita a marchar contra una \"intervención
militarista\" de EE. UU. en Venezuela", 30 January:
https://www.elespectador.com/noticias/politica/petro-invita-marchar-contra-una-intervencion-militarista-de-ee-uu-en-venezuela-articulo-836896

Tomaselli, W. (2018) Ivan Duque is Colombia\'s Youngest President-Elect
Ever. Now He Has to Fix the Divided Country, Time.com:
http://web.a.ebscohost.com/ehost/detail/detail?vid=0&sid=53c67f1e-ec02-462b-a3fc-3931a72a4cf5%40sessionmgr4006&bdata=JnNpdGU9ZWhvc3QtbGl2ZQ%3d%3d#AN=130819446&db=bth

Uribe, Á. (2002) "Manifiesto Democrático -- 100 puntos de Álvaro Uribe
Vélez":
https://www.mineducacion.gov.co/1621/articles-85269_archivo_pdf.pdf

Villamizar, D. (1995) "Aquel 19 será", Santa Fe de Bogotá: Planeta
Colombiana Editorial.

Zuluaga, O (2014b) "Óscar Zuluaga anuncia suspención de los diálogos con
las FARC si gana la Presidencia en Colombia" 26 May:
https://www.youtube.com/watch?v=dGyMGIspHMA

Zuluaga, O. (2014a) "Zuluaga es Centro Democrático", 10 March:
https://www.youtube.com/watch?v=NsJirgvH6hg

Abad Cisneros, Angélica. 2015. «Estrategia política y comportamiento
electoral. El voto a candidatos populistas en la región andina».
Doctoral Thesis. Universidad de Salamanca.
http://hdl.handle.net/10366/128138 (26 de septiembre de 2023).

Caro Pulido, Jessica Lizeth. 2020. «Estrategias populistas en el
discurso del M-19 en los medios gráficos a lo largo de su accionar
guerrillero (1974-1990)». Tesis. Universidad Nacional de La Plata.
http://sedici.unlp.edu.ar/handle/10915/107683 (26 de septiembre de
2023).

González Figueroa, Mateo. 2018. «La construcción discursiva de la
hegemonía : análisis del discurso de Gustavo Petro durante el periodo
2010-2018». *instname:Universidad de los Andes*.
https://repositorio.uniandes.edu.co/handle/1992/38902 (26 de septiembre
de 2023).

Grisales, Yenifer Tamayo. 2022. «¿Una apuesta por el populismo?
Movilización ideológica en las elecciones presidenciales de 2022:
Gustavo Petro y Rodolfo Hernández». *Revista Debates* (88): 62-73.

Kajsiu, Blendi, y Yenifer Tamayo Grisales. 2019. «Neoconservadurismo
versus populismo socialdemócrata. Una comparación de los discursos
anticorrupción de Iván Duque y Gustavo Petro en la segunda vuelta
presidencial de 2018». *Estudios Políticos* (56): 123-47.

León, Marcela Viviana, Helmer David Agualimpia, y Muriel Carolina
Barrios. 2018. «Populismo latinoamericano, elitismo político y legado
familiar en Colombia». *Amauta* 16(31): 157-73.
