---
title: Denmark
subtitle: 'Date range: 1980-2020.'
title-block-banner: yes

---

# Case notes

## Progress Party 

The Danish Progress Party (*Fremskridtspartiet*, FrP) was established in
the 1970s as a libertarian anti-tax party by eccentric tax lawyer Mogens
Glistrup. Glistrup had famously bragged on TV that his evasion of tax
constituted heroism on par with wartime resistance (Widfeldt 2000, 489).
The party achieved success early on, winning 15.9% in 1973, but
subsequently declined to 3.6% by 1984 when Glistrup was imprisoned for
tax evasion (Klein 2013, 106). He was replaced by Pia Kjærgaard, whose
star rose throughout the 1990s as a more pragmatic face of Glistrup's
provocative politics (Klein 2013, 107). This coincided with a turn
towards anti-immigration politics alongside the party's well established
neoliberalism. After Glistrup was released from prison, a factional
battle ensued between anti-compromise hardliners (led by Glistrup) and
relatively pro-compromise pragmatists (led by Kjærgaard), resulting in
the latter faction breaking off to form the Danish People's Party (see
below) and the decline of Progress to irrelevance by 2000s (J. G.
Andersen and Bjørklund 2000, 197).

Bound to Progress' anti-tax position was a deep anti-establishment
criticism of the political class (J. G. Andersen and Bjørklund 1990,
201; J. Andersen 2004; Siim and Meret 2016, 116) (OTH_POLCLASS = 3). In
the mid-1980s the party turned attention more toward opposition to
multiculturalism and immigration on increasingly ethnocentric lines (J.
Andersen 2004, 3). Rydgren cites 1985 as the year this occurred, in part
because the party learned from the breakout success of the Front
National in the 1984 French elections (Rydgren 2004, 480) (OTH_IMMIGRANT
= 1 1981-1984, 3 1987-2001). In later elections Glistrup called for
Muslim girls to be "sold to Paraguay", and proudly declared "Of course
I'm a racist -- all good Danes are. Either you're a racist or a traitor"
(Widfeldt 2000, 490). Progress campaigned in 2001 for a "Mohammedan-free
Denmark" (Rydgren 2004, 487). We have therefore increased OTH_ETHNIC
from 1 to 3 simultaneous to OTH_IMMIGRANT.

The party's leadership, initially by Glistrup and then by Kjærgaard, has
clearly been a very important element of Progress' meaning and appeal.
The former had a complicated role in the party after his return from
prison, acting as a kind of figurehead even when he was at odds with the
official party leadership (Rydgren 2004, 480). Glistrup also tried
actively to prevent the party from organising beneath him (J. G.
Andersen and Bjørklund 2000, 201). While this subject could be debated,
we have coded Progress 3 on CHARISMA for its duration. We have seen no
evidence that the party should register on the LIBDEMNORMS variable (=
1), nor that any of its leaders have been present in previous
governments (INSIDER = 1).

## Danish People\'s Party 

Founded after the split within Progress in 1995, the Danish People's
Party (*Dansk Folkeparti*, DF) was less tax-focused and more dedicated
to cultural issues, especially opposition to Muslim immigration. From
the outset, Kjærgaard positioned the party as a credible alternative to
major parties and expelled more extreme members (Klein 2013, 108). DF
participated in several governing coalitions with mainstream
conservative parties from 2001-2011 and 2015-2019, making it one of the
most successful right-wing populist parties in Europe.

Attacks on the political establishment have always been a pillar of the
DF (Kosiara-Pedersen 2020, 321). The party has always referred to
politicians as 'they' rather than 'we' -- even when it was a member of
coalition government after 2001 (Rydgren 2004, 486; see also Awad,
Doerr, and Nissen 2022, 999). Several sources point out that Kjærgaard's
approach to this matter is not as extreme as Glistrup (J. Andersen 2004,
3; Rydgren 2004, 487; Kosiara-Pedersen 2020, 321), and Rydgren contends
that this type of rhetoric became "less aggressive" after it joined the
governing coalition in 2001 (Rydgren 2004, 486). While this could be
considered cause for a reduction in the OTH_POLCLASS variable, we've
left it at 2 from the party's first election in 1998.

The party has always been explicitly hostile to ethnic others and
immigrants (Siim and Meret 2016, 21). In 2002, for example, it stated
that "Denmark is not an immigrant-country and never has been. Thus we
will not accept transformation to a multiethnic society... Denmark
belongs to the Danes" (Klein 2013, 110) (OTH_IMMIGRANT = 3). The party
is especially hostile to Muslim immigrants (Siim and Meret 2016, 126),
asserting that cultural integration is impossible and that Muslims, in
the words of DF MEP Mogens Camre, have "come to take over Denmark"
(Klein 2013, 111; see also Rydgren 2004, 485) (OTH_ETHNIC = 3). This is
often packaged in a welfare chauvinism perspective that ties mass
immigration to the draining of welfare to those Danes who deserve it
(Careja et al. 2016; Rydgren 2004, 486). While the party has
occasionally expelled overtly racist members and groups, this does not
mean that it should be coded less than 3 on either of these two
registers. While the DF had dropped the neoliberalism of Progress,
notably by defending aspects of the welfare state (J. Andersen 2004, 4;
Siim and Meret 2016, 116), this has not led to an OTH_ECONOMIC populism
(= 1). The DF is against the EU, but only to the level of 2 on
OTH_FOREIGN. The party's economic ideology has been considered centrist
or centre left (Jordan 2022, 5; Nicolaisen 2023), however due to the
salience of its of its ethnonationalist rhetoric it is universally
considered far right, and we agree (LRPOSITION = FR).

The dominant leadership of Kjærgaard (Meret 2015; J. Andersen 2004, 4;
Siim and Meret 2016, 120) seems to warrant 3 for CHARISMA while she led
the party, and while her successor Kriastian Thulesen Dahl is also
generally popular, it does not seem accurate to call the party
leader-defined under his tenure (= 1 from 2015). After it joined
coalition government in 2001 we have coded it 2 on INSIDER. we have seen
no evidence that the party has violated LIBDEMNORMS.

**References**

Andersen, Jørgen. 2004. 'The Danish People's Party and New Cleavages in
Danish Politics', January.

Andersen, Jørgen Goul, and Tor Bjørklund. 1990. 'Structural Change and
New Cleavages: The Progress Parties in Denmark and Norway'. *Acta
Sociologica* 33 (3): 195--217.

---------. 2000. 'Radical Right Wing Populism in Scandanavia: From Tax
Revlt to Neo-Liberalism and Xenophobia'. In *The Politics of the Extreme
Right: From the Margins to the Mainstream*, edited by Paul Hainsworth,
193--223. London: Bloomsbury Publishing Plc.
http://ebookcentral.proquest.com/lib/rmit/detail.action?docID=4659880.

Awad, Sarah, Nicole Doerr, and Anita Nissen. 2022. 'Far-Right Boundary
Construction towards the "Other": Visual Communication of Danish
People's Party on Social Media'. *The British Journal of Sociology* 73
(5): 985--1005.

Careja, Romana, Christian Elmelund‐Præstekær, Michael Baggesen
Klitgaard, and Erik Gahner Larsen. 2016. 'Direct and Indirect Welfare
Chauvinism as Party Strategies: An Analysis of the Danish People's
Party'. *Scandinavian Political Studies* 39 (4): 435--57.
https://doi.org/10.1111/1467-9477.12075.

Jordan, Jason. 2022. 'The Strategic Ambiguity of the Radical Right: A
Study of the Danish People's Part'. *Party Politics*, 13540688221136819.

Klein, Andreas. 2013. 'The End of Solidarity? On the Developement of
Right-Wing Populist Parties in Denmark and Sweden'. In *Exposing the
Demagogues: Right Wing and National Populist Parties in Europe.*, edited
by Karsten Grabow and Florian Hartleb, 105-131. Bruessels and Berlin,
Centre for European Studies and the Konrad Adenauer Stiftung.

Kosiara-Pedersen, Karina. 2020. 'The Danish People's Party:
Centre-Oriented Populists?'

Meret, Susi. 2015. 'Charismatic Female Leadership and Gender: Pia
Kjærsgaard and the Danish People's Party'. *Patterns of Prejudice* 49
(1--2): 81--102. https://doi.org/10.1080/0031322X.2015.1023657.

Nicolaisen, Mathias Holst. 2023. 'From Toleration to Recognition:
Explaining Change and Stability in Party Responses to the Danish
People's Party'. *Comparative European Politics*, 1--18.

Rydgren, Jens. 2004. 'Explaining the Emergence of Radical Right-Wing
Populist Parties: The Case of Denmark'. *West European Politics* 27 (3):
474--502. https://doi.org/10.1080/0140238042000228103.

Siim, Birte, and Susi Meret. 2016. 'Right Wing Populism in Denmark:
People, Nation and Welfare in the Construction of the "Other"'. *The
Rise of the Far Right in Europe: Populist Shifts and 'Othering'*, July,
109--37. https://doi.org/10.1057/978-1-137-55679-0_5.

Widfeldt, A. 2000. 'Scandinavia: Mixed Success for the Populist Right'.
*Parliamentary Affairs* 53 (3): 486--500.
https://doi.org/10.1093/pa/53.3.486.
