---
title: Ecuador
subtitle: |-
  Date range: 1984-2017
  <br>
  A military dictatorship was established in Ecuador in 1972, overthrowing
  Velasco Ibarra, the great populist figure of the 20th century who had
  been president on five different occasions and had declared himself as
  dictator two years before. In 1978, the military called for a referendum
  and the Ecuadorians chose a new democratic constitution. Presidential
  elections were held in 1978-1979 and Jaime Roldós, of the Concentration
  of Popular Forces (CFP) was elected president. Ecuadorian politics
  includes many populist parties. The most relevant ones are CFP, PRE,
  Patriotic Society Party and Alianza PAIS.
title-block-banner: yes

---

# Case notes

## Concentration of Popular Forces 

The inclusion of the CFP is problematic due to the fact that most
analysis of the party stop in 1981, when both of its main leaders, Assad
Bucaram and Jaime Roldós, died. The party still competed in elections in
later years and surpassed the 5% barrier in 1984, 1986 and 1988.
However, there is very little information about this party during this
period. The following analysis assumes that the CFP's historical trend
continued into the 80s. To explain the party's ideology some historical
background is needed.

Concentration of Popular Forces (CFP) was founded in 1944 by Carlos
Guevara Moreno. During the 60s and 70s, Assad Bucaram, of Lebanese
origin, became the undisputed leader of the party. He was barred from
participating in the 1978 elections by the military establishment
because he was accused of not being born in Ecuador (Martz 1983, 33).
Jaime Roldós, who was married to Bucaram's niece, was elected as the CFP
candidate under the motto "Roldós to government, Bucaram to power.\"
(Martz 1983, 37) and won the elections in a ticket with Oswaldo Hurtado.
Roldós "expanded upon the techniques already developed by CFP leaders"
by cultivating an image of the suburbs (Sosa-Buchholz 1999, 151),
however, soon a conflict arose between Roldós and Bucaram that divided
the party. The untimely deaths of both leaders in 1981 did not help to
resolve the crisis. The Roldosist faction created a new party
paradoxically led by Assad Bucaram's nephew, Abdalá Bucaram (see below),
while the Bucarism faction remained under the leadership of Ángel
Duarte. Duarte had been a minister in government prior to the military
regime and led the party in the 1984 and 1988 presidential elections
(INSIDER = 2). It is reasonable to assume that there is strong
continuity in discourse during the Duarte years given that the party had
a very strong populist tradition and that we have found no reference to
a change in positions.

The CFP ran on a populist platform promising to break "the tradition of
political manipulation of the people" (Sosa-Buchholz 1999, 148) and it
is widely considered a clear example of a populist party (Martz 1983).
The party concentrated most of its power in the poor suburbs of
Guayaquil and their leaders "refused to identify themselves with the
left, right or center", emphasizing instead Ecuadorian popular ideology
and the connection with the "*jefe máximo*" or supreme leader
(Sosa-Buchholz 1999, 148). Roldós stated very clearly that:

> Unquestionably those responsible for exploitation are the great
> economic sectors which have unlawfully kept a series of privileges by
> means of subsidies to businesses... and tax write-offs. Such sectors
> have not been properly taxed in Ecuador. These sectors, which have not
> been placed at the service of the community, have definitively created
> what we term a criollo oligarchy. And they have been equally in
> contact with international sectors dedicated to creating in the
> country a totally dependent economy \.... Unquestionably the Chambers
> of Production are in some measure expressions of that criollo
> oligarchy, because at their highest levels they represent the interest
> of those economic sectors (Nueva, May I978:61-62). (quoted in (Martz
> 1983, 35)

We have thus coded the CFP as 3 in OTH_POLCLASS, OTH_FOREIGN and
OTH_ECONOMIC. Roldós defined himself in the centre-left (LRPOSITION =
CL):

> We may define ourselves as men of the left, in that we propose
> structural changes. We are not in agreement with existing structures
> \.... we believe in giving private enterprise the possibility for full
> development, but certainly within the conditions established in\...
> the new constitution. Thus, if we established qualifications and
> categories within the left, we would be center-left (El Universo, July
> 2, 1978:1) (quoted in (Martz 1983, 44).

Duarte did not have the charisma of his predecessors and the party would
have existed without him (CHARISMA = 1). We also have not found any
criticism of migrants, ethnic others or violation of established
liberal-democratic norms (OTH_IMMIGRANTS, OTH_ETHNIC, LIBDEMNORMS = 1).

## Ecuadorian Roldosist Party

Abdalá Bucaram, nephew of Assad and brother-in-law of Roldós, led the
division of the CFP and created a new party; the Ecuadorian Roldosist
Party (PRE). He is considered one of the most important populist figures
in Ecuador (De La Torre 1997; Sosa-Buchholz 1999; Ulloa 2017). Abdalá
became the mayor of Guayaquil and then presented his candidacy to the
presidential election in 1988, 1992 and 1996, finally winning that last
year. Abdalá was known as "*el loco*", the crazy one, and presented
himself as a passionate politician who did not abide by the etiquette of
traditional politicians (Ulloa 2017, 101). "He challenges their
respectability \[of the elite\] by glorifying the qualities of the
people, insulting his rivals, and acknowledging and accentuating his own
ugliness" and employed "simple, humorous, direct, and authentically
popular language" (De La Torre 1997, 17; Moreano y Donoso 2006). His
ideological basis was summed up in one of his campaign slogans: "Only
one ideology, against the oligarchy" (Sosa-Buchholz 1999, 153). As he
stated once: "The oligarchy is an amorphous entity, an insensitive and
exploitative system, an anti-Christian system. \... I think that the
oligarchy is everywhere" (Bucaram 1990, 24). De la Torre argues that the
oligarchy is incarnated mainly in rival politicians thus, for example,
"in the 1988 elections, Bucaram presented himself as the child of Christ
in struggle against 'the devil,' \[Socialist leader\] Rodrigo Borja" (De
La Torre 1997, 16). Bucaram employed a moralistic language to frame the
struggle between the people and the elite and contrasted the effeminate
nature of the elite with the virility of the Ecuadorian people (De La
Torre 1997, 16) (OTH_ECONOMIC = 3, OTH_POLCLASS = 3).

The ideological classification of Abdalá Bucaram is complicated, because
he "presented himself as a rejection of the elites, rather than a clear
project" (De La Torre 1999, 560). Several authors coincide in the
diffuse character of his ideology (Moreano y Donoso 2006; Ulloa 2017).
He has been called a neopopulist because "he campaigned with a leftist
discourse but implemented neoliberal measures during his government and
formed his team with members of the oligarchy" (Ulloa 2017, 118). He ran
on the promise to improve the living conditions of the poor
(Sosa-Buchholz 1999, 153) and had as a campaign slogan "the strength of
the poor" (Ulloa 2017, 117). In government, he applied personalistic
measures such as the "Abdalact, cheap milk for Guayaquil's *suburbios*,
of free back-packs and textbooks, notebooks and pencils bearing the
president's name for poor students" (Sosa-Buchholz 1999, 154). However,
not only did he never question capitalism (De La Torre 1997, 18), he
even implemented strong neoliberal policies by inviting Domingo Cavallo,
a former Argentinian finance minister, to advise him. He also showed a
great degree of pragmatism forming coalitions with other parties or
including members of the former conservative government into his
cabinet. We have decided to code him as CL on LRPOSITION to reflect his
pro-poor policies, although it should be noted that, as other populists
in the 1990's, he shifted significantly once in government.

Although the military did not form the main target of his attacks, he
criticized it considerably. In 1985, he flew to Panamá because he was
sentenced to four days in prison for saying that the military "had no
other use than spend money and march in civic celebrations"
(OTH_MILITARY = 2). Abdalá tried to "incarnate the representation of
Indians, cholos, whites, blacks and mestizos" (Ulloa, 2017: 120), thus,
we have coded 1 for OTH_ETHNIC. We have not found any criticism of
immigrants, in fact, as his family was of Lebanese origin, he used this
background as part of his narrative "he narrates how his humble social
origins as a child of Lebanese immigrants has not prevented him from
becoming a successful lawyer, politician and businessman" (De La Torre
1999, 562) (OTH_IMMIGRANTS = 1).

On his leadership role it is important to point out that the party was
created and led by Abdalá and that he was his candidate in all
elections. Moreover, he used a personalistic style by which he
personified the "real Ecuador". "His propaganda delivered a populist
message of total antagonism between the people, whose will he claimed to
embody, and the evil oligarchy that needed to be crushed. His
commercials started with images of extreme poverty and suffering
provoked by oligarchical governments. Then they presented Bucaram as the
"leader of the poor," the messiah, who will redeem the underprivileged
from misery" (De La Torre 1999, 560) (CHARISMA = 3).

Abdalá was related to both Assad Bucaram and Jaime Roldós and was mayor
of Guayaquil, Ecuador's second most important city, before running for
president in 1988. Therefore, he can be considered as a significant
figure in previous governments (INSIDER = 2). We have not found
references or significant attacks on foreign powers or interests
(OTH_FOREIGN = 1). Although several authors point to his "lack of
respect for the rights of others" (De La Torre 1997, 19) or his
clientelism (Acosta 1996), he did not deviate significantly from the
liberal-democratic norms of other parties. He entered into pragmatic
coalitions with other parties, thus reproducing the existing political
system he criticized (Ulloa 2017, 118). He is said to have "never
surpassed the frame of representative democracy (Ulloa 2017, 118) and
did not "criticize the mass media, as Correa and Chávez do" (Ulloa 2017,
284) (LIBDEMNORMS = 1). In fact, when his economic austere policies
resulted in widespread opposition, he was impeached by the parliament
under the vague pretext of his mental incapacity and was substituted by
an 'interim president' a novel move for Ecuadorian politics of dubious
constitutionality. A new constitution was approved, and elections
followed in 1998.

With its leader gone and new elections coming soon, the PRE had to find
a replacement and Álvaro Noboa was chosen as the presidential candidate
for the 1998 elections. He was one of the most successful businessmen in
Ecuador. Nevertheless, he lost that election and then founded the
Institutional Renewal Party of National Action, or PRIAN and ran for
president in all elections until 2013, coming in second place in 2002
and in 2006. Noboa has sometimes been described as a populist (Nohlen
2005, 372), however, his classification as such is contentious. Although
he cultivated an image of a political outsider, in 1998, he stressed his
technical abilities in management and differentiated himself from Abdalá
Bucaram (Noboa 2010). More importantly, as Carlos de la Torre argues,
Noboa lacks the Manichaean confrontation between the people and the
power in his discourse (Ecuadorinmediato 2006). He is better described
as a personalistic leader than as a populist candidate. Thus, we have
not included him in the dataset.

We have, however, included the party in the dataset since the party's
position did not change after Abdalá left office. In the 2002 elections,
the last in which the party obtained more than 5% of the vote, the party
was led by Jacobo Bucaram, Abdalá's older brother. Jacobo was a
sportsman and university chancellor who had been part of Jaime Roldós
government (although not in ministerial role), became vice-president of
the Congress between 1992 and 1993 and was major of the city of Milagro.
He was known in the country for beating Congressman Jamil Mahuad (who
would later become president). Due to his political career as
vice-president of the congress and brother of the president we have
codified him as a 2 on INSIDER. He was in favour of the construction of
a united Latin American currency that would help redistribute wealth and
combat the problem of insecurity (BBC Mundo 2002). He also wished to
renegotiate Ecuador's debt with the IMF and promote an agrarian
revolution (BBC Mundo 2002). We have also keep the same code for
CHARISMA = 3, as it was understood that he stood in replacement of his
brother.

## Lucio Gutiérrez and the Patriotic Society Party

Lucio Gutiérrez was an unknown coronel without political experience
(INSIDER = 1) who became famous nationwide because of a coup d'état, in
a similar fashion to Chávez in Venezuela. In January 2000, in the midst
of a deep economic crisis, several factions of the military allied with
indigenous movements to overthrow the government of President Mahuad. As
(Gutiérrez 2013a) then declared: "from now on you, the people, will
always be put first and those who have benefited from the people must
step aside". However, the military was not able to hold power and
Mahuad's vice-president was elected president. Gutiérrez was briefly
arrested and later founded the Patriotic Society Party to run for the
presidency in the 2002 elections.

De la Torre argues that Gutiérrez "employed the populist rhetoric of
confrontation between the people, whom he said he represented, against
the oligarchy, symbolized by the corrupt politicians" (De La Torre 2008,
201) (OTH_POLCLASS = 3, OTH_ECONOMIC = 3). He also exploited the image
of the military man as a man of the people who would not sell himself to
"antinational interests" as well as his humble origins (De La Torre
2008, 202) (OTH_MILITARY = 1). We have seen no reason to code above 1
for OTH_FOREIGN.

The ideological classification of Gutiérrez is not easy because he was
able to "reconcile opposed tendencies as well as had an enormous
flexibility to transform himself" (Montúfar 2008, 269). He has been
described as a neopopulist because of his popular rhetoric before
achieving power and his neoliberal policies once in government (Ulloa
2017, 102). He campaigned on a leftist platform, particularly concerned
with the indigenous movement's claims. Moreover, he campaigned against
neoliberal measures (De La Torre 2008, 206). He was, however, less
leftist than Chávez, as he himself stated "I admire the courage of
Chávez... for challenging a corrupt government. I did the same in
Ecuador. But I am not a communist. I am deeply Christian and respect
private property and human rights" (El País 2005). However, once in
power, he soon broke his alliance with leftist and indigenous parties
and supported himself with right-wing parties (Ulloa 2017, 124). He then
applied measures dictated by the IMF and appointed technocrats with ties
to the business powers (Burbano de lara 2003). We believe the best
classification for is to code LRPOSITION as Centre Left in 2002 and
Centre Right in 2006 under Gilmar's leadership.

His political platform was strongly based on the indigenous movements,
which he identified as the main component of "the people" (De La Torre
2008, 218) and he did not attack immigrants. (OTH_IMMIGRANTS and
OTH_ETHNIC = 1).

The Patriotic Society Party was created by Gutiérrez as a platform to
run for president. The party did not do well in the legislative
elections (2.5% of the vote share), which gives an idea of the lack of
relevance of the party compared to the figure of its leader. The party
later changed its ideological position when Gutiérrez did, which implies
that it did not have a solid ideological basis apart from being
Gutiérrez's platform. We have therefore coded the party 3 on CHARISMA,
since Gutiérrez's populism was entirely based on his persona.

Gutiérrez's violation of Liberal Democratic norms was patently evident.
He became known in his country through a coup d'état against the elected
president. His downfall also showed his lack of respect for democratic
norms. Due to corruption scandals, Gutiérrez's alliance with the
conservative parties broke down, and he decided to seek the help of the
PRE and Álvaro Noboa. He then proceeded to substitute judges in the
Supreme court and those judges declared null the charges against Abdalá
Bucaram. Massive protests followed and Gutiérrez declared the state of
exception and sacked the Supreme Court judges. This was seen as an
authoritarian intervention against judicial independence and, finally,
in 2005, the congress voted to substitute Gutiérrez with his
vice-president, who also had become extremely critical of Gutiérrez's
measures. We have coded him and the party 3 in LIBDEMNORMS.

In the 2006 elections, Gutiérrez was expecting to run for president, but
the Supreme Court removed his political rights for two years. His
brother Gilmar, who also had participated in Gutiérrez's 2000 military
coup and had been a congressman, had to run instead. Given his personal
ties with his brother we have coded 2 in INSIDER 3 in CHARISMA because
he was simply temporarily substituting Lucio Gutiérrez.

Lucio was, however, able to run in 2009 and 2013 and was the undisputed
leader of Patriotic Society Party since he founded the party (3 in
CHARISMA and INSIDER). During this time, his rhetoric was focused on his
opposition to Rafael Correa. Gutiérrez did not lose his populist
rhetoric, but the elite was now embodied by the government of Correa
whom he accused of corruption (Gutiérrez 2013b). Lucio called into
question the transparency of the elections and criticized Correa for
participating in the coup d'état that overthrew his "democratically
elected government, thus violating the will of the people" (Gutiérrez
2013b). Gutiérrez was also a critic of Correa's closure of media outlets
and called into question the impartiality of the Ecuadorian
institutions, saying that they only benefited the president but not the
people (Gutiérrez 2013c).

Gutiérrez continued running a populist platform of difficult ideological
classification. As Bowen argues, he "generally eschewed well-defined
platforms in favor of personalistic appeals" and "attempted, with some
success, to mobilize clientelist networks that he had built during his
period as president" (Bowen 2010, 187). However, he moved from his
initial leftist positions to become a critic of Correa's progressive
policies. He argued for the lowering of taxes (Gutiérrez 2012) and had
become, paradoxically, "the preferred candidate among the country\'s
economic elite who see him as the only candidate capable of challenging
Correa" (Bowen 2010, 189). Thus, although he continued to be a populist
leader, his definition of elite radically changed, and we could argue
that his populism is mainly directed against a political elite (Correa
and his government) and not anymore anti-economic class or anti-foreign
interest. Therefore, we have changed both OTH_ECONOMIC and OTH_FOREIGN
to 1 and kept LRPOSITION to CR in all subsequent elections.

## Rafael Correa and PAIS Alliance

Rafael Correa, who obtained his PhD at the University of Illinois, was a
professor of economics in Ecuador when he entered politics. Probably
because of his technocratic profile, he was called by Alfredo Palacio to
be Minister of Economy after the downfall of Lucio Gutiérrez. "He was
the ultimate outsider---a college economics professor who had never even
belonged to a party" (De La Torre 2013, 35). He remained only four
months in the post because he disagreed with the free-trade policies of
the government. He then created the movement Alianza PAIS (Patria Altiva
i Soberana) or PAIS Alliance (Proud and Sovereign Homeland) and won the
2006 elections. Although he was a minister, we have coded him 1 on
INSIDER because his time as minister was very brief and previously, he
had no political experience or public exposure.

His platform has been repeatedly compared to that of Hugo Chávez (De La
Torre 2013; Ulloa 2017). Correa argued for a "citizens revolution" that
called "for the closure of Congress followed by elections for a
constituent assembly that would write a new basic law. The underlying
goal was to break the 'partidocracia' or system of domination by
political parties" (De La Torre 2013, 36). Since his intention was to
call for a constituent assembly that would create a new constitution and
change the way the political system worked up until then, PAIS Alliance
did not present any candidate for the legislative body. This indicated
his aim to connect directly with the people, bypassing the formal
institutions of representation. Ulloa points out the importance of
Correa's charisma and the concentration of party power in his hands
(Ulloa 2017, 127) (CHARISMA = 3).

His aim was to "refound the homeland" to achieve "a radical and rapid
change in the existing structures of Ecuadorean society, in order to
change the bourgeois state into a truly popular one" (Correa 2012). In
his inaugural speech, he claimed that Ecuador needed to "get its
homeland back" (Correa 2006a) and argued that, under his government,
"the fatherland was no longer for sale" (Correa 2006a). "Correa
presented himself as a leftist candidate, anti-international credit
organizations, defendant of sovereignty; he employed an anti-political
discourse that was, above all, anti-party" (Ulloa 2017, 128). Correa
defined himself as a "socialist from a Christian, not Marxist, source; I
like to define myself as a leftist Christian humanist" (Correa 2006b)
whose platform was based primarily on fighting corruption and reversing
neoliberal policies. He claimed that "we will never forget the crimes of
the corrupt bankers who bankrupt us" (Correa 2006a). Moreover, he stated
that neoliberal policies whose "consequences have been disastrous" "were
not only imposed but were also enthusiastically applauded by our elites"
(Correa 2006a). Thus, Correa promised a second Independence of Ecuador
(De La Torre 2013, 44) by which "Ecuador will become independent from
international organizations, that represent foreign paradigms and
interests" (Correa 2006a). The most appropriate coding for Correa seems
to be FL in LRPOSITION, and 3 for OTH_POLCLASS, OTH_ECONOMIC, and
OTH_FOREIGN.

Correa had good relations with the military at the beginning of his
presidency and although it later deteriorated due to spending cuts
(Flores 2016), the military was not a target of his populist speech
(OTH_MILITARY = 1). Another of the pillars of Rafael Correa's platform
was what in Quechua is called the "*sumak kawsay*, which literally means
'the life well lived'" (De La Torre 2013, 39). The concept "comes from
indigenous cosmology, and aims to build 'the good life,' understood as
non-Western relationships between society, nature, and development." (De
La Torre 2013, 39). This pillar was concretized in Ecuador's new
constitution with the definition of the country as 'plurinational' and
the inclusion of "nature rights". Additionally, Correa included a leader
of the indigenous movement as president of the constituent assembly and
finished his inaugural speech with some words in Quechua (Correa 2006a).
His relations with the indigenous communities deteriorated later due to
disagreements over mineral extraction. The indigenous communities were
opposed to these extractions, but Correa's government thought them
necessary for the independence of the country (De La Torre 2013, 41).
However, neither immigration nor other ethnic communities were ever
identified by Correa as part of the elite or were targets of "othering"
rhetoric (OTH_ETHNIC and OTH_IMMIGRANTS = 1).

Although Correa claimed to seek the democratization of Ecuador, his
actions in government fall short of his electoral promises (De La Torre
2013; Ulloa 2017). Moreover, he launched several attacks on the media
because, as he put it "the media have always been one of the de facto
powers that have dominated Latin American countries" (quoted in (De La
Torre 2013, 42)). Members of 'El Universo' were convicted of defamation
for an editorial they wrote, and the newspaper was heavily fined as
well. Moreover, every week Correa hosted 'Enlace Ciudadano' a three-hour
show in which he criticized the media's representation of his government
treating them as political actors (Ulloa 2017, 289). Insults and mocking
of other political leaders were very common in his shows.

Furthermore, his call for a constituent assembly has been questioned for
its legality (Ulloa 2017, 136-37). That possibility was not one of the
prerogatives of the president in the constitution and it completely
bypassed the legislative body. However, he went ahead with his plans due
to his massive popular support. De la Torre argues that Correa
represents a case of "soft authoritarianism" similar to that of Chávez
(De La Torre 2013, 22). Taking into consideration his attacks on the
press, we have coded him as 2 in LIBDEMNORMS.

Carlos de la Torre points out that Correa, himself an "expert" in
economics as an academic, exhibited a kind of technocratic populism by
which he had the knowledge to rebuild his nation and bring progress and
modernization (De La Torre 2018, 39). Thus, he combined technocracy with
populism. Lenín Moreno, vice-president during most of Correa's years in
power and UN special delegate on disability issues would represent this
technocratic element in his government. Moreno won the 2017 elections
with PAIS Alliance. Moreno had a leftist ideology and continued with
many of Correa's policies; however, he was less charismatic than his
predecessor and did not employ the level of confrontational rhetoric
that Correa used. Although many saw him as the marionette of Correa, he
soon started to differentiate himself from Correa in what De la Torre
calls Ecuador's "perestroika" (De La Torre 2018). Moreno strongly
persecuted corruption, removed the asylum to Julian Assange and engaged
in a dialogue with all political forces, including Right-wing parties;
actions that were strongly criticized by Correa. Moreno's case can be
compared to that of Juan Manuel Santos in Colombia and his relationship
with Álvaro Uribe, where a non or less-populist leader inherited the
party that the populist leader created. Following the criteria used with
Santos and acknowledging that Moreno has inherited mainly Correa's
ideological basis but not so much his populism, we have not included him
in the dataset. We have, however, included Alliance PAIS in the
legislative elections to show that the party was still very much
influenced by Correa's personality. We have not changed the INSIDER and
CHARISMA coding given that we see the 2017 election as a continuation of
the leadership of Correa.

## Not included 

The **Popular Democratic Movement** (MPD) is not included in the dataset
because it has been described as a "traditional party" based on a
communist and Maoist ideology (De La Torre 2013, 34-35) with strong
connections with the country's unions. Although it briefly supported
Lucio Gutiérrez and Rafael Correa, it later became part of the
opposition to these populist leaders. None of the sources consulted
describes this party as populist.

**References**

Acosta, Alberto. 1996. «Ecuador. El bucaramismo en el poder». *Nueva
Sociedad* 146: 6-16.

BBC Mundo. 2002. «Los Que Quedaron Atrás». *BBC Mundo*.
http://news.bbc.co.uk/hi/spanish/specials/cambio_de_mando_en_ecuador/newsid_2500000/2500965.stm#5
(16 de noviembre de 2023).

Bowen, James D. 2010. «Ecuador's 2009 Presidential and Legislative
Elections». *Electoral Studies* 29(1): 186-89.

Bucaram, Abdalá. 1990. *Bucaram, A. (1990) Las verdades de Abdalá.*
Quito: Editorial El Duende.

Burbano de lara, F. 2003. «Lucio Gutiérrez, la política indígena y los
frágiles equilibrios en el poder». *nuario Social y Político de América
Latina y el Caribe* 6.

Correa, Rafael. 2006a. «Discurso de Posesión de Rafael Correa Presidente
del Ecuador».
https://web.archive.org/web/20090304151840/http://www.rafaelcorrea.com/la_noticia/942/Discurso%20de%20Posesi%C3%B3n%20de%20Rafael%20Correa%20Presidente%20del%20Ecuador
(16 de noviembre de 2023).

---------. 2006b. «Perfil de Rafael Correa». *YouTube - alianzapais35*.
https://www.youtube.com/watch?v=I8aSHojROqY (16 de noviembre de 2023).

---------. 2012. «Ecuador's Path». *New Left Review* (77): 89-104.

De La Torre, Carlos. 1997. «Populism and Democracy: Political Discourses
and Cultures in Contemporary Ecuador». *Latin American Perspectives*
24(3): 12-24.

---------. 1999. «Neopopulism in Contemporary Ecuador: The Case of
Bucaram's Use of the Mass Media». *International Journal of Politics,
Culture and Society* 12(4): 555-71.

---------. 2008. «Carlos de la Torre Protesta y democracia en ecuador la
caída de lucio Gutiérrez». En *Luchas contrahegemónicas y cambios
políticos recientes de América Latina*, eds. Margarita López Maya,
Nicolás Iñigo Carrera, y Pilar Calveiro. Buenos Aires: CLACSO.

---------. 2013. «Technocratic Populism in Ecuador». *Journal of
Democracy* 24(3): 33-46.

---------. 2018. «La perestroika de Lenín Moreno en Ecuador». *Letras
Libres*.
https://www.letraslibres.com/espana-mexico/politica/la-perestroika-lenin-moreno-en-ecuador.

Ecuadorinmediato. 2006. «Noboa es un neo populista con riesgo de que
aglutine poderes». *Ecuadorinmediato*.
http://www.ecuadorinmediato.com/index.php?module=Noticias&func=news_user_view&id=43490.

El País. 2005. «El coronel que no se parece a Chávez». *El País*.
https://elpais.com/diario/2005/04/19/internacional/1113861613_850215.html
(16 de noviembre de 2023).

Flores, Thalía. 2016. «Rafael Correa llama a los soldados del Ejército
ecuatoriano a rebelarse». *Diario ABC*.
https://www.abc.es/internacional/abci-rafael-correa-llama-soldados-ejercito-ecuatoriano-rebelarse-201609131620_noticia.html
(2 de noviembre de 2023).

Gutiérrez, Lucio. 2012. «Expresidente Lucio Gutiérrez inscribe su
candidatura a la presidencia de Ecuador». *YouTube - NTN24*.
https://www.youtube.com/watch?v=vZTYR3K8jks (16 de noviembre de 2023).

---------. 2013a. «((👊)) ¿Derrocado? - El día que cayó Mahuad y subió
Gutiérrez (2000) \| HISTORIA VIVA». *YouTube - ROBINSON ROBLES*.
https://www.youtube.com/watch?v=5Up6pZtUBJ8 (16 de noviembre de 2023).

---------. 2013b. «Entrevista Lucio Gutiérrez - Contacto Directo».
*YouTube - Ecuavisa Contenido*.
https://www.youtube.com/watch?v=hB3CPfIZUm0 (16 de noviembre de 2023).

---------. 2013c. «Inicio de Campaña de Lucio Gutiérrez - 3 PSP».
*YouTube - La República EC*. https://www.youtube.com/watch?v=p4sIOxW9TY4
(16 de noviembre de 2023).

Martz, John D. 1983. «Populist Leadership and the Party Caudillo:
Ecuador and the CFP, 1962--81». *Studies In Comparative International
Development* 18(3): 22-49.

Montúfar, C. 2008. «EL populismo intermitente de Lucio Gutiérrez». En
*El retorno del pueblo*, eds. Carlos De La Torre y E. Peruzzotti. Quito:
FLACSO, 267-98.

Moreano, Hernán, y Claudia Donoso. 2006. «Populismo y neopopulismo en
Ecuador». *Revista Opera* 6(6): 117-40.

Noboa, Álvaro. 2010. «ALVARO NOBOA - RODRIGO BORJA - FREDDY ELHERS».
*YouTube - VIDEOLATINOMUSICAL*.
https://www.youtube.com/watch?v=A5Os85QXynU (16 de noviembre de 2023).

Nohlen, Dieter, ed. 2005. *Elections in the Americas: A Data Handbook*.
New York: Oxford University Press.

Sosa-Buchholz, X. 1999. «The Strange Career of Populism in Ecuador». En
*Populism in Latin America*, ed. M. Conniff. London: The University of
Alabama Press.

Ulloa, César. 2017. *El populismo en escena: ¿Por qué emerge en unos
países y en otros no?* Quito: Unidad Editorial de FLACSO Ecuador.
https://revistas.iaen.edu.ec/index.php/estado_comunes/article/view/41
(14 de septiembre de 2023).
