---
title: El Salvador
subtitle: |-
  Date range: 1984-2020
  <br>
  El Salvador suffered a Civil War from 1980 until 1992. During the first
  years, the conflict pitted the military-led Junta that governed the
  county against the FMLN (Frente Farabundo Martí para la Liberación
  Nacional or Farabundo Martí National Liberation Front). The FMLN was an
  umbrella organization that coordinated, at least, five left-wing
  guerrilla groups. El Salvador approved a new constitution in 1983, held
  its first democratic and direct elections in 1984, and reached a peace
  agreement with the FMLN in 1992. The Chapultepec Peace Accords included
  the demobilization of armed forces and the legalization of the FMLN as a
  political party. Since the 1994 presidential elections, the FMLN become
  the main left-wing party in the country. In 2019, for the first time in
  decades, a candidate not belonging to any party, Nayib Bukele, won the
  presidency.
title-block-banner: yes

---

# Case notes

## Nayib Bukele

Nayib Bukele became president of El Salvador in 2019. He is a former
businessman of Palestinian origins who once belonged to the FMLN. With
this party, he became the mayor of the capital, but he did not take part
in the national government of the FMLN (INSIDER = 1). He created a new
party in 2017 and was subsequently expelled from the FMLN. The new
party, however, was forbidden by the courts to run in the 2019 elections
because the inscription period had already pass. Bukele decided, then,
to be the presidential candidate of GANA, a right-wing party. Bukele
argued that he used that party only as a necessary means to an end (ABC,
2019).

Bukele is widely considered a populist in the literature (Díaz González,
Ulloa, y Mora Solano 2022; Nilsson 2022; Roque 2021; Wolf 2021) and the
main axis of his campaign consisted of presenting himself as an outsider
who will fight the corruption of the two ruling parties (Gaviña 2018).
"Bukele blamed both parties for the country's precarious security
situation, lack of economic opportunities, and depleted public finances.
Under the campaign slogan "Return what you stole," he promised
transparency and an end to corruption" (Wolf 2021, 64). He defended that
"this battle is for every person from El Salvador that has been ignored
by their governments" (Bukele 2019a) and used short mottos such as
"there is enough money when nobody steals it" to depict the previous
governments as corrupt (OTH_POLCLASS = 3).

It is difficult to pin down Bukele's ideology. Some argue that he is a
"classic populist" for which the categories of left and right are not
useful anymore (González Díaz 2019). He framed his policies as
"'pragmatic' ideas, which sought to move away from the ideological
debate of right and left" (Díaz González, Ulloa, y Mora Solano 2022,
40). He ran on a platform based on bashing traditional politicians and
promising to solve El Salvador's security issues (Nilsson 2022, 16). We
have decided to code him as Centre in LRPOSITION as to show that he
draws from a variety of ideological sources.

Being himself from a wealthy family and having worked as a businessman
in the field of marketing, Bukele aimed at creating a productive economy
for El Salvador that would improve the conditions of the country. He did
not display animosity against the financial elite but defined the elite
in primarily political terms (OTH_ECONOMIC = 1). Regarding foreign
actors, Bukele repeated constantly his desire to "re-establish, improve
and increase relations with the US" (Bukele 2019b). Bukele did not
display any antagonism against any other country but harshly criticized
Maduro's (Venezuela) and Ortega's (Nicaragua) governments for using
force to remain in power (González Díaz 2019), which contrasts with the
position taken by Sánchez Cerén (OTH_FOREIGN = 1). Being himself of
migrant origins Bukele made no negative mention of incoming migrants or
ethnic groups (OTH_ETHNIC and OTH_IMMIGRANTS = 1). The fact that Nayib
Bukele presented himself as the candidate of a party with a different
ideology, based the campaign solely on his figure and still won the
election in the first round, shows the extreme importance of the
personality of the presidential candidate (CHARISMA = 3).

Bukele's actions in government have been widely described as
authoritarian (Nilsson 2022; Wolf 2021). He has imprisoned tens of
thousands of people as part of his anti-gang policies and "in a veiled
threat to those who interfere with his political agenda, he frequently
proclaims that "nobody will stand between God and the people" (Wolf
2021, 64). He "has also launched relentless attacks on press freedom"
(Wolf 2021, 65). However, we found little indication of a significant
violation of liberal democratic norms prior to holding office. He did
throw an apple to a member of the Municipal body and there have been
some reports of his team faking a newspaper website (Roque 2021, 242-43)
but, in general, his election was seen as positive for democracy by
commentators (Díaz González, Ulloa, y Mora Solano 2022, 40). We have
therefore decided to code him as 1 in LIBDEMNORMS.

## Not included:

While the **FMLN** emerged as a party from a far-left guerrilla group
and thus displays an important criticism towards the political system,
its inclusion as a populist party is not clear. At this stage, we have
decided against including the party in the dataset.

Sprenkels (Sprenkels 2019) argues that the party went through an
"ambivalent moderation" in which it was recurrently in internal conflict
between the different factions within it. It should be noted that the
FMLN was far from an ideologically unified party and that it had
numerous internal struggles. (Allison y Martín Alvarez 2012) explain
that the party was torn apart by two main tendencies: on the one side
more ideologically radical "orthodox" or "revolutionary socialists",
which saw peace as the next step towards achieving the revolution and
were more ideologically radical, and on the other side the "moderates"
or "renovators" who argued that the peace was the revolution. In the
internal clashes between these broad tendencies, the hard-liners managed
to hold control of the organization most of the time and this led to up
to three splits from the moderate faction and the creation of new
parties.

Moreover, the FMLN accepted the democratic route to gain power (Zamora
1998, 227) and its first presidential candidate, Rubén Zamora, offered a
discourse of "national reconciliation" (Martinez 1993) based on "small-
and mid-sized business growth, modernization and decentralization of the
state's inefficient bureaucracy, environmental cleanup and water
conservation. \[and\] a healthy boost in education and health-care
budgets" (Martinez 1993). This was also expressed in the campaign ads
that the FMLN run, which stressed positive messaging looking into the
future instead of criticism of other political parties (FMLN 1992;
Zamora 1994). While the "identities as Marxist revolutionary
organizations and their intent on constructing socialism" (Allison y
Martín Alvarez 2012, 99) was still present, that is not enough to
qualify as populist in our dataset and given that we have found very
little reference to their populism in the literature, we have decided
not to include the party in the dataset. Moreover, we have found little
reference in the literature that treat the party as populist (Acosta y
Rogers 2020; Allison y Martín Alvarez 2012; Armando González 2011;
Chinchilla 2009; Lazo M. 1995; Martinez 1993; Sprenkels 2019; Young
2020).

**References**

Acevedo Moreno, Héctor. 2006. «Un FMLN organizado bajo principios
leninistas». Escuela de formación política e ideológica Feliciano Ama
Sonsonate.
https://docplayer.es/19159979-Escuela-de-formacion-politica-e-ideologica-feliciano-ama-sonsonate.html
(2 de noviembre de 2023).

Acosta, Benjamin, y Melissa Ziegler Rogers. 2020. «When Militant
Organizations Lose Militarily but Win Politically». *Cooperation and
Conflict* 55(3): 365-87.

Allison, Michael E., y Alberto Martín Alvarez. 2012. «Unity and Disunity
in the FMLN». *Latin American Politics and Society* 54(4): 89-118.

Armando González, Luis. 2011. «El fmln salvadoreno de la guerrilla al
gobierno». *Nueva Sociedad* 234.

Bukele, Nayib. 2019a. «Speech».
https://www.youtube.com/watch?v=sgExL0vFULI (20 de octubre de 2023).

---------. 2019b. «Una de nuestras más recurrentes promesas de campaña
(la dijimos claramente en cada oportunidad que tuvimos) fue que íbamos a
restablecer, mejorar e incrementar nuestras relaciones con los Estados
Unidos. En estos días, estamos haciendo eso. Primera promesa cumplida.»
*Twitter*. https://twitter.com/nayibbukele/status/1106314873347166208 (2
de noviembre de 2023).

Chinchilla, Fernando A. 2009. «Extremism, Moderation y Gobernanza
democrática en el posconflicto: Las FARC-EP y el FMLN desde una
perspectiva comparada». *\^5 09?A SA.94A W3)q* 53: 129-56.

Díaz González, José Andrés, César Ulloa, y Sindy Mora Solano. 2022.
«Aproximaciones al populismo en Daniel Ortega, Rafael Correa y Nayib
Bukele». *Revista Rupturas*: 49-52.

FMLN. 1992. «Primer spot del FMLN (1992) - YouTube». *YouTube*.
https://www.youtube.com/watch?v=u_AmNQiKaiM (11 de octubre de 2023).

Gaviña, Susana. 2018. «Nayib Bukele: "Yo no negocio con las maras, lidio
con las comunidades donde viven sus familias"». *Diario ABC*.
https://www.abc.es/internacional/abci-niyab-bukele-no-negocio-maras-lidio-comunidades-donde-viven-familias-201811080221_noticia.html
(2 de noviembre de 2023).

González Díaz, Marcos. 2019. «Quién es Nayib Bukele, el joven empresario
millennial que asume como presidente de El Salvador». *BBC News Mundo*.
https://www.bbc.com/mundo/noticias-america-latina-47112057 (2 de
noviembre de 2023).

Lazo M., José Francisco. 1995. «Elecciones y lecciones\... ¿Qué paso en
marzo de 1994?» *Realidad: Revista de Ciencias Sociales y Humanidades*
(43): 109-90.

Martinez, Ruben. 1993. «El Salvador's New Left: A Model for Latin
America : Elections: Ruben Zamora, Facing Increased Death-Squad
Activities, Delivers an Unexpected Message Aimed at National
Reconciliation.» *Los Angeles Times*.
https://www.latimes.com/archives/la-xpm-1993-10-31-op-51576-story.html
(11 de octubre de 2023).

Nilsson, Martin. 2022. «Nayib Bukele: Populism and Autocratization, or a
Very Popular Democratically Elected President?» *Journal of Geography,
Politics and Society* 12(2): 16-26.

Réserve, Roody. 2016. «El Salvador: Un año político y social convulso».
*Revista de ciencia política (Santiago)* 36(1): 177-94.

Roque, Ricardo. 2021. «Nayib Bukele: populismo e implosión democrática».
*Andamios, Revista de Investigación Social* 18(46): 233-55.

Sprenkels, Ralph. 2019. «Ambivalent Moderation: The FMLN's Ideological
Accommodation to Post-War Politics in El Salvador». *Government and
Opposition* 54(3): 536-58.

Wolf, Sonja. 2021. «A Populist President Tests El Salvador's Democracy».
*Current History* 120(823): 64-70.

Young, Kevin A. 2020. «El FMLN de El Salvador y las restricciones sobre
el gobierno de izquierda». *Cuadernos Inter.c.a.mbio sobre Centroamérica
y el Caribe* 17(1): e40496-e40496.

Zamora, Rubén. 1994. «Ruben Zamora FMLN 1994 propaganda - YouTube».
*YouTube*. https://www.youtube.com/watch?v=vRvQOW4jumk (11 de octubre de
2023).

---------. 1998. *El Salvador, heridas que no cierran : los partidos
políticos en la post-guerra*. San Salvador: FLACSO El Salvador.

---------. 2017. «Rubén Zamora habla sobre los Acuerdos de Paz».
https://www.youtube.com/watch?v=uYx\_\_C09dkc (2 de noviembre de 2023).
