---
title: Greece
subtitle: |-
  Date range: 1980-2020**\
  **
title-block-banner: yes

---

# Case notes

## Panhellenic Socialist Movement (PASOK)

The Panhellenic Socialist Movement (*Panhellinion Socialistiko Kinema*,
PASOK) was a left-wing party founded by Andreas Papandreou after the end
of the Greek military Junta in 1974. After rapid growth in the late
1970s the party formed government after winning 48.2% in the 1981
elections and was then re-elected with 45.8% in 1985. PASOK has been one
of the two major parties (the other being New Democracy) in the Greek
party system until that system changed dramatically after the economic
crisis in the 2010s.

While the party eventually became a non-populist centre-left party
(Papathanassopoulos, Giannouli, and Andreadis 2016, 197; see also
Fouskas 1998), it is usually considered to have practiced a kind of
populism in the 1970s and 1980s. That said, deciding when to include the
party is a difficult question, and some comparative populism scholars
(Van Kessel 2015) have chosen to avoid it altogether. On the balance of
evidence of its 1980s rhetoric, we've included the party for the 1981,
1985, 1989 (x2) and 1990 elections, but following Lyrintzis (Lyrintzis
2005, 248, 250) and Spourdalakis and Tassis (Spourdalakis and Tassis
2006, 499) it seems that the party adopted a much more moderate
"modernising" discourse by the 1993 election, after which its original
populism never returned. Katsambekis & Stavrakakis date this transition
to the "early 1990s" (Katsambekis and Stavrakakis 2017, 391).

At its foundation in the 1970s, PASOK was an anti-systemic" "protest"
party (Moschonas 2001, 12) Rather than appealing to one particular
social class (as the Greek communist party did), PASOK appealed to a
broad and vague category of "non-privileged" (Mavrogordatos 1984, 160):
by which it meant "farmers, workers, employees, craftsmen and artisans,
the youth and all the people who are subject to odious exploitation by
modern monopoly capital, local as well as foreign" (cited in Lyrintzis
1984, 111). Conversely, the "privileged"/"establishment" were
represented as an "oligopoly" consisting of local and foreign forces
(Lyrintzis 1984, 668; Mavrogordatos 1984, 160; Katsambekis and
Stavrakakis 2017, 396), including the former Junta and the political
"right" -- byword for the party's political enemies (Pappas and
Aslanidis 2015) (OTH_POLCLASS = 3) (OTH_ECONOMIC = 3).

PASOK made the "foreign factor" -- imperialism and foreign capital --
the enemy (Lyrintzis 1984, 111; Moschonas 2001, 12; Markou 2017, 65--66)
in its populism, and used nationalistic statements like "Greece belongs
to the Greeks" (Papathanassopoulos, Giannouli, and Andreadis 2016, 197).
This rhetoric was positioned in a well-developed narrative relating to
the underdevelopment of peripheral and post-colonial states in the world
economy (Pappas and Aslanidis 2015, 183). It was initially opposed to
membership in the EEC, although this softened in its first term in
office and by 1985 it was pro-accession (Moschonas 2001, 12). These
sentiments gave the party's discourse a strong degree of nationalism
(OTH_FOREIGN =3). There is no evidence of anything that would register
on the OTH_ETHNIC, OTH_IMMIGRANTS and OTH_MILITARY variables (all = 1).

While unambiguously left wing at its outset (Lyrintzis 1984, 111), PASOK
has both drifted to the centre and engaged in ideological vagueness
(Lyrintzis 1987, 667) in its program. We've coded the party's LRPOSITION
as L in its first two elections and CL after its embrace of austerity
following the 1985 election. The party was never internally democratic,
and "the personality and charisma of Papandreou influenced powerfully
its development and nature" (Lyrintzis 1984, 111--12, 114; see also
1987, 668; Mavrogordatos 1984, 160; Pappas 2014, 9--10) (CHARISMA = 3).
We have coded it 3 on INSIDER after the 1981 election, before which it
was a 2, as Papandreou had served in senior positions in the government
in the 1960s).

According to Pappas and Aslanidis,

> Successive PASOK governments developed an ever-growing disrespect for
> political liberalism and its institutions, which, as the current logic
> went, could be compromised, impaired, or otherwise twisted as long as
> it was in favour of realising popular supremacy. Following that logic,
> institution building ceased to be a priority, and an understanding of
> institutions as means of achieving the gratification of the people was
> put firmly in place. (Pappas and Aslanidis 2015, 185)

Although we've seen no evidence that this reached the level of a
critical threat to democracy itself, we've coded the party 2 on
LIBDEMNORMS.

## The Popular Orthodox Rally (LAOS)

The Popular Orthodox Rally (*Laikos Orthodoxos Synagermos*, LAOS) was an
ultra-nationalist party founded in 2000 by George Karatzaferis, a
renegade journalist and former member of the centre-right New Democracy
(ND) party. It launched amid a controversy relating to the PASOK
government's removal of religious affiliation from Greek national
identity cards, a move strongly opposed by the Orthodox Church. The
party only breached the 5% mark in the 2009 election, before collapsing
totally after its support for the unpopular bailout in 2011, after which
most of its key politicians were absorbed into ND.

LAOS engaged in anti-establishment politics, accusing the "rotten
establishment" of both PASOK and ND (the two dominant parties at the
time) of enslaving the country to its enemies (Ellinas 2012, 131;
Katsambekis and Stavrakakis 2017, 399; Verney 2004, 21). Unlike "all the
others" in the political sphere, LAOS stressed its own absolute fidelity
to "the people" in classically populist terms (Pappas and Aslanidis
2015, 186) (the word "laos" even means "people" in Greek). While this
clearly suggests an OTH_POLCLASS coding of 3, according to Katsambekis &
Stavrakakis, (Katsambekis and Stavrakakis 2017, 400) LAOS engaged in an
office-seeking strategy to win power in 2009 (the only election included
in the dataset), employing a much softer rhetoric against the other
parties. On this basis we've coded it 2 for the 2009 election, however
this should be reviewed. In advancing nationalist claims about the
people's sovereignty, opposition to foreign influence in a number of
forms was particularly relevant to LAOS. The party suggested that PASOK
and ND were overly-deferential to the US (Ellinas, 2012:130), and was
uncompromisingly critical of other traditional foreign enemies of Greece
such as Turkey and North Macedonia (Ellinas 2012, 130; Bistis 2013, 38)
(OTH_FOREIGN = 3).

LAOS also constructed "the people" and their "others" in explicitly
ethnocentric and religiously sectarian terms (Georgiadou 2013, 83;
Katsambekis and Stavrakakis 2017, 399). As its name suggests, it
presented itself as the political wing of the Orthodox Church
(particularly of its leader Archbishop Christodoulos, who was something
of a populist in his own right) (Papastathis 2015, 233). Antisemitism
was one of its recurring themes in this regard, with Karatzaferis
suggesting in 2000 that Greece was "run by Jews" (Ellinas 2012, 130). It
also practiced a strong hostility toward Muslims (Ellinas 2012, 130;
Lazaridis and Tsagkroni 2016, 211) (OTH_ETHNIC = 3). It was also
strongly opposed to immigration, proposing to use state funds to
resettle immigrants back in their home countries (Lazaridis and
Tsagkroni 2016, 207; Doxiadis and Matsaganis 2012, 53;
Papathanassopoulos, Giannouli, and Andreadis 2016, 207; Katsambekis and
Stavrakakis 2017, 399) (OTH_IMMIGRANTS = 3).

It is universally considered to be far right in the literature (Doxiadis
and Matsaganis 2012, 53; Lazaridis and Tsagkroni 2016; Bistis 2013) even
though it has included some more moderate members of the right and
exhibited a degree of ideological "ambiguity" (Georgiadou 2013, 84)
(LRPOSITION = FR). Key to this ambiguity was its approach to welfare
policy and attacks on the financial elite. While LAOS had been generally
free-market and a proponent of lower tax cuts, by the 2009 election the
party dropped its tax liberalism (Bistis 2013, 39), and according to
Ellinas, (Ellinas 2012, 131) "LAOS makes a significant effort to appeal
to leftist voters, especially low-earning workers, through fierce
populist attacks on globalization, foreign chains and commercial banks"
(see also Georgiadou 2013, 83). Karatzaferis actually considered his
party left-wing on social issues, and used his first speech in
Parliament to declare that "Bankers are thieves, Mr Prime Minister, and
you must send the attorney in to check on them" (cited in Ellinas 2012,
131) (OTH_ECONOMIC = 3).

There can be little doubt that the personal charisma of Karatzaferis was
essential to the party's identity, and that it was built on a generally
"personalistic structure" (Dinas 2008, 605) (CHARISMA = 3), and although
he was an ND MP before founding the party, this level of power should
not escalate the party to a 2 on INSIDER (= 1). The party is difficult
to code on LIBDEMNORMS: its character seems of a keeping with illiberal
far-right parties in Europe, but we've seen no evidence in the secondary
literature that it practiced any violence (this absense is inferred by
Roushas 2014, 10), or showed particular hostility to liberal state
institutions that could be considered a threat to liberal democratic
norms, and hence we've coded it 1 for now.

## The Independent Greeks (ANEL)

Independent Greeks (*Anexartitoi Ellines*, ANEL) was a right-wing
populist party led by Panos Kammenos, who -- similar to Karatzaferis and
LAOS -- split from ND to form the party in 2012. It rose to prominence
after opposing the 2012 bailout (which LAOS supported), drawing on
nationalist themes to poll 10.6% in the 2012 elections. After this
success it joined an unlikely "populist coalition" with Syriza, with
which it was in government until 2019, when it withdrew due to
disagreements over the Macedonian naming compromise. It did not
participate in the 2019 elections.

In the context of the financial crisis, Kammenos accused the whole
political class of corruption and disloyalty to the people, asserting
that the major parties are involved in a decades-old "pact" to hand the
wealth of the country to foreign forces (Pappas and Aslanidis 2015, 192;
Doxiadis and Matsaganis 2012, 79). Both major parties (PASOK and ND)
were considered "traitors" and "conspirators" for their willingness to
comply with the austerity demands of the "troika" (Katsambekis and
Stavrakakis 2017, 401; see also Aslanidis and Rovira Kaltwasser 2016,
1081) (OTH_POLCLASS = 3).

In typically nationalist terms, ANEL's most important "others" were
foreign entities. It alleged that there was a "New World Order"
controlling Greece, and that national politicians are complicit
inwilfully surrendering national sovereignty to it (Pappas and Aslanidis
2015, 192). Accordingly, the party suggested that the financial crisis
was artificially induced by foreign actors (with PM Papandreou acting as
a willing agent) and that the bailout was a way for those actors to
steal Greece's wealth (Pappas and Aslanidis 2015, 192). Anti-German
sentiment was particularly strong, as ANEL accused Chancellor Merkel of
imposing a "4^th^ Reich" on Greece via its austerity demands
(Papathanassopoulos, Giannouli, and Andreadis 2016, 200). Kammenos also
engaged in anti-American rhetoric, while stressing the "Orthodox bonds"
Greece had with Russia (Petsinis 2016, 286, 288). In the context of this
foreign assault, ANEL claims to fight for national sovereignty (Fielitz
2018, 2) (OTH_FOREIGN = 3).

ANEL's narrative of "the people" is constructed in mainly ethnic terms
(Papathanassopoulos, Giannouli, and Andreadis 2016), and the party has
engaged in racist and anti-Semitic rhetoric (Aslanidis and Rovira
Kaltwasser 2016, 1081) (OTH_ETHNIC = 3). Its discourse was also

strongly hostile to immigrants (Ellinas 2013, 558), who were alleged to
have been sent by the New World Order to harm the country (Pappas and
Aslanidis 2015, 193), and who constituted a threat to the Greek *ethnos*
(Fielitz 2018, 15) (OTH_IMMIGRANTS = 3).

ANEL's economic policy had strong elements of state interventionism
(Katsambekis and Stavrakakis 2017, 401), but is always considered in the
literature to be either right-wing (Stavrakakis, Andreadis, and
Katsambekis 2017, 450; Vasilopoulou and Halikiopoulou 2013, 529) or
far/extreme/radical right (Lazaridis and Tsagkroni 2016, 210; Aslanidis
and Rovira Kaltwasser 2016; Fielitz 2018). It is likely the case that
the former designation is a product of implicit comparisons with the
neo-Nazi Golden Dawn, and that by global or regional standards it is a
typically far right party (LRPOSITION = FR). The party's OTH_ECONOMIC
rhetoric in the context of the financial crisis was clearly strong, and
even though this was tied up with its OTH_FOREIGN discourse, its
references to "loan sharks who have enslaved the nation" (cited in
Vasilopoulou and Halikiopoulou 2013, 533) earn it a 3 on this variable.

ANEL is clearly a "leader-centric" party that revolves around Kammenos
(Pappas and Aslanidis 2015, 192; Stavrakakis, Andreadis, and Katsambekis
2017, 457), who monopolises its representation in the media (Fielitz
2018, 16) (CHARISMA = 3). According to Pappas & Aslanidis (Pappas and
Aslanidis 2015, 192) it was not characterised by violent tendencies.
However aspects of rhetoric -- declaring that the 2012 election was not
a "democratic process" but rather "we are dealing with occupation troops
which violate democracy" (Pappas and Aslanidis 2015, 193) -- and
immigration policy -- its policy that illegal immigrants be placed in
maximum security detention, (Lazaridis and Tsagkroni 2016, 209) --
justify a 2 coding on LIBDEMNORMS, although this should be confirmed.
Kammenos was not powerful enough in ND to be considered an INSIDER by
the time of the 2012 election (= 1).

## Golden Dawn

"People's Association -- Golden Dawn" (*Chrysi Avgi*, GD) is a fascist
and nationalist movement started in 1983 by Nikos Michaloliokos. After
two decades flying under the radar it achieved a breakthrough in the
2010 local elections, when Michaloliokos won a seat on the Athens city
council. Following this GD's national vote spiked at 6.92% in the 2013
elections -- conducted in the heat of the economic crisis -- and
remained constant through the two 2015 elections (6.3%, 7.0%) before
collapsing to below 3% in 2019. Due to its extremism some scholars do
not consider the party populist, particularly those who see populism and
fascism as exclusive categories (Katsambekis and Stavrakakis 2017, 404;
Stavrakakis, Andreadis, and Katsambekis 2017, 450).

GD's political discourse is highly critical of the political
"establishment" (Pappas and Aslanidis 2015, 202), and it has frequently
been called "anti-system" (Roushas 2014, 5; Ellinas 2015, 4). It
considers non politicians "thieves" functioning in only a "pseudo
democracy", with prosecutions of GD members attributed to the
"conspiracy" of these established forces (cited in Ellinas 2015, 4; see
also Koronaiou and Sakellariou 2013, 337) (OTH_POLCLASS = 3). It is
explicitly racist, calling for a state which is homogenous on the lines
of "race, blood and ancestry" (Georgiadou 2013, 88; Pappas and Aslanidis
2015, 200; Ellinas 2013, 549). Party leadership has repeatedly disputed
the "Greekness" of citizens who are not ethnically Greek (Ellinas 2015,
5), and the party refers to ethnically Greek citizens as "the people"
(Kyriazi 2016; Stavrakakis, Andreadis, and Katsambekis 2017, 450). It is
also deeply anti-Semitic, attributing the ills of both capitalism and
communism to the forces of international "Zionism" (Koronaiou and
Sakellariou 2013, 336) (OTH_ETHNIC = 3). Relatedly, GD is sharply
hostile to immigrants, associating them with crime and unemployment and
advocating for their forced expulsion from the country (Pappas and
Aslanidis 2015, 200; Bistis 2013, 47; Roushas 2014; Ellinas 2015, 4). It
also accused the "parties of the establishment of the so-called left" of
pursuing high rates of immigration in order to achieve a "demographic
alteration" of the Greek nation (Ellinas 2013, 549), and cultural
"genocide" (Kyriazi 2016, 2532) (OTH_IMMIGRANTS = 3).

GD has also adopted a strong degree of "anti-plutocratic" discourse
against multinational business and neo-liberal capitalism (Ellinas 2013,
550), which it associates with Zionism (Koronaiou and Sakellariou 2013,
335). Some scholars have suggested that the party's food drives to
unemployed (and ethnically Greek) citizens developed a kind of "Robin
Hood" image (Bistis 2013, 49; see also Koronaiou and Sakellariou 2013)
(OTH_ECONOMIC = 3). GD accuses the establishment of being controlled by
foreign forces at the expense of national sovereignty (Ellinas 2013,
551), and refers to the 2010 memorandum signed between the government
and foreign debt holds the "ethnocide memorandum" (Lazaridis and
Tsagkroni 2016, 213). It also makes irredentist claims against Albania,
and is sharply opposed to accepting the name "Macdedonia" in any form in
North Macedonia (Ellinas 2013, 551). It is also hostile to the EU and
opposed to "American Zionism" (Ellinas 2015, 4) (OTH_FOREIGN = 3).

Despite its somewhat left-wing economic policies (such as higher taxes
on businesses and opposition to privatisations (see Roushas 2014,
19--20), GD is universally considered radical/extreme right in the
literature (LRPOSITION = FR). According to Ellinas (Ellinas 2013, 552),
GD is totally controlled and defined by the "towering presence" of
Michaloliokos, whose hierarchical leadership is embedded in
military-like hierarchies (Dinas et al. 2016, 81) (CHARISMA = 3). GD has
a strong paramilitary presence, and its members have engaged in violence
against immigrants and leftists for decades (Georgiadou 2013, 87--88;
Pappas and Aslanidis 2015, 200; Ellinas 2013, 548; Bistis 2013, 44--45;
Doxiadis and Matsaganis 2012, 55). Among numerous examples, party MPs
have assaulted political rivals on television, party vigilantes have
engaged in 'cleansing' operations to attack dark-skinned merchants in
market places, and party documentation asks members to reject the
authority of Parliament (Ellinas 2013, 549--50). Michaloliokos has also
defended the legitimacy of the right-wing military Junta that ruled
Greece 1967-74 (Bistis 2013, 51; Roushas 2014, 8). It is also hostile to
media scrutiny, with Michaloliokos once accusing a TV interviewer of
"taking orders from the New York Times and international Zionism (cited
in Ellinas 2013, 550). Due to these features the party should be
considered highly authoritarian to the extent that it is a direct threat
to democracy itself (LIBDEMNORMS = 3). Neither Michaloliokos nor the
party have ever been in government (INSIDER = 1).

## Coalition of the Radical Left (SYRIZA)

The Coalition of the Radical Left (*Synaspismós Rizospastikís
Aristerás*, SYRIZA) is a grouping of minor non-communist left-wing
parties that in various forms sat on the fringes of Greek politics
throughout the 1990s and early 2000s. It vaulted into the mainstream on
the back of mass protests (the "movement of the squares" or
"*aganaktismenoi*") against austerity measures imposed by emergency
lenders following the 2010 debt crisis. Following a dramatic climb to
26.6% in the (June) 2012 elections, SYRIZA became the formal opposition
party, and then after polling 36.3% in 2015 formed a coalition
government with ANEL. While this coalition of opposing forms of populism
was surprisingly stable, by the 2019 vote SYRIZA's support had declined
to 31.5%, and it lost government. Given that SYRIZA did a significant
about-turn by accepting the bailout conditions in 2015, there would seem
to be a strong case that the party might have dropped or changed its
populist rhetoric toward the 2019 elections. The available evidence
suggests however that Tsipras' discourse on the people's "enemies"
remained unchanged (Markou 2017, 6).

In the context of the Greek financial crisis, SYRYZA's populist
discourse melded the political class, the business elite, and foreign
actors into one "other" (Papathanassopoulos, Giannouli, and Andreadis
2016, 198). The party referred to the "establishment" of political
parties including PASOK, ND, LAOS and DIMAR (Stavrakakis and Katsambekis
2014, 129--30; Markou 2017, 62) and the *diaploki --* the network of
political and business elites (Pappas and Aslanidis 2015, 194). In 2012
the party campaigned in Manichean terms against "an almighty authority
of the triangle of sin, which has the corrupt bipartisan political
system on its top corner, the bankers on the other, and the interweaving
media on the third", declaring that "It's either Them or Us" (cited in
Pappas and Aslanidis 2015, 194; see also Tsakatika 2016, 528; Markou
2017, 62) (OTH_POLCLASS = 3).

SYRIZA's version of "the people" is put in material rather than ethnic
terms, and one of their enemies are the "oligarchs" (Pappas and
Aslanidis 2015, 194; Papathanassopoulos, Giannouli, and Andreadis 2016,
199; Katsambekis 2015, 154), declaring during the 2012 election campaign
that the race was a battle "Between the Greece of the Oligarchy and the
Greece of Democracy" (Stavrakakis and Katsambekis 2014, 128). In this
context the Memorandum was seen as a way for "oligarchs" to "increase
their wealth and privileges" (Pappas and Aslanidis 2015, 194), and the
party portrayed the political sphere as divided between pro-memorandum
and anti-memorandum forces that aligned with the elite and the people
respectively (Katsambekis 2015, 156) (OTH_ECONOMIC = 3). Tsipras
declared himself the successor of Papandreou's original PASOK, whose
principles the current PASOK leadership had, in his view, abandoned
(Pappas and Aslanidis 2015, 194).

The Troika of European debt holders (The European Commission, the
European Central Bank and the International Monetary Fund) were a
constant "enemy" of the people in SYRIZA's discourse, and the division
of "external troika" and "internal troika" was used to denote those
domestic political forces which were alleged to be acting as lackeys of
the foreign forces (Stavrakakis and Katsambekis 2014, 131; Tsakatika
2016, 528). In 2012 the WWII themes of a Nazi "4^th^ Reich" -- in common
with ANEL -- were strong in SYRIZA's discourse against German domination
of Europe (Pappas and Aslanidis 2015, 193), and the party portrayed a
lineage the anti-Nazi resistance group the National Liberation Front
(Tsakatika 2016, 528). Given that this anti-foreign discourse relied on
the context of the memorandum, we've coded it 1 on OTH_FOREIGN in 2007
and 3 from 2012 on. SYRIZA's version of the "people" and their "others"
are also non-ethnic (Stavrakakis and Katsambekis 2014; Markou 2017, 63)
(OTH_ETHNIC = 1), and its rhetoric was largely pro-immigrant
(Katsambekis and Stavrakakis 2017, 400--401; Markou 2017, 63; Mudde
2016, 35) (OTH_IMMIGRANTS = 1).

As its name suggests, the party is unambiguously left wing (LRPOSITION =
FL). It is an open question whether the party should carry this label
through to the 2019 election, when it had arguably watered down its
radical identity. Given that the party was a fairly well-structured
coalition of parties before its rapid ascendance in 2012, and the fact
that this ascendance was driven by a somewhat organic relationship with
the popular protests of the 2010-12 period and earlier (Katsambekis
2016, 394--95), there doesn't seem to be a good case to be made that it
relied on the leadership of Tsipras in the 2012 election. However,
according to Tsakatika, Syriza's campaigns increasingly focused "on his
person" (Tsakatika 2016, 532), and other scholars have mentioned that
the leader's personality became increasingly important to its identity
over time (Pappas 2016; Mudde 2016, 9, 28, 31) (CHARISMA = 1 in 2007-12,
2 2015-19). As neither Tsipras nor the party were in power before their
2015 election victory, it is coded 1 on INSIDER before that election and
3 after.

Regarding LIBDEMNORMS, there is little to place the party above 1 in its
early elections. However several actions that it undertook in government
lead some scholars to claim that the party was a mild threat to liberal
institutional norms. Examples of this are its such as pushing for the
prosecution of statistician Andreas Georgio whom it accused of
sabotaging the national debt figures in 2009 and the alleged use of
state media to pursue the party's agenda (Aslanidis and Rovira
Kaltwasser 2016, 1082; Iosifidis and Papathanassopoulos 2019; Karaliotas
2021). While this should be further studied, we don't think this quite
reaches the level of 2 on LIBDEMNORMS, and therefore we've coded it 1
throughout its time in the dataset.

## Not included

It is occasionally mentioned that New Democracy -- the dominant
conservative force in Greece since 1974 -- went through a populism phase
that mimicked PASOK in the early 1990s under Miltiades Evert's
leadership (Pappas and Aslanidis 2015, 181). From the available evidence
however this appears to have a been a much softer version than that
practices by Papandreou (Papathanassopoulos, Giannouli, and Andreadis
2016, 197), and we have made the decision to leave it out of the
dataset.

**References**

Aslanidis, Paris, and Cristóbal Rovira Kaltwasser. 2016. 'Dealing with
Populists in Government: The SYRIZA-ANEL Coalition in Greece'.
*Democratization* 23 (6): 1077--91.

Bistis, George. 2013. 'Golden Dawn or Democratic Sunset: The Rise of the
Far Right in Greece'. *Mediterranean Quarterly* 24 (3): 35--55.

Dinas, Elias. 2008. 'The Greek General Election of 2007: You Cannot Lose
If Your Opponent Cannot Win'. *West European Politics* 31 (3): 600--607.

Dinas, Elias, Vassiliki Georgiadou, Iannis Konstantinidis, and Lamprini
Rori. 2016. 'From Dusk to Dawn: Local Party Organization and Party
Success of Right-Wing Extremism'. *Party Politics* 22 (1): 80--92.

Doxiadis, Aristos, and Manos Matsaganis. 2012. 'National Populism and
Xenophobia in Greece'. *Populist Fantasies: European Revolts in
Context*, 31--98.

Ellinas, Antonis A. 2012. 'LAOS and the Greek Extreme Right since 1974'.
In *Mapping the Extreme Right in Contemporary Europe*, 140--56.
Routledge.

---------. 2013. 'The Rise of Golden Dawn: The New Face of the Far Right
in Greece'. *South European Society and Politics* 18 (4): 543--65.
https://doi.org/10.1080/13608746.2013.782838.

---------. 2015. 'Neo-Nazism in an Established Democracy: The
Persistence of Golden Dawn in Greece'. *South European Society and
Politics* 20 (1): 1--20.

Fielitz, Maik. 2018. 'From Indignation to Power: The Genesis of the
Independent Greeks'. In *Radical Right Movement Parties in Europe*,
97--113. Routledge.

Fouskas, Vassilis. 1998. 'The Muffled Voice of the New PASOK:
Reflections on Neo-Revisionist Socialism in Greece'. *South European
Society and Politics* 3 (1): 130--41.

Georgiadou, Vassiliki. 2013. 'Right-Wing Populism and Extremism: The
Rapid Rise of "Golden Dawn" in Crisis-Ridden Greece'. *Right-Wing in
Europe*, 75.

Iosifidis, Petros, and Stylianos Papathanassopoulos. 2019. 'Media,
Politics and State Broadcasting in Greece'. *European Journal of
Communication* 34 (4): 345--59.

Karaliotas, Lazaros. 2021. 'Geographies of Politics and the Police:
Post-Democratization, SYRIZA, and the Politics of the "Greek Debt
Crisis"'. *Environment and Planning C: Politics and Space* 39 (3):
491--511.

Katsambekis, Giorgos. 2015. 'The Rise of the Greek Radical Left to
Power: Notes on Syriza's Discourse and Strategy'. *Linea Sur* 9:
152--61.

---------. 2016. 'Radical Left Populism in Contemporary Greece: Syriza's
Trajectory from Minoritarian Opposition to Power'.

Katsambekis, Giorgos, and Yannis Stavrakakis. 2017. 'Revisiting the
Nationalism/Populism Nexus: Lessons from the Greek Case'. *Javnost-The
Public* 24 (4): 391--408.

Koronaiou, Alexandra, and Alexandros Sakellariou. 2013. 'Reflections on
"Golden Dawn", Community Organizing and Nationalist Solidarity: Helping
(Only) Greeks'. *Community Development Journal* 48 (2): 332--38.

Kyriazi, Anna. 2016. 'Ultranationalist Discourses of Exclusion: A
Comparison between the Hungarian Jobbik and the Greek Golden Dawn'.
*Journal of Ethnic and Migration Studies* 42 (15): 2528--47.

Lazaridis, Gabriella, and Vasiliki Tsagkroni. 2016. 'Posing for
Legitimacy? Identity and Praxis of Far-Right Populism in Greece'. *The
Rise of the Far Right in Europe: Populist Shifts and'Othering'*,
201--37.

Lyrintzis, Christos. 1984. 'Political Parties in Post-Junta Greece: A
Case of 'bureaucratic Clientelism'?' *West European Politics* 7 (2):
99--118.

---------. 1987. 'The Power of Populism: The Greek Case'. *European
Journal of Political Research* 15 (6): 667--86.

---------. 2005. 'The Changing Party System: Stable Democracy, Contested
"Modernisation"'. *West European Politics* 28 (2): 242--59.

Markou, Grigoris. 2017. 'The Rise of Inclusionary Populism in Europe:
The Case of SYRIZA'. *Contemporary Southeastern Europe* 4 (1): 54--71.

Mavrogordatos, George Th. 1984. 'The Greek Party System: A Case of
'limited but Polarised Pluralism'?' *West European Politics* 7 (4):
156--69.

Moschonas, Gerassimos. 2001. 'The Path of Modernization: PASOK and
European Integration'. *Journal of Southern Europe and the Balkans* 3
(1): 11--24.

Mudde, Cas. 2016. *SYRIZA: The Failure of the Populist Promise*.
Springer.

Papastathis, Konstantinos. 2015. 'Religious Discourse and Radical Right
Politics in Contemporary Greece, 2010--2014'. *Politics, Religion &
Ideology* 16 (2--3): 218--47.

Papathanassopoulos, Stylianos, Iliana Giannouli, and Ioannis Andreadis.
2016. 'Greece: Populism between Left and Right'. In *Populist Political
Communication in Europe*, 195--206. Routledge.

Pappas, Takis S. 2014. 'Populist Democracies: Post-Authoritarian Greece
and Post-Communist Hungary'. *Government and Opposition* 49 (1): 1--23.

---------. 2016. 'Are Populist Leaders "Charismatic"? The Evidence from
Europe'. *Constellations* 23 (3): 378--90.

Pappas, Takis S., and Paris Aslanidis. 2015. 'Greek Populism: A
Political Drama in Five Acts'. *European Populism in the Shadow of the
Great Recession*, 181--96.

Petsinis, Vassilis. 2016. 'Russophilia as a Component of National
Populism in Greece'. *Критика и Хуманизъм*, no. 46: 281--98.

Roushas, Roxani. 2014. 'Understanding the Electoral Breakthrough of
Golden Dawn in Greece: A Demand and Supply Perspective'.

Spourdalakis, Michalis, and Chrisanthos Tassis. 2006. 'Party Change in
Greece and the Vanguard Role of PASOK'. *South European Society &
Politics* 11 (3--4): 497--512.

Stavrakakis, Yannis, Ioannis Andreadis, and Giorgos Katsambekis. 2017.
'A New Populism Index at Work: Identifying Populist Candidates and
Parties in the Contemporary Greek Context'. *European Politics and
Society* 18 (4): 446--64.

Stavrakakis, Yannis, and Giorgos Katsambekis. 2014. 'Left-Wing Populism
in the European Periphery: The Case of SYRIZA'. *Journal of Political
Ideologies* 19 (2): 119--42.

Tsakatika, Myrto. 2016. 'SYRIZA's Electoral Rise in Greece: Protest,
Trust and the Art of Political Manipulation'. *South European Society
and Politics* 21 (4): 519--40.

Van Kessel, Stijn. 2015. *Populist Parties in Europe: Agents of
Discontent?* Springer.

Vasilopoulou, Sofia, and Daphne Halikiopoulou. 2013. 'In the Shadow of
Grexit: The Greek Election of 17 June 2012'. *South European Society and
Politics* 18 (4): 523--42. https://doi.org/10.1080/13608746.2013.779784.

Verney, Susannah. 2004. *The End of Socialist Hegemony: Europe and the
Greek Parliamentary Election of 7th March 2004*. Sussex European
Institute Brighton.
