---
title: Iceland
---


-   Date range: 1980-2020.

-   Elections included:

    -   Legislative: 1983, 1987, 1991, 1995, 1999, 2003, 2007, 2009,
        2013, 2016, 2017.

## Progressive Party / Centre Party

Progressive Party (*Framsóknarflokkurinn*, FSF) is an agrarian party
that has been one of Iceland's major parties since its foundation in
1916. The party undertook a dramatic change in leadership and rhetoric
after the in 2008 financial crisis, following which it alleged that
Iceland had become the victim of foreigners (in part due to the specific
issue of the "Icesave" bank collapse and its consequences). It alleged
that the incumbent government was guilty of "treason" and "humiliating
the nation" by showing leniency to the UK, the Netherlands and the IMF
(Eiríkur Bergmann 2015, 46; Newhouse 2017) (OTH_POLCLASS =3, OTH_FOREIGN
= 3). The party's hard line position on the issue led to a dramatic
increase in its electoral fortunes in 2013, when it surged to 24.43%
(Önnudóttir et al. 2022, 40). It also campaigned against corruption in
the banking sector as a whole (Hallgrímsdóttir and Brunet-Jailly 2016,
112) (OTH_FINANCIAL = 3). The new party leadership also gradually
developed a nativist opposition to immigrants, associating asylum
seekers with crime, and standing against Muslims and the construction of
Mosques (Eiríkur Bergmann 2015, 48; Holbrook 2014; Newhouse 2017).
However, there seems to be a consensus that the party fell short of
becoming the out and out right wing nativist parties common in mainland
Europe and Scandinavia (see for example Herkman and Jungar 2021, 247),
and hence we've coded both OTH_IMMIGRANTS and OTH_ETHNIC at 2. Following
Önnudóttir *et al* we've coded the party as CR on LRPOSITION (Önnudóttir
et al. 2022, 2).

During this time the party was strongly dependent on its leader
Sigmundur Davíð Gunnlaugsson (Eiríkur Bergmann 2015, 48) although it had
a well-established base as well (CHARISMA = 2 2009-13). Sigmundur Davíð
joined the PP only weeks before the 2009 election (Harðarson and
Kristinsson 2010, 524). The party won the 2013 elections and Sigmundur
Davíð became Prime Minister, before being forced to quit after his
offshore tax evasion was exposed in the Panama Papers in 2016 (Bernburg
2019). He then took his faction out of the PP and formed the **Centre
Party (CP)** for the snap 2017 election, which (from the limited
available evidence) seems to have carried the same populist narrative as
PP (Önnudóttir et al. 2022, 22), and been even more centred on his
personal appeal (Malmquist 2017) (CHARISMA =3). After this change in
leadership the PP returned to its pre-crisis non-populist form (Eirikur
Bergmann 2017, 94).

## Citizens' Movement 

The Citizens\' Movement (*Borgarahreyfingin*, CM -- sometimes called the
"Civic Movement") was a direct offshoot of the "pots and pans"
revolution that followed the financial crisis -- named after the kitchen
utensils that protesters banged together on the streets outside
Parliament (Harðarson and Kristinsson 2010, 524; Bernburg and
Víkingsdóttir 2016). This spontaneous set of protests brought down the
Independence Party government that had overseen the neoliberal financial
policies blamed for the crisis. CM polled 7.2% in the election, but
disbanded son afterward due to infighting due to the conflicting
priorities of its members (Ómarsdóttir and Valgarðsson 2020, 846).

The party positioned itself as an agent of radical change (Ómarsdóttir
and Valgarðsson 2020, 845), and maintained a staunch anti-political
anti-establishment character (Önnudóttir et al. 2022, 23; Newhouse
2017). In the 2009 election the party campaigned broadly against "the
system, politicians and bankers" (Van Kessel 2015, 51) and according to
Ólafsson possessed a streak of "militant radicalism" (Ólafsson 2019,
127) (OTH_POLCLASS =3, OTH_FINANCIAL = 3). It thus formed a left-leaning
protest narrative that contrasted with the PP's simultaneous nationalism
(OTH_IMMGIRATNS = 1, OTH_ETHNIC = 1, LRPOSITION = L). The party won 4
seats in that election on a platform of "Let\'s bring the people to
parliament" (Þórsson 2017). We have seen no evidence of OTH_FOREIGN
discourse (= 1), but this could be further investigated.

The party is regarded as a quite "grassroots" initiative (Ólafsson 2019,
127), whose leaderlessness was evident in the way it collapsed soon
after the election (CHARISMA = 1). We've seen no evidence that it
threatened liberal democratic norms (LIBDEMNORMS = 1), and none of its
leaders had ever served in government (INSIDER = 1).

## Pirate party 

The Pirate Party (*Píratar*) was a continuation of the CM, led and
founded by one of that party's four MPs Birgitta Jónsdóttir. It combined
leftist opposition to the financial system with libertarian
individualism and administrative decentralisation. It had a close
association with Wikileaks (whom Jónsdóttir used to work for), and
frequently raised the issue of press freedom. After leading the polls
for months in the run up to the 2016 election, the party received 14.6%
and thus became one of the best represented parties in the legislature.
This dropped to 9.2% in the 2017 election. These results make the
Icelandic Pirates one of the most successful Pirate Parties in the
world.

There is much debate by comparative populism theorists about whether
Pirate Parties should be considered populist in any way, and some have
declared that Iceland's is not populist (see for example Van Kessel
2015, 52). Iceland's Pirates appear to differ from others within this
family by being more serious about policy beyond the internet freedom
issues that 'Piratism' had depended on (Newhouse 2017; Dapin 2017), and
given the context of the banking crisis (associated with failure of the
political class as a whole), the party appears to have had a more
pronounced "anti-system" character in its discourse (Önnudóttir et al.
2022, 23) -- albeit packaged in a very institutionally liberal approach.
Newhouse, for example, argues that the Pirates picked up the mantle of
anti-establishment revolt that had started in the pots and pans
revolution and continued through the CM, culminating in the 2016
election campaign in which "the Pirates established themselves early on
as the antithesis to the establishment politicians in power" (Newhouse
2017). On this basis, we've included the Pirates in the dataset, and
coded them 3 on OTH_POLCLASS 3. Given their leftist orientation and
their legacy in the pots and pans revolution, it seems likely that the
party was also opposed to OTH_FINANCIAL elites -- however we've not come
across direct evidence of this, so we've labelled the party 1 for the
time being. Likewise, we've seen no evidence regarding OTH_FOREIGN
discourse (= 1).

While the ideology of all Pirate parties is somewhat alien to the
conventional left-right scale, the Icelandic Pirates appear to have
adopted a generally left-wing approach to issues like welfare,
healthcare, and housing (Ómarsdóttir and Valgarðsson 2020, 848), and
hence seem to fit the L category on LRPOSITION. The party has never been
in government (INSIDER = 1), and does not attempt to violate the norms
of liberal democracy according to available evidence (LIBDEMNORMS = 1).
The party possessed a relatively strong organisational base (Ólafsson
2019, 127), and as it formally has no official leader (Ómarsdóttir and
Valgarðsson 2020, 847), I doesn't seem to rely on its leadership for its
appeal (CHARISMA = 1).

## Not included

**Bright future** has links to an earlier populist party, the Best Party
of comedian Jón Gnarr, who previously ran successfully in the Reykjavik
mayoral election on an enti-estblishment and anti-politics narrative
(Ómarsdóttir and Valgarðsson 2020, 846). While Gnarr joined Bright
Future, available evidence suggests that this party charted a different
direction to the Best Party (Önnudóttir et al. 2022, 119), and we have
therefore not included it here. The **People's Party** of Inga Sæland is
a relatively young and small party has been considered populist in some
literature. This seems to be due to Sæland's occasional criticism of the
welfare benefits that asylum seekers, and her focus on corruption.
However we've not found sufficient evidence to show that this reached a
level that warrants inclusion in the dataset. This should be
investigated further.

**References**

Bergmann, Eiríkur. 2015. 'Populism in Iceland: Has the Progressive Party
Turned Populist?' *Icelandic Review of Politics & Administration* 11
(1): 33--54. https://doi.org/10.13177/irpa.a.2015.11.1.3.

Bergmann, Eirikur. 2017. *Nordic Nationalism and Right-Wing Populist
Politics: Imperial Relationships and National Sentiments*. Springer.

Bernburg, Jón Gunnar. 2019. 'The Cascading Crisis and the Changing Base
of Popular Protest: The Case of Iceland'. *Current Sociology* 67 (7):
1018--38.

Bernburg, Jón Gunnar, and Anna Soffía Víkingsdóttir. 2016. 'Political
Opportunity, Framing, and Mobilization in Iceland's Post-Crash
Protests'. In *Iceland's Financial Crisis: The Politics of Blame,
Protest, and Reconstruction*, edited by Valur Ingimundarson, Philippe
Urfalino, and Irma Erlingsdóttir, 81--102. London: Routledge.

Dapin, Mark. 2017. 'Iceland Activist Birgitta Jonsdottir: The Future
Face of Populism?' *The Sydney Morning Herald*, 26 January 2017.
https://www.smh.com.au/lifestyle/the-future-face-of-populism-20170126-gtyv9f.html.

Hallgrímsdóttir, Helga Kristín, and Emmanuel Brunet-Jailly. 2016.
'Contentious Politics, Political Expediency, and the Real Costs of the
Icesave Debt'. In *Iceland's Financial Crisis: The Politics of Blame,
Protest, and Reconstruction*, edited by Valur Ingimundarson, Philippe
Urfalino, and Irma Erlingsdóttir, 102--20. London: Routledge.

Harðarson, Ólafur, and Gunnar Kristinsson. 2010. 'The Parliamentary
Election in Iceland, April 2009'. *Electoral Studies - ELECT STUD* 29
(September): 523--26. https://doi.org/10.1016/j.electstud.2010.04.011.

Herkman, Juha, and Ann-Cathrine Jungar. 2021. 'Populism and Media and
Communication Studies in the Nordic Countries'.

Holbrook, Donald. 2014. 'A Cold Reception: The Rise of Anti-Islamic
Sentiments in Iceland?' OpenDemocracy. 12 June 2014.
https://www.opendemocracy.net/en/can-europe-make-it/cold-reception-rise-of-antiislamic-sentiments-in-iceland/.

Malmquist, Björn. 2017. 'Iceland's Ex-Leader Poised for Political
Resurrection'. POLITICO. 27 October 2017.
https://www.politico.eu/article/sigmundur-david-gunnlaugsson-iceland-ex-leader-poised-for-political-resurrection/.

Newhouse, Alex. 2017. 'A Story of Pirates and Populism'. *Medium*, 4
June 2017.
https://medium.com/@AlexBNewhouse/a-story-of-pirates-and-populism-6ea9aee2d1c7.

Ólafsson, Jón. 2019. 'So Strong, Yet So Weak: The Emergence of Protest
Publics in Iceland in the Wake of the Financial Crisis'. *Protest
Publics: Toward a New Concept of Mass Civic Action*, 117--36.

Ómarsdóttir, Silja Bára, and Viktor Orri Valgarðsson. 2020. 'Anarchy in
Iceland? The Global Left, Pirates and Socialists in Post-Crash Icelandic
Politics'. *Globalizations* 17 (5): 840--53.
https://doi.org/10.1080/14747731.2020.1722496.

Önnudóttir, Eva H., Agnar Freyr Helgason, Ólafur Th Harðarson, and Hulda
Thórisdóttir. 2022. *Electoral Politics in Crisis after the Great
Recession: Change, Fluctuations and Stability in Iceland*. Taylor &
Francis.

Van Kessel, Stijn. 2015. *Populist Parties in Europe: Agents of
Discontent?* Springer.

Þórsson, Elías. 2017. 'From Iceland --- Flokkur Fólksins: The Populist
Uprising?' The Reykjavik Grapevine. 15 August 2017.
https://grapevine.is/mag/2017/08/15/flokkur-folksins-the-populist-uprising/.

