---
title: Indonesia
subtitle: 'Date range: 1999-2020'
title-block-banner: yes

---

# Case notes

## Prosperous Justice Party

The Prosperous Justice Party (*Partai Kaedilan Sejahtera,* PKS) formed
out of the Justice Party (PK) which contested the 1999 election without
much success. Both entities emerged from networks of students without
links to the major parties, linked to the Muslim Brotherhood in Egypt
and the powerful *tarbiyah* movement of Islamist education. The PKS was
an ostensibly Islamist party, and has been situated among the
'modernist' family of Muslim parties in Indonesia, but one that
initially eschewed calls for *sharia* and an Islamic state in favour of
universalist policies focusing on clean government (Eliraz 2004, 124).
The party had a breakout performance in the 2004 election, tallying
7.3%, doing particularly well in Jakarta (25%). It has since matched and
exceeded that performance in subsequent elections.

There is frustratingly little written about the PKS' precise rhetoric
regarding the political class. In broad terms, however, there is wide
consensus in the literature that the party accused the political system
*writ large* of corruption and self-interest at the expense of ordinary
people (Hasan 2009, 3; Smith 2004, 2; Liddle and Mujani 2005, 121;
Aspinall 2005, 154; Nakamura 2005, 29). While all parties in the
*reformasi* period (immediately post-Suharto) used the language of
opposing '*Korupsi, Kolusi, Nepotisme*' or KKN, the PKS was notably more
extreme in calling for a more holistic "change of regime" (Aspinall
2005, 134). In Buchori's words (cited in Collins 2003, 15): "\[t\]he
party reiterates time and again that the present chaos in Indonesia is
caused primarily by a lack of morality among the nation's leaders". In
the 2004 election it released material citing the "24 reasons PKS is the
enemy of slippery characters", listing the multiple times that its
leaders in provincial assemblies had refused to partake in corruption
along with the major parties (Collins and Fauzi 2007). It built this
image in part on the fact that it was both relatively young in in its
leadership and cadres, and unconnected to the personalities or parties
of the Suharto era -- something unique among the major parties in 2004
and a major distinction between it and other Islamist parties like the
PPP (Machmudi 2008, 11; Collins 2003). In contrast to the established
political parties, PKS presented itself as "clean" (Shihab and Nugroho
2008, 253; Smith 2004, 3) and "caring" (Qodari 2005, 80; Liddle and
Mujani 2005, 121), and emphasised its commitment to help "little people"
who had been neglected (Machmudi 2008, 15; see also Siregar et al. 2020,
9; Slater 2004, 62--63). In Slater's words: "PKS represents a challenge
to this system insofar as it insists that politics should be about
representing the *rakyat* (the people) rather than carving up the
perquisites of state." (Slater 2004, 62--63). According to Tanuwidjaja
(2012, 535), the party's rhetoric had not changed by 2012, even as it
began to be mired in corruption scandals of its own. Under the
leadership of Anis Matta from 2013, the party started to take on a more
aggressive posture against the "enemies of PKS", particularly the
anti-corruption bodies that had pursued PKS leaders (Machmudi 2020,
174). Owing to the lack of direct examples of party rhetoric, and the
fact that it adopted an increasingly accommodating strategy regarding
other parties and elites over the years, a case could be made that the
party should either be consistently coded 2 on OTH_POLCLASS or start at
3 and come to 2 in later elections. Further research should clarify this
-- according to the available evidence we've coded it 3 for the
duration.

PKS is Islamist in the sense of advocating piety to the core values of
Islam, and proposing that these values could be used to solve national
problems. It has not used religious identity in an exclusionary or
defensive way to assert the rights of Muslims over others or posit that
Muslims were under any kind of threat by the party's main rivals (Hasan
2009, 6). In a number of ways, the party emphasised that it was not
intolerant of non-modernist Muslims, even to the point of choosing
non-Muslim candidates in some local elections (Collins 2004, 119). The
party's Islamic credentials have become even more moderate over later
election cycles (Tomsa 2012), and its 2008 agenda explicitly praised the
"plurality in Indonesian society" as an "asset" for national progress
(Shihab and Nugroho 2008, 242). For this reason we've coded the party 1
for OTH_ETHNIC. Likewise, we've seen no evidence that it should register
above 1 on either OTH_IMIGRANT, OTH_ECONOMIC, or OTH_MILITARY. The
party's consistent opposition to the United States and Israel -- albeit
on more of a pan-Islamic sense than a domestic grievances one -- has
been a consistent element of its rhetoric and appeal (Hasan 2009, 17;
Machmudi 2008, 14). Given that this has not risen to the point of
accusing domestic rivals of being controlled by these foreign states,
we've coded the party 2 on OTH_FOREIGN.

Beyond its general espousal of "clean" political values and practices,
PKS did not, in Hasan's words, have a "political blueprint for social
transformation", and lacked clear policy stances on many of the salient
issues of the day, save several things clearly in its wheelhouse such as
opposition to pornography and support for Palestine (Hasan 2009, 11). It
has been consistently pro-welfare and anti-poverty (but not in a
class-based sense) yet culturally conservative. Party Chairman Hidayat
Nur Wahid called the PKS a "centrist Islamic party" (Collins 2003), and
though there may be a case for coding it C on LIBDEMNORMS, the salience
of cultural conservatism in its policy leads us to code it CR.

The party has neither opposed democracy nor supported violence (Nakamura
2005, 29; Kershaw 2004, 363). Though they are classified as an Islamist
party, they have consistently eschewed calls to implement an Islamic
state governed by Shariya, and maintain that participating in the
democratic system is compatible with pursuing Islamic values in
government (Collins 2004, 119; see also Hasan 2009, 4) (LIBDEMNORMS = 1)
The PKS is generally considered to be genuine vehicle of mass
participation and internal rules based democracy (Kershaw 2004, 362),
without a reliance on leadership or an elite network. Numerous scholars
have emphasised that the party did not revolve around its leader in the
same way that other parties did at the time (Hasan 2009, 10; Baswedan
2004, 18) "PKS is the best organized of all Indonesian parties, with
400,000 carefully selected and well-trained cadres, and has cultivated
an image of collective decision making in which no individual leader
stands out." (Liddle and Mujani 2005, 121). At no election has the PKS's
current leader served in a government (INSIDER = 1).

## Gerindra/ Prabowo Subianto

Prabowo Subianto is a former military General and inner-circle member of
the late Suharto regime (he was the Suharto's son-in-law). After a
period in exile after the collapse of the New Order regime, he returned
and unsuccessfully sought the Golkar presidential nomination in 2004,
losing out to Wiranto. In 2008, he created his own party, *Gerakan
Indonesia Raya* (Greater Indonesia Party, or "Gerindra") as a personal
vehicle for his presidential aspirations. Gerindra underperformed in the
2009 elections (gaining 4,5%), but emerged in 2014 as a part of a
coalition of parties big enough to support Prabowo's presidential bid
against Joko Widodo (Jokowi). Funded by his billionaire brother Hashim,
Prabowo built alliances with conservative Islamist parties and
movements, narrowly losing to Jokowi in both 2014 and 2019.

Despite being a scion of the political establishment and oligarchy,
Prabowo's presidential campaigns have been based on a trenchant critique
of the political class, which he classifies as "corrupt" (Gammon 2020,
106; Rakhmani and Saraswati 2021; Warburton and Aspinall 2019, 266), and
"traitors" (Aspinall 2015, 13; Kimura 2017, 1). While general accusation
of corruption are commonplace among most Indonesian politicians, Prabowo
elevated this rhetoric to a more precise and invective allegation that
the nation was run by a "mafia" (Aspinall 2015, 18) that was "stealing
the Indonesian people's money" (Gammon, cited in Hadiz and Robison 2017,
493), in contrast to which he styled himself as the avatar of the
"Indonesian people" (Aspinall 2015, 18; Hellmann 2017, 170). He applied
this critique not to specific politicians or parties, but in blanket
terms to the entire political elite (Aspinall 2015, 18; Hellmann 2017,
170) (OTH_POLCLASS = 3. Several scholars have pointed out that Prabowo
mimicked the oratory style of Soekarno, even to the point of wearing
similar safari suits and using replica microphones similar to those used
by the former president (Aspinall 2015, 13).

Prabowo's critique of the political elite was bound together with a
general accusation that the nation was being plundered by foreign forces
(Hellmann 2017, 169; Mietzner 2014, 120; Rukmana and Sugito 2020;
Rakhmani and Saraswati 2021, 453; Lane 2017, 3; Warburton 2020, 31). He
used the term *kebocoran*, ('leaks') to suggest that the nation was
bleeding its natural wealth to these foreigners, and used this narrative
to explain most of the nation's problems (Hatherell and Welsh 2020, 58;
see also Warburton 2018, 140). His 2004 book claimed that "the
domination of foreign powers" amounted to a "surrender" of national
independence, and the enslavement of the people of Indonesia (Aspinall
2015, 14): "Our Indonesia" he said during the 2014 campaign, "is
nurtured by foreign forces like a cow" (Robison and Hadiz 2017, 901).
Domestic elites, he claimed, were either too "weak" to prevent this
(Hatherell and Welsh 2020, 59), or complicit cronies to these foreign
agents (Widian, Satya, and Yazid 2022, 11; Satrio 2019, 176; Mietzner
2015, 36; Hara 2017, 108). He extended this to Jokowi, whom he called
*antek asing* (a "stooge of foreigners") (Mietzner 2015, 36) who was
actively "selling Indonesia off" to Chinese investors and labourers
through his infrastructure programs (Warburton 2018, 139). He was vague
in identifying exactly which foreign powers were involved in this,
although he did single out the IMF for waging an "economic war" against
Indonesia in the wake of the 1997 Asian Financial Crisis that hit the
nation hard and triggered the downfall of Suharto (Aspinall 2015, 14)
(OTH_FOREIGN = 3).

This rhetoric against "foreigners" is in many ways aimed at targeting
domestic enemies, specifically Chinese and Christians (Widian, Satya,
and Yazid 2022, 2). Even though neither Prabowo nor Gerindra are hard
line Islamists, their alliances with numerous Islamist factions has led
many scholars to consider them "sectarian" (Warburton 2020, 31),
"nativist" (Murphy 2019, 80) and "hostile to ethnic minorities"
(Gueorguiev, Ostwald, and Schuler 2018, 242). While Jokowi is also a
Muslim, the Prabowo campaign, in Warburton's words, depicted Jokowi as
an enemy of the *ummah* (the Muslim community) and as a threat to pious
Muslims and Islamist organizations" (Warburton 2020, 28). This is built
on a combination of Jokowi's pluralist ideology, his association with
various Chinese and Christian political figures (notably former Jakarta
Governor Ahok), and a smear campaign that Jokowi was secretly a
Christian. These were tactics of convenience for Prabowo, and ironically
his shift to ally with Jokowi after the 2019 election saw him embrace
the government's harsh tactics against Islamist parties (Warburton 2020,
29--30). Nonetheless, given Prabowo's consistent -- albeit implicit --
reliance on ethnocentric narratives, we've coded him and Gerindra as 2
for OTH_ETHNIC for the 2014 and 2019 elections.

In spite of his own enormous wealth and the family connections that
helped to generate it, a significant pillar of Prabowo's campaigns
targeted the financial elite and wealth inequality (Warburton 2018, 135;
Hara 2017, 108; Widian, Satya, and Yazid 2022, 11), and "drew heavily on
narratives of economic injustice and exploitation" (Warburton and
Aspinall 2019, 276). These are often bound up with the foreign
exploitation narrative, as the domestic oligarchy is accused of
profiting off the plunder of national wealth at the expense of the
people (Widian, Satya, and Yazid 2022, 11; Satrio 2019, 176; Mietzner
2015, 36; Hara 2017, 108). Given that this anti-oligarchic element was a
significant part of Prabowo's discourse, but that it remained somewhat
vague and secondary to other "other" narratives, we've coded
OTH_ECONOMIC 2. We've seen no evidence for anything on the
OTH_IMMIGRANTS (= 1), or OTH_MILITARY (= 1) variables.

As a party, Gerindra was totally controlled by Prabowo and his
loyalists, and dedicated solely to the goal of making him president
(Aspinall 2015, 9; see also Gammon 2020, 106). Numerous sources talk of
Prabowo's commanding, demagogic charisma as an element of both his and
his party's appeal (Widian, Satya, and Yazid 2022, 14; Kenny 2017, 33),
and the fact that his rhetorical style was "self-referential to a degree
that is unusual among Indonesian politicians" (Aspinall 2015, 13),
something which contrasted with the political styles of other Indonesian
politicians (CHARISMA = 3).

Prabowo's campaign constituted a direct threat to liberal democratic
norms for several reasons. He has a well-known history as an "enforcer"
against pro-democracy activists during the Suharto regime, and stood
accused of several violations of human rights during that period
(Aspinall and Mietzner 2019, 106; Mietzner 2015, 20). He also has what
Warburton and Aspinall call a "well known history of personal brutality"
(Warburton and Aspinall 2019, 258). He has consistently threatened
democratic institutions since the collapse of the new order, including
attempting to interfere with the vote count after the 2014 election
(Mietzner 2014, 111). On a more ideological basis, during his campaigns
he articulated an opposition to liberal democracy (Hadiz and Robison
2017, 494), despite assurances that he as in fact a democrat (Aspinall
2015, 20). This included support for returning to the 1945 constitution
which included unchecked executive power (Aspinall and Mietzner 2019,
106; Satrio 2019, 176). and support for reforms aimed at
"re-centralising\... power and disassembling key democratic
institutions" (Pardede 2020, 41), such as the abolition of direct
presidential elections and returning to the system where a constituent
assembly decides, this being more in line with "Indonesian traditions"
(Lane 2017, 4). Prabowo has openly lamented that "Indonesia is not ready
for democracy," and considered a "benign authoritarian regime" more
suitable (Mietzner 2015, 22). In a more general sense, many scholars
have pointed out that Prabowo and Gerindra have become leading
figureheads in an anti-democratic compact between nationalist oligarchs
and hard-line Islamists. (Lane 2017). For these reasons they deserve a
clear 3 on the OTH_LIBDEMNORMS variable.

Prabowo and Gerindra have been called "nationalist" (Hellmann 2017,
162), "economically nationalist" (Aspinall 2015, 14) and
"ultranationalist"(Arifianto et al. 2019, 44; Mietzner 2014, 112),
"conservative nationalist" (Robison and Hadiz 2017, 901), and
"right-wing". While much of his economic rhetoric constituted a critique
of liberalisation, "it would be a mistake", in Aspinall's words, "to
exaggerate the policy cohesiveness or sophistication of his economic
nationalism" (Aspinall 2015, 15). Owing to this and the salience of
Probowo's cultural nationalism, we've placed him and Genindra as R on
LRPOSITION. Given that Prabowo was a political/military insider in the
Suharto regime (Aspinall 2015, 6), we've coded him 2 on INSIDER

## Not Included

The **Democratic Party of Struggle** (*Partai Demockrasi Indonesia
Perjuangan*, PDI-P) is the successor to the lineage of Indonesia's first
president, Sukarno, who was ousted by Suharto in 1967. It was formed in
1999 by Sukarno's daughter, Megawati Sukarnoputri, who served as
president from 2001-2004 and has remained a powerbroker since. Sukarno
had a notably populist style, and some have suggested that Megawati
embodied this style by claiming his political legacy and mandate
(Thompson 1999, 2). However the available evidence suggests that
Megawati has maintained an aloof personal style, characterised by
"self-restraint" rather than charisma (Ziv 2001, 85), and that the PDI-P
under her leadership has been similar to Suharto's Golkar party. Before
the 2014 elections she handed the party's presidential nomination to
popular Jakarta governor Jokowi. The literature frequently considers
Jokowi populist (Pardede 2020, 41; Hara 2017; Mietzner 2014; Hadiz and
Robison 2017; Kenny 2022, 88), but this is more in the sense of his
perceived kinship with ordinary people and genuine non-elite origins
than any anti-elite rhetoric or outright rejection of the political
status quo (Warburton 2018, 137). Jokowi has campaigned as more of a
technocrat than a demagogue (Hatherell and Welsh 2020), offering what
Aspinal and Mietzner call a "mellow developmentalist vision" (Aspinall
and Mietzner 2019, 104). While he did campaign against corruption, this
was done no more than any other politician (Hatherell and Welsh 2020,
60). For this reason we don't think that he has met the WPD's minimum
definition of populism, and he is not in the database. **The National
Mandate Party** (*Partai Amanat Nasional,* PAN) is the creation of Amien
Rais, a student leader during the *reformasi* protests against the
Suharto regime. The party is explicitly secular but has roots in the
modernist Islamic political tradition. Rias ran for president in 2004.
PAN and Rais are occasionally considered "populist" (Liddle 2000, 35;
Carnegie 2008, 4), but there doesn't appear to be much evidence of this
in their rhetorical approach other than the fact that Rais is considered
"outspoken" (Ziv 2001) and clearly more charismatic than other party
leaders (for more on PAN see Zenzie 1999; Sherlock 2004).

**References**

Arifianto, Alexander R., Thomas Pepinsky, Evan A. Laksmana, Dewi Fortuna
Anwar, and Ann Marie Murphy. 2019. "Indonesia after the 2019 Election."
*Asia Policy* 14 (4): 43--87.

Aspinall, Edward. 2005. "Elections and the Normalization of Politics in
Indonesia." *South East Asia Research* 13 (2): 117--56.

---------. 2015. "Oligarchic Populism: Prabowo Subianto's Challenge to
Indonesian Democracy." *Indonesia* 99: 1--28.

Aspinall, Edward, and Marcus Mietzner. 2019. "Southeast Asia's Troubling
Elections: Nondemocratic Pluralism in Indonesia." *Journal of Democracy*
30 (4): 104--18.

Baswedan, Anies Rasyid. 2004. "Political Islam in Indonesia: Present and
Future Trajectory." *Asian Survey* 44 (5): 669--90.

Carnegie, Paul J. 2008. "Political Islam and Democratic Change in
Indonesia." *Asian Social Science* 4 (11): 3--7.

Collins, Elizabeth Fuller. 2003. "Islam Is the Solution: Dakwah and
Democracy in Indonesia." *Kultur, the Indonesian Journal for Muslim
Cultures* 3 (1): 148--82.

---------. 2004. "Islam and the Habits of Democracy: Islamic
Organizations in Post-New Order South Sumatra." *Indonesia*, no. 78:
93--120.

Collins, Elizabeth Fuller, and Ihsan Ali Fauzi. 2007. "Islam and
Democracy." *Inside Indonesia*, July 25, 2007.
https://www.insideindonesia.org/islam-and-democracy.

Eliraz, Giora. 2004. "Islamic Radicalism in Indonesia: The Global and
Historical Contexts." *RIMA: Review of Indonesian and Malaysian Affairs*
38 (1): 123--71.

Gammon, Liam. 2020. "Is Populism a Threat to Indonesian Democracy." In
*Democracy in Indonesia: From Stagnation to Regression*, edited by
Thomas Power and Eve Warburton, 101--17. Singapore: ISEAS.

Gueorguiev, Dimitar, Kai Ostwald, and Paul Schuler. 2018. "Rematch:
Islamic Politics, Mobilisation, and the Indonesian Presidential
Election." *Political Science* 70 (3): 240--52.

Hadiz, Vedi R., and Richard Robison. 2017. "Competing Populisms in
Post-Authoritarian Indonesia." *International Political Science Review*
38 (4): 488--502.

Hara, Abubakar Eby. 2017. "Populism in Indonesia and Its Threats to
Democracy." In *Third International Conference on Social and Political
Sciences (ICSPS 2017)*, 106--11. Atlantis Press.

Hasan, Noorhaidi. 2009. *Islamist Party, Electoral Politics and Da'wa
Mobilization among Youth: The Prosperous Justice Party (PKS) in
Indonesia*. S. Rajaratnam School of International Studies, Nanyang
Technological University.

Hatherell, Michael, and Alistair Welsh. 2020. "Populism and the Risks of
Conceptual Overreach: A Case Study from Indonesia." *Representation* 56
(1): 53--69. https://doi.org/10.1080/00344893.2019.1663904.

Hellmann, Olli. 2017. *Populism in East Asia*. Oxford: Oxford University
Press.

Kenny, Paul D. 2017. *Populism and Patronage: Why Populists Win
Elections in India, Asia, and Beyond*. Oxford University Press.

---------. 2022. "Populism in Southeast Asia." In *The Palgrave Handbook
of Populism*, 471--83. Springer.

Kershaw, Roger. 2004. "The Inconvenient Rationality of Islamism: Harakah
during the Pergau Dam Episode." *Indonesia and the Malay World* 32 (94):
345--65.

Kimura, Ehito. 2017. "Populist Politics in Indonesia." *Asia Pacific
Bulletin*, no. 407 (December). EastWestCenter.org/APB.

Lane, Max. 2017. *A New Ideological Contestation Emerging in Indonesia?*
ISEAS-Yusof Ishak Institute.

Liddle, R. William. 2000. "Indonesia in 1999: Democracy Restored."
*Asian Survey* 40 (1): 32--42.

Liddle, R. William, and Saiful Mujani. 2005. "Indonesia in 2004: The
Rise of Susilo Bambang Yudhoyono." *Asian Survey* 45 (1): 119--26.

Machmudi, Yon. 2008. *Islamising Indonesia: The Rise of Jemaah Tarbiyah
and the Prosperous Justice Party (PKS)*. Canberra: ANU Press.
https://doi.org/10.26530/OAPEN_459299.

---------. 2020. "The PKS and Tarbiyah Movement: Its Agenda and Future
in Indonesia." In *Rising Islamic Conservatism inIndonesia*, 163--80.
Routledge.

Mietzner, Marcus. 2014. "Indonesia's 2014 Elections: How Jokowi Won and
Democracy Survived." *Journal of Democracy* 25 (4): 111--25.

---------. 2015. *Reinventing Asian Populism: Jokowi's Rise, Democracy,
and Political Contestation in Indonesia*. Honolulu, HI: East-West
Center.

Murphy, Ann Marie. 2019. "Prospects for U.S.-Indonesian Relations in
Jokowi's Second Term." *Asia Policy* 14 (4): 79--87.

Nakamura, Mitsuo. 2005. *Islam and Democracy in Indonesia: Observations
on the 2004 General and Presidential Elections*. Islamic Legal Studies
Program, Harvard Law School Cambridge, MA.

Pardede, Carlos Margondo. 2020. "Prabowo Subianto-Sandiaga Uno Grand
Campaign 7 April 2019 On Indonesian Presidential Election: Experience of
Othering and Online Media Framing." *Jurnal Komunikasi Indonesia*,
40--48.

Qodari, Muhammad. 2005. "Challenge and Change in East Asia: Indonesia's
Quest for Accountable Governance." *Journal of Democracy* 16 (2):
73--87.

Rakhmani, Inaya, and Muninggar Sri Saraswati. 2021. "Authoritarian
Populism in Indonesia: The Role of the Political Campaign Industry in
Engineering Consent and Coercion." *Journal of Current Southeast Asian
Affairs* 40 (3): 436--60.

Robison, Richard, and Vedi R. Hadiz. 2017. "Indonesia: A Tale of
Misplaced Expectations." *The Pacific Review* 30 (6): 895--909.

Rukmana, Lisa, and Nuzon Sugito. 2020. "Strategy of Prabowo Populism in
2019 General Elections." In *2nd International Conference on Social
Science and Character Educations (ICoSSCE 2019)*, 20--23. Atlantis
Press.

Satrio, Abdurrachman. 2019. "A Battle between Two Populists: The 2019
Presidential Election and the Resurgence of Indonesia's Authoritarian
Constitutional Tradition." *Australian Journal of Asian Law* 19 (2):
175--95.

Sherlock, Stephen. 2004. "The 2004 Indonesian Elections: How the System
Works and What the Parties Stand For." *Canberra: Centre for Democratic
Institutions, Research School of Social Sciences, Australian National
University*.

Shihab, Najwa, and Yanuar Nugroho. 2008. "The Ties That Bind: Law,
Islamisation and Indonesia's Prosperous Justice Party (PKS)." *Austl. J.
Asian L.* 10: 233.

Siregar, Fahmi Azhari, Gun Gun Heryanto, Munadhil Abdul Muqsith, and
Refly Setiawan. 2020. "Prosperous Justice Party (PKS) Image Management
In The 2019 Election." *SALAM: Jurnal Sosial Dan Budaya Syar-i* 7 (11):
1009--24.

Slater, Dan. 2004. "Indonesia's Accountability Trap: Party Cartels and
Presidential Power after Democratic Transition." *Indonesia*, no. 78:
61--92.

Smith, Anthony L. 2004. "Indonesia's April 2004 Parliamentary Elections:
Implications for Presidential Elections and Policies. Asia-Pacific
Center for Security Studies, Volume 3, Number 6, June 2004."
ASIA-PACIFIC CENTER FOR SECURITY STUDIES HONOLULU HI.

Tanuwidjaja, Sunny. 2012. "PKS in Post-Reformasi Indonesia: Catching the
Catch-All and Moderation Wave." *South East Asia Research* 20 (4):
533--49.

Thompson, Eric C. 1999. "Indonesia in Transition: The 1999 Presidential
Elections." 9. National Bureau of Asian Research Washington DC.

Tomsa, Dirk. 2012. "Moderating Islamism in Indonesia: Tracing Patterns
of Party Change in the Prosperous Justice Party." *Political Research
Quarterly* 65 (3): 486--98.

Warburton, Eve. 2018. "Inequality, Nationalism and Electoral Politics in
Indonesia." *Southeast Asian Affairs*, 135--52.

---------. 2020. "Deepening Polarization and Democratic Decline in
Indonesia." *Political Polarization in South and Southeast Asia: Old
Division, New Dangers, Eds. Thomas Carothers and Andrew O'Donohue*,
25--40.

Warburton, Eve, and Edward Aspinall. 2019. "Explaining Indonesia's
Democratic Regression." *Contemporary Southeast Asia* 41 (2): 255--85.

Widian, Rizky, Putu Agung Nara Indra Prima Satya, and Sylvia Yazid.
2022. "Religion in Indonesia's Elections: An Implementation of a
Populist Strategy?" *Politics and Religion*, 1--23.

Zenzie, Charles U. 1999. "Indonesia's New Political Spectrum." *Asian
Survey* 39 (2): 243--64.

Ziv, Daniel. 2001. "Populist Perceptions and Perceptions of Populism in
Indonesia: The Case of Megawati Soekarnoputri." *South East Asia
Research* 9 (1): 73--88.
