---
title: Ireland
---


-   Date range: 1980-2020

-   Elections included:

    -   Legislative: 1981, 1982a, 1982b, 1987, 1989, 1992, 1997, 2002,
        2007, 2011, 2016, 2020.

    -   Presidential: 1983, 1990, 1997, 2004, 2011, 2018.

Ireland is a tricky one for populism research by European standards. The
legacy of nationalist politics has meant that there is little space for
a far-right populist movement. O'Malley and FitzGibbon (O'Malley and
FitzGibbon 2015) argue that populism has an 'everywhere and nowhere'
presence in Irish politics, in that the general tropes of rural people
being forgotten by the establishment is almost ubiquitous in political
rhetoric. This is most often said of the long-time dominant party Fianna
Fáil (Garner 2007, 109; Suiter 2016, 127) (although less so from the
2000s on). Despite this, there is not sufficient reason to treat that
party as populist by our standards -- further research should confirm
this.

## The Workers' Party 

In the late 1960s Sinn Fein and the IRA split into two groups: the
"official" group under the incumbent leadership and the "provisional"
breakaway faction. The official leadership wanted to remake
republicanism into a more Marxist-aligned and anti-militarism grouping,
whereas the provisionals wanted to continue armed struggle (so-called
"physical force" republicanism) against the British presence in the
North. Over time the provisionals became known as simply "Sinn Fein" and
the officials adopted the "Workers' Party" (WP) by 1982. The party
gradually improved its performance through the 1980s to peak at 5% in
1989, after which it split into a number of other left-wing movements.

Information on the WP is hard to come by, but evidence suggests that it
should be included in this dataset for its general anti-establishment
stance and its advocacy of anti-system politics. This included refusing
to participate in coalition governments (Abedi 2004, 53) (OTH_POLCLASS =
3). According to Dunphy & Hopkins, (Dunphy and Hopkins 1992, 105), it
benefited from a general protest vote against the more established
parties in the 1980s, particularly in the poorer areas of Dublin. As a
left-wing party, it should be inferred that it maintained a strong
OTH_FINANCIAL opposition, although it should be noted that I've not
found explicit articulations of this populism in research to-date.

WP initially maintained the republican tradition's anti-foreign
influence politics, accusing its rivals of being in the service of
"Anglo-American imperialism in all its exploitative forms" (Dunphy and
Hopkins 1992, 95). However over the years it reduced this pillar of its
politics in accordance with its shift toward a more domestic class
politics (Dunphy and Hopkins 1992, 97) (OTH_FOREIGN = 2), marking a
significant difference from the "provisional" Sinn Fein. The also party
differed from the provisional Sinn Fein in the force of its
anti-sectarian form of republicanism (Dunphy and Hopkins 1992, 94)
(OTH_ETHNIC = 1).

While the ideology of the party was strongly far-left since its
foundation, during the 1989 election it was led by the far more moderate
Proinsias de Rossa, who expressed more centrist views on market-based
economics. While there may be an argument that this should bring the
party's LRPOSITION coding towards the centre, I've left it at FL for now
given its Marxist ideological legacy since its foundation. Even though
the party tried to demilitarise its political movement (the bone of
contention between it and the provisionals), it nonetheless maintained
as association with a paramilitary (the official IRA) for years after
the split (Dunphy and Hopkins 1992, 94, 96), and should therefore be
coded as no lower than 2 on LIBDEMNORMS. There is no reason for the
party to rise above a 1 on the CHARISMA or INSIDER variables.

## Sinn Féin

Sinn Fein has been the face of the radical republican movement since its
foundation in 1905 -- although the party has undergone a number of
reformations since then. It is difficult to categorise, and doesn't fit
well into various party 'families' in the rest of Europe. Given its
association with militant republicanism -- historically against the
post-Treaty government of the republic and in favour of reunification
with Northern Ireland -- it has generally been the placeholder of
radical nationalist politics in Ireland. Yet it identifies as left wing,
and campaigns on many progressive platforms, making it stand out from
other 'radical nationalist' parties in Europe (McDonnell 2008, 212). The
party was a political outlier for many decades, before emerging in
greater numbers in recent elections -- arguably since its more
moderately nationalist rival Fianna Fail was associated with the
post-2008 economic crisis and the resulting controversial austerity
measures (Walsh and O'Malley 2012, 15), and since its acceptance of the
1997 Good Friday peace agreement moderated its image. The party's
fortunes improved dramatically in the 2020 elections, where it surged to
24% under new leader Mary Lou McDonald.

The most important reason for its inclusion here is its strong current
of anti-establishment politics dating back to the party's original
militant opposition to the treaty which established the Republic of
Ireland in 1922. SF regarded the parties who supported it (including
many of its own former members and factions) as sell outs to the
nationalist cause. For many decades the party refused to stand in
legislative elections for this reason, and recognised the pre-1922 Dáil
Éireann (revolutionary parliament) as the legitimate legislature. The
party slowly withdrew form this position to stand in national elections,
but the legacy of the hostility to the pro-treaty political class lives
on in the party. In several other aspects of policy (crime policy and
anti-drugs policy for example) it has expressed a general distrust of
the state, and campaigns against the established parties in a generally
populist manner (Fitzgibbon and Guerra 2010, 280; McDonnell 2008, 212;
Walsh and O'Malley 2012, 7; Maillot 2005, 5). In the words of O'Malley
and Fitzgibbon, SF "frequently juxtaposes itself with the mainstream
parties, Fianna Fáil and Labour, and promotes itself as the only
uncorrupted political representatives of the Irish people" (O'Malley and
FitzGibbon 2015, 284; see also Coakley 2021). In recent elections it has
considered the two main parties as a single entity engaged in a "phoney
war" against each other (Park and Suiter 2021, 126). Under the
leadership of Gerry Adams and Martin McGuinness the party has pursued a
more 'political' strategy of abandoning formal ties with militants
(especially the Irish Republican Army, of which many see SF as the
political wing) which has arguably led to a decline in its radical
anti-political class credentials. Nonetheless, the party still seems to
deserve a 3 on OTH_POLCLASS by our standards. Under the leadership of
McDonald, SF2 202 campaign has also been seen as highly "anti-elite" and
populist (Park and Suiter 2021, 126; Little 2020, 716).

Sinn Fein's nationalism is build primarily around an opposition to
foreign intervention, especially from the UK, and to a lesser degree
from the EU, which it generally opposes (McDonnell 2008, 212; Suiter
2016, 131). The party's designation of the UK as an enemy of the Irish
people dates back to its revolutionary foundations. Its Euroscepticism
has fluctuated over the years, but at times culminated in denunciations
of the "euro-elite" in Brussels and their bailout policies (O'Malley and
FitzGibbon 2015, 288; Fitzgibbon and Guerra 2010, see also), and after
the financial crisis it accused the Irish elite of giving in too easily
to easily to EU policies (ibid). This too has probably declined from a
peak in the Troubles (c.1969-97) after the signing of the Good Friday
Agreement (which the party supported). Nonetheless, the history and
culture of anti-colonial nationalism in the party earn it 3 on
OTH_FOREIGN.

While elements like nationalism strike a chord with the European radical
right, several aspects of its politics differ significantly from others
in this family. First the party is economically left-wing, advocating a
strong welfare state and protectionist policies to restrict the impact
of economic globalisation (O'Malley 2008, 969; Field 2020, 622; Müller
and Regan 2021, 550) (LRPOSITION = L). The party's nationalism is also
manifest in its anti-globalisation politics. It opposes the Irish
government's over reliance on foreign direct investment and instead
advocates state support for indigenous businesses (Walsh and O'Malley
2012, 7). In line with its leftist economic ideology and populist
rhetoric, the party has frequently juxtaposed the Irish people with the
financial elite, especially after the financial crisis. It's 2014 EU
manifesto accused mainstream parties of putting "the needs of the banks
ahead of the needs of the people" (O'Malley and FitzGibbon 2015, 290).
This strain of its politics is somewhat vague (Doyle 2005, 5), and while
worth registering does not quite reach a 3 on OTH_FINANCIAL (= 2).

Second, the party has a strong history of advocating minorities' rights
and is not anti-immigrant in any way (O'Malley 2008; Doyle 2005, 3)
(OTH_IMMIGRANT = 1). The party campaigned 'no' on the 2004 referendum on
repealing citizenship rights for the children of migrants, and has a
long association with anti-racist causes and movements (Doyle 2005, 3).
There are many reasons for this, but one of which may be the party's
long established advocacy for the rights of Irish migrants in other
countries, particularly the UK (O'Malley 2008, 974; O'Malley and
FitzGibbon 2015, 283).

The party's ethnocentrism is also difficult to pin down. Given its firm
advocacy for a united Ireland, it would seem to be somewhat majoritarian
on the Irish cultural (namely Catholic) identity, to which Ulster
Protestants are an important 'other'. This is in accordance with its
general anti-British attitudes. While it has renounced violence since
the Good Friday Agreement, the party does have a legacy of supporting
sectarian conflict in the Troubles (Walsh and O'Malley 2012, 7) which
makes it controversial to this day. Despite that, given its significant
focus on social issues and its repeated opposition to sectarianism, and
explicit endorsement of ethnic pluralism (McDonnell 2008, 212), SF does
not deserve a 3 on OTH_ETHNIC, and hence I have put it at 2 here. There
may even be an argument that it deserves a 1 on this scale, which should
be the subject of further investigation.

It is also somewhat authoritarian, not only due to its history of
advocating violent struggle (it is generally regarded as the political
wing of the Irish Republican Army) but also due to allegations that
Adams' leadership has relied on violence to quell internal dissent
(Walsh and O'Malley 2012, 13) and various other acts of violence
committed by the IRA (Fitzgibbon and Guerra 2010, 280). There would have
been a time when the party deserved a 3 on the LIBDEMNORMS scale, but
post-1998 (Good Friday Agreement) period it would be a stretch to
categorise it as a threat to democratic governance (Doyle 2005, 10),
hence they receive a 2 on this scale. The party has a long history and
an robust organisation, but in recent decades has become strongly
associated with the leadership of Gerry Adams (Walsh and O'Malley 2012,
13; Maillot 2005, 98), who seems to have had a very strong personal
control over its strategy and identity during the later years of his
leadership (see McDonnell 2008, 212 for a discussion of this point).
Adams stepped down as leader in 2018 and was replaced by Mary Lou
McDonald. We've therefore coded SF 2 on CHARISMA until 2018 and 1 in
2020. The party has never been in government (INSIDER = 1) (it has been
in a power sharing government in Northern Ireland, but this should not
count in this Republic of Ireland election).

## Peter Casey

Peter Casey is a businessperson and media personality who ran for
president in 2018. Coming from relative obscurity, he finished in second
place behind incumbent Michael Higgins with 23%. We've not found very
much information about Casey, but he appears to be universally regarded
as a right-wing populist (Field 2020, 619). The best information about
his campaign narrative comes from Duggan, who characterises Casey as a
maverick and outspoken negative campaigner against Higgins (Duggan 2019,
307). His campaign against Higgins included numerous allegations of
corruption -- for example that the president used €10,000 of taxpayers
money on dog-grooming bills (Duggan 2019, 309). More information would
be good to bolster this, but coupled with his "outsider" independence it
appears to fit a pattern OTH_POLCLASS campaigning (= 3).

The other issue for which Casey made headlines was his allegation that
the Irish traveller community were not a true ethnic minority and were
instead "basically people camping in someone else's land" (Duggan 2019,
310; Murphy 2021, 14). In the context of Irish society this is
essentially OTH_ETHNIC rhetoric, and hence we've coded Casey as 2 on
this variable. Given Casey's pro-business background it's safe to assume
that he did not campaign on OTH_FINANCIAL discourse, and we've not seen
any information regarding his rhetoric on OTH_IMMIGRANTS, OTH_FOREIGN or
OTH_MILITARY, and hence he is coded 1 for all. We've coded him R in
LRPOSITION in line with the literature (Field 2020, 619), and 3 on
CHARISMA given his lack of party and "headline grabbing" campaigning
style (Duggan 2019, 307). We've seen no evidence to code him above 1 on
LIBDEMNORMS, and he was never part of a government before his campaign
(INSIDER = 1).

**References**

Abedi, Amir. 2004. *Anti-Political Establishment Parties: A Comparative
Analysis*. Routledge.

Coakley, John. 2021. 'The Election in Context'. In *How Ireland Voted
2020: The End of an Era*, edited by Michael Gallagher, Michael Marsh,
and Theresa Reidy, 321--39. Cham: Springer International Publishing.
https://doi.org/10.1007/978-3-030-66405-3_14.

Doyle, John. 2005. 'Republican Policies in Practical Politics: Placing
Contemporary Sinn Féin in a European Context'. In *University College
Dublin, Institute for British-Irish Studies, IBIS Working Papers,
No.45*. University College Dublin. Institute for British-Irish Studies.

Duggan, Alan. 2019. 'Irish Presidential Election 2018'. *Irish Political
Studies* 34 (2): 303--14.

Dunphy, Richard, and Stephen Hopkins. 1992. 'The Organizational and
Political Evolution of the Workers' Party of Ireland'. *The Journal of
Communist Studies and Transition Politics* 8 (3): 91--118.

Field, Luke. 2020. 'Irish General Election 2020: Two-and-a-Half Party
System No More?' *Irish Political Studies* 35 (4): 615--36.

Fitzgibbon, John, and Simona Guerra. 2010. 'Not Just Europeanization,
Not Necessarily Populism: Potential Factors Underlying the Mobilization
of Populism in Ireland and Poland'. *Perspectives on European Politics
and Society* 11 (3): 273--91.

Garner, Steve. 2007. 'Ireland and Immigration: Explaining the Absence of
the Far Right'. *Patterns of Prejudice* 41 (2): 109--30.

Little, Conor. 2020. 'Change Gradually, Then All at Once: The General
Election of February 2020 in the Republic of Ireland'. *West European
Politics* 44 (3): 714--23.

Maillot, Agnès. 2005. *New Sinn Féin: Irish Republicanism in the
Twenty-First Century*. Psychology Press.

McDonnell, Duncan. 2008. 'The Republic of Ireland: The Dog That Hasn't
Barked in the Night?' In *Twenty-First Century Populism: The Spectre of
Western European Democracy*, edited by Daniele Albertazzi and Duncan
McDonnell, 198--216. Basingstoke and New York: Palgrave Macmillan.

Müller, Stefan, and Aidan Regan. 2021. 'Are Irish Voters Moving to the
Left?' *Irish Political Studies* 36 (4): 535--55.

Murphy, Gary. 2021. 'The Road to the Election'. In *How Ireland Voted
2020: The End of an Era*, edited by Michael Gallagher, Michael Marsh,
and Theresa Reidy, 1--22. Cham: Springer International Publishing.
https://doi.org/10.1007/978-3-030-66405-3_1.

O'Malley, Eoin. 2008. 'Why Is There No Radical Right Party in Ireland?'
*West European Politics* 31 (5): 960--77.

O'Malley, Eoin, and John FitzGibbon. 2015. 'Everywhere and Nowhere:
Populism and the Puzzling Non-Reaction to Ireland's Crises'. In
*European Populism in the Shadow of the Great Recession*, edited by
Hanspeter Kriesi and Takis S. Pappas, 281--94. Colchester: ECPR Press.

Park, Kirsty, and Jane Suiter. 2021. 'Media and the Election: Social and
Traditional Media Narratives in the Campaign'. In *How Ireland Voted
2020: The End of an Era*, edited by Michael Gallagher, Michael Marsh,
and Theresa Reidy, 113--34. Cham: Springer International Publishing.
https://doi.org/10.1007/978-3-030-66405-3_6.

Suiter, Jane. 2016. 'Ireland: The Rise of Populism on the Left and among
Independents'. In *Populist Political Communication in Europe*, edited
by Toril Aalberg, Frank Esser, Carsten Reinemann, Jesper Stromback, and
Claes De Vreese, 127--37. New York: Routledge.

Walsh, Dawn, and Eoin O'Malley. 2012. 'The Slow Growth of Sinn Féin:
From Minor Player to Centre Stage?' Dublin City University Working
Papers in International Studies, no.2/2012. Dublin City University.

