---
title: Latvia
subtitle: |-
  Date range: 1990-2020
  <br>
  Latvia is generally considered a country where populist rhetoric
  (particularly in the form of anti-corruption politics) is somewhat
  ubiquitous, including in the main parties, making it a very difficult
  case. Several authors have suggested that the master cleavages of
  Latvian politics have been ethno-linguistic (Latvian speakers and
  Russian speakers) and, within the ethnic Latvian side of that cleavage,
  corruption (anti-corruption vs "oligargic" parties) (Auers 2013, 86).
  Most populist parties have been short-lived entrants within the
  anti-corruption side of the Latvian bloc, although the far-right
  National Alliance has recently emerged on Latvian ethno-centric lines.
  Latvia's politics has also been generally been very volatile, with a
  succession of new parties winning big in post-communist elections. There
  are quite a few difficult calls below, and some parties that arguably
  could be featured that are currently not.
title-block-banner: yes

---

# Case notes

## People's Movement for Latvia (Seigerists' Party)

People's Movement for Latvia (*Tautas Kustība Latvijai*, TKL) was
founded in 1994 to contest in the 1995 election. As its semi-formal
nickname **--** Seigerists' Party **--** suggests, it was the vehicle of
its founder, controversial German-Latvian businessman and former LNNK MP
Joaachim Siegerists, "a demagogic populist with a talent for
self-advertisement" (Davies and Ozolins 1996, 126). Siegerists, born in
Germany, only discovered his Latvian heritage in 1992, at which point he
decided to become engaged in the Latvian political scene without even
speaking the Latvian language fluently (Nissinen 1999, 137). Despite
this, TKL exceeded expectations to win 15% in 1995, before crashing to
1.73 in 1998.

Like the contemporaneous DPS, the TKL captured the generally frustrated
mood of the Latvian electorate with a discourse harshly critical of the
political establishment (Pabriks and Štokenberga 2006, 59). Nissinen
claims that his rhetoric accused any political rival of being a
"communist", and tended not to discriminate among members of the
political establishment (he suggested that 80% of Latvian politicians
were "bandits") (Nissinen 1999, 139). The country's woes had not
improved, he claimed, because the old communist elite (the "devil") were
still in power (Nissinen 1999, 139) (OTH_POLCLASS = 3).

While the party was certainly nationalist, the role of ethnocentrism in
Siegerists party is difficult to pin down. He had a chequered history of
association with far right organisations in Germany, where he was
accused of race hatred offences (Davies and Ozolins 1996, 126). He was
also on record making a number of anti-Roma statements, and Učeň
categorises the party xenophobic (although without explanation) (Učeň
2007, 52). Nonetheless, Nissinen convincingly argues that there was not
a lot of this in his 1995 platform, even if the media accused of being
far-right (Nissinen 1999, 136--40). We have coded him 2 on OTH_ETHNIC.
There is no evidence for anything registering on the OTH_IMMIGRANT
variable. With a generally pro-market neoliberal platform (Nissinen
1999, 136), the party did not antagonise big business or the wealthy as
an "other" (OTH_ECONOMIC = 1). Likewise, according to Nissinen
Siegerists was harshly critical of Russia in his 1993 election, but
shifted sharply to support greater ties with Russia by 1995 (OTH_FOREIGN
= 1)

The party has been called "non-ideological" (Balcere 2013, 95), but was
clearly right-wing on both economic policy and nationalist rhetoric
(Müller-Rommel and Nørgaard 2001, 31) (LRPOSITION = R). The party is
generally seen to be a vehicle for Siegerists' personality -- to the
extent that it is often called "Seigerists' Party" (Davies and Ozolins
1996, 126; see also Pettai and Kreuzer 1998, 156; Nissinen 1999, 136)
(CHARISMA = 3). Nissinen goes as far as calling it a "personality cult"
due to the synonymy between leader and party (Nissinen 1999, 136). Aside
from his flamboyant and controversial personality, his very conventional
campaign methods (handing out bananas to would-be voters, for example)
received considerable press attention. Učeň categorises the party as
"authoritarian" (Učeň 2007, 52), but other than the fact that Seigerists
had a generally domineering personality, we have not see any reason to
label the party greater than 1 for LIBDEMNORMS. Niether Siegerists nor
his party served in government (INSIDER = 1)

## Democratic Party Saimnieks 

Democratic Party Saimnieks ("Master", DPS) were a merger of the smaller
"Saimnieks" local party from Riga and the Democratic Centre party, who
united to contest the 1995 elections (Ikstens 2003, 5). It had ties to
both business elites and liberal communists from the old regime
(Nissinen 1999, 146). The party achieved a breakout 15% in those
elections and went on to govern in a coalition before collapsing in the
subsequent 1998 elections.

The party is almost universally described as populist in the literature
(see Učeň 2007, 59; Balcere 2013, 95). It campaigned in 1995 on a
vaguely anti-corruption, and anti-establishment platform in its breakout
1995 election (Auers 2013, 102), appealing to those who had lost out in
the market transitions (Auers and Kasekamp 2013, 239) and victims of a
recent major banking collapse (Pettai and Kreuzer 1998, 156). There is
not a lot available detailing the nature of the party's actual populist
rhetoric and allegations in 1995, and Nissinen, whose text is most
detailed, seems to think that the party's populism was significantly
lighter than the likes of the Seigerists'(Nissinen 1999). Hence we have
coded it 2 for OTH_POLCLASS.

The party has been variously called centre-right (Auers and Kasekamp
2013, 88; Nakai 2014, 68), centrist (Stanley 2017, 149; Balcere 2013,
95), and centre left (Nissinen 1999, 146; Galbreath 2006, 387; Dreifelds
1995, 89). We have placed its LR_POSITION coding at C, but this could be
contested. According to Auers & Kasekamp, corrupt businessmen were a
target of the party's populism (Auers and Kasekamp 2013, 239), although
Nissinen claims that the party had significant links with the business
class (particularly Russian businesses) (Nissinen 1999, 147; see also
Nakai 2014, 68). We have left the OTH_ECONOMIC coding at 2. We have seen
no evidence to register the party on the OTH_ETHNIC, OTH_FOREIGN or
OTH_IMMIGRANTS variables (all = 1).

The party is not discussed in generally leader-centric terms (CHARISMA =
1), or in any way that threatened the democratic order (LIBDEMNORMS =
1). As the party was in a governing coalition from 1995, it is labelled
2 on INSIDER in the subsequent 1998 election.

## New Era 

New Era (*Jaunais Laiks*, JL) was formed in 2001 by the former Central
Bank Governor Einārs Repše to compete in the 2002 election. Its
anti-corruption rhetoric proved highly successful, with the party
winning those elections and Einārs Repše becoming Prime Minister for a
short period before falling out with coalition partners. The party
continued surprisingly well in the next elections without him. It is
often seen in similar terms as the contemporaneous Res Publica party in
neighbouring Estonia.

Repše, a popular public figure at the time, claimed to be shocked by the
rates of corruption and mismanagement in the political system (Auers
2002, 106; 2018, 352), and accused the country's incumbent elites of
betraying the national interests (Učeň 2007, 59; Stanley 2017, 150;
Balcere 2016). As its name suggests, it sold the electorate an idea of
"new politics" in which the slate would be wiped clean and a new
generation brought in (Sikk 2009, 7) (OTH_POLCLASS = 3). According to
Učeň (Učeň 2007, 59--60), the party maintained this anti-political
establishment stance even after forming government.

The party is usually considered centre-right (Učeň 2007, 59; Nakai 2014,
66) and neo-liberal (Sikk 2006, 133), or occasionally centrist (Auers
and Kasekamp 2013, 239). We have labelled it CR on LRPOSITION. In
accordance with its opposition to corruption, the party styled itself as
hostile to "oligarchs" (Auers 2013, 104; Nakai 2014, 70) -- a term which
in Latvia refers to wealthy politicians rather than just wealthy
citizens (see Auers 2013, 103). Due to this precise meaning it could be
argued that the party should be labelled 1 on OTH_ECONOMIC -- we have
left it at 2 for now. The literature makes no reference to any stances
against OTH_ETHNIC, OTH_IMMIGRANTS, OTH_FOREIGN or OTH_MILITARY (all =
1).

The party was generally considered to be based around Repše's
personality (Pabriks and Štokenberga 2006, 58; Sikk 2006, 153), and was
able to mobilise successfully without spending very much money (Sikk
2006, 141) (CHARISMA = 3). However, Repše resigned from its leadership
in 2004, and we have therefore dropped this to 1 for 2006. The party did
not appear to violate any LIBDEMNORMS (= 1). Given that New Era was
founded by the former head of the central bank, it would be wrong to
label it a 1 on INSIDER even though he was not formally in government,
so we've placed the party at 2 for its initial election, and 3 afterward
(after Respse was Prime Minister).

## TB-LNNK/National Alliance 

This entity is a complicated grouping of three separate parties. "For
Fatherland and Freedom" (*Tēvzemei un Brīvībai*/TB) and the Latvian
National Independence Movement (*Latvijas Nacionāls Neatkarības
kustība/*LNNK) were separate nationalist parties in the early 1990s that
merged in 1997. This party was right wing, and generally ethnocentric in
favour of the ethnically Latvian majority, but from the available
evidence it does not seem to be a populist party (Galbreath 2006;
Braghiroli and Petsinis 2019; Auers and Kasekamp 2013, 239). In 2010,
TB-LNNK allied with the far-right youth movement and political party All
for Latvia! (Visu Latvijai!/VL) to form a single list in the elections
that year, and a formal party, the National Alliance (NA), in 2011. The
VL group had long criticised TB-LNNK for selling out nationalist
interests (Auers 2011, 3). According to Auers and Kasekamp, the All for
Latvia! grouping effectively took over the party after the merger (Auers
and Kasekamp 2013, 236). The National Alliance is usually considered
Latvia's first and so far only true populist radical right party, and is
often associated with the Estonian People's Conservative Party (EKRE).

According to Auers, "The VL! wing of the NA added anti-elite populism to
the existing nativism and authoritarianism of TB-LNNK, with VL!s more
youthful deputies regularly tweeting and using social media to complain
about the older parties' lack of respect for parliament" (Auers 2018,
351). The VL! had achieved this image via a number of well-attended
rallies in the 2006 election (when they nonetheless failed to pass the
5% threshold) that offered an "aggressive critique of the political
elite" (Auers and Kasekamp 2013, 239). While this suggests a 3 on
OTH_POLCLASS, Braghiroli & Petsinis, suggest that this rhetoric has been
checked since entering government after the 2011 elections (Braghiroli
and Petsinis 2019), and hence we have coded the party 3 for 2010 and
2011 and 2 since then. Further research should clarify this.

While a general ethno-centric stance had been common among ethnic
Latvian parties in the immediate post-communist period, the increasing
acceptance of multiculturalism allowed the NA to claim that the national
elite had abandoned the ethnic majority (Braghiroli and Petsinis 2019,
4). In the NA (and other parties) the most common target of this is the
Russian-speaking minority (Jakobson et al. 2012, 47). Among numerous
controversial manifestations of this, it supported an annual march of
Waffen SS veterans, the limitation of the Russian language in the
private sphere (job advertisements for example) (Auers 2011, 5), and
commenced its 2011 manifesto with the line that "Latvians must feel at
home in their ethnic homeland" (Auers and Kasekamp 2013, 242; see also
Bennich-Björkman and Johansson 2012). There are also credible
accusations of anti-Semitism in the party (Auers and Kasekamp 2013, 243)
(OTH_ETHNIC = 3). NA is staunchly opposed to refugees (Braghiroli and
Petsinis 2019)(OTH_IMMIGRANT = 3), but this appears to only have become
an issue after the 2015 migrant crisis in Europe (see Auers and Kasekamp
2013, 241), when Latvia agreed to accept its quota. We have labelled the
party 1 on this variable before the crisis. The party is hostile to the
influence of both Russia and to a lesser extent the EU (Braghiroli and
Petsinis 2019, 6). The party espouses a well-articulated "intermarium"
theory that attempts to maintain eastern European culture from threats
emanating from both east and west (OTH_FOREIGN = 3). We have seen no
evidence that the party is opposed to OTH_ECONOMIC (= 1).

The party is unambiguously radical right (Auers and Kasekamp 2013, 239)
(LRPOSITION = FR), and has violated a number of important democratic
norms, particularly by parading in military uniforms and celebrating the
memory of controversial pre-war dictator Karlis Ilmanis (Auers and
Kasekamp 2013, 243) (LIBDEMNORMS = 3). While backed by a strong and
somewhat independent party organisation (the old TB-LNNK), the NA is
strongly identified with its young and charismatic leader Raivis
Dzintars (Auers and Kasekamp 2013, 240) (CHARISMA = 2). Given that the
NA was in coalition government after the 2011 elections, we've labelled
it 2 on INSIDER from 2014.

## Zatlers Reform Party

The (September) 2011 election occurred so soon after the (December) 2010
one because incumbent president Valdis Zatlers triggered a clause in the
constitution to recall parliament. He did this because he alleged that a
trio of oligarchs had taken control of the government: "At the moment we

can observe not just theft from state resources but a gradual
privatization of Latvian democracy" (cited in Auers 2013, 85). Zatlers
went on to form his own party to participate in the election, the
"Reform Party" (*Reformu partija*, RP), a.k.a "Zatler's Reform Party"
(ZRP).

As the name and context suggests, the central issue of the party was the
endemic corruption of the political class (OTH_POLCLASS = 3). It is a
somewhat difficult case because the party alleged that specific parties,
not all politicians, were corrupt, so there could be an argument that it
shouldn't feature in the dataset. However, available evidence suggests
that the 2011 election called by Zatler "almost exclusively focused
around corruption and the illicit influence of the oligarchs" (Auers
2013, 105), and that the party did talk about corruption in "systemic"
terms (Jakobson et al. 2012, 45). On this basis the party is often
considered populist (Auers 2018, 352; Auers and Kasekamp 2013, 245;
Jakobson et al. 2012, 122). For its anti-oligarch stance, we've coded it
3 on OTH_ECONOMIC. There is some evidence that the party opposed Russian
influence in Latvia (Jakobson et al. 2012, 49), but not to the extent to
register on OTH_FOREIGN (= 1). We've seen no reason to code above one
for OTH_ETHNIC, OTH_IMMIGRANTS, or OTH_MILITARY (= 1).

The party appears to be centre right (LR_POSITION = CR) but this should
be confirmed. The party was based on the personality of Zatler himself
(Jakobson et al. 2012) (CHARISMA = 3), and seems not to have threatened
democratic norms (LIBDEMNORMS = 1). Zatler was President of Latvia, but
given that this position is not the head of government in Latvia, we
have coded the party 2 on INSIDER.

## For Latvia from the Heart 

For Latvia from the Heart (*No sirds Latvijai/*NSL) was founded by
former auditor general Ingunda Sudraba, famed for tackling the
"oligarch's" whose influence in politics her party opposed. Not a lot is
written about the party other than the fact that it is generally
considered right wing (Braghiroli and Petsinis 2019, 16; Kneuer 2019,
37) (LRPOSITION = CR), that it campaigned on an anti-corruption message
(Eihmanis 2019, 258; Cianetti 2014, 3), and that her campaign took a hit
from a video of her having lunch with a Russian "oligarchs" in question.
Nonetheless, NSL picked up 6.8% in the 2014 election, before cratering
to less than 1% in 2018. For her anti-oligarch stance I've labelled her
2 on OTH_ECONOMIC.

Sudraba is considered by Bukovskis and Sprūds to be a "charismatic
longtime critic of Latvia's bureaucratic apparatus and political
leadership" (Bukovskis and Sprūds 2015) (OTH_POLCLASS = 3). There
appears to be nothing to the party other than its leader (CHARISMA = 3),
and there is no evidence for anything registering on any other variable.
We do not consider her position as auditor general as being an INSIDER
(= 1). More research should be done to confirm whether NSL's populism
reaches the threshold of the dataset.

## Who owns the state?

Who owns the State? (*Kam Pieder Valsts?* KPV-LV is another
anti-establishment party, founded by independent MP Artuss Kaimiņš, a
former actor who became well known for filming parliamentary proceedings
and posting them online to show problems in the political system
(Balcere 2016; Auers 2018, 352). The party's message is that the
political establishment -- politicians and civil servants -- is corrupt
and that existing parties waste taxpayers' money (Kaža 2018; Auers 2018,
352) (OTH_POLCLASS = 3). Recent scandals in the political and banking
sectors (see Higgins 2018) helped the party surge to second place in the
2018 elections only two years after its foundation, performing
particularly well among diasporic communities (Arroque 2018). It formed
coalition government after those elections.

The party is anti-EU (Higgins 2018) (OTH_FOREIGN = 2), but, from what we
can tell, does not hold many traditionally far-right positions against
OTH_ETHNIC and OTH_IMMIGRANTS (= 0). Available evidence suggests that it
is conservative (LRPOSITION = CR) although it seems somewhat similar to
the Five Star Movement in Italy in its deliberately non-ideological
identity (Petsinis 2019), focusing only on hostility to the political
class. It is also heavily reliant on Kaimiņš\' confrontational
personality (Arroque 2018; Kaža 2016; Bukovskis and Sprūds 2015)
(CHARISMA = 3). Given Kaimiņš threats to "personally fire" journalists
who upset him (Higgins, 2018), KPV-LV constitutes a mild threat to
liberal democratic norms (LIBDEMNORMS = 2). Kaimiņš has not been any
kind of INSIDER (= 1).

**References**

Arroque, Stefano. 2018. 'Who Owns the State? Latvian Anti-Establishment
Party Aims for Power'. New Eastern Europe. 13 November 2018.
https://neweasterneurope.eu/2018/11/13/owns-state-latvian-anti-establishment-party-aims-power/.

Auers, Daunis. 2002. 'Latvia's 2002 Elections-Dawn of the New Era'.
*Eeastern European Constitutional Review* 11 (4): 106--10.

---------. 2011. 'Europe and the 2010 Parliamentary Election in Latvia'.
Election Briefing No.60. European Parties Elections and Referendums
Network (EPERN).

---------. 2013. 'Latvia'. In *The Handbook of Political Change in
Eastern Europe*, edited by Sten Berglund, 3rd ed., 85--123. Elgar
Original Reference. Cheltenham. UK ; Edward Elgar.

---------. 2018. 'Populism and Political Party Institutionalisation in
the Three Baltic States of Estonia, Latvia and Lithuania'. *Fudan
Journal of the Humanities and Social Sciences* 11: 341--55.

Auers, Daunis, and Andres Kasekamp. 2013. 'Comparing Radical-Right
Populism in Estonia and Latvia'. In *Right-Wing Populism in Europe:
Politics and Discourse*, edited by Ruth Wodak, Majid KhosraviNik, and
Brigitte Mral, 235--48. London and New York: Bloomsbury Academic.

Balcere, Ilze. 2013. 'Perceptions of Populism: Analysis of Media
Discourse in Latvia'. *Baltic Journal of Political Science*, no. 2:
85--97.

---------. 2016. 'Latvia Pop: Three Cases of Post-Soviet Populism'.
*POP: Populism Observer* (blog). 27 June 2016.
https://populismobserver.com/2016/06/27/latvia-pop-three-cases-of-post-soviet-populism/.

Bennich-Björkman, Li, and Karl Magnus Johansson. 2012. 'Explaining
Moderation in Nationalism: Divergent Trajectories of National
Conservative Parties in Estonia and Latvia'. *Comparative European
Politics* 10 (5): 585--607.

Braghiroli, Stefano, and Vassilis Petsinis. 2019. 'Between Party-Systems
and Identity-Politics: The Populist and Radical Right in Estonia and
Latvia'. *European Politics and Society* 20 (4): 431--49.

Bukovskis, Kārlis, and Andris Sprūds. 2015. 'Latvia'. In *Nations in
Transit 2015*, edited by Freedom House. Rowman & Littlefield.
https://freedomhouse.org/report/nations-transit/2015/latvia.

Cianetti, Licia. 2014. 'The Governing Parties Survived Latvia's
Election, but the Issue of the Country's Russian-Speaking Minority
Remains Centre-Stage'. *LSE European Politics and Policy (EUROPP) Blog*
(blog). London School of Economics and Political Science. 2014.
blogs.lse.ac.uk
/europpblog/2014/10/08/the-governing-parties-survived-latvias-election-but-the-issue-of-thecountrys-
russian-speaking-minority-remains-centre-stage/.

Davies, Philip John, and Andrejs Valdis Ozolins. 1996. 'The Latvian
Parliamentary Election of 1995'. *Electoral Studies* 15 (1): 124--28.

Dreifelds, Juris. 1995. 'Latvia'. In *Estonia, Latvia, and Lithuania
Country Studies*, edited by Walter R. Iwaskiw, 83--165. Washington, DC:
Library of Congress, Federal Research Division.

Eihmanis, Edgars. 2019. 'Latvia--An Ever-Wider Gap: The Ethnic Divide in
Latvian Party Politics'. In *European Party Politics in Times of
Crisis*, edited by Swen Hutter and Hanspeter Kriesi, 236--58. Cambridge:
Cambridge University Press.

Galbreath, David J. 2006. 'From Nationalism to Nation-Building: Latvian
Politics and Minority Policy'. *Nationalities Papers* 34 (4): 383--406.

Higgins, Andrew. 2018. 'Populist Wave Hits Latvia, Lifting Pro-Russia
Party in Election'. *The New York Times*, 7 October 2018, sec. World.
https://www.nytimes.com/2018/10/07/world/europe/latvia-election-russia.html.

Ikstens, Jānis. 2003. 'Party Organizations in Latvia'. Research paper.
National Council for Eurasian and East European Research.

Jakobson, M., Ilze Balcere, Oudekki Loone, Anu Nurk, Tõnis Saarts, and
Rasa Zakeviciute. 2012. 'Populism in the Baltic States'. Research
report, Tallinn University Institute of Political Science and Governance
/ Open Estonia Foundation.

Kaža, Juris. 2016. 'Latvia's New Taxpayer Party --- Not Insane after
All?' Medium. 5 May 2016.
https://juriskaza.medium.com/latvias-new-taxpayer-party-not-insane-after-all-9903919d1feb.

---------. 2018. 'Who Is Who In Upcoming Latvian Parliamentary
Elections'. Re:Baltica. 14 August 2018.
https://en.rebaltica.lv/2018/08/who-is-who-in-upcoming-latvian-parliamentary-elections/.

Kneuer, Marianne. 2019. 'The Tandem of Populism and Euroscepticism: A
Comparative Perspective in the Light of the European Crises'.
*Contemporary Social Science* 14 (1): 26--42.

Müller-Rommel, Ferdinand, and Ole Nørgaard. 2001. 'Latvia'. In *Cabinets
in Post-Communist East-Central Europe and in the Balkans: Introduction*,
edited by Jean Blondel, Ferdinand Müller-Rommel, Jean Blondel, Ferdinand
Müller-Rommel, and Ole Nørgaard, 29--39. Basingstoke: Palgrave.

Nakai, Ryo. 2014. 'The Influence of Party Competition on Minority
Politics: A Comparison of Latvia and Estonia'. *JEMIE* 13 (1): 57--85.

Nissinen, Marja. 1999. *Latvia's Transition to a Market Economy:
Political Determinants of Economic Reform Policy*. Basingstoke:
MacMillan.

Pabriks, Artis, and Aiga Štokenberga. 2006. 'Political Parties and the
Party System in Latvia'. In *Post-Communist EU Member States: Parties
and Party Systems*, edited by Susanne Jungerstam-Mulders, 51--68.
Aldershot: Ashgate Publishing, Ltd.

Petsinis, Vassilis. 2019. 'Identity Politics and Right-Wing Populism in
Estonia: The Case of EKRE'. *Nationalism and Ethnic Politics* 25 (2):
211--30.

Pettai, Vello, and Marcus Kreuzer. 1998. 'Party Politics in the Baltic
States: Social Bases and Institutional Context'. *East European Politics
and Societies* 13 (1): 148--89.

Sikk, Allan. 2006. 'Highways to Power: New Party Success in Three Young
Democracies'. Tartu University Press.

---------. 2009. 'Parties and Populism'. Working Paper 2009-02.
University College London.

Stanley, Ben. 2017. 'Populism in Central and Eastern Europe'. *The
Oxford Handbook of Populism* 1 (6): 140--58.

Učeň, Peter. 2007. 'Parties, Populism, and Anti-Establishment Politics
in East Central Europe'. *The SAIS Review of International Affairs* 27
(1): 49--62.
