---
title: Netherlands
subtitle: 'Date range: 1980-2020'
title-block-banner: yes

---

# Case notes

## List Pim Fortuyn

Wilhelmus 'Pim' Fortuyn was a sociologist who emerged as a leader of a
small new party, *Leefbaar Nederland* (LD) ("Liveable Netherlands"),
before the 2002 elections. The previous year he had written a book
called "against the Islamization of our culture", asserting that Muslim
influence was a threat to liberal Dutch values. After breaking with LD
and forming his own party, *List Pim Fortuyn* (LPF), Fortuyn was shot
and killed while campaigning three months before the elections. LPF did
surprisingly well in those elections with 17%, before infighting led to
its collapse soon afterward.

Lucardie describes Fortuyn's politics as "an eclectic -- but not
necessarily incoherent -- mixture of liberalism, nationalism,
communitarianism and populism" (Lucardie 2008, 158). Fortuyn campaigned
on the idea that bureaucrats, managers, and "partycrats" ran the country
without considering the needs of average citizens (Lucardie 2008, 159;
Van Kessel 2015, 102) (OTH_POLCLASS = 3). By far his biggest platform
was his intolerance towards Muslims, including asylum seekers. In a
notorious interview (that saw him sacked by LD), he claimed that Islam
was a "backward culture" (Van Kessel 2015, 102) and that if it were up
to him he would ban Muslims from entering the country (Akkerman 2005,
348). In Akkerman's words, "his nationalist wake-up call became
increasingly shrill. He feared the downfall of Dutch culture and Dutch
society, and argued that people in Western Europe are living in a
situation like the last days of the Roman Empire" (Akkerman 2005, 347).
Unlike other far-right politicians in the region, this position was not
rooted in a fundamentally socially conservative outlook, but one of
protecting liberal social values which he considered Islam to be
essentially hostile to (Akkerman 2005, 341). Due to this threat, the LPV
manifesto spoke called for restrictions in immigration (Van Kessel 2015,
104). This clearly warrants a 3 for OTH_ETHNIC and OTH_IMMIGRANTS.
Despite being anti-EU, it is not clear that hostility to the EU in the
form of OTH_FOREIGN populist rhetoric is relevant here (= 1). Likewise,
Fortuyn's liberal rhetoric appears not to have incorporated any
OTH_ECONOMIC rhetoric (despite being a former Marxist).

Fortuyn himself was a flamboyant and outspoken figure, and as the name
of the party suggests, he dominated it (Lucardie 2008, 158; Koopmans and
Muis 2009, 643) (CHARISMA=3). His ideology was liberal in both economic
policy and social values, but included notable conservative streaks in
law and order and the preservation of national culture (Lucardie 2008,
159; Van Kessel 2015, 104). In line with most stances in the literature
(Van Holsteyn, Irwin, and Den Ridder 2003; Akkerman 2005, 344), We have
labelled him R in LRPOSITION. We have also not seen any evidence that
the party violated any LIBDEMNORMS (= 1). We have raised INSIDER from 1
to 2 in 2003 as the LPF was in a coalition government after the 2002
election.

## Party for Freedom 

Geert Wilders was an MP who fell out with the Liberal Party over the
question of Turkey's EU membership in 2004. He went on to form his own
party, the Freedom Party (*Partij voor de Vrijheid*, PVV) on the eve of
the 2006 election. After success in this and the subsequent 2010
election, the PVV entered a minority government that lasted until 2012,
when the party refused to sign on to the government's austerity
measures.

In many ways it seems that Wilders follows in Fortuyn's footsteps:
politically populist, culturally nationalist, avowedly liberal, and
fanatically opposed to Islam. In van Kessel's words: "Wilders appealed
to the 'ordinary people' even more explicitly than Fortuyn, and shared
the latter's hostility towards the political elite" (Van Kessel 2015,
104). This included the allegation that "cowardly and frightened" elites
of all major parties had "hijacked" the country from "ordinary citizens"
(Van Kessel 2015, 104; Vossen 2011, 183) (OTH_POLCLASS = 3). Frequently,
this elite was alleged to be the political left -- or the "Church of the
Left" (Coffé and Van Den Berg 2017, 878). In one expression, Wilders
argued for a more direct democracy: "Not the political elite, but the
people should have the opportunity to express more often their will,
because together the people know better than that left-wing clique"
(cited in Vossen 2011, 185).

The PVV's central message lay in its opposition to Islam, which the
party saw as a political ideology more than a religion (Lucardie and
Voerman 2013, 193; Vossen 2011, 183). From 2006, Wilders began
propagating radical conspiracy theories of the Islamification of Europe,
suggesting a deliberate plot on the part of all Muslims to mask their
true agenda of political domination (Vossen 2011, 184). Like Fortuyn,
this was packaged in a peculiar defence of liberal and progressive
social values -- although according to Lucardie and Voerman the party's
liberalism diminished over time (Lucardie and Voerman 2013, 191). In the
words of one party document, Islamisation "drives out Jews and gay
people, and flushes the century-long emancipation of women down the
toilet" (cited in Van Kessel 2015, 105). The party even claimed to
support the integration of various non-white minorities like the
Surinamese and Indo-Dutch (Vossen 2011, 185), and Wilders was a critic
of traditional nationalism due to its destructive nature (Lucardie and
Voerman 2013, 192). As with Fortuyn however, the fact that this is
atypical of the European far-right in this regard should not reduce it
from a 3 on both the OTH_ETHNIC and OTH_IMMIGRANT variables --
especially the latter as Wilders increasingly targeted other migrants
from Poland, Bulgaria, Romania and other locations (Vossen 2011, 185).
With a somewhat mixed approach to economic policy, OTH_ECONOMIC has not
been a relevant factor for the PVV (the party's economic platform has
generally been quite liberal, albeit increasingly opposed to spending
cuts) (Lucardie and Voerman 2013, 192; Vossen 2011, 186).

Where Wilders differed from Fortuyn is in the degree of his
Euroscepticism. The party believes that the EU is a superstate run by
elites indifferent to Islamisation and estranged from the interests of
the Dutch people. This rhetoric hit a new level in the 2012 election (in
the peak of the Eurozone crisis) (Van Kessel 2015, 106; Coffé and Van
Den Berg 2017, 878), when the party started advocating for a full exit
from the Union and a return to the guilder (the old currency) (Lucardie
and Voerman 2013, 193). As a consequence, we have coded the party 2 on
OTH_FOREIGN in 2006 and 2010, and 3 since 2012.

The dominance of Wilders' personality in the meaning of the party and
his control of its (barely existent) organisation (Vossen 2011, 180;
Pas, Vries, and Brug 2013; Coffé and Van Den Berg 2017, 8; De Lange and
Art 2011, 1240) warrants a 3 on CHARISMA, even if there is some debate
about whether he fits the brief of a typically charismatic populist
(Vossen 2010, 28--29). INSIDER is coded 2 since the PVV's time in
coalition government 2010-12 and 1 before. We see no evidence that the
party condoned threats to liberal democratic norms sufficient to
register on the LIBDEMNORMS scale (= 1).

**References**

Akkerman, Tjitske. 2005. 'Anti-Immigration Parties and the Defence of
Liberal Values: The Exceptional Case of the List Pim Fortuyn'. *Journal
of Political Ideologies* 10 (3): 337--54.

Coffé, Hilde, and Job Van Den Berg. 2017. 'Understanding Shifts in
Voting Behaviour Away from and towards Radical Right Populist Parties:
The Case of the PVV between 2007 and 2012'. *Comparative European
Politics* 15: 872--96.

De Lange, Sarah L., and David Art. 2011. 'Fortuyn versus Wilders: An
Agency-Based Approach to Radical Right Party Building'. *West European
Politics* 34 (6): 1229--49.

Koopmans, Ruud, and Jasper Muis. 2009. 'The Rise of Right-Wing Populist
Pim Fortuyn in the Netherlands: A Discursive Opportunity Approach'.
*European Journal of Political Research* 48 (5): 642--64.

Lucardie, Paul. 2008. 'The Netherlands: Populism versus Pillarization'.
In *Twenty-First Century Populism: The Spectre of Western European
Democracy*, edited by Daniele Albertazzi and Duncan McDonnell, 151--65.
London: Palgrave Macmillan UK. https://doi.org/10.1057/9780230592100_10.

Lucardie, Paul, and Gerrit Voerman. 2013. 'Geert Wilders and the Party
for Freedom in the Netherlands: A Political Entreneur in the Polder'. In
*Exposing the Demagogues: Right-Wing and National Populist Parties in
Europe*, edited by Karsten Grabow and Florian Hartleb, 187--203.
Brussels: Konrad Adenauer Stiftung.

Pas, Daphne van der, Catherine de Vries, and Wouter van der Brug. 2013.
'A Leader without a Party: Exploring the Relationship between Geert
Wilders' Leadership Performance in the Media and His Electoral Success'.
*Party Politics* 19 (3): 458--76.

Van Holsteyn, Joop JM, Galen A. Irwin, and Josje M. Den Ridder. 2003.
'In the Eye of the Beholder: The Perception of the List Pim Fortuyn and
the Parliamentary Elections of May 2002'. *Acta Politica* 38: 69--87.

Van Kessel, Stijn. 2015. *Populist Parties in Europe: Agents of
Discontent?* Springer.

Vossen, Koen. 2010. 'Populism in the Netherlands after Fortuyn: Rita
Verdonk and Geert Wilders Compared'. *Perspectives on European Politics
and Society* 11 (1): 22--38. https://doi.org/10.1080/15705850903553521.

---------. 2011. 'Classifying Wilders: The Ideological Development of
Geert Wilders and His Party for Freedom'. *Politics* 31 (3): 179--89.
