---
title: New Zealand
---


-   Date range: 1980-2020

-   Elections included:

    -   Legislative: 1981, 1984, 1987, 1990, 1993, 1996, 1999, 2002,
        2005, 2008, 2011, 2014, 2017, 2020.

## Social Credit

Social Credit (sometimes called "Socred") evolved from the Social Credit
Political League of the 1950s, and like its successful namesake Canada,
was based on the social credit economic philosophy developed by C. H.
Douglas. Social Credit went through many different phases as a party,
but achieved its best result of 20.65% in 1981 under the leadership of
Bruce Beetham. The party gradually declined after that, and by the 1987
election it had changed its name to the Democratic Party.

Gustafson (Gustafson 2006, 61) and Miller (Miller 1997, 168) both
suggest that under Beetham Social Credit Party was a fundamentally
populist party given its conspiratorial hostility to financial elites.
The party advocated financial reform and was built on a mainly rural and
religious voter base. Its policies were a complicated balance of
hostility to financial elites (OTH_FINANCIAL = 3) and a libertarian
distrust in state bureaucrats (Davis 1980, 3). While there is some
opposition to the political class in this, Beetham's stated conciliatory
strategy of working with opponents (Davis 1980, 4) makes him difficult
to and the party a somewhat awkward fit for OTH_POLCLASS. We've coded
Social Credit 2 on this variable, but more evidence of his campaigning
language would help to clarify this. Beetham was highly critical of the
IMF based global monetary system (Davis 1980, 3), but it would be a
stretch to say that this constitutes a register on the OTH_FOREIGN
variable (= 1). We've seen no evidence of anything for OTH_ETHNIC,
OTH_IMMIGRANT or OTH_MILITARY.

While it seems to have been personally dominated by Beetham, the party
had a well-established base of support and ideology before his
ascendance, and hence we've coded it 2 on CHARISMA in 1981 and 1984, and
1 in the 1987 election after it parted with Beetham. We've seen no
evidence to code above 1 for INSIDER or LIBDEMNORMS. The party is very
difficult to code ideologically, but given the primacy of its criticisms
of the economic system we've coded it CL.

## New Zealand Party

The New Zealand Party (NZP) was founded by a group of business leaders
before the 1984 election to advocate for neo-liberal policies at odds
with the conservative National Party government. It soon became a
personal vehicle for its leader, brash property mogul and former
National financier Bob Jones. The NZP tallied 12% in the 1984 vote,
where its main effect was allegedly to take votes away from National and
put the Labour opposition into government (Roy 1986). Before the
following election Jones claimed to be satisfied with the neo-liberal
economic policies of the Labour government and withdrew from the party,
precipitating its decline.

It is debatable whether Jones' campaign narrative quite reaches the
threshold for our minimum definition of populism, or whether his
antipathy to elites was a combination of his singular grudge with
incumbent Prime Minister Robert Muldoon and his neo-liberal ideological
opposition to state power. We have included him mainly on the work of
Gustafson, who suggests that Jones "detested state intervention and
control and the interference of bureaucratic regulators, politically
correct busybodies, traffic officers and journalists in his life"
(Gustafson 2006, 59). In that capacity he accused Muldoon of being a
"dictator" (Pugh 1984, 312). Given that this is less consistent than
more conspiratorial narratives against the political class, we've coded
NZP 2 on OTH_POLCLASS. We've seen no evidence for coding above 1 for
OTH_ETHNIC, OTH_IMMIGRATS, OTH_FOREIGN, OTH_FINANCIAL, or OTH MILITARY.

The NZP's image was built around Jones' "explosive personality" (Martin
1984, 394), such that soon after its launch it became known as the
"Jones Party" (Aimer 1988, 3) (CHARISMA =3). The party included some
left-libertarian positions, but it is broadly considered right wing due
to the primacy of its neo-liberal economic positions (Martin 1984, 394)
(LRPOSITION = R). Jones had not held any position in government before
his campaign, even though he and Muldoon were "old mates" (Simpson 1986,
266). Jones famously punched a journalist the year after the election
and was notably hostile to the media on the campaign trail, but we don't
think this quite rises to a violation of liberal democratic norms
(LIBDEMNORMS = 1).

## New Zealand First 

New Zealand First (NZF) was formed by outspoken former National Party MP
and minister Winston Peters in 1992 after he left his former party in
opposition to its economic policy. NZF won 8.4% in the election the
following year, which increased to its peak of 13.4% the following
election before hovering around the high-single digits for most of the
following two decades. Peters is known for his crass and abrasive style,
offering personal criticisms of journalists and fellow politicians. The
party has thrice played the part of kingmaker in minority governments
led by both major parties, leading Peters to serve as Deputy PM and
Treasurer 1996-98 (with the Nationals), and twice as Minister for
Foreign affairs 2005-08 and 2017-present (both times with Labour).

Given his longevity on the political scene in New Zealand, coupled with
his movement in and out of government (MacDonald 2022), the populist
discourses of NZF have fluctuated to the point that they are difficult
to pin down. In abstract terms, however, NZF's discourse has been a
combination of anti-elitism, anti-neoliberal and anti-globalisation
economic stances, cultural nativism, and opposition to immigration. The
most important feature that qualifies NZF for inclusion in the dataset
is Peters' relatively consistent anti-elitism (MacDonald 2022, 75). He
claims to represent the "relegated, denigrated and forgotten" people of
New Zealand against political, business, bureaucratic, and intellectual
elites (Gustafson 2006, 62--63; Denemark and Bowler 2002, 51), capturing
an "anti-party" sentiment unlike any other party in the country (Bale
and Roberts 2002, 12). The following example of Peters' rhetoric against
the incumbent national government in 2017 captures the conspiratorial
nature of this claim well:

> We have a government that works only for the elite few -- not for you!
> We have a government that always puts the short-term profits and greed
> of its cronies ahead of the interests of New Zealanders as a whole. We
> have a government that serves the globalization agenda of its mates in
> big corporates and international business (cited in MacDonald 2019,
> 235--36).

There is an argument that Peters' has occasionally toned down his
opposition to the political elite while serving in government (MacDonald
2022, 70), but for now we've coded him consistently 3 on OTH_POLCLASS.

There has been a consistent ethno-centrism to Peters' discourse. The
most complex and debated component of this relates to Maori issues.
While Peters and many NZF MPs are of Maori heritage, he has been
critical of what he calls the "grievance industry" (MacDonald 2019,
238), and he opposes affirmative action programs that favour indigenous
people (Moffitt 2017, 133). This appears not to take a categorical
"other" component within his populist language, but rather targets the
Maori elite whom he claims has profited at the expense of "regular"
Maori (Barker and Vowles 2020, 24). Peters and NZF have also framed
their opposition to immigration in ethnic and cultural terms (MacDonald
2019, 236), particularly regarding Asian migrants (Vowles 2020, 46). He
has claimed that New Zealand was witnessing a "Chinese invasion"
(Gustafson 2006, 64), that domestic enterprises could be taken over by
Chinese nationals (Callister 2011, 115), and he has been critical about
the social habits of Asian migrants (Gustafson 2006, 64). More recently
he has singled out Muslim migrants and asylum seekers, alleging that
there was a "militant underbelly" to Islam (Moffitt 2017, 133).
According to MacDonald, however, in recent years (especially since
becoming foreign minister in 2005) Peters' has engaged in more "dog
whistle" xenophobia than the clear-cut nativism of his earlier
statements, and has in more recent times distanced himself from more
overtly racist comments made by members of his party (MacDonald 2019,
227, 236). This could be further researched, but we've coded Peters 3 on
OTH_ETHNIC until 2005 and 2 afterward. We find that OTH_IMMIGRANT should
be coded at 3 consistently.

Peters' discourse has also targeted the business elite (Barker and
Vowles 2020, 21), whom he once accused of "hijacking" the government
(Miller 1997, 169). We have not seen quite enough evidence that this
reaches beyond 2 on OTH_FINANCIAL. He has also build a general antipathy
to foreign entities and interests that threaten the people of New
Zealand. In 1996, for example, Peters asked "whose country is it? A
country fit for the families of ordinary New Zealanders, whose votes
have placed the politicians in power, or a paradise for foreign
take-over merchants looking for cheap gains at our expense?" (cited in
Gustafson 2006, 63). Given he has not alleged that his domestic rivals
are wholly controlled by and loyal to these interests, we've kept
OTH_FOREIGN at 2.

NZF is somewhat difficult to define on the left-right scale (see Donovan
2020). Peters original reason for leaving National was his opposition to
privatisations and neo-liberal policies, and many scholars have placed
the party in the ideological centre (Bale and Roberts 2002, 3; Vowles
2020, 63). However the more salient features of his rhetoric appear to
be a kind of soft nationalism (Vowles 1997) and social conservativism
(MacDonald 2019, 235). We've therefore coded him CR on LRPOSITION, which
appears to be in line with most of the literature. The party has been
totally reliant on Peters' personality and "charismatic style" from its
inception (Denemark and Bowler 2002, 52; Miller 1997, 172; Levine and
Roberts 1994, 242; Joiner 2009), and he has maintained control of its
organisation (Mulgan and Aimer 2004, 253) (CHARISMA =3). Peters has had
a highly antagonistic relationship with the press throughout his career
(Rudd and Connew 2007, 53), but we do not see enough evidence to code
above 1 on LIBDEMNORMS (this is backed up by Barker and Vowles 2020,
22). As Peters held a cabinet position in National government before he
launched NZP, we have labelled the party 2 on INSIDER from its
inception.

## Not included

Former Labour Party president Jim Anderton founded the breakaway
**NewLabour** **Party** (NLP) in 1989 in reaction to the neo-liberal
turn in Labour (specifically the privatisation of assets). NLP drew many
members from the Labour Party, although Anderton was its only MP. After
the 1990 election, the NLP merged with several other parties (including
the Democratic Party, a.k.a. Social Credit) to form **The Alliance**
before the 1993 election, with Anderton as its leader. After initially
polling well, the fortunes of the party declined before the 1993
election when Winston Peters (with whom the Alliance had been in
discussions about recruiting) started NZF (Jesson 1997, 159). The
Alliance went on to form government with Labour after the 1999 election,
after which their electoral fortunes declined. Gustafson claims that
Anderton himself was "undeniably" a populist (Gustafson 2006), and the
Alliance played heavily on the promise that they would not break their
promises like the other parties did, even pledging to resign if they
did, giving them a "revivalist" and anti-politics appeal in the
electorate (Jesson 1997, 162). However we have not seen enough evidence
that this quite reaches the threshold of anti-elite hostility necessary
to meet our minimum definition, and the party appears to be more of a
policy driven soft-protest party rather than a truly populist one. There
is a case to be made that **Robert Muldoon** (National Party PM 1975-84)
was a populist (see Gustafson 2006), and some have considered Peters to
be the natural successor of Muldoon's in this regard (Joiner 2009). This
could be investigated further, but for now we don't quite see the
evidence for this as it relates to our minimum definition. 

**References**

Aimer, Peter. 1988. 'The Rise of Neo-Liberalism and Right Wing Protest
Parties in Scandinavia and New Zealand: The Progress Parties and the New
Zealand Party'. *Political Science* 40 (2): 1--15.

Bale, Tim, and Nigel S. Roberts. 2002. 'Plus Ça Change ... ? Anti-Party
Sentiment and Electoral System Change: A New Zealand Case Study'.
*Commonwealth & Comparative Politics* 40 (2): 1--20.
https://doi.org/10.1080/713999587.

Barker, Fiona, and Jack Vowles. 2020. 'Populism and Electoral Politics
in New Zealand'. In *A Populist Exception?: The 2017 New Zealand General
Election*, edited by Jack Vowles and Jennifer Curtin, 9--34. Acton: ANU
Press.

Callister, Paul. 2011. 'The Construction of Ethnicity and "belonging" in
New Zealand: Where We Have Come from and Where We Might Be Going'.
*Journal of New Zealand Studies*, January.
https://search.informit.org/doi/abs/10.3316/informit.315948902859049.

Davis, Dianne R. 1980. 'The "Operational Code" of Bruce Craig Beetham'.
*Political Science* 32 (1): 1--17.
https://doi.org/10.1177/003231878003200101.

Denemark, David, and Shaun Bowler. 2002. 'Minor Parties and Protest
Votes in Australia and New Zealand: Locating Populist Politics'.
*Electoral Studies - ELECT STUD* 21 (March): 47--67.
https://doi.org/10.1016/S0261-3794(00)00034-2.

Donovan, Todd. 2020. 'Misclassifying Parties as Radical Right/Right Wing
Populist: A Comparative Analysis of New Zealand First'. *Political
Science* 72 (1): 58--76.

Gustafson, Barry. 2006. 'Populist Roots of Political Leadership in New
Zealand'. In *Political Leadership in New Zealand*, edited by Raymond
Miller and Michael Mintrom, 51--69. Auckland, N.Z: Auckland University
Press.

Jesson, Bruce. 1997. 'The Alliance'. In *New Zealand Politics in
Transition: Raymond Miller*, edited by Raymond Miller, 156--64.
Auckland: Oxford University Press.
https://www.amazon.com/Zealand-Politics-Transition-Raymond-Miller/dp/0195583396.

Joiner, Margaret. 2009. 'New Zealand First: Parallels between the Man
and the Party'. In *New Zealand Political Studies Association
Conference*. Vol. 30.

Levine, Stephen, and Nigel S. Roberts. 1994. 'The New Zealand Electoral
Referendum and General Election of 1993'. *Electoral Studies* 13 (3):
240--53.

MacDonald, David B. 2019. 'Between Populism and Pluralism: Winston
Peters and the International Relations of New Zealand First'. In
*Populism and World Politics: Exploring Inter- and Transnational
Dimensions*, edited by Frank A. Stengel, David B. MacDonald, and Dirk
Nabers, 227--49. Global Political Sociology. Cham: Springer
International Publishing. https://doi.org/10.1007/978-3-030-04621-7_9.

---------. 2022. '"An Antipodean Populism? Winston Peters, New Zealand
First, and the Problems of Misclassification"'. In *The Palgrave
Handbook of Populism*, edited by Michael Oswald, 69--83. Cham: Springer
International Publishing. https://doi.org/10.1007/978-3-030-80803-7_4.

Martin, Ged. 1984. 'From Muldoon to Lange: New Zealand Votes in 1984'.
*The Round Table* 73 (292): 392--402.

Miller, Raymond. 1992. 'The Minor Parties'. In *New Zealand Politics in
Perspective*, edited by Hyam Gold, 3rd ed., 310--25. Auckland: Longman
Paul.

---------. 1997. 'The New Zealand First Party'. In *New Zealand Politics
in Transition*, 165--76. Oxford University Press.

Moffitt, Benjamin. 2017. 'Populism in Australia and New Zealand'. In
*The Oxford Handbook of Populism*, edited by Paulina Ochoa Espejo,
Pierre Ostiguy, Paul Taggart, and Cristóbal Rovira Kaltwasser, 121--39.
Oxford University Press.

Mulgan, Richard, and Peter Aimer. 2004. *Politics in New Zealand*.
Auckland, UNITED STATES: Auckland University Press.
http://ebookcentral.proquest.com/lib/rmit/detail.action?docID=1563891.

Pugh, Michael. 1984. 'New Zealand: The Battle for the Middle Ground'.
*The World Today* 40 (7): 308--14.

Roy, Theo. 1986. 'What Happened in New Zealand'. *Quadrant* 30 (5):
33--36.

Rudd, Chris, and Scott Connew. 2007. 'Minor Parties and Media Coverage
during the 2005 New Zealand Election'. *Political Science* 59 (2):
51--62.

Simpson, Alan. 1986. 'A New Generation Takes Over in New Zealand'. *The
Round Table* 75 (299): 263--68.

Vowles, Jack. 1997. 'The New Zealand General Election of 1996'.
*Electoral Studies* 16 (2): 258--62.

---------. 2020. 'Populism and the 2017 Election - The Background'. In
*A Populist Exception?: The 2017 New Zealand General Election*, edited
by Jack Vowles and Jennifer Curtin, 35--70. Acton: ANU Press.

