---
title: Pakistan
---


## Muhajir Qaumi Movement/ Muttahida Qaumi Movement

The Muhajir Qaumi Movement (MQM), which in 1997 changed its name to the
Muttahida Quami Movement, represents the "Muhajirs" ("migrants" or
"refugees") in Pakistan -- Urdu-speaking Muslim immigrants who moved to
Pakistan (primarily to the Sindh province and Karachi in particular)
from various "Muslim minority" parts of India after partition. With
roots in the Muhajir student organisation from the 1970s, the party
emerged as a political force out of the 1985-86 ethnic riots in Karachi
under the charismatic leadership of Altaf Hussain, appealing primarily
to second generation Muhajirs, more open to ethno-nationalism than their
parents (Malik 1995, 51). Initially supported and armed by military
ruler Zia ul-Huq in the 1980s as a spoiler to the Pakistan People's
Party (PPP) in Sindhi (M. A. Shah 1998, 508), the MQM subsequently
formed alliances with both major parties over its three decades. After
it embraced violence against state and military officials in the early
1990s, "Operation Clean-up" targeted its leadership forcing Hussain into
exile in London from which he has never returned. The party has had
several offshoots against Hussain's leadership, including the
unsuccessful MQM-Haqiqi faction and more recently the so-called
MQM-Pakistan, however the only MQM parties to poll over 5% in national
elections are those that Hussain has led. After a heavily-criticised
speech in 2016 in which he called Pakistan a "cancer for the whole
world", Hussain's effectively lost control of the party and its fortunes
plummeted in the subsequent 2018 elections.

The MQM claims that Muhajir's have been the victims of systematic
oppression and disloyalty by successive Pakistani governments since
independence. In Altaf Hussain's words: "What has been done in twenty
years by the government? \[...\] The faces change, but the policies
remain the same" (Baloch 2012, 6). And in another speech: "We are left
with half-achieved independence. Muslims got the country, but we are
still slaves. Before it was the foreigners, the colonialists and today
we are slaves to our own people" (Baloch 2012, 7). The MQM claimed that
it had diverged from traditional "drawing room politics" of the other
major parties by truly representing the excluded poor (Waseem 1996,
625). It also claims that a feudal "privileged class" runs Pakistan, and
that the party sought to "end the rule of the 2%, and create the rule of
the 98% (Richards 1994, 307--8; see also Schied 2001, 34). The policy
background was the establishment of the quota system that sought to make
appointments to the civil service (in which Muhajir's had been highly
overrepresented) more equally distributed. While Muhajirs were
overrepresented in the state bureaucracy in the early decades after
independence, various quota systems have made it more difficult for them
to get jobs in the federal and provincial bureaucracy (Haq 1995, 992).
The MQM has repeatedly claimed that this system was a deliberate
strategy to marginalise Muhajirs, especially young and relatively poor.
It also claimed that the decision not move the capital from Karachi to
Islamabad in 1958 was a done deliberately to marginalise Muhajirs (Haq
1995, 991). For this reason we have coded OTH_POLCLASS at 3 for each
election.

MQM discourse emphasised (and arguably created) the concept of Muhajir
as an ethnic identity, and positioned itself as the exclusive defender
of that communities interests (Naqvi 2020; Shahzad 2013; M. A. Shah
1998, 510). At its peak this included demands for a separate province to
be carved out of Sindh as a formal homeland necessary "for their
\[Muhajir's\] very survival" (Schied 2001, 36). In championing the
Muhajir cause the MQM's rhetoric frequently asserted that other ethnic
groups were essentially antagonistic to Muhajir interests. This targeted
Pakistan's biggest ethnic bloc, Punjabis, (K. M. Shah and Sareen 2019,
7; Schied 2001, 32) and especially the Sindhis and Pashtuns in and
around Karachi and Hyderabad, all of whom were frequent "others" to the
Muhajir identity as portrayed in MQM discourse. By the late 1990s the
party attempted to moderate its ethnocentric image, including changing
the meaning of "MQM" to *Mutahida* Qaumi Movement (United National
Movement) (Haq 1995, 1001). By some accounts this was part of a
significant strategy to shift from an ethnocentric party limited to
Urban Sindh to a broader middle class movement. However the available
evidence suggests that this was not a substantial shift, as the party's
demands, rhetoric and leadership remained essentially unchanged (Schied
2001, 39), and it was ultimately "unable to transition to non-ethnic
politics" (K. M. Shah and Sareen 2019, 14) (OTH_ETHNIC = 3).

One of Hussain and the MQM's key political targets has been the
Pakistani military, which it has accused the military of genocide
against Muhajirs (Haq 1995, 1001). Hussain has also associated the
higher ranks of the armed forces with the core of the corrupt political
system: "we must not forget the Generals. Lest we forget, they remain
the real oppressors today" (Baloch 2012, 7). In contrast to the
sacrifice of the Muhajir migration, he portrays the military elite of
being "wealthy but devoid of moral fibre and patriotism" (Waseem 1996,
628; see also Schied 2001, 36). Hostility to the military became
especially strong after the army's terror violent Operation Clean-up in
1992 (Ahmar 1996, 1035). According to Baloch, it was only after this
that Hussain started to directly criticise the military. For this
reason, we've coded OTH_MILITARY 1 for the 1988 election and 3 from
1993. Despite claiming to represent the poor, the MQM was "policy
neutral" on key economic matters (Waseem 1996, 626), perhaps in part due
to the fact that may Muhajirs were well established in the business
community (OTH_FINANCIAL = 1). We've seen no evidence that OTH_FOREIGN
sentiment features in the party's discourse (= 1).

Ironically, even though the MQM's mission is to represents migrants from
outside of Pakistan, and has consistently advocated for the increased
immigration of Muslim's from other parts of India and Bangladesh
("stranded Pakistanis") (Shahzad 2013, 133), it has often engaged in
nativist anti-immigrant politics targeting immigrants from other places
(Waseem 1996, 626). This has focussed especially Pashtuns from
Afghanistan and non-Muhajir Pakistanis into urban Karachi and Hyderabad
(Schied 2001, 40). It's early charters demanded that only citizens (or
"real Sindhis") be able to vote, own businesses and buy property
(Shahzad 2013, 133), and that Afghan refugees be deported ack to
Afghanistan (Haq 1995, 998). Later on, it claimed that the influx of
Pashtuns into Karachi signified the Taliban's "taking over" the city (K.
M. Shah and Sareen 2019, 14) (OTH_IMMIGRANTS = 3). The MQM is very
difficult to pin down on a left-right ideological spectrum. It is at
once "ideologically agnostic" (Waseem 1996, 626), a self-proclaimed
champion of the poor, yet a "fascist leaning" (Newberg 1994) party of
violent ethno-nationalism. Given that the latter of these best describes
the party's core discourse and activities, we've coded it FR on
LRPOSITION, but this could be further scrutinised.

Altaf Hussain gained complete control over the organisation from 1987,
and became known as *quaid* ("the leader") and *Pir Sahib* ("spiritual
guide") (Haq 1995, 997). The MQM created a "cult of personality" around
him, promoting an explicit doctrine of "blind faith" in its leader
(Waseem 1996, 625; Naqvi 2020, 81; see also Malik 1995; Schied 2001, 43;
Gayer 2003, 21; Baloch 2012). Most scholars consider the MQM agenda to
have been solely set by him (Ahmar 1996, 1043; N. Khan 2010, 108), and
even after fleeing to London he still addressed party meetings by phone
(Haq 1995, 1002). This is sufficient to code the party 3 on CHARISMA.

Since its emergence from the riots of the 1980s, the MQM has been a
fundamentally violent movement (Ahmar 1996, 1037; Shahzad 2013; N. Khan
2010; Abid 2017; M. A. Shah 1998, 511). MQM rallies have explicitly
advocated violence, and even been used to distribute weapons (N. Khan
2010, 68). It has also violently harassed and intimidated critical
journalists, (Haq 1995, 1002--3; Waseem 1996, 627; Ahmar 1996, 1034;
Malik 1995, 66; Shahzad 2013, 145), extorted Karachi businesses into
donating to the movement (Haq 1995, 1002--3), and violently clamped down
on internal dissent against Hussain's leadership and non-MQM Muhajirs
who were seen as a threat for not supporting the party (K. M. Shah and
Sareen 2019, 9). Party workers have abducted and tortured military
officers (Waseem 1996, 627), While these activities probably peaked
during the violent periods of the late 1980s and 1990s, the party's use
of violence continued through the 2000s (Siddiqui 2022, 2), although
Khan (N. Khan 2010, 75) claims that it has went somewhat "underground".
For these reasons we have consistently coded the party 3 on LIBDEMNORMS.
Given that the party was a part of a power sharing agreement with the PP
after its first election in 1988, we have coded it 1 on INSIDER for that
election, and 2 for subsequent elections.

Note that in 1988, MQM candidates officially participated as
independents, and in 1990-97 they were officially called the "Haq Parast
Group" (HPG) (*Dawn* 2018). Despite this, the secondary literature
universally refers to both election groups as MQM, and there should be
no doubt that this is the same party.

## Pakistan Tehreek-e-Insaf 

Pakistan Tehreek-e-Insaf (PTI) was formed in 1996, by cricketer Imran
Khan. As one of the country's most identifiable sports personalities
during the 1980s and 1990s, Khan entered the political realm via his
philanthropic endeavors. While the party did not gain any momentum in
its first decade, during the military regime of Perves Musharraf
(1999-2008) Khan became a feature on political talk shows, often
criticising Musharraf's pro-US actions during the War on Terror, and
maligning the political class for its corruption (Yılmaz and Shakil
2021, 7). After boycotting the 2008 election (in protest of Musharraf's
decision not to stand down), PTI first emerged electorally in 2013,
winning 17% of the vote mainly from middle and upper classes mobilised
through newly available electronic media avenues. By emerging as the
favoured candidate of the military, and benefitting from high profile
corruption scandals in 2016-17, Khan and the PTI took almost 32% of the
vote in the 2018 election and formed government.

The core political theme of the PTI is Khan's "aggressive
anti-corruption crusade" (Faiz 2022b, 55; see also A. Shah 2019, 129;
Javid and Mufti 2022, 77; Mulla 2017, 4185; Javid 2019, 11; Rastogi
2021, 3). He developed an "anti-politics" discourse (Evans 2012, 221)
which describes the elite as a "corrupt mafia ruling over Pakistan"
(Faiz 2022b, 59; Shakil and Yilmaz 2021, 6), and (in the party's
manifestos) as "inept, corrupt and selfish politicians, feudals, civil
and military bureaucrats with vested interests" who have "plundered" the
nation (T. M. Khan 2020, 66; see also Sheikh 2018, 110). Repatriating
money stolen from the national coffers, Khan suggested, would finance
the "new (*naya*) Pakistan", prosperous and free of corruption (Shakil
and Yilmaz 2021, 8). An essential element of this narrative is that the
two major parties (the Pakistani People's Party/PPP and the Pakistan
Muslim League-Nawaz/PML-N) were equally culpable in creating and
benefitting from this corrupt order. He has accused PPP and PML-N of
engaging in a *muq muqa*, ("nefarious deal" in Punjabi slang), in which
they acted as each other's faux opposition, taking turns in government
and partaking in the same forms of corruption (T. M. Khan 2020, 60; Faiz
2022b, 56). The Panama Papers leaks in 2016, which revealed the offshore
holdings of Prime Minister Nawaz Sharif's family, gave this campaign a
significant boost before the 2018 election (Faiz 2022b, 59). Several
scholars (T. M. Khan 2020; Javid and Mufti 2022, 78) have noted that
that the party shifted away from its mass-party organisational approach
between 2013 and 2018 elections in order to build coalitions with other
"electables" (politicians whose wealth, connections, and land ownership
enabled them to win local contests) and therefore form government.
However, there is no indication that this altered the party's or Khan's
discourse in the latter election. Therefore, we have coded OTH_POLCLASS
as 3 for the duration.

The military relationship with PTI is somewhat complicated. In his early
years of political engagement Khan was often critical of the military's
actions, especially during the Musharraf regime. This included "severe
criticism" Musharraf's (military) regime and strong opposition to the
military's cooperation with the US War on Terror, positions which "did
not endear him to the military establishment" (T. M. Khan 2020, 64). But
in a deeper sense the PTI was always connected to the military
establishment (Faiz 2022b, 55), with which he shared a common
interpretation of Pakistan's problems (T. M. Khan 2020, 64). Early
manifestos of the PTI were noticeably silent on the subject of the
military's intervention in politics (Sheikh 2018, 110). Shah (A. Shah
2019, 130) claims that "Khan always omits Pakistan's decidedly
unaccountable military from his boasts about holding politicians
accountable," and it is commonplace among scholars to assert that the
military establishment had a hand in ensuring that the PTI won the 2018
elections instead of the PPP or PML-N (A. Shah 2019, 129; Faiz 2022b;
Javid and Mufti 2022). In government, Khan espoused a narrative of
"unprecedented civil-military harmony" (Faiz 2022b, 62). For this
reason, we've coded the PTI as 1 on OTH_MILITARY.

Opposition to foreign interference in Pakistan has been a strong theme
in Khan and the PTI's discourse, particularly regarding the United
States (Evans 2012, 221; A. Shah 2019, 131; Mulla 2017, 4187; Yılmaz and
Shakil 2021, 8). The American use of drones in the War on Terror, many
instances of which occurred in northwest Pakistan and included high
civilian casualties, drew fierce criticism from Khan. According to
Shakil and Yilmaz, this reached a proportion in which " 'the West' and
its supporters were deemed the antagonistic and conspiring other"
(Shakil and Yilmaz 2021, 7). India has also featured as a foreign power
behind the status quo in Khan's rhetoric (Faiz 2022b, 60; Shakil and
Yilmaz 2021, 9). According to Yilmaz and Shakil (Yılmaz and Shakil 2021,
11) he has openly accused his critics of being "agents of 'India's
fascist government'", and accused the national elite of making Pakistan
a "puppet state" and a "slave" to the west and its financial
institutions (particularly the IMF) (Shakil and Yilmaz 2021, 8). There
may be some debate about whether this *consistently* reaches the highest
level on the OTH_FOREIGN scale, but on the balance of evidence we've
coded the party 3. The literature does not present any evidence that PTI
or Khan engaged in an ethnocentric politics (OTH_ETHNIC = 1). Likewise,
there is no evidence of any discourse against financial elites
(OTH_FINANCIAL = 1) or immigrants (OTH_IMMIGRANTS = 1).

Almost all articles on the PTI's rise emphasis how Khan's charisma was
essential to its meaning in the eyes of voters (see Javid and Mufti
2022, 68; Mulla 2017, 4184; Shakil and Yilmaz 2021, 11). This was
especially true for its early elections when the PTI was totally
synonymous with Khan (T. M. Khan 2020, 63; Yilmaz and Shakil 2021, 5).
The party's use of social media was one of the factors that allowed
Khan's personality to connect directly with voters in an unmediated way
(Javid and Mufti 2022, 81; Mulla 2017; Faiz 2022b, 58). The literature
does not suggest that there Khan and the PTI consistently espoused any
consistent economic ideology with political salience, but was rather an
"amalgamation of piecemeal ideologies" (Yılmaz and Shakil 2021, 10; see
also Khalid 2020). The reason why Khan and the PTI are usually
considered "right wing" (Faiz 2022b, 55; A. Shah 2019, 128) or
"centre-right" (Sheikh 2018, 109) has to do more with its embrace of
cultural conservatism and nationalism. Khan is has consistently
portrayed himself as a religious conservative, and a major part of his
public identity before starting PTI in 1996 was a shift away from his
former playboy lifestyle and an embrace of a devout form of Islam after
the death of his mother (Shakil and Yilmaz 2021, 6; A. Shah 2019, 131;
Faiz 2022b, 57). He has often vilified liberal and progressive
intellectuals for seeing Pakistan through a "westernised lens" (Yılmaz
and Shakil 2021, 9; see also Faiz 2022b, 57; Shakil and Yilmaz 2021, 9).
For this reason we've coded PTI as R on LRPOSITION.

Khan was notable among major politicians for expressing solidarity with
the Taliban, whom he labelled "freedom fighters" (T. M. Khan 2020, 64).
The Tehrik Taliban Pakistan even nominated Khan to be their
representative in negotiations with the government 2014, which he
declined (Faiz 2022b, 57). Evidence suggests that media freedoms were
curtailed during the PTI's time in government (Hussain, Abbas, and
Sheikh 2022; Mulla 2017), and Faiz contends that, Khan abused
anti-corruption authorities to target opposition politicians (Faiz
2022b, 56). After losing the 2013 election, Khan discredited electoral
institutions, claiming that a number of state bodies (including the
judiciary) had rigged him of victory (Faiz 2022b, 58; A. Shah 2019, 131;
Javid and Mufti 2022, 80; Cheema, Chacko, and Gul 2019, 32). These are
all violations of liberal democratic standards, but given the context of
Pakistani politics we find that this doesn't quite reach the threshold
of 3 on LIBDEMNORMS (= 2). As Khan had not served in government prior to
2018 PTI is coded 1 on INSIDER.

**Not included**

**Pakistan People's Party**

The Pakistan People's Party (PPP) is often considered a populist party
in its early years under the leadership of Zulifkar Ali Bhutto (Jones
2020; Shafqat 2020, 25; Ayoob 1985, 157; Nasr 1996, 259). This includes
its first period in government in the mid-1970s. Bhutto, a charismatic
student leader and cabinet minister in the 1960s, led a mass movement to
overthrow the military rule of Gen Ayub Khan in 1969, going on to
institute a relatively reformist period in power before being overthrown
by the military in 1977 and executed in 1979. The PPP has formed
government several times since 1980, including two prime ministerial
stints under Bhutto's daughter and successor Benazir Bhutto (1988-90,
1993-96), and another between 2008 and 2013 under Yousaf Gillani and
Raja Ashraf. Benazir's husband Asif Ali Zadari also served as president
between 2008 and 2013, following the former's assassination in 2007.

There is a strong case that the rhetoric of the elder Bhutto's campaigns
in the 1970s constitute populist discourse by our definitions. However
the available evidence suggest that following this period the PPP became
a more mundane and patronage-based party (Jones 2020; Faiz 2022a).
Benazir Bhutto's 1980s and 1990s campaigns saw her "court" military
leadership rather than antagonising it (Newberg 1994, 168), and the
extent of populist sentiment appears to be the evocation of the legacy
of her father (Syed 1991), and reformist policy proscriptions were
significantly softened (Rais 1989, 205). More recently the PPP has acted
as a mainstream party, even when in opposition. In Faiz's
interpretation, the it "largely operates as a conventional opposition
party whose resistance to government does not include an anti-system
narrative" (Faiz 2022a, 1).

**References**

Abid, Muhammad. 2017. "Muttahida Qaumi Movement: Mode of Politics and
Political Attitudes." *Pakistan Perspectives* 22 (2).

Ahmar, Moonis. 1996. "Ethnicity and State Power in Pakistan: The Karachi
Crisis." *Asian Survey* 36 (10): 1031--48.

Ayoob, Mohammed. 1985. "Dateline Pakistan: A Passage to Anarchy?"
*Foreign Policy*, no. 59: 154--73.

Baloch, Bilal. 2012. "The Role of Leadership and Rhetoric in Identity
Politics: Muttahida Qaumi Movement (MQM), a Case Study." *Al Nakhlah*,
1--13.

Cheema, Azeema, Johann Chacko, and Shirin Gul. 2019. "Mobilising Mass
Anxieties: Fake News and the Amplification of Socio-Political Conflict
in Pakistan." *Fake News* 17.

*Dawn*. 2018. "Muttahida Qaumi Movement - Pakistan," July 18, 2018.
https://www.dawn.com/news/1404613.

Evans, Alexander. 2012. "Continuity and Change in Pakistani Politics1."
*Contemporary South Asia* 20 (2): 213--24.

Faiz, Asma. 2022a. "The Peculiar Case of the Pakistan Peoples Party as
an Opposition Party."

---------. 2022b. "We Are on the Same Page: The Curious Case of Imran
Khan's Populism in Pakistan." In *Contemporary Populists in Power*,
edited by Alain Dieckhoff, Christophe Jaffrelot, and Elise Massicard,
55--74. Cham: Palgrave Macmillan.

Gayer, Laurent. 2003. "A Divided City:'Ethnic'and 'Religious' Conflicts
in Karachi." *Pakistan (Www. Ceri-Sciences-Po. Org*.

Haq, Farhat. 1995. "Rise of the MQM in Pakistan: Politics of Ethnic
Mobilization." *Asian Survey* 35 (11): 990--1004.

Hussain, Shabir, Qamar Abbas, and Mohammad Anas Sheikh. 2022. "Media
Freedom in a Populist Regime: Evidence From Pakistan." *International
Journal of Communication* 16: 20.

Javid, Hassan. 2019. "Patronage, Populism, and Protest: Student Politics
in Pakistani Punjab." *South Asia Multidisciplinary Academic Journal*,
no. 22.

Javid, Hassan, and Mariam Mufti. 2022. "Electoral Manipulation or Astute
Electoral Strategy? Explaining the Results of Pakistan's 2018 Election."
*Asian Affairs: An American Review* 49 (2): 65--87.

Jones, Philip E. 2020. "Pakistan People's Party: From Populism to
Patronage." In *Pakistan's Political Parties: Surviving Between
Dictatorship and Democracy*, edited by Mariam Mufti, Sahar Shafqat, and
Niloufer Siddiqui, 41--59. Washington, UNITED STATES: Georgetown
University Press.
http://ebookcentral.proquest.com/lib/rmit/detail.action?docID=6177091.

Khalid, Muhammad Umair. 2020. "Valence Populism in Pakistan: Making
Sense of Imran Khan's Ideological Cluelessness." Central European
University.

Khan, Nichola. 2010. *Mohajir Militancy in Pakistan: Violence and
Transformation in the Karachi Conflict*. Routledge.

Khan, Tabinda M. 2020. "Pakistan Tehreek-e-Insaf: From a Movement to a
Catch-All Party." In *Pakistan's Political Parties: Surviving Between
Dictatorship and Democracy*, edited by Mariam Mufti, Sahar Shafqat, and
Niloufer Siddiqui. Washington, UNITED STATES: Georgetown University
Press.
http://ebookcentral.proquest.com/lib/rmit/detail.action?docID=6177091.

Malik, Iftikhar H. 1995. "Ethno-Nationalism in Pakistan: A Commentary on
Muhajir Qaumi Mahaz (MQM) in Sindh." *South Asia: Journal of South Asian
Studies* 18 (2): 49--72.

Mulla, Ayesha. 2017. "Mediatized Populisms\| Broadcasting the Dharna:
Mediating\" Contained\" Populism in Contemporary Pakistan."
*International Journal of Communication* 11: 16.

Naqvi, Tahir. 2020. "What Remains of the Muttahida Qaumi Movement."
*Pakistan's Political Parties: Surviving between Dictatorship and
Democracy*, 76.

Nasr, Seyyed Vali Reza. 1996. "Pakistan: State, Agrarian Reform and
Islamization." *International Journal of Politics, Culture, and
Society*, 249--72.

Newberg, Paula. 1994. "Dateline Pakistan: Bhutto's Back." *Foreign
Policy*, no. 95: 161--74.

Rais, Rasul B. 1989. "Pakistan in 1988: From Command to Conciliation
Politics." *Asian Survey* 29 (2): 199--206.

Rastogi, Prashant. 2021. "The Articulation of Discourse in Populism:
Understanding 21st Century Pakistan." *E-International Relations.
Available Online: Https://Www. e-Ir.
Info/2021/01/05/the-Articulation-of-Discourse-in-Populism-Understanding-the-Case-Ofpakistan-in-the-21st-Century/(Accessed
on 5 January 2021)*.

Richards, Julian James. 1994. "Mohajir Subnationalism and the Mohajir
Qaumi Movement in Sindh Province, Pakistan." PhD Thesis, University of
Cambridge.

Schied, Michael. 2001. "The Muttahida Qaumi Movement and the Pakistani
State." *Internationales Asienforum* 32 (1--2): 27--45.

Shafqat, Saeed. 2020. "The Formation, Development, and Decay of the
Pakistan Muslim League-Nawaz." In *Pakistan's Political Parties:
Surviving Between Dictatorship and Democracy*, edited by Mariam Mufti,
Sahar Shafqat, and Niloufer Siddiqui. Washington, UNITED STATES:
Georgetown University Press.
http://ebookcentral.proquest.com/lib/rmit/detail.action?docID=6177091.

Shah, Aqil. 2019. "Pakistan: Voting under Military Tutelage." *Journal
of Democracy* 30 (1): 128--42.

Shah, Kriti M., and Sushant Sareen. 2019. "The Mohajir: Identity and
Politics in Multiethnic Pakistan." Observer Foundation Research.
http://www. orfon line. org/wp-conte nt/uploa ....

Shah, Mehtab Ali. 1998. "The Emergence of the Muhajir Quami Movement
(MQM) in Pakistan and Its Implications for Regional Security." *The
Round Table* 87 (348): 505--19.

Shahzad, Aisha. 2013. "Ethnic Politics of MQM from 1980s till Election
2002." *Pakistan Perspectives* 18 (1): 127--63.

Shakil, Kainat, and Ihsan Yilmaz. 2021. "Religion and Populism in the
Global South: Islamist Civilisationism of Pakistan's Imran Khan."
*Religions* 12 (9): 777.

Sheikh, Shiraz. 2018. "The Promise of 'Naya Pakistan'and the Rise of
Pakistan Tehreek-e-Insaf." *Indian Journal of Politics and International
Relations (Kottayam) Vol* 11: 108--47.

Siddiqui, Niloufer. 2022. "Political Parties and Violence in Karachi,
Pakistan." *Comparative Political Studies*, 00104140221115174.

Syed, Anwar H. 1991. "The Pakistan People's Party and the Punjab:
National Assembly Elections, 1988 and 1990." *Asian Survey* 31 (7):
581--97.

Waseem, Mohammad. 1996. "Ethnic Conflict in Pakistan: The Case of MQM."
*The Pakistan Development Review*, 617--29.

Yilmaz, Ihsan, and Kainat Shakil. 2021. "Pakistan Tehreek-e-Insaf:
Pakistan's Iconic Populist Movement." *ECPS. Available Online:
Https://Www. Populismstudies.
Org/Pakistan-Tehreek-e-Insaf-Pakistans-Iconic-Populist-Movement/(Accessed
on 7 May 2021)*.

Yılmaz, Ihsan, and Kainat Shakil. 2021. "Imran Khan: From Cricket
Batsman to Populist Captain Tabdeli of Pakistan."

