---
title: Poland
subtitle: 'Date range: 1989-2020'
title-block-banner: yes

---

# Case notes

## Stanisław Tymiñski / Party X

Stanisław Tymiński, a Polish-Canadian businessman, ran an unlikely
presidential campaign in 1990 with his newly founded "Party X". Although
he started with very little name recognition, he surprised all observers
by coming second in the first ballot (23.1%), although he only increased
this to 25.75% in the second where he was roundly defeated by
Solidarity's Lech Wełeşa. Party X did not do well in following year's
legislative elections (0.5%), and Tymiński did not play an important
role in Polish politics afterward.

Tymiński's campaign consisted of a personality centric diatribe against
the political class -- including both the post-communist and Solidarity
factions -- calling himself a "third force" that was neither left nor
right wing (De Lange and Guerra 2009, 535; Stanley and Cześnik 2019, 70;
Jasiewicz 2008, 22; Kucharczyk and Wysocka 2008, 80) (OTH_POLCLASS = 3).
For this his 1990 campaign is universally considered "populist"
(Pankowski 2010, 66; Surazska and Bivand 1997, 76; Millard 1994, 54; Van
Kessel 2015a, 124). While his policy proposals were light, his
"entrepreneurial populism" (Kasprowicz and Hess 2017, 204) was built on
the idea that as a successful business man he could create wealth for
the people (Sanford 2002, 178; Schöpflin 1991, 239), generally catering
to those who felt that they had lost out in the transition to a market
system under Solidarity (Surazska and Bivand 1997, 76; Bell 1997, 1268;
Sanford 2002, 178). This makes him difficult to code on LRPOSITION, but
we have coded him C.

Not a lot is written about his platform, but Rok claims that Tymiński
was anti-semitic (Rok 1992), and other sources claim that party
supporters exhibited high levels of xenophobia (Jasiewicz 2008, 22).
While there is not a lot of evidence to corroborate this, we have coded
him 2 on OTH_ETHNIC. We have seen no evidence for anything registering
on the OTH_IMMIGRANT and OTH_FOREIGN variables (= 1). As a "self-made"
millionaire, he did not present any hostility to the rich (Schöpflin
1991, 248) (OTH_ECONOMIC = 1). The party was based totally on Tymiński's
persuasive (Jasiewicz 2008, 22) and "eccentric" (Bell 1997, 1270)
persona (Schöpflin 1991, 239) (CHARISMA = 3). Tyminski had no
affiliation with the political class, and no established party
organisation (Bell, 1997:1267) (INSIDER = 1). We have seen no evidence
that he violated LIBDEMNORMS (= 1).

## League of Polish Families 

The League of Polish Families (*Liga Polskich Rodzin*, LPR), founded in
2001, was a clerical social conservative party that was puritanically
anti-EU and opposed to foreign influences in "traditional" Polish
(Catholic) culture. The party was the product of conservative Father and
media figure Tadeusz Rydzyk, who cobbled together various right wing and
Catholic parties in existence at the time (Rafal Pankowski 2010:111).
After two strong performances in 2001 and 2005 (7.9% and 8%
respectively), the party joined a coalition government with Civic
Platform and Order and Justice, after which it was seen by supporters to
compromise too much on its program and receded by the early 2007
elections. Most of its voters turned to PiS (Zuba 2017, 91).

Anti-establishment rhetoric was an important pillar of LPR's discourse
(De Lange and Guerra 2009, 539; Zuba 2017, 100), as it frequently
accused the political class of conspiring with foreigners to subvert
Polish values and interests. Several scholars point out that the party's
anti-establishment rhetoric was not as extreme as other populists at the
time (notably Self Defence) (Markowski and Tucker 2010, 526), but from
the available evidence this should still be coded as 3 in the
OTH_POLCLASS variable. The party had a generally ethnocentric outlook on
the nation (Jasiewicz 2008, 15; Moroska and Zuba 2010, 131), and
according to de Lange & Guerra, (De Lange and Guerra 2009, 538) it
"vehemently opposes" non-Catholic "others", and "openly attacks the
roles that Jews" have in society. Members of affiliated youth movements
(see below) also promoted explicitly anti-Semitic doctrines (Rafal
Pankowski 2010, 116). For this we have coded the party 3 on OTH_ETHNIC.
Immigration was not high enough during LPR's time in parliament to
register in its populism (Moroska and Zuba 2010, 131). That said, de
Lange & Guerra, (De Lange and Guerra 2009, 539) record that a number of
LPR politicians made statements against immigration on cultural grounds.
We have left OTH_IMMIGRANT at 1 for now, but there is a case to be made
that it should be 2.

Opposition to European integration was the definitive policy of the
party (Moroska and Zuba 2010, 130; Jasiewicz 2008, 15; De Lange and
Guerra 2009, 537; Markowski and Tucker 2010), as it considered European
liberal values to be antithetical to conservative Polish ones (Jasiewicz
2008, 11). Polish politicians sympathetic to EU integration were accused
of "anti-Polish" politics (Moroska and Zuba 2010, 131). Numerous members
also made statements alleging that Germans and Jews were the principle
beneficiaries of the EU's schemes (Jasiewicz 2008, 15).This tied in with
its generally nationalist outlook that frequently alleged that foreign
interests of conspiring against Polish ones (Pankowski 2010, 113)
(OTH_FOREIGN = 3). The party opposed foreign investment in Poland (De
Lange and Guerra 2009, 539), but in more of a nationalist than an
economic sense. Giertych did however accuse Poland's new business elite
of conspiring with foreign interests and former communist officials
(Rafal Pankowski 2010: 113), and for this reason I've coded it 2 on
OTH_ECONOMIC.

While there is an argument that the party's ideology shifted somewhat in
its 7 years in Parliament, based on the above policies we have labelled
the party FR on LRPOSITION, and it is usually considered so by scholars
(Wysocka 2013, 295; Pankowski 2010, 113; Markowski and Tucker 2010,
526). Father Tadeusz Rydyk, owner of a media empire that included the
influential Radio Maryja, was a charismatic influence in founding and
endorsing the party (Zuba 2017, 90; Moroska and Zuba 2010, 127;
Pankowski 2010, 111; Jasiewicz 2008, 15; Stanley and Cześnik 2019, 72).
While he was never actually leader, we have coded it 2 on CHARISMA for
the 2001 elections given his direct relationship to the meaning of the
party. Subsequently, the young Roman Giertych took over and established
himself as a charismatic leader (Millard 2006, 1017; Kucharczyk and
Wysocka 2008, 78) (especially via a committee post that empowered him to
investigate corruption, see: (Pankowski 2010, 112--13)), albeit of a
party with a strong base. Therefore we have kept the CHARISMA coding at
2 for the 2005 and 2007 elections.

The party had direct links with the All-Polish Youth (*Młodzież
Wszechpolska*, MW) (Kucharczyk and Wysocka 2008, 78), a radical and
violent nationalist street movement whose members "came to dominate the
wider party organisation" (Rafal Pankowski 2010, 112-116). MW members
intimidated opponents or the LPR and targeted LGBT, feminist and Jewish
organisations in particular (Pankowski, 2010:113-16). For this reason we
have coded it 3 for LIBDEMNORMS. The party and its leaders had not
participated in government before joining in coalition with PiS
following the 2005 election (Millard 2009, 791), after which (2007
election) I have coded it 2 on INSIDER.

## Self Defence

Self Defence (*Samoobrona Rzeczpospolitej Polskiej,* SRP) was long an
agrarian trade union before it became a political party, even though it
sent candidates to run for office from the 1990s. Appealing to the rural
"losers" of the post-communist transition, it was seen by many to
espouse a nostalgia for the former regime, albeit with some nationalist
ideas (Pankowski 2010,132). It achieved a breakthrough performance of
10.2% in 2001, and Lepper polled 15.1% in the 2005 presidential election
before the party receded to 1.5% in the 2007 legislative election. It
briefly served in coalition government with PiS and LPR between 2005 and
2007. The party was totally dominated by its founder-leader Andrzej
Lepper, and the inconsistency of many of its (his) positions makes it
very difficult to code.

One aspect of the SRP that was not at all ambiguous was that it was
"anti-establishment by nature" (Moroska and Zuba 2010, 132). Lepper
self-identified as "populist" campaigning for the ordinary citizen
against the "self-proclaimed new elites" (Jasiewicz 2008, 13; see also
Van Kessel 2015a, 125), thus tapping into a growing cynicism of the
political class among voters (Szczerbiak 2007, 212) (OTH_POLCLASS = 3).
It also often espoused xenophobia, especially towards Germans (Moroska
and Zuba 2010, 130) and Jews, whom Lepper has called "the most dangerous
nation for Poland" (Pankowski 2010, 139). While there is a case to be
made that the ambiguity, inconsistency, and unpredictability of these
positions should dampen their place in the party's core outlook, we have
labelled SRP 3 on OTH_ETHNIC. We have seen no evidence that the party
was concerned with OTH_IMMIGRANTS (= 1), although this may be wrong.

In its more nationalist tones, the party alleged that foreign interests
interfered with the Polish economy. It was occasionally opposed to EU
integration, arguing that it would harm the wellbeing of ordinary
farmers and enrich a small elite (Jasiewicz 2008, 11; Stanley and
Cześnik 2019, 71). For this the party earns a 2 on OTH_FOREIGN (there is
a case to be made that this should be 3). Moroska & Zuba, (Moroska and
Zuba 2010, 133) claim that the party stood against foreign capital and
capitalists, and much of its early political activities were aimed at
opposing debt collectors and high interest charging banks repossessing
farms (Pankowski 2010, 133; Markowski and Tucker 2010, 527).
(OTH_ECONOMIC = 3).

The party's ideology was ambiguous and erratic (Pankowski 2010, 135) --
even to the point that some have called it non-ideological. This was in
part due to the fact that Lepper's charismatic leadership was the
essence of its political meaning (Jasiewicz 2008, 14; Pankowski 2010,
142) (CHARISMA = 3). In the words of Moroska & Zuba, (Moroska and Zuba
2010, 129), "Andrzej Lepper consequently became not only the person who
expressed his party's position, but also a spontaneous creator of that
position." While the party has occasionally been considered left wing
(Jasiewicz 2008, 11; De Lange and Guerra 2009, 537; Markowski and Tucker
2010, 527; see also Pankowski 2010, 135), the preponderance of evidence
suggests that it espoused no actual ideology other than a vague
championing of the rural poor (Moroska and Zuba 2010, 130, 132), and
Lepper himself seemed to stress different ideological labels at
different times, and at other suggested that it was neither left, right
or centre, but just "patriotic" (Pankowski 2010, 136). We have therefore
coded its LRPOSITION at C.

As a social movement, Self Defense often held rallies that were accused
of violence and lawlessness (Pankowski 2010, 132--33; Markowski and
Tucker 2010, 527), and when in Parliament Lepper often brought in PA
speakers to drown out the other members when he wanted to drown out
other members (Jasiewicz 2008, 13). According to Pankowski, this image
of anti-system lawlessness was a key part of the party's image and
appeal (Pankowski 2010) (LIBDEMNORMS = 3). The party was never in
government before joining a coalition in 2005, after which (2007) it is
coded 2 on INSIDER.

## Law and Justice

Law and Justice (*Prawo i Sprawiedliwość*, PiS) is the party of brothers
Jarosław and (the late) Lech Kaczyński, two senior members of the
Solidarity movement that took a particularly hard line on the role of
ex-communists in the new regime in the 1990s. The brothers initially
created the Centre Agreement party in the early 1990s, but without a
populist stance nor significant electoral success. After Lech's stint as
Minister of Justice in the centre right Buzek government in which he
became popular for fighting corruption (Millard 2009, 790--91), the
brothers founded PiS in 2001, gaining 9.5% in that election. In 2005
Lech Kaczyński won the presidency and the party entered minority
"populist coalition" government with the LPR and SRP, which collapsed in
2007. While its coalition partners faded in that vote, PiS saw its
popularity rise (essentially swallowing the supporters of its two
coalition partners), only more so after the death of Lech in a plane
crash in Russia in 2010. PiS formed government outright in 2015, when it
also retook the presidency. In many of the OTH\_ variables, PiS is noted
to have made a steady shift away from the centre towards radicalism,
particularly by the time of its 2005 and 2007 elections (Jasiewicz 2008,
23; Markowski and Tucker 2010, 528; Pankowski 2010; Vermeersch 2007, 6),
which makes its early elections (2001 in particular) slightly difficult
to code.

The party advocated a "fourth republic" that would rid the polity of the
corrupt leadership which characterised the third republic (as the post
1989 state had been known) (Jasiewicz 2008, 9; Wysocka 2013, 303;
Kucharczyk and Wysocka 2008, 79; see also Markowski 2008, 1056). It
targeted what it called the *uklad* ("network" or "pact") of elites --
ex-communist officials, corrupt post-solidarity politicians, and foreign
influences -- whom it alleged ran the state: "The network has taken
everything for itself. That explains why, after 1989, the people have
not had a chance" (cited in Wysocka 2013, 304). There are several
scholars who think that PiS only really adopted anti-political class
populism by 2005 (Van Kessel 2015a, 121) or that it was radicalised by
2007 (Jasiewicz 2008, 23; Markowski and Tucker 2010, 528). Stanley &
Cześnik (Stanley and Cześnik 2019, 73) persuasively argue that the party
was hostile to corruption in 2001, but not nearly as radical as the LPR
and SRP (see also Pankowski 2010, 153). Therefore we have coded it 2 on
OTH_POLCLASS in 2001, and 3 from 2005 on. There is some suggestion that
PiS had a more moderate and less confrontation stance in the 2010
presidential election (Szczerbiak 2013, 485), but not enough evidence to
justify changing the coding.

The PiS clearly considered the "people" in ethnic and sectarian
(Catholic) terms, especially after it inherited the nationalist
far-right mantle of the LPR by 2007 and the support of the
fundamentalist Radio Maryja with it (Pankowski and Kornak 2013, 162).
Over time Jarosław Kaczyński made statements to the effect that he had
been mistaken to oppose anti-semitism in the past (Pankowski 2010, 155),
and the party included some known anti-semitic politicians in its ranks
(Pankowski 2010, 157). There was also an infamous incident in which the
party and its campaign managers accused Lech Kaczyński's 2005
presidential rival Donald Tusk of being too German because his
grandfather allegedly fought briefly with the Wehrmacht (Tusk's
grandfather was actually from the Kashuba ethnic minority which had been
forcibly conscripted by the Nazis). According to Pankowski (Pankowski
2010, 157), this triggered ethnocentric anti-German and anti-Kashuba
hostility as much as nationalist disloyalty. Amid the EU refugee crisis
in 2015, PiS honed a sharply anti-Islam discourse, alleging that Muslims
posed a threat to Polish society, and alleging that they had taken over
neighbourhoods and churches in Western Europe (Krzyżanowska and
Krzyżanowski 2018, 615; Krzyżanowski 2018). Like other variables, it is
difficult to pin down precisely when this rhetoric began and what level
it achieved. We have coded OTH_ETHNIC 1 in 2001, 2 2005-2011 and 3 from
2015 on (when anti-Muslim sentiment started to dominate). By 2015, the
European Migrant crisis led the PiS to adopt a harsh xenophobic line on
asylum seekers (Krzyżanowska and Krzyżanowski 2018, 615; Krzyżanowski
2018), and in doing so won over many voters "who normally never would
have voted for it" (Fomina and Kucharczyk 2016, 62). Before 2015
immigration was not a major topic of political discourse (Krzyżanowski
2018, 76) (OTH_IMMIGRANT = 1 2001-2011, 3 2015-).

A number of foreign powers are highly relevant to the PiS's populist
nationalism. Hostility toward Germany (historically a rich vein for the
Polish right) was a key pillar of PiS's politics (Wysocka 2013, 305;
Szczerbiak 2013, 489), and after the 2010 crash that killed Lech the
party propagated a number of conspiracy theories that alleged a Russian
assassination (Stanley and Cześnik 2019, 75; Szczerbiak 2013, 486). The
party has also over time become thoroughly hostile to the EU, which it
accuses of imposing socially liberal values on Poland -- although this
only developed around 2005-07 (Markowski and Tucker 2010, 528).
According to Pankowski, (Pankowski 2010, 157--58), each of these
oppositions were significantly milder in the 2001 election (OTH_FOREIGN
= 2 in 2001, 3 from 2005). While a pro-welfare class politics has often
been a pillar of the Kaczyñskis politics (Szczerbiak 2007, 218;
Pankowski 2010, 163), this does not appear to rise above 1 on the
OTH_ECONOMIC variable (= 1).

While PiS always advocated for a pro-welfare policy of state
intervention in the economy (Millard 2006, 1021; Kucharczyk and Wysocka
2008, 79; Szczerbiak 2007, 211), it has always been considered a party
of the post-solidarity right, whose anti-communism makes it incompatible
with any left wing branding. According to a number of observers (Wysocka
2013, 293; Pankowski 2010, 152) the party started off as centre right in
the early 2000s, before embracing a more right wing agenda in subsequent
elections. Owing to the above traits of ethnocentrism and nationalism,
the party should clearly be defined as far right today (Kasprowicz and
Hess 2017, 204). While it is debatable exactly when this shift should
take place, we have coded its LRPOSITION CR in 2001, R in 2005, and FR
from 2007, as this election is when it is usually considered to have
taken LPRs place on the far right (Jasiewicz 2008, 11).

The party has been defined by the personalities of the Kaczyñski twins
(Jasiewicz 2008, 12; Wysocka 2013, 306) who also control its
organisation totally (Pankowski 2010, 164), although according to Fomina
& Kucharczyk, (Fomina and Kucharczyk 2016, 60) the party pulled Jarosław
"out of public view" for the 2015 elections. It is also worth noting
that other leaders have served as PiS Prime Minister and President in
its recent terms in government. Furthermore, according to some, the
brothers are not actually particularly charismatic, even if they are
well known. This makes the party difficult to code on CHARISMA -- we've
coded it 2, but this could possibly be 3. The brothers had actually been
intimately involved with the highest levels of post-1989 politics
(Jasiewicz 2008, 11; Pankowski 2010, 151), making PiS a 2 on INSIDER up
to 2005, when it formed government and is thenceforth coded 3.

The PiS has, from its inception until its time in government, projected
a majoritirian authoritarianism that threatens liberal democratic norms
(Fomina and Kucharczyk 2016; Pankowski and Kornak 2013, 162). In its
early manifestos, PiS made it clear that it wanted to expand the powers
of the presidency (Millard 2006, 1017) and reduce those of the
legislature and courts (Jasiewicz 2008, 13). It also proposed in 2003 to
rewrite the constitution as an explicitly Catholic document -- beginning
its draft with the words "In the name of God Alighty!" and removing all
references to religious and ethnic minorities (Pankowski 2010, 154). In
government it has been particularly hostile to the judicial system and
media scrutiny (Wysocka 2013, 306, 309) when these have been critical of
the party's interests. According to Pankowski, in the 2001 elections the
PiS "did not challenge the basic elements of the Polish democratic
system" (Pankowski 2010, 151),, and hence we have coded it 2 on
LIBDEMNORMS in that election and 3 ever since.

## Palikot's Movement

Palikot's Movement (*Ruch Palikota*, RP), was a short-lived left-wing
party best known for its anti-clerical stance. It was a vehicle for the
flamboyant and controversial businessman Janusz Palikot, who broke from
the Civic Platform in 2010 after accusing its leadership of veering too
far to the right. On top of its anti-clericalism, the party advocated a
number of left-wing stances, such as drug liberalisation, legalised
abortion, and LGBT rights (Szczerbiak 2013, 389). The party performed
surprisingly well with 10% in the 2011 election, but after significant
internal divisions waned into insignificance by the 2015 polls, by which
time it was a member of a left coalition that could not be considered
populist.

Palikot's populism targeted the power of the Church in Polish politics:
"The Church is not so holy. It is a greedy political party that tries at
any cost to keep a firm hand on its own interests" (cited in Zuba 2017,
92). Within this construction, he accused the political class of
dependence on the Church (Zuba 2017, 100; see also Fomina and Kucharczyk
2016), and maintained a generally anti-establishment character
(Szczerbiak 2013, 489; Van Kessel 2015a, 130) -- even to the point of
saying that he and his nemesis Jarosław Kaczyński were alike in their
"being against the system" (Wróbel 2011, 450). In the party's own
anti-political class words: '\[w\]e are not the next configuration of
the same old elite . . . AWS, PiS, PO, ZChN, PC, KPN, ROP, and now PJN
-- different names, but the same people' (cited in Stanley and Cześnik
2016, 706) (OTH_POLCLASS = 3).

Palikot ran a very business-friendly campaign promising liberal small
government (Szczerbiak 2013, 489) (OTH_ECONOMIC = 1), and while the
party is usually considered left-wing (Zuba 2017; Szczerbiak 2013;
Sokołowski 2012), this has less to do with economic policy than social
policy -- which by all accounts was a more important pillar of the
party's image (Stanley and Cześnik 2016, 707) (LRPOSITION = L). There is
no evidence for anything on the OTH_ETHNIC, OTH_IMMIGRANT, or
OTH_FOREIGN variables, which are all coded 1. As its name suggests it
was totally dominated by its leader (Zuba 2017, 92; Kosowska-Gąstoł and
Sobolewska-Myślik 2019, 14) (CHARISMA = 3), and there is no evidence
that it violated LIBDEMNORMS (= 1). Despite being a well-known deputy in
the PO government until 2010, Palikot wasn't really powerful or
established enough to be an INSIDER (= 1) (Kosowska-Gąstoł and
Sobolewska-Myślik 2019, 15).

## Kukiz '15

The Association for a New Constitution Kukiz'15 (*Stowarzyszenienarzecz
Nowej Konstytucji Kukiz'15*, usually referred to as just "Kukiz '15"),
was the creation of rock singer Paweł Kukiz, who gradually became active
in politics in the 2000s-2010s. Originally affiliated with the Civic
Platform, his main concern grew into constitutional reform of the
electoral system, advocating the adoption of single member districts.
Kukiz stood in the 2015 presidential election, where he added a holistic
criticism of the political class to his calls for electoral reform,
picking up a surprising 20.8% to place third. Months later, he built on
this momentum by creating an "association" to contest the parliamentary
elections on broadly the same campaign themes. Despite winning 42 seats,
the group collapsed early in the term due to internal disagreements.
Both campaigns relied heavily on online platforms (Facebook and Twitter
in particular) and were targeted at young voters (Kasprowicz and Hess
2017, 212; Olczyk and Wasilewski 2016; Stanley and Cześnik 2019, 83).

Kukiz'15 is frequently regarded as "anti-establishment" (Fomina and
Kucharczyk 2016, 60; Zuba 2017, 100; Stanley and Cześnik 2019, 75;
Olczyk and Wasilewski 2016, 58; Lipiński and Stępińska 2019, 72), and
"anti-system" (Kosowska-Gąstoł and Sobolewska-Myślik 2019, 22; Stanley
and Cześnik 2019, 81; Szczerbiak 2018) for its total rejection of the
political class, which it regarded as corrupt and oligarchic
(Kosowska-Gąstoł and Sobolewska-Myślik 2019, 16; 2017, 146; Kasprowicz
and Hess 2017, 206; Olczyk and Wasilewski 2016, 59; Stępińska et al.
2016, 315). It propagated a narrative of the "partiocracy" -- an
established network of professional politicians whose parties (including
both CO and PiS) only pretend to differ in any meaningful way (Stanley
and Cześnik 2019, 76) (OTH_POLCLASS = 3). For this reason it was very
careful not to define and register itself as a party, but as an
"electoral committee of voters" (Kosowska-Gąstoł and Sobolewska-Myślik
2019, 15). In line with its "ordinary person" appeal, candidates for the
parliamentary elections were selected by a simple online questionnaire
(Kosowska-Gąstoł and Sobolewska-Myślik 2017, 147) -- one reason why it
was so difficult to keep together after the vote.

While the party's programme was (intentionally) vague (Stanley and
Cześnik 2019, 76), there were several core elements to its ideological
outlook. Many of the party's candidates and supporters were drawn from
existing radical right parties (Kosowska-Gąstoł and Sobolewska-Myślik
2019, 22), giving it a nationalist and nativist politics (Stanley and
Cześnik 2019, 76), often in accord with Kukiz's own statements.
According to Fomina & Kucharczyk it "spouted anti-European, nationalist,
and xenophobic slogans but had no substantive program beyond reforming
the electoral system" (Fomina and Kucharczyk 2016, 60). Furthermore,
Kukiz himself made several barely-cryptic anti-Semitic statements about
Poland's role in the Holocaust and the role of Jews in the former
communist regime (Pankowski 2018, 25). While there is a case to be made
that this did not quite reach the level of a 3 on OTH_ETHNIC (mainly due
to the vagueness of the party's positions), we have coded it 3 for now.
Opposition to Syrian refugees was an important pillar of the party's
rhetoric in 2015 (Stanley and Cześnik 2019, 76; Lipiński and Stępińska
2019, 72), and Wciseł claims that the migration crisis was the "driving
force" behind the 2015 campaign (Wciseł 2016, 28), even though he
vacillated between harder and softer approaches (OTH_IMMIGRANT = 3). The
party was "anti-European" (Fomina and Kucharczyk 2016, 60), and claimed
that Poland had become a "neo-colony of foreign governments and
international corporations" (cited in Stanley and Cześnik 2019, 76). It
also considered tolerance of refugees to equate to political allegiance
to Germany (Wciseł 2016, 28) (OTH_FOREIGN = 3). There was an element of
hostility towards foreign capital in the party's discourse (Kasprowicz
and Hess 2017, 210; Stanley and Cześnik 2019, 76), but these policies
were not as important as the party's nativism in its political discourse
(Stanley and Cześnik 2019) (OTH_ECONOMIC = 2).

The party's economic ideology was very vague (Olczyk and Wasilewski
2016, 57) and its formal policies were a somewhat contradictory blend of
conventional left and right. This coupled with the fact that Kukiz's
music had both left and right-wing themes (Olczyk and Wasilewski 2016,
58), and with the fact that its extremely open form of candidate
selection produced an eclectic mix of leaders, makes it difficult to
place the party on LRPOSITION (Kosowska-Gąstoł and Sobolewska-Myślik
2017, 147). Stanley & Cześnik (Stanley and Cześnik 2019, 85) claim that
the party is actually centrist -- that even though it had links and
affinities with the radical right, its programme is actually vague and
its appeal is built mainly on anti-political class populism. However
most scholars seem to agree that the party should generally be
considered "conservative"/"economic nationalis\[t\]" (Kosowska-Gąstoł
and Sobolewska-Myślik 2019, 13) and "right-wing" (Lipiński and Stępińska
2019; Szczerbiak 2018; Wciseł 2016, 28), and hence we have coded it R on
LRPOSITION.

The party is clearly based around the persona of Kukiz himself (Olczyk
and Wasilewski 2016; Kosowska-Gąstoł and Sobolewska-Myślik 2017, 146;
Szczerbiak 2016) (CHARISMA = 3), and was a genuinely new political force
(Kosowska-Gąstoł and Sobolewska-Myślik 2019, 16) (INSIDER = 1). The
party was extremely hostile to media criticism, and accused the
(national and global) press of being complicit in maintaining the
establishment (Kasprowicz and Hess 2017, 210). It is debatable whether
this should land the party on LIBDEMNORMS -- we have coded it 2 for now.

## Not included

There is an argument to be made that several political parties and
actors from the early post-communist years should be classified as
populist. The Polish Peasant Party (PSL) had a populist history that
predated the communist regime, and some consider this to have lived on
in the 1990s (Jasiewicz 2008, 9). However most scholars tend to agree
that it was not genuinely populist by the time that most of its
supporters were swallowed up by (the unambiguously populist) Self
Defence in the 1990s (Pankowski 2010; Markowski and Tucker 2010, 528).
There is also a case to be made that Lech Wełeşa himself should be
considered a populist for his common man appeal and hostility to the
communist political class. We however do not see that this continued
into the 1990s to the extent that he should be included in the dataset.

**References**

Bell, Janice. 1997. 'Unemployment Matters: Voting Patterns during the
Economic Transition in Poland, 1990--1995'. *Europe-Asia Studies* 49
(7): 1263--91.

De Lange, Sarah L., and Simona Guerra. 2009. 'The League of Polish
Families between East and West, Past and Present'. *Communist and
Post-Communist Studies* 42 (4): 527--49.

Fomina, Joanna, and Jacek Kucharczyk. 2016. 'The Specter Haunting
Europe: Populism and Protest in Poland'. *Journal of Democracy* 27 (4):
58--68.

Jasiewicz, Krzysztof. 2007. 'George Sanford. Democratic Government in
Poland: Constitutional Politics Since 1989. Basingstoke and New York:
Palgrave Macmillan, 2002. Xix, 256 Pp. \$68.00.' *Canadian-American
Slavic Studies* 41 (2): 244--45.

---------. 2008. 'The New Populism in Poland: The Usual Suspects?'
*Problems of Post-Communism* 55 (3): 7--25.

Kasprowicz, Dominika, and Agnieszka Hess. 2017. 'Populism in Poland:
Between Demagoguery and Demophilia'. *Środkowoeuropejskie Studia
Polityczne* 10 (2): 201--14.

Kosowska-Gąstoł, Beata, and Katarzyna Sobolewska-Myślik. 2017. 'New
Political Entrepreneurs in Poland'. *Politologickỳ Časopis= Czech
Journal of Political Science* 24 (2): 137--57.

---------. 2019. 'New Parties in the Polish Party System 2011--2018: The
Palikot Movement, Kukiz'15 and the Modern Party of Ryszard Petru as
Genuinely New Parties?' *Central European Journal of Politics* 5 (1):
6--29.

Krzyżanowska, Natalia, and Michał Krzyżanowski. 2018. '"Crisis" and
Migration in Poland: Discursive Shifts, Anti-Pluralism and the
Politicisation of Exclusion'. *Sociology* 52 (3): 612--18.

Krzyżanowski, Michał. 2018. 'Discursive Shifts in Ethno-Nationalist
Politics: On Politicization and Mediatization of the "Refugee Crisis" in
Poland'. *Journal of Immigrant & Refugee Studies* 16 (1--2): 76--96.

Kucharczyk, Jacek, and Olga Wysocka. 2008. 'Poland'. In *Populist
Politics and Liberal Democracy in Central and Eastern Europe*, edited by
Grigorij Mesežnikov, Ol'ga Gyárfášová, and Daniel Smilov, 71--100.
Bratislavia: Institute for Public Affairs.

Lipiński, Artur, and Agnieszka Stępińska. 2019. 'Polish Right-Wing
Populism in the Era of Social Media: The Unexpected Careers of Paweł
Kukiz and Janusz Korwin-Mikke'. *Problems of Post-Communism* 66 (1):
71--82.

Markowski, Radoslaw. 2008. 'The 2007 Polish Parliamentary Election: Some
Structuring, Still a Lot of Chaos'. *West European Politics* 31 (5):
1055--68.

Markowski, Radoslaw, and Joshua A. Tucker. 2010. 'Euroscepticism and the
Emergence of Political Parties in Poland'. *Party Politics* 16 (4):
523--48.

Millard, Frances. 1994. 'Nationalist Themes in Polish Politics
1989--1993'. *Journal of Area Studies* 2 (4): 43--55.

---------. 2006. 'Poland's Politics and the Travails of Transition after
2001: The 2005 Elections'. *Europe-Asia Studies* 58 (7): 1007--31.

---------. 2009. 'Poland: Parties without a Party System, 1991-2008'.
*Politics & Policy* 37 (4): 781--98.

Moroska, Aleksandra, and Krysztof Zuba. 2010. 'Two Faces of Polish
Populism. The Causes of the Success and Fall of Self Defence and the
League of Polish Families'. *Totalitarismus Und Demokratie* 7 (1):
123--47.

Olczyk, Tomasz, and Jacek Wasilewski. 2016. 'From Rock Star to Political
Star-Curious Case of Pawel Kukiz's Persona Power'. *Persona Studies* 2
(2): 57--70.

Pankowski, Rafal. 2010. *The Populist Radical Right in Poland: The
Patriots*. London and New York: Routledge.

---------. 2018. 'The Resurgence of Antisemitic Discourse in Poland'.
*Israel Journal of Foreign Affairs* 12 (1): 21--37.

Pankowski, Rafal, and Marcin Kornak. 2013. 'Poland'. In *Right-Wing
Extremism in Europe. Country Analyses, Counter-Strategies and
Labor-Market Oriented Exit Strategies*, edited by Ralf Melzer and
Sebastian Serafin, 157--68. Universität Tübingen.

Rok, Adam. 1992. 'Antisemitic Propaganda in Poland---Centres,
Proponents, Publications'. *East European Jewish Affairs* 22 (1):
23--37.

Sanford, George. 2002. *Democratic Government in Poland: Constitutional
Politics since 1989*. Springer.

Schöpflin, George. 1991. 'Post-Communism: Constructing New Democracies
in Central Europe'. *International Affairs* 67 (2): 235--50.

Sobolewska-Myślik, Beata, and Katarzyna Kosowska-Gąstoł. 2019. 'New
Parties in the Polish Party System 2011--2018: The Palikot Movement,
Kukiz'15 and the Modern Party of Ryszard Petru as Genuinely New
Parties?' *Central European Journal of Politics* 5 (1): 6--29.

Sokołowski, Jacek K. 2012. 'The 2011 Elections in Poland: Defining a New
Cleavage'. *Representation* 48 (4): 461--73.

Stanley, Ben, and Mikołaj Cześnik. 2016. 'Poland's Palikot Movement:
Voice of the Disenchanted, Missing Ideological Link or More of the
Same?' *Party Politics* 22 (6): 705--18.

---------. 2019. 'Populism in Poland'. In *Populism Around the World: A
Comparative Perspective*, edited by Daniel Stockemer, 67--87. Cham:
Springer.

Stępińska, Agnieszka, Artur Lipiński, Agnieszka Hess, and Dorota
Piontek. 2016. 'Poland: A Fourth Wave of Populism?' In *Populist
Political Communication in Europe*, edited by Toril Aalberg, Frank
Esser, Carsten Reinemann, Jesper Stromback, and Claes De Vreese,
311--25. Routledge.

Surazska, Wisla, and Roger Bivand. 1997. 'From Populist Vote to the
Post-Communist Victory in Poland: Regional Differences'. *European Urban
and Regional Studies* 4 (1): 76--84.

Szczerbiak, Aleks. 2007. '"Social Poland" Defeats "Liberal Poland"? The
September--October 2005 Polish Parliamentary and Presidential
Elections'. *Journal of Communist Studies and Transition Politics* 23
(2): 203--32.

---------. 2013. 'Poland (Mainly) Chooses Stability and Continuity: The
October 2011 Polish Parliamentary Election'. *Perspectives on European
Politics and Society* 14 (4): 480--504.

---------. 2016. 'Poland's Rock Star-Politician: What Happened to Paweł
Kukiz?' *LSE European Politics and Policy (EUROPP) Blog* (blog). London
School of Economics and Political Science. 2016.
http://blogs.lse.ac.uk/europpblog/2016/05/11/polands-rock-star-politician-what-happened-to-pawel-kukiz/.

---------. 2018. 'What Are the Prospects for Poland's Rock
Star-Politician Paweł Kukiz?' *LSE European Politics and Policy (EUROPP)
Blog* (blog). London School of Economics and Political Science. 2018.
http://blogs.lse.ac.uk/europpblog/2018/06/12/what-are-the-prospects-for-polands-rock-star-politician-pawel-kukiz/.

Van Kessel, Stijn. 2015a. *Populist Parties in Europe: Agents of
Discontent?* Springer.

---------. 2015b. *Populist Parties in Europe: Agents of Discontent?*
Springer.

Vermeersch, Peter. 2007. 'Ethnic Minority Protection and
Anti-Discrimination in Central Europe before and after EU Accession: The
Case of Poland'. *JEMIE - Journal on Ethnopolitics and Minority Issues
in Europe* 6: 1--21.

Wciseł, Wojciech. 2016. 'Migratory Crisis in the Eyes of the Party
Leaders during the Parliamentary Campaign in Poland in 2015'. *Political
Preferences*, no. 13: 21--34.

Wróbel, Szymon. 2011. 'Mourning Populism. The Case of Poland'. *Polish
Sociological Review* 176 (4): 437--56.

Wysocka, Olga. 2013. 'Polish Populism: Time for Settlement'. In
*Exposing the Demagogues: Right-Wing and National Populist Parties in
Europe*, edited by Karsten Grabow and Florian Hartleb, 293--322.
Brussels: Konrad Adenauer Stiftung.

Zuba, Krzysztof. 2017. 'From Fringe to Fringe: The Shift from the
Clericalist League of Polish Families to the Anticlericalist Palikot
Movement 2001--2015'. *Religion, State & Society* 45 (2): 87--105.
