---
title: Portugal
subtitle: 'Date range: 1980-2020'
title-block-banner: yes

---

# Case notes

## Democratic and Social Centre -- People's Party

The Democratic and Social Centre (*Centro Democrático e Social*, CDS)
was originally founded as a centrist party in the 1970s, fluctuating
around 5-15% of the national vote until the 1990s and shifting
considerably in its ideology (De Sousa 2001, 159). In 1992, the young
and charismatic Manuel Monteiro assumed the party leadership and added
the name "People's Party" (*Partido Popular*, henceforth CDS-PP).
Monteiro moved the party toward the ideological right and embraced a
populist discourse. This precipitated a turnaround of party fortunes,
with its vote share rising from 4.4 to 9.1 between the 1991 and 1995
elections. There seems to be little evidence that the party was populist
before or after Monteiro's leadership -- Lisi & Borghetto call it
"mainstream" in 2018 (Lisi and Borghetto 2018, 407). Monteiro went on to
found another party -- the New Democracy Party -- in 2003, but this did
not achieve much success.

There are not many expansive texts in English discussing the CDS-PP's
populism at length, but several references give evidence as to the broad
elements of Monteiro's populist discourse. The party's 1995 election
manifesto claimed that "Two classes of citizens are present in Portugal:
the politicians, who have used the law to get more and more privileges,
and the rest, who work an entire life, pay taxes and do not get access
to any of them" (Lisi and Borghetto 2018, 414). Similarly, several
scholars point to Mandeiro's will to "mobilise protest by targeting the
sectors of the population disillusioned with the two main parties" (De
Sousa 2001, 179; see also Salgado and Zúquete 2016, 238--39), suggesting
a strong presence on the OTH_POLCLASS variable (= 3).

Monteiro positioned the party on the right (LRPOSITION = R) in an
attempt to garner the nationalist vote (Corkill 1996, 406), and adopted
conservative stances on crime and social issues. This also included a
strong Euroscepticism (Corkill 1996, 406; Costa Lobo 2003, 109; Costa
Lobo and Magalhães 2011, 90) on nationalist, pro-sovereignty grounds
(OTH_FOREIGN = 2), and anti-immigrant policies (Salgado and Zúquete
2016, 239) (OTH_IMMIGRANT = 2). We have not found evidence to suggest
OTH_ETHNIC or OTH_ECONOMIC variables (= 1), but further research should
confirm this.

The party was in coalition government in the 1970s, but given that
Monteiro was not a part of that government we have coded the party 1 on
INSIDER for the 1995 election. While the party has been established
since the 1970s, several texts make it clear that Monteiro's leadership
and "belligerent" style (The Economist Intelligence Unit 1998, 13) was a
central component of its image and appeal (CHARISMA = 2). Monteiro
suggested that popular militias could fight crime (Corkill 1996, 406)
and that drug addicts be "interned" in treatment clinics (The Economist
Intelligence Unit 1997, 15), for which we have coded him 2 on
LIBDEMNORMS.

## Left Bloc

The Left Bloc (*Bloco de Esquerda*, BE) is the product of a 1999 merger
of two small far left parties -- the Revolutionary Socialist Party and
the Popular Democratic Union. According to Lisi, the party was created
to overcome the fractured nature of the Portuguese left, and to appeal
to independents dissatisfied with the incumbent socialist government
(Lisi 2009, 131). In contrast to the established Portuguese Communist
Party, it showed more interest in "left-libertarian" (post-materialist)
values, a willingness to link with other social movements (Lisi 2009,
132), and a move away from Marxian ideas of class conflict toward a more
general "interclassist" approach (Lisi and Borghetto 2018, 418)
(LRPOSITION = L). The party's fortunes increased during the economic
crisis in 2010-11 and the government's controversial austerity package
that followed it (Lisi 2013, 33; Lisi and Borghetto 2018, 420).

There are few sources which detail the nature of the party's
anti-establishment rhetoric, but there seems to be a general consensus
in the literature that it is an anti-establishment populist party that
reaps protest votes from dissatisfied voters (Gómez-Reino Cachafeiro and
Plaza-Colodro 2018, 351; Silva 2018; March 2008, 11; Soeiro 2009, 183;
Lisi and Borghetto 2018, 413) (OTH_POLCLASS = 3). At its foundation, the
party aimed to be a highly decentralised "political movement of
citizens" in contrast to the traditional left-wing parties and their
rigid hierarchies (Lisi 2013, 25), and to harvest protest votes against
the incumbent government (Lisi 2009, 135). In advertising campaigns
throughout the post-crisis protests, the party accused the established
parties of being unrepresentative and unresponsive (Lisi 2013, 34; 2009,
132). Lisi also suggests that both anti-establishment appeal and far
left ideology dissipated after the conservative government came to power
in 2003 (Lisi 2009, 136) -- this should be further investigated.

In keeping with its leftist ideology, the party is hostile to business
and financial elites (Soeiro 2009, 180; Lisi and Borghetto 2018, 420)
(OTH_ECONOMIC = 3). The party also maintains a generally Eurosceptic
stance (Gómez-Reino Cachafeiro and Plaza-Colodro 2018, 351). In its 2005
manifesto, it claimed that "In today's Europe, where Berlin's power is
the only rule, the defence of democracy is the people's weapon against
blackmail" (Lisi and Borghetto 2018, 417) (OTH_FOREIGN = 2). Further
research should discuss whether this rating should remain constant
throughout the party's period of inclusion in the dataset. We have seen
no evidence to code above 1 on OTH_ETHNIC, OTH_IMMIGRANTS, or
OTH_MILITARY. We have also seen no evidence for any coding above 1 on
either LIBDEMNORMS or CHARISMA, and the party has never been in
government (INSIDER = 1).

**References**

Corkill, David. 1996. 'Portugal Votes for Change and Stability: The
Election of 1995'. *West European Politics* 19 (2): 403--9.
https://doi.org/10.1080/01402389608425140.

Costa Lobo, Marina. 2003. 'Portuguese Attitudes Towards EU Membership:
Social and Political Perspectives'. *South European Society and
Politics* 8 (1--2): 97--118. https://doi.org/10.1080/13608740808539645.

Costa Lobo, Marina, and Pedro C. Magalhães. 2011. 'Room for Manoeuvre:
Euroscepticism in the Portuguese Parties and Electorate 1976--2005'.
*South European Society and Politics* 16 (1): 81--104.
https://doi.org/10.1080/13608740903432375.

De Sousa, Luís. 2001. 'Political Parties and Corruption in Portugal'.
*West European Politics* 24 (1): 157--80.
https://doi.org/10.1080/01402380108425422.

Gómez-Reino Cachafeiro, Margarita, and Carolina Plaza-Colodro. 2018.
'Populist Euroscepticism in Iberian Party Systems'. *Politics* 38 (3):
344--60. https://doi.org/10.1177/0263395718762667.

Lisi, Marco. 2009. 'New politics in Portugal: the rise and success of
the left bloc'. *Pôle Sud* 30 (1): 127--44.
https://doi.org/10.3917/psud.030.0127.

---------. 2013. 'Rediscovering Civil Society? Renewal and Continuity in
the Portuguese Radical Left'. *South European Society and Politics* 18
(1): 21--39. https://doi.org/10.1080/13608746.2012.757450.

Lisi, Marco, and Enrico Borghetto. 2018. 'Populism, Blame Shifting and
the Crisis: Discourse Strategies in Portuguese Political Parties'.
*South European Society and Politics* 23 (4): 405--27.
https://doi.org/10.1080/13608746.2018.1558606.

March, Luke. 2008. *Contemporary Far Left Parties in Europe: From
Marxism to the Mainstream?* Berlin: Friedrich-Ebert-Stiftung.
https://www.research.ed.ac.uk/en/publications/contemporary-far-left-parties-in-europe-from-marxism-to-the-mains.

Salgado, Susana, and Jose Pedro Zúquete. 2016. 'Portugal: Discreet
Populisms Amid Unfavorable Contexts and Stigmatization'. In *Populist
Political Communication in Europe*, edited by Toril Aalberg, Frank
Esser, Carsten Reinemann, Jesper Stromback, and Claes De Vreese,
235--48. New York: Routledge.

Silva, Bruno Castanho. 2018. 'Populist Radical Right Parties and Mass
Polarization in the Netherlands'. *European Political Science Review* 10
(2): 219--44.

Soeiro, José. 2009. 'The "Bloco de Esquerda" and the Founding of a New
Left in Portugal'. In *The Left in Europe*, edited by C. Hildebrandt and
B. Daiber, 176--83. Brussels: Rosa Luxemburg Foundation.

The Economist Intelligence Unit. 1997. 'Country Report: Portugal'. 2nd
Quarter. London.

---------. 1998. 'Country Report: Portugal'. 1st Quarter. London.
