---
title: Slovakia
---


## Movement for a Democratic Slovakia 

The Movement for a Democratic Slovakia (*Hnutie za demokratické
Slovensko*, HZDS) split off from the major Slovakian anti-communist
dissident movement Public Against Violence (VPN) in 1991 (Bútora and
Bútorová 1993, 79). Throughout the 1990s it was the major party of
government, with its founder and leader Vladimir Mečiar serving as Prime
Minister three times between 1990 and 1998 (throughout the period of the
Velvet Divorce form Czechia). After the 1994 elections HZDS governed in
coalition with two other smaller populist parties, the Slovak National
Party (SNS) and the Union of Slovak Workers (ZRS). This government was
defeated in 1998. The party added the words "People's Party" to the end
of its name (HZDS-ĽS) in 2000, but its support steadily declined in
subsequent elections. Still under Mečiar's leadership, HZDS joined the
new Smer government after the 2006 elections (where it polled 8.79%),
but its vote dropped below 5% in the subsequent 2010 elections and it
formally dissolved in 2014.

Despite the fact that HZDS was always a core part of the political
establishment of the Slovak Republic, it portrayed itself as
representing ordinary people against a "'grand coalition' of forces
conspiring to remove it from power" (Stanley 2017, 149--50). It often
relied on grandiose rhetoric that depicted its opponents as "evil ones
opposing Slovakia" (Ferencei 2020, 168), or simply "enemies of Slovakia"
(Haughton 2003a, 269; Abrahám 1995, 99). These attacks often targeted
other figures within the state, (including Mečiar's archrival President
Michal Kováč) whom the party collectively accused of trying "destroy the
political system in Slovakia" in 1995 (Deegan-Krause 2012, 194). In
Deegan-Krause's words, Mečiar's success was based on his "ability to
sustain the image of an underdog fighting against a unified elite even
while he exercised the full power of the state" (Deegan-Krause 2012,
187) (OTH_POLCLASS = 3). According to a number of other sources, the
party's anti-elite populist rhetoric declined after the 1998 election,
at which point it tried to portray itself as a "normal party"
(Deegan-Krause and Haughton 2009, 831; Stanley 2017, 50). For this
reason, we've included it in the dataset only up to this election.

Most sources suggest that Mečiar embraced a form of Slovak nationalism
that defined the people and their "others" in ethnic terms (Scheiring
2021, 1588; Deegan-Krause 2012, 186). This involved the frequent
scapegoating of the large Hungarian minority (Stanley 2011, 258--59;
Abrahám 1995, 97). In 1994, for example, HZDS campaign leaflets
asserted: "Who does not vote for HZDS is voting for Hungarian autonomy"
(Haughton 2001, 752). The HZDS's ethnocentrism also targeted the
Slovakian Roma population. One HZDS minister told a rally in 1995 that
the government would ensure that the Roma birth rate is lower than that
of the white population (Haughton 2001, 753). On both fronts it appears
that the HZDS's rhetoric has been somewhat softer than other parties
(notably the SNS) (Abrahám 1995, 97). Nonetheless, there is sufficient
evidence to code it 3 on OTH_ETHNIC in the years in which it features in
the dataset. We've found no evidence that opposition to immigrants
featured prominently in the party's appeal (perhaps in part due to the
low immigration rate in the 1990s) (OTH_IMMIGRANTS = 1).

In line with his nationalistic ideology, Mečiar's opposition to the
domestic political elite and ethnic minorities tied into a general claim
that these enemies of the nation represented foreign powers, such that
the true "elite" was elsewhere (Deegan-Krause 2012, 188; Deegan-Krause
and Haughton 2009, 831). The Hungarian minority was thus linked to
Hungarian meddling, as Roma were linked to the influence of the European
Union (Deegan-Krause 2012, 186). The United States and the Czech
Republic were also linked to domestic rivals in this way (Deegan-Krause
2012, 188) (OTH_FOREIGN = 3). We've seen no evidence of any OTH_MILITARY
(= 1) or OTH_FINANCIAL (= 1) rhetoric.

HZDS's ideology is generally considered nationalist, (Deegan-Krause
2012; Kim 2021, 224; Menzies 2004; Carpenter 1997), although it also
contained a number of economically centrist, centre-left, or just "hazy"
policy approaches that make the party difficult to categorise on the
left-right spectrum (Haughton 2001, 763; Bútora and Bútorová 1993, 81).
Throughout much of the 1990s it was considered "centrist" (Ferencei
2020, 168). Most sources claim that the party's cultural nationalism was
its most salient ideological element (Kim 2021, 224), and therefore
we've coded it CR on LRPOSITION.

Mečiar has been considered a charismatic (Abrahám 1995, 89) and
demagogic (Carpenter 1997, 212) figure, and many analysts have contended
that the party's appeal was meaningless but for its association with his
personality (Haughton 2001, 748; 2003a, 269; Haughton and Rybář 2008,
242). Mečiar himself said "the strongest stream in the HZDS am I" (Van
Duin and ková 2000, 342). According to Menzies,

> The ideology of the movement was not sufficient to hold together a
> movement full of ambiguities and contradictions. From the very
> beginning, Vladimir Mečiar had been crucial in holding all these
> interests and beliefs together. That continued to be the case and so
> the HZDS must be seen as an example of a charismatic party (Menzies
> 2004, 65).

Structurally, while the party possessed a relatively robust party
organisation (Deegan-Krause and Haughton 2009, 831), over time it came
to be totally dominated by Mečiar (Deegan-Krause 2012, 195) (Haughton
2001, 754). As a consequence many in the literature have considered the
party a "charismatic party" (Haughton 2001, 755) or at least a
"leader-oriented political movement" (Ferencei 2020, 167) (CHARISMA =
3).

Owing to his time in government in the 1990s, Mečiar has been
consistently considered as hostile to liberal democratic norms in
Slovakia, with some analysts claiming that he "derailed" the transition
to liberal democratic government altogether (Stanley 2011, 258), and
embraced an "authoritarian" model (especially after 1994) (Kim 2021,
233). Regarding Slovakia's democratic institutions, the HZDS government
purged the state bureaucracy and intelligence services of non-allied
employees (Bútora and Bútorová 1993, 81; Carpenter 1997, 215--16;
Ferencei 2020, 168), kicked the opposition off powerful committees in
parliament and other oversight institutions (Deegan-Krause 2012, 194;
Żarna 2018, 105), called the Constitutional Course a "diseased element"
(Ferencei 2020, 168), and sought to weaken the power of the president
(Ferencei 2020, 168; Deegan-Krause 2012, 194). The government also
curtailed the freedom of the press by shutting down opposition
newspapers (Bútora and Bútorová 1993, 81; Abrahám 1995, 5), placing
party members in charge of media regulation (Kim 2021, 233), and firing
the political editor of a television broadcaster due to "biased
coverage," leading to the cancelling of all government-critical
programming (Carpenter 1997, 215--16). Mečiar was also allegedly engaged
in a plot to kidnap the son of president Michal Kováč's (Carpenter 1997,
216; Haughton 2003b, 67). This is sufficient to code the party 3 on
LIBDEMNORMS. Given that the party emerged out of the existing government
within Slovakia (before the split with the Czech Republic), we've coded
it 3 on INSIDER.

## Slovak National Party

The Slovak National Party (*Slovenská národná strana*, SNS), was founded
in 1990, at which point it was organised primarily around the demand for
independence from the Czechoslovak union (Pytlas 2013, 168). The party
claimed successorship to the original SNS active between 1870 and 1938
(Walter 2017, 176). Though the party was regarded by some as an "extreme
nationalist party" from its foundation in 1990 (see Żarna 2018, 74),
others claim that under the leadership of Ľudovit Černák it espoused
more of a "liberal conservative pragmatism" in its early years
(Haughton, Rybář, and Deegan-Krause 2021, 331), and only turned to a
radical ethno-nationalism and anti-establishment populism after the
Velvet Divorce from Czechia and under the new leadership of Ján Slota
from 1994 (Pytlas 2013, 168; Kevický 2022, 6). On the balance of
evidence we've decided not to include the party in the dataset until its
first election under Slota's leadership in 1994. Under Slota the party
polled 5.4% in the 1994 elections and gained 9 seats, forming a
coalition government with HZDS and ZRS until 1998. The party split in
2002 when Anna Malikova took the leadership from Slota, who went on to
found the Real Slovak National Party in protest (Haughton 2003b, 82).
Both entities fared poorly and reunited under Slota's leadership before
the 2006 election, in which it won 11.7% and entered a coalition with
Smer. It's vote then declined and it failed to make the 5% threshold to
enter Parliament in 2012, leading Slota to step down. His replacement
Andrej Danko the party condemned Slota's leadership and expelled him
from the party (Rybář and Spáč 2017, 154), and made other changes to
abandon radical nationalism and extremism (Školkay 2021, 11; Struhár
2016, 27) such that "the party may be considered a traditional
right-wing party" from this point on (Karabová and Filipec 2018, 6). We
have therefore not included the party in the dataset under Danko's
leadership.

Slota and the SNS engaged in "populist anti-establishment rhetoric"
(Pytlas 2013, 168) against the Slovak political elite whom it accused of
"extreme cosmopolitanism" (Żarna 2018, 111) and opposition to the Slovak
nation (Ferencei 2020, 168). However, there is not a lot of discussion
in the literature about the specifically anti-establishment elements of
the party's rhetoric, and Engler *et al* (Engler, Pytlas, and
Deegan-Krause 2019, 1326) claim that the party's anti-establishment
rhetoric was notably lower than other populist parties in the region.
More evidence would be useful here on the specific nature of the claims,
but this does appear to be sufficient to code the party 2 for
OTH_POLCLASS under Slota.

The principle framework of the SNS was ethnonationalism, which was
targeted to appeal to ethnic Slovaks (Deegan-Krause and Haughton 2009,
829), and made "others" of both ethnic Hungarians and Roma (Haughton
2003b, 82; Haughton, Rybář, and Deegan-Krause 2021, 331; Lang 2005, 9).
Its 2006 campaign slogan, for example, was "Let's return Slovakia into
the hands of Slovaks!" (Haughton and Rybář 2008, 241). It was initially
the Hungarian minority whom the party focused on most, accusing it of
national disloyalty (Stanley 2011, 258--59), comprising of a great evil
(Deegan-Krause and Haughton 2009, 831), and seeing Slovakia as merely a
*Felvidék* ("upperlands") of the Hungarian state to which it should
return (Pytlas 2013, 173). Slota said in 1994, for example that "the
Hungarian \[minority\] political subjects should be outlawed because
their true and direct objective is the destruction of the Slovak
Republic as a state" (Carpenter 1997, 215). The party also targeted Roma
as "parasites" underserving of social support (Ferencei 2020, 169) and
alleged that the "Gypsy problem" (a pejorative term) could only be
solved by extreme policies like confiscating children from "maladjusted
parents" (Struhár 2016, 27), or, in more violent terms, with "long whip
and a small yard" (Haughton 2001, 753). This is clearly deserving of a 3
on OTH_ETHNIC. Throughout the 1990s immigration was not on the party's
radar at all, but this changed as the party developed an
anti-immigration stance after about 2005 (Stefancik, Némethová, and
Seresová 2021, 732) (OTH_IMMIGRANTS = 1 1994-1998, 3 2006-2012).

Slota and the SNS exuded OTH_FOREIGN rhetoric, primarily against
neighbouring Hungary but also against NATO (Evans and Whitefield 1998,
121; Żarna 2018, 111). However as this did not rise to the level of
alleging that the political elite was wholly controlled by foreign
powers (although it did think this about the ethnic Hungarian parties in
Slovakia), we've coded it 2 on OTH_FOREIGN. We've seen no evidence for
anything on the OTH_FINANCIAL or OTH_MILITARY variables (= 0).

The party is considered "far-right" by most scholars (Struhár 2016, 27;
Stojarová 2018, 38), and ideologically nationalist and conservative
(Sekerák 2019, 237). In its economic policy it has been considered
either centrist (Hloušek and Kopeček 2008, 543--44) or right of centre
(Pinterič and Žúborová 2014, 360), and at the time of its foundation it
advocated for pro-market reforms (Barański 2020, 38). However its
economic policy were "not important parts of the party's platform"
(Hloušek and Kopeček 2008, 543--44), and on the basis of its evident
ethno-nationalism we've coded it FR. While the SNS was a highly
leader-centric structure and communication strategy (Haughton, Rybář,
and Deegan-Krause 2021, 334), and was clearly attached to Slota's
"boorish behaviour" under his leadership (Haughton, Rybář, and
Deegan-Krause 2021, 331; Učeň and Gyárfášová 2021, 289), it also had a
relatively strong base that evidently withstood a number of leadership
changes since its creation (Rybář and Spáč 2020, 643--44). We've
therefore coded it 2 on CHARISMA.

The SNS is somewhat difficult on the subject of liberal democratic
norms. The best reason to code it above 1 on this register is its
occasional celebration of the fascist World War II era Sovak President
Jozef Tiso (Slota proposed a commemorative plaque to Tiso in 2000,
Haughton 2001, 752). Aside from that, Slota has used violent language in
is solutions to Roma related problems (see above) (Haughton 2001, 753).
On more philosophical grounds, Abrahám claims that the SNS was hostile
to the principle of individual human rights (Abrahám 1995, 98). While
this is grounds to elevate the party beyond 1, we've not seen a lot of
evidence of other violations of liberal democratic norms such as actual
practices of violence or hostility to electoral or judicial democratic
institutions that would put it on per with other parties coded 3, and
hence we've coded the SNS 2 on LIBDEMNORMS for its time in the dataset.
Due to the SNS's role in the coalition government after the 1994
election, we've coded it 2 on INSIDER from 1998 onward.

## The Slovak Workers' Association

The Slovak Workers' Association (*Združenie robotníkov Slovenska*, ZRS)
was a left-wing party created by a former Party of the Democratic Left
(SDL) MP Ján Ľupták. Ľupták formed the ZRS (first as a civic
organisation in 1992 and then as a party in 1994) due to his frustration
with the SDL's failure to represent the interests of working people
(Haughton 2004, 186). The party took an impressive 7.3% in the 1994
elections, where it campaigned as an "unpredictable" protest party
(Abrahám 1995, 89). After that election it became a coalition partner of
the HZDS and SNS in government until 1998. Voters abandoned the party in
droves after this, in part due to the fact that Ľupták had promised not
to join any government (Wightman and Szomolänyi 1995, 613), and it won
only 1.3% in 1998. According to a number of sources, the party's time in
government dampened its anti-establishment themes (Spáč 2012, 244;
Stanley 2017), and it "lost its distinctive voice and its ability to
express anti-elite grievances" (Deegan-Krause and Haughton 2009, 830).

Appealing to the losers of Slovakia's transition to a market system
(Żarna 2018, 105), Ľupták and the ZRS crafted broad critique of the
entirety of the political class (Deegan-Krause 2007, 6), which it
accused of pursuing its own interests at the expense of ordinary people
(Stanley 2017). Corruption allegations against the political
establishment focused specifically on the sale of state assets (Abrahám
1995, 90; Ferencei 2020, 170). In Spáč's words:

> It defined itself as a politically and morally clean party with the
> goal of unifying the broader segments of society. The existing
> establishment was accused by the party of being egoistical and placing
> its own goals above general national and civic interest... From the
> beginning Ľupták's party positioned itself to exploit the tension
> between society and the elites, with society being seen as morally
> good, the elites as a stratum that had betrayed its trust. (Spáč 2012,
> 243)

Ľupták articulated this "anti-establishment" (Školkay and Žúborová 2019,
7) politics in a "demagogic" style (Żarna 2018, 105), at one point
demanding the "resignation of all deputies who have publicly humiliated
workers" (Ulč 1996, 348). On this evidence we've coded the party 3 on
OTH_POLCLASS.

Aside from the political class, the ZRS focused attacks on the emerging
economic elite that benefited from state privatisations (Nemčok and Spáč
2019, 767; Abrahám 1995, 90). According to Ulč, Ľupták was "an advocate
of class hatred" who claimed that he could "respect only those people
who built a house with their own hands" (Ulč 1996, 348) (OTH_FINANCIAL =
3). He was also critical of NATO, the EU and IMF (Bútora 1994, 53), and
alleged that the west would convert Slovakia into its colony (Ulč 1996,
348). However we've not seen evidence that this related in any way to
the party's domestic rivals, so we've labelled it 1 on OTH_FOREIGN.
We've seen no evidence of any discourse on the OTH_ETHNIC,
OTH_IMMIGRANT, or OTH_MILITARY variables (all = 1).

The literature considers the party "extreme left" (Wightman and
Szomolänyi 1995, 612), "far left" (Nemčok and Spáč 2019, 760), "radical
left" (Hloušek and Kopeček 2008, 537; Stanley 2017) "ultra leftist" (Ulč
1996, 348), or variations, owing to its clear opposition to market
reforms and privatisations (Nemčok and Spáč 2019, 761). We see no reason
to dispute this, and have coded it FL on LRPOSITION. The party had a
strong membership and ideological base, but was clearly centralised
around Ľupták in both organisation and image (Spáč 2012, 240). Some
scholars attribute a portion of the party's 1994 success to Ľupták
personal popularity (Haughton 2004, 186) (CHARISMA = 3). The closest
evidence we've found of violations of liberal democratic norms are
Ľupták's general criticisms of journalists (Carpenter 1997, 215), but
this is insufficient to be coded above 1 on LIBDEMNORMS. Ľupták did not
serve in government before 1994 (INSIDER = 1).

## Smer-SD

Smer (meaning "direction") was created by former SDL MP Robert Fico soon
after the 1998 election (Spáč and Havlík 2015, 5). It placed third in
2002 and continually increased its vote in successive elections, forming
a coalition government with the smaller HZDS and SNS in 2006, before
going back into opposition in 2010, and returning to government outright
in 2012. From 2006 onward, the party added the words "Social Democracy"
to its name ("Smer-SD"). After dominating Slovak politics for over a
decade, Fico was forced to resign in 2018 in the wake of mass protests
following the death of a journalist who had uncovered corruption in his
government (Weyland 2022, 26). After an initial non-ideological stance,
by 2006 the party adopted a clear left-wing position and focused on
socioeconomic issues in critique of the Dzurinda government's liberal
reforms (Hloušek and Kopeček 2008, 539), after which it moved into a
more ethno-centric nationalism while in government. Smer's vote declined
to 18% in the 2020 election under Fico's successor Peter Pellegrini.
Smer supported the candidacy of incumbent President Ivan Gašparovič in
the 2009 presidential election. However Gašparovič was an independent,
and never belonged to Smer, hence we have not included that election in
the dataset. Fico ran as Smer's candidate in the following 2014
election, which we have included. He lost in the second round to
independent Anrej Kiska with 40.6%.

There is no doubt that Fico and Smer were populist actors in the 2002
election, where it was "an avowedly anti-elite force" (Stanley 2011,
260), exercising "vitriolic personal attacks" on the incumbent
government and established parties (Haughton 2003b, 78; Spáč 2012,
236--37). This campaign considered the political elite to be fundamental
estranged from ordinary people, the latter having been "abandoned and
mistreated by the elite" (Stanley 2017). In Kim's words "In his creation
of the 'politicians' as an antagonist, he merged the current and former
governments 'part of the same corrupt power bloc that has alternated in
government and failed'" (Kim 2021, 241). As this implies, Fico did not
consider differences within the elite to be any more than superficial,
as all politicians were equally corrupt (Učeň 2007, 55; Deegan-Krause
and Haughton 2009, 830). He also considered this elite to be
fundamentally self-serving, deliberately placing their own interests
before those of the ordinary people (Učeň 2004, 55; Kim 2021, 240; Spáč
and Havlík 2015, 6). This was well-captured by the party's iconic slogan
from 2012: "as they stole under Mečiar, so they steal under Dzurinda"
(Spáč 2012, 245). However the party is somewhat more difficult to
classify from the 2006 election onward. Aside from its ideological shift
toward the left (see below), several sources claim that Fico and Smer
toned down personal attacks in the 2006 campaign (Haughton and Rybář
2008, 240), and even departed from a populist tone altogether (Stanley
2017, 247), especially after it was in power after 2006 (Spáč and Havlík
2015, 8; Školkay 2021, 7; Frič and Gyárfášová 2019, 237). However many
of these claims appear to be linked to the fact that Smer moved its
ideological profile from a "pure" populist force to a social-democratic
one by 2006 (which doesn't' disqualify or alter their anti-political
class populism by our definition), and other sources claim that Fico
maintained a populist discursive stance after Smer's post-2002 shift
(Učeň, Gyárfášová, and Krivý 2005, 44), and continued to do so while in
government (Deegan-Krause 2012, 197; Školkay 2021, 7). For these reasons
we've coded SMER 3 on OTH_POLCLASS in 2002 but reduced this to 2 from
2006 onward.

Fico and Smer have repeatedly supplemented their anti-elite populist
with a kind of "light" ethnonationalism (Stojarová 2018, 38) against
minorities and immigrants. The targeting of ethnic Hungarians and Roma
was present in 2002 (Haughton 2003b, 77; Mesežnikov 2008, 10; Rybář and
Spáč 2017, 154). In 2001 Fico alleged that the incumbent Dzurinda
government "assists Hungarians in their step-by-step coordinated
endeavor aimed at strengthening their position in Southern Slovakia from
the inside as well as from the outside" (Mesežnikov 2008, 20). He has
also criticised the "irresponsible growth irresponsible growth of the
Roma population" (Spáč and Havlík 2015, 6). Unlike the SNS, these appear
to be "forays" into ethno-centric rhetoric rather than core pillars
(Haughton 2003b, 77), and hence we've coded the party 2 on OTH_ETHNIC.
In the context of the 2015 refugee crisis, anti-immigration rhetoric --
specifically he labelling of migrants as an economically motivated
security threat -- "dominated" Smer's 2016 campaign (Rybář and Spáč
2017, 154; see also Gyárfášová and Hlatky 2023, 4). We've therefore
coded Smer 3 on OTH_IMMIGRANT from 2016 onward. Given that Fico's
anti-Hungarian rhetoric was targeted at both the ethnic Hungarians
living in Slovakia and the Hungarian state (Mesežnikov 2008), we've
coded Smer 2 on OTH_FOREIGN. Interestingly, though the party adopted a
left leaning economic policy alongside its anti-elite populism from
2006, we've not seen any evidence that economic elites or businesses
were targeted as "others" of the ordinary people in Smer's populist
rhetoric. In fact, according to Učeň (Učeň 2007, 56) Fico expressed an
admiration for private sector management, which he advocated for the
state (OTH_FINANCIAL = 1). We have also found no reference to the
military (OTH_MILITARY = 1).

Smer's ideological profile has been the subject of much discussion in
the literature. At its formation Fico positioned the party in a
post-ideological "third way" space that espoused "common sense" over the
ideologies of other parties (Kim 2021, 240--41; Spáč and Havlík 2015, 2;
Gyárfášová and Hlatky 2023, 4). Smer however is and always was a
somewhat nationalist party (Walter 2017, 176; Mesežnikov 2008;
Gyárfášová 2008), and one with a streak of conservative stances on
social and cultural issues (Gyárfášová and Hlatky 2023, 4). On the
balance of evidence it doesn't appear that these are quite salient
enough to consider it a fundamentally right leaning party, and hence the
vast majority of the literature considers Smer to be left-wing from 2006
onward (Stojarová 2018, 38; Hloušek and Kopeček 2008, 543; Gyárfášová
and Hlatky 2023, 4). From the available evidence it seems that its'
socio-economic policy was relatively mild (see Lang 2005, 11; Učeň 2007,
58), and hence we've coded it CL on LRPOSITION from 2006 onward, and C
in 2002

The literature clearly sees Fico as a dominant figure in the public
images and internal organisation of Smer (Gyárfášová and Hlatky 2023, 4;
Deegan-Krause and Haughton 2009, 831; Gyárfášová and Hlatky 2023, 4;
Haughton 2003b, 77; Haughton, Novotná, and Deegan-Krause 2011, 397;
Marušiak 2017, 185). In the words of Spáč and Havlík, "The party was
created as a sole act of its founder Robert Fico what was reflected in
its internal framework and processes. The original 'structure' of SMER
consisted only of chairman, general manager and a central executive
committee, however overshadowed by the party leader" (Spáč and Havlík
2015, 8) (CHARISMA = 3 2002-2016). This is more difficult to assess
under Pellegrini during the 2020 election, given that Fico remained the
party leader while Pellegrini was Prime Minister (Marušiak 2021). Even
with this shift, Fico played a "supportive role" (Haughton, Rybář, and
Deegan-Krause 2022, 742), and we've considered it hard to pain the party
as either 1 or 3 on CHARISMA in 2020 for this reason (= 2).

There are a number of reasons to claim that Fico and Smer threatened
liberal democratic norms in Slovakia, including their attacks on the
judiciary and open hostility to the media government (Stanley 2011,
259--60). However, in Deegan-Krause's words,

> Fico's populism did not coincide with a significant erosion of
> democracy. It is true that the Fico government interfered with the
> independence of the judiciary, imposed restrictions on the use of the
> Hungarian language, and exhibited significant corruption. But unlike
> Mečiar Fico did not pose a fundamental threat to Slovakia's basic
> democratic institutions (Deegan-Krause 2012, 197)

On this evidence we've coded Smer 2 on LIBDEMNORMS for its duration in
the dataset. We've also coded it 3 on INSIDER from 2010 on, after Fico's
first stint as Prime Minister 2009-2010 (note that Pellegrini was
incumbent Prime Minister in 2020).

## Ordinary People and Independent Personalities

Ordinary People and Independent Personalities (*Obyčajní ľudia a
nezávislé osobnosti*, OĽaNO) started off as civic association founded by
media mogul Igor Matovič that entered parliament in 2010 as a faction of
the Freedom and Solidarity (SaS) party (which we do not consider
populist -- see below). The group soon fell out with the SaS leadership
(which was part of the governing coalition) and registered as an
independent political party in late 2011. In the next two elections
(2012 & 2016) OĽaNO polled third place with 8.6% and 11% respectively.
As Matovič built a reputation as a flamboyant and effective
anti-corruption campaigner (Kazharski and Makarychev 2020, 183), OĽaNO
benefited most from the decline of Fico and Smer from 2018. In the 2020
election its vote rose to 25%, and Matovič became Prime Minister in a
coalition government with three smaller parties.

OĽaNO is frequently described as an "anti-establishment" party (Rybář
and Spáč 2017, 153; Engler, Pytlas, and Deegan-Krause 2019, 1322;
Kohutova and Horvat 2018, 21; Marušiak 2017, 192) and a "protest
movement" (Buzalka 2021, 1664; Školkay 2021, 12) with an "anti-party"
character (Kim 2021, 223; Rybář and Spáč 2020, 646; Hloušek, Kopeček,
and Vodová 2020, 103). The driving force behind its anti-establishment
narrative was its anti-corruption motif, which took the place of any
binding ideological agenda (Kazharski and Makarychev 2020, 182;
Stojarová 2018, 37). In contrast to the "evil" ways of its established
rivals (Hloušek, Kopeček, and Vodová 2020, 104), OĽaNO has, according to
Gyárfášová and Hlatky, "dedicated itself to being perceived as a direct
antithesis to political parties and establishment politics" (Gyárfášová
and Hlatky 2023, 4). A key element of this has been Matovič's elaborate
and performative style (Kazharski and Makarychev 2020, 181), which have
involved numerous publicity seeking stunts and crude language (Haughton,
Rybář, and Deegan-Krause 2022, 737). For example, he once emptied a bag
of fake banknotes in parliament to protest alleged corruption (Kazharski
and Makarychev 2020, 183). Built into this anti-establishment narrative
was the assertion that politicians were essentially a homogenous class
opposed pitted against ordinary people (Engler, Pytlas, and
Deegan-Krause 2019, 1323--24), and one whose main crime was being
"thieves" (Kohutova and Horvat 2018, 15): in one of its manifestos, for
example, it pledged that "property stolen by politicians we will return
to the people" (Haughton, Rybář, and Deegan-Krause 2022, 739; see also
Viera 2015, 105). This is clearly enough evidence to code the party 3 on
OTH_POLCLASS.

Beyond its hostility toward the political class, OĽaNO did not exibit
much rhetorical opposition to many other "Other" groups (Školkay 2021,
12). Matovič presented policies aimed at integration of Roma and
criticised the media for stereotypes in coverage of Roma issues
(Kohutova and Horvat 2018, 21). He also made a point of reminding voters
that one of OĽaNO's candidates was a Roma, and criticised the "fascism"
of the ĽSNS (Hloušek, Kopeček, and Vodová 2020, 108). We've seen no
evidence of other ethnocentric "othering" (OTH_ETHNIC = 1). The party
also did not engage in the anti-migrant politics of the 2015 crisis, and
were generally open to integrating migrants into society (Kohutova and
Horvat 2018, 19) (OTH_IMMIGRANTS = 1). Matovič considered Russia to be
the primary external threat to Slovakia (Kohutova and Horvat 2018, 21),
but not to the degree that would be considered on the OTH_FOREIGN scale
(= 1). We've also seen no evidence for OTH_MILITARY (= 1). One exception
here is economic elites, given that Matovič repeatedly claimed that
Slovakia had degenerated into an "oligarchic state" (Učeň and Gyárfášová
2021, 293), and contrasted OĽaNO to other parties due to the fact that
"no oligarch's stand behind us" (Učeň and Gyárfášová 2021, 293). This
however doesn't appear to have been as salient a part of the party's
rhetoric as its opposition to political elites, and we've coded OĽaNO 2
for OTH_FINANCIAL.

The initial literature on OĽaNO universally considers it to be a
non-ideological party (Rybář and Spáč 2020, 651; Kohutova and Horvat
2018, 14), and lacking in any clear policy agenda or program (Mihálik
2017, 13; Stojarová 2018, 37; Engler, Pytlas, and Deegan-Krause 2019,
1322). More recent sources claim that OĽaNO was "conservative" (Kim
2021, 223), this appears to relate more to the recruitment of Christian
and nationalist MPs into its ranks before the 2020 election (Buzalka
2021, 1658). These however appear to be factions among others (Just
2022, 167), and there appears to be nothing in Matovič's or OĽaNO's own
stances that are notably right of centre, and hence we've coded it C on
LRPOSITION.

All sources on OĽaNO state that Matovič's image dominated the party's
brand. Specifically, his "unconventional" (Gyárfášová and Hlatky 2023,
4) "unrestrained" (Kazharski and Makarychev 2020, 182), and "demagogic"
(Buzalka 2021, 1664) behaviour personified the party's image. In
Hloušek, Kopeček, and Vodová's words: "Matovič displayed an attractive
style of performance based on emotion and provocation. This political
entrepreneur offered no technocratic-managerial vision, but a radical,
uninhibited political performance" (Hloušek, Kopeček, and Vodová 2020,
101). Structurally, the party has had no real membership base of
organisation beneath Matovič (Školkay 2021, 13), and it has been called
an "owner party" (Marušiak 2017, 193), a "personalist" party (Weyland
2022, 37), and a "one man show" (Hloušek, Kopeček, and Vodová 2020).
This means that Matovič has been unrivalled within the party for
leadership (Rybář and Spáč 2020, 646). (CHARISMA = 3). We've seen no
evidence that OĽaNO as violated liberal democratic norms (on the
contrary, OĽaNO made point of distancing itself from anti-democratic
nature of more extreme populist parties, see: Kohutova and Horvat 2018,
23). Given that Matovič and was briefly a member of the governing
coalition 2010-12, we've coded OĽaNO 2 on INSIDER for each subsequent
election.

## People\'s Party - Our Slovakia (L'SNS)

People's Party -- Our Slovakia (*Ľudová Strana Naše Slovensko*, ĽSNS)
formed as a political party in 2010 under the leadership of Marian
Kotleba, a far right activist with a history of membership in neo-Nazi
movements (Harris 2019, 540). The party made breakthrough in 2016 on the
back of the 2015 migrant crisis (Kazharski and Makarychev 2020, 177),
when its vote escalated to 8% and it won 14 seats in parliament. It
maintained this level of support in 2020, though soon afterward Kotleba
was convicted of extremism and the party fell into disarray (Kevický
2022, 7).

The ĽSNS has consistently represented the political elite as a corrupt
"system" distinct from the "decent people" (Kazharski and Makarychev
2020, 180; see also Mihálik 2017; Struhár 2016, 28; Harris 2019, 541;
Cirner and Dudinská 2020, 185), and on this basis it has frequently been
considered anti-establishment (Engler, Pytlas, and Deegan-Krause 2019,
1323) and anti-elitist (Just 2022, 163) in the literature. Its central
campaign slogan in 2016, for example was "With Courage Against the
System" (Filipec 2017, 24). The party considered the political elite to
be essentially homogenous (Drábik 2022, 426) and to have "betrayed" the
people (Stefancik, Némethová, and Seresová 2021, 739; Mihálik 2017, 13),
by deliberately serving its own interests at the expense of the people
(Řádek 2019, 47). Its campaigns claimed therefore that it was "trying to
prevent further theft of Slovakia by politicians and parasites" (Řádek
2019, 48) (OTH_POLCLASS = 3).

ĽSNS was a fundamentally ethnonationalist party (Kim 2021, 223) that
viewed the people and their "others" in largely racial and ethnic terms
(Kazharski and Makarychev 2020, 180; Filipec 2017, 25). Its original
target for this rhetoric were Roma (Drábik 2022, 422; Kazharski 2019,
1), whom the party called "social parasites" (Struhár 2016, 28) and
practitioners of "Gypsy extremism" (Kazharski 2019, 1), who should be
subjected to "discipline" (Škobla and Filčák 2020, 786--87) or even
"cleansing" (Buzalka 2021, 1669). The party has also consistently
espoused anti-Semitism (Just 2022, 163; Harris 2019, 542; Kazharski
2019, 7), and since the migrant crisis has developed discourse harshly
critical of "inhuman" Islam (Kevický 2022, 7), and "violent Africans,
Turks and Asians" (Stefancik, Némethová, and Seresová 2021, 738)
(OTH_ETHNIC = 3). ĽSNS has discussed the threat of immigration as
"occupation" (Filipec 2017, 25), or potentially "national suicide"
(Stojarová 2018, 36). One campaign document said that "Europe is
inundated by an invasion of dangerous immigrants from Africa and Asia.
They attack, rob, rape and murder the indigenous people of European
countries every day" (Drábik 2022, 426) (OTH_IMMIGRANT = 3).

Alongside its ethno-nationalism, ĽSNS considered economic elites inside
and outside of the country to be an enemy of the people (Filipec 2017,
24; Buzalka 2021, 1669). The party's campaign discourse repeatedly
considered "oligarch's" as a part of the "system" (Kazharski 2019, 8)
who had "stolen" businesses in the privatisation process (Řádek 2019,
49). For example, one billboard stated "We will take from the oligarchs
and mafia and give to mothers, fathers, and pensioners!" (Buzalka 2021,
1671). Though perhaps not as salient as the party's opposition to ethnic
others and immigrants, this appears to be strong enough to code the
party 3 on OTH_FINANCIAL. Another aspect of the party's populism is its
opposition to Western foreign forces (Mesežnikov and Gyárfášová 2018,
85), whom it accuses of attempting to control and subordinate Slovakia.
It has called NATO a terrorist organisation (Řádek 2019, 48) and a
"criminal pact" (Filipec 2017, 24--25), and considered Slovakia's
membership in the EU akin to colonisation (Kazharski 2019, 8) due to the
latter's plan to "destroy us not only economically but also socially"
(Stefancik, Némethová, and Seresová 2021, 739; see also Kazharski 2019,
8; Buzalka 2021, 1671). It also considered the political class to be
controlled by outside forces such as, Zionists and international
financiers, who insert multiculturalism as part of a plot to replace
nation states with a single world government (see Kazharski 2019, 7--8;
Řádek 2019, 48) (OTH_FOREIGN = 3). We've seen no evidence of
OTH_MILITARY discourse (= 1).

Owing to the salience of ethno-nationalism in its ideological outlook,
ĽSNS has been universally classed as a "far right" (Stojarová 2018, 38),
or "neo-fascist" (Haughton, Rybář, and Deegan-Krause 2021, 331; Cirner
and Dudinská 2020; Gyárfášová and Hlatky 2023, 4; Frič and Gyárfášová
2019, 238), and "neo-Nazi" (Drábik 2022, 417) party. While its economic
program was clearly redistributionist, these or any other conventional
policy issues were barely mentioned in its campaign materials (Drábik
2022, 424) (LRPOSITION = FR). There is relatively little written about
the position of Kotleba in the party, but he has clearly played a
dominant role it its functioning and representation (Gyárfášová and
Hlatky 2023, 4). The party also added the name "Kotleba" to its official
title in 2015 to indicate this. While there is a case that the ĽSNS's
populism is less leader-centric than other parties, given Kotleba's
position in and control of the party we've coded it 3 on CHARISMA.

According to numerous analysts, in words and actions ĽSNS has mounted a
"denial of the fundamental principles and values of liberal democracy"
(Frič and Gyárfášová 2019, 238; see also Kazharski 2019, 2; Harris 2019,
538). The most notorious examples of this are the party's use of
uniformed "security patrols" on trains (Harris 2019, 542; Kazharski and
Makarychev 2020, 179), protecting "decent" people from "Gypsy
extremists" (Struhár 2016, 28). According to Kazharski and Makarychev,
these guards deliberately wore uniforms similar to those of the
nationalist militia active in Slovakia during the fascist wartime regime
of Josef Tiso (Kazharski and Makarychev 2020, 179). The party has also
pledged its affinity to the Tiso regime by parroting its slogans (Harris
2019, 538). As the party has never been a member of a governing
coalition, we've coded it 1 on INSIDER.

## We Are Family/Sme Rodina

We Are Family (*Sme Rodina*, SR) was created by *Boris Kollár, a
controversial businessman with a "*tabloid celebrity profile*" in 2015*
(Frič and Gyárfášová 2019, 238)*. It won 6.6% of the vote in the
subsequent 2016 elections, which increased to 8.24 in 2020. Kollár and
SR maintained an anti-establishment* (Rybář and Spáč 2017, 155) *and
anti-elite narrative that emphasised the untrustworthiness of the
political system* (Mihálik 2017, 17)*, which he accused of endemic
corruption* (Školkay and Žúborová 2019, 8; Stojarová 2018, 38). SR
conceived of politicians as a distinct and unified class who stood
against the ordinary people's interests, as is well-captured in its most
memorable slogan form 2016: "I *don't vote for politicians, I vote for
Boris"* (Marušiak 2017, 193) (OTH_POLCLASS = 3).

Aside from its antagonism to the political elite, SR's main campaign
issue was its opposition to immigrants (Školkay and Žúborová 2019, 8),
particularly Muslims, whom the party considered a danger to "our
culture, religion and freedom, including our homes and families"
(Mihálik 2017, 14; Marušiak 2017, 193)*. We've therefore coded it 3 for
both OTH_ETHNIC and OTH_IMMIGRANT.* SR was also strongly opposed to the
European Union (Stojarová 2018, 38), which Kollár called "Euro-rubbish"
and the "Brussels elite" (Školkay and Žúborová 2019, 13--15). While this
foreign "other" was clearly an enemy of the people in SR's rhetoric, it
does not seem to be the case that it was considered to control the
domestic elite (OTH_FOREIGN = 2). Despite Kollár's own history as a
businessperson, he and SR campaigned against financial interests and
"oligarchs" influencing the political system (Mihálik 2017, 14;
Stojarová 2018, 38). In one video he accused the political elite of
"sponsoring grand capital with cheap labour" (Školkay and Žúborová 2019,
16). We've therefore coded SR 3 on OTH_FINANCIAL. We've seen no evidence
of any opposition to the military (OTH_MILITARY = 1).

SR is somewhat difficult to define ideologically (Frič and Gyárfášová
2019, 238). On face value, it campaigned without any clear ideology
(Mihálik 2017, 13), and Kollár frequently emphasised his aversion to any
ideological label (Marušiak 2017, 193). The policies of the party are
somewhat eclectic (Školkay and Žúborová 2019, 13). On the one hand its
opposition to oligarchs and embrace of support for low-income people
(Rybář and Spáč 2017, 155; Engler, Pytlas, and Deegan-Krause 2019, 1324)
suggest a left-leaning position. On the other, the party is more
frequently associated with the right owing to the centrality of its
anti-immigrant nativism (Kim 2021, 223), its social conservativism
(Marušiak 2017, 193; Gyárfášová and Hlatky 2023, 4), and its national
conservativism (Just 2022, 167). Owing to the perceived salience of the
latter issues in its campaigns we've coded it R on LRPOSITION, but this
could be revisited.

SR was built around Kollár's image, to the extent that it has been
classed as an "entrepreneurial" party (Frič and Gyárfášová 2019, 238),
and an "electoral vehicle" for its leader (Gyárfášová and Hlatky 2023,
4). The literature suggests that the party depended totally on Kollár's
charisma (Marušiak 2017, 193; Učeň and Gyárfášová 2021, 290; Školkay and
Žúborová 2019, 8) (CHARISMA = 3). The literature does not suggest that
SR threatened liberal democratic norms in Slovakia (Školkay and Žúborová
2019, 16) (LIBDEMNORMS = 1), and Kollár had not featured in government
prior to the 2016 or 2020 elections (INSIDER = 1).

## Not Included

There are several parties that have been occasionally considered
populist in the literature which we have not included in the dataset.
**The Party of Civic Understanding (*Strana občianskeho porozumenia*,
SOP)** emerged before the 1998 elections under the leadership of Rudolf
Schuster. It also offered a broad critique of the political class
(Stanley 2017, 149), due to which it has been considered populist in
some of the literature (Učeň 2004, 52; Spáč 2012, 17). However its main
criticism of the elite was less about moral failures and more about its
inability to work together (Marušiak 2017, 184), and it based its
campaigns on the proposition of a "national understanding" to bring all
parties together (Učeň, Gyárfášová, and Krivý 2005, 32). Any element of
anti-elite populism was also lost after it joined formed the coalition
government in 1998 (Deegan-Krause and Haughton 2009, 830--31). On the
available evidence we've not considered SOP populist by our definition.

**New Citizens Alliance (ANO)** was a personal vehicle of powerful media
mogul Pavol Rusko, who launched the party to advocate for liberalisation
of the economy before the 2002 elections. ANO has occasionally been
considered among populist parties in Slovakia (Učeň 2004, 59--60), owing
to what seems to have been a present but quite mild opposition to the
political elite (Spáč 2012, 237 (Spáč 2012, 237; Stanley 2017, 149), and
its allegation of improper links between politicians and economic elites
(Učeň, Gyárfášová, and Krivý 2005, 36). However other scholars have
questioned its degree of populism (Kim 2021, 244; Školkay 2021, 11), and
according to most literature that we've seen there is not quite enough
rhetoric in line with our definition to warrant its including in the
dataset. For example, according to Učeň, ANO "focused on criticizing
incompetence rather than chastising the elite for its moral failings"
(Učeň 2004, 59--60).

**Freedom and Solidarity (*Sloboda a Solidarita*, SaS)** was a sort
lived anti-immigrant and anti-EU party led by Richard Sulík that has
also been included in the broad discussions of Slovak populism. There
are some sources that claim SaS practiced an "anti-establishment
rhetoric" (Marušiak 2017, 191), but this is not consistent enough in the
literature to consider them populist by our standards.

## References

Abrahám, Samuel. 1995. "Early Elections in Slovakia: A State of
Deadlock." *Government and Opposition* 30 (1): 86--100.

Barański, Marek. 2020. "The Political Party System in Slovakia in the
Era of Mečiarism. The Experiences of the Young Democracies of Central
European Countries." *Eastern Review*, no. 9: 33--48.

Bútora, Martin. 1994. "Slovakia Still at the Crossroads? Contrasting
Signals from the Early Elections in Slovakia." *Perspectives*, no. 4:
53--60.

Bútora, Martin, and Zora Bútorová. 1993. "Slovakia after the Split."
*Journal of Democracy* 4 (2): 71--83.

Buzalka, Juraj. 2021. "Village Fascists and Progressive Populists: Two
Faces of the Countermovement in Slovakia." *Europe-Asia Studies* 73 (9):
1658--82. https://doi.org/10.1080/09668136.2021.1978934.

Carpenter, Michael. 1997. "Slovakia and the Triumph of Nationalist
Populism." *Communist and Post-Communist Studies* 30 (2): 205--19.

Cirner, Michal, and Irina Dudinská. 2020. "The Entry of an Extreme Right
Party into the Slovak Parliament after the 2016 and 2020 Elections: The
Return of Fascists?" *Balkan Social Sciences Review* 16: 175--97.

Deegan-Krause, Kevin. 2007. "Populism and the Logic of Party Rotation in
Postcommunist Europe." *Visegrad Elections: Domestic Impact and European
Consequences. Bratislava: Institute for Public Affairs (IVO)*, 141--59.

---------. 2012. "Populism, Democracy, and Nationalism in Slovakia." In
*Populism in Europe and the Americas: Threat or Corrective for
Democracy*, edited by Cas Mudde and Cristóbal Rovira Kaltwasser,
182--204. Cambridge: Cambridge University Press.

Deegan-Krause, Kevin, and Tim Haughton. 2009. "Toward a More Useful
Conceptualization of Populism: Types and Degrees of Populist Appeals in
the Case of Slovakia." *Politics & Policy* 37 (4): 821--41.

Drábik, Jakub. 2022. "'With Courage against the System.' The Ideology of
the People's Party Our Slovakia." *Journal of Contemporary Central and
Eastern Europe* 30 (3): 417--34.

Engler, Sarah, Bartek Pytlas, and Kevin Deegan-Krause. 2019. "Assessing
the Diversity of Anti-Establishment and Populist Politics in Central and
Eastern Europe." *West European Politics* 42 (6): 1310--36.

Evans, Geoffrey, and Stephen Whitefield. 1998. "The Structuring of
Political Cleavages in Post-Communist Societies: The Case of the Czech
Republic and Slovakia." *Political Studies* 46 (1): 115--39.

Ferencei, Lucia. 2020. "The Ethnopolitics of the HZDS-SNS-ZRS Coalition
Government in Slovakia from 1994 to 1998." *Border and Regional Studies*
8 (4): 161--85.

Filipec, Ondřej. 2017. "People's Party - Our Slovakia: An Anti-System
Party?" In *Current Trends and Public Administration*, 21--30. Uherské
Hradiště: FSV UCM Uherské Hradiště.

Frič, Pavol, and Ol'ga Gyárfášová. 2019. "The Rise of the Politics of
Emotions: Anti-Elitism and Anti-Corruptism as Traits of Czech and Slovak
Populist Parties." *Politické Vedy*, no. 4: 221--46.

Gyárfášová, Oľga. 2008. "National Populism in Slovakia: Political
Attitudes and Views of the Public." In *National Populism in Slovakia*,
by Grigorij Mesežnikov and Oľga Gyárfášová, 35--50. Working Papers.
Bratislava: Institute for Public Affairs.

Gyárfášová, Oľga, and Roman Hlatky. 2023. "Personalized Politics:
Evidence from the Czech and Slovak Republics." *Electoral Studies* 81
(February): 102567. https://doi.org/10.1016/j.electstud.2022.102567.

Harris, Erika. 2019. "Nation before Democracy? Placing the Rise of the
Slovak Extreme Right into Context." *East European Politics* 35 (4):
538--57.

Haughton, Tim. 2001. "HZDS: The Ideology, Organisation and Support Base
of Slovakia's Most Successful Party." *Europe-Asia Studies* 53 (5):
745--69.

---------. 2003a. "Facilitator and Impeder: The Institutional Framework
of Slovak Politics during the Premiership of Vladimír Mečiar." *Slavonic
and East European Review* 81 (2).

---------. 2003b. "'We'll Finish What We've Started': The 2002 Slovak
Parliamentary Elections." *Journal of Communist Studies and Transition
Politics* 19 (4): 65--90.

---------. 2004. "Explaining the Limited Success of the
Communist-Successor Left in Slovakia: The Case of the Party of the
Democratic Left (SDL')." *Party Politics* 10 (2): 177--91.

Haughton, Tim, Tereza Novotná, and Kevin Deegan-Krause. 2011. "The 2010
Czech and Slovak Parliamentary Elections: Red Cards to the 'Winners.'"
*West European Politics* 34 (2): 394--402.

Haughton, Tim, and Marek Rybář. 2008. "A Change of Direction: The 2006
Parliamentary Elections and Party Politics in Slovakia." *Journal of
Communist Studies and Transition Politics* 24 (2): 232--55.

Haughton, Tim, Marek Rybář, and Kevin Deegan-Krause. 2021. "Leading the
Way, but Also Following the Trend: The Slovak National Party." *Politics
and Governance* 9 (4): 329--39. https://doi.org/10.17645/pag.v9i4.4570.

---------. 2022. "Corruption, Campaigning, and Novelty: The 2020
Parliamentary Elections and the Evolving Patterns of Party Politics in
Slovakia." *East European Politics and Societies* 36 (3): 728--52.
https://doi.org/10.1177/08883254211012765.

Hloušek, Vít, and Lubomír Kopeček. 2008. "Cleavages in the Contemporary
Czech and Slovak Politics between Persistence and Change." *East
European Politics and Societies* 22 (3): 518--52.

Hloušek, Vít, Lubomír Kopeček, and Petra Vodová. 2020. "Two Tycoons and
Their One-Man Shows." In *The Rise of Entrepreneurial Parties in
European Politics*, edited by Vít Hloušek, Lubomír Kopeček, and Petra
Vodová, 93--117. Palgrave Studies in European Political Sociology. Cham:
Springer International Publishing.
https://doi.org/10.1007/978-3-030-41916-5_4.

Just, Petr. 2022. "Toward Exclusion or Inclusion? Acceptance and
Perception of National Populist Parties in Slovakia: The Case Study of
the Kotlebists-Peoples Party Our Slovakia (SNS)." In *The Rise of
Populism in Central and Eastern Europe*, 160--72. Edward Elgar
Publishing.

Karabová, Denisa, and Ondřej Filipec. 2018. "The Europeanization of
Slovak Political Parties: The Case of Smer-Social Democracy, the Slovak
National Party and Most-Híd." *Contemporary European Studies*, no. 2.

Kazharski, Aliaksei. 2019. "Frontiers of Hatred? A Study of Right-Wing
Populist Strategies in Slovakia." *European Politics and Society*, no.
DOI: 10.1080/23745118.2019.1569337.

Kazharski, Aliaksei, and Andrey Makarychev. 2020. "Populism in Estonia
and Slovakia: Performances, Transgressions, and Communicative Styles."
*Populism* 3 (2): 165--85.

Kevický, Dominik. 2022. "Where Is the Populist Radical Right Successful?
Spatial Analysis of Populist Radical Right Parties in Slovakia and
Czechia." *Eurasian Geography and Economics* 0 (0): 1--22.
https://doi.org/10.1080/15387216.2022.2151485.

Kim, Seongcheol. 2021. *Discourse, Hegemony, and Populism in the
Visegrád Four*. London: Routledge.
https://doi.org/10.4324/9781003186007.

Kohutova, Maria, and Mateja Horvat. 2018. "Populism in Old and New
Democracies: Comparative Analysis of True Finns, Sweden Democrats, ANO
and OL'aNO." *Mali Levijatan: Studentski Časopis Za Politologiju* 5 (1):
3--33.

Lang, Kai-Olaf. 2005. "Populism in Central and Eatsern Europe-A Threat
to Democracy or Just Political Folklore?" *Slovak Foreign Policy
Affairs* 6 (01): 6--16.

Marušiak, Juraj. 2017. "Political Entrepreneurs as a Challenge for the
Party System in Slovakia." *Politologickỳ Časopis-Czech Journal of
Political Science* 24 (2): 179--200.

---------. 2021. "'Slovak, Not Brussels Social Democracy':
Europeanization/De-Europeanization and the Ideological Development of
Smer-SD Before 2020 Parliamentary Elections in Slovakia\*."
*Politologický Časopis - Czech Journal of Political Science* 28 (1):
37--58.

Menzies, Catriona. 2004. *Meciarism and the HZDS (Movement for a
Democratic Slovakia), 1992-1998: The Ideology of a Post-Communist
Political Party*. University of London, University College London
(United Kingdom).

Mesežnikov, Grigorij. 2008. "National Populism in Slovakia: Actors,
Issues, Strategies." In *National Populism in Slovakia*, by Grigorij
Mesežnikov and Oľga Gyárfášová, 7--34. Working Papers. Bratislava:
Institute for Public Affairs.

Mesežnikov, Grigorij, and Ol'ga Gyárfášová. 2018. "Explaining Eastern
Europe: Slovakia's Conflicting Camps." *Journal of Democracy* 29 (3):
78--90.

Mihálik, Jaroslav. 2017. "The Electoral Aftermath: New Wave Populism and
Radicalism in Slovakia." In *Current Trends and Public Administration*,
9--20. Uherské Hradiště: FSV UCM Uherské Hradiště.

Nemčok, Miroslav, and Peter Spáč. 2019. "Referendum as a Party Tool: The
Case of Slovakia." *East European Politics and Societies* 33 (3):
755--77.

Pinterič, Uroš, and Viera Žúborová. 2014. "Party Arenas in Slovenia and
Slovakia." *Društvena Istraživanja: Časopis Za Opća Društvena Pitanja*
23 (2): 349--68.

Pytlas, Bartek. 2013. "Radical-Right Narratives in Slovakia and Hungary:
Historical Legacies, Mythic Overlaying and Contemporary Politics."
*Patterns of Prejudice* 47 (2): 162--83.

Řádek, Miroslav. 2019. "Election Program of Political Party
Kotleba--People's Party Our Slovakia'." *University Review* 13 (1):
46--50.

Rybář, Marek, and Peter Spáč. 2017. "The March 2016 Parliamentary
Elections in Slovakia: A Political Earthquake." *Electoral Studies* 45:
153--56.

---------. 2020. "Social Origin Is No Destiny: Background,
Institutionalization, and Electoral Performance of New Political Parties
in Slovakia." *East European Politics and Societies* 34 (3): 637--62.

Scheiring, Gábor. 2021. "Varieties of Dependency, Varieties of Populism:
Neoliberalism and the Populist Countermovements in the Visegrád Four."
*Europe-Asia Studies* 73 (9): 1569--95.

Sekerák, Marián. 2019. "Towards Conservatism? Party Politics in Slovakia
at the End of the 2010s." *European View* 18 (2): 233--41.

Škobla, Daniel, and Richard Filčák. 2020. "Mundane Populism: Politics,
Practices and Discourses of Roma Oppression in Rural Slovakia."
*Sociologia Ruralis* 60 (4): 773--89.

Školkay, Andrej. 2021. "Impact of Populism on the Party System in
Slovakia 2000--2020." Background Study for DEMOS H2020 Project (February
2021).

Školkay, Andrej, and Viera Žúborová. 2019. "Populist Political Movement
Sme Rodina--Boris Kollár (We Are a Family--Boris Kollár)."
*Środkowoeuropejskie Studia Polityczne*, no. 4: 5--26.

Spáč, Peter. 2012. "Populism in Slovakia." In *Populist Political
Parties in East Central Europe*, edited by Vlastimil Havlík and Aneta
Pinková, 227--58. Brno: Munipress.

Spáč, Peter, and Vlastimil Havlík. 2015. "Overcoming the Danger of
Incumbency: The Case of Smer Party in Slovakia." In *ECPR General
Conference in Montreal*.

Stanley, Ben. 2011. "Populism, Nationalism, or National Populism? An
Analysis of Slovak Voting Behaviour at the 2010 Parliamentary Election."
*Communist and Post-Communist Studies* 44 (4): 257--70.

---------. 2017. "Populism in Central and Eastern Europe." *The Oxford
Handbook of Populism* 1 (6): 140--58.

Stefancik, Radoslav, Ildikó Némethová, and Terézia Seresová. 2021.
"Securitisation of Migration in the Language of Slovak Far-Right
Populism." *Migration Letters* 18 (6): 731--44.

Stojarová, Věra. 2018. "Populist, Radical and Extremist Political
Parties in Visegrad Countries Vis à Vis the Migration Crisis. In the
Name of the People and the Nation in Central Europe." *Open Political
Science* 1 (1): 32--45.

Struhár, Pavol. 2016. "Solution of Roma Issue by Slovak Far Right
Parties in Parliamentary Elections 2016." *University Review* 10 (1):
26--29.

Učeň, Peter. 2004. "Centrist Populism as a New Competitive and
Mobilization Strategy in Slovak Politics." *Party Government in
Slovakia: Experience and Perspectives*, 45--73.

---------. 2007. "Parties, Populism, and Anti-Establishment Politics in
East Central Europe." *The SAIS Review of International Affairs* 27 (1):
49--62.

Učeň, Peter, and Ol'ga Gyárfášová. 2021. "Parties and Linkages in the
Slovak Party System: An Overview." *Politics in Central Europe* 17 (2):
273--95.

Učeň, Peter, Oľga Gyárfášová, and Vladimír Krivý. 2005. "Centrist
Populism in Slovakia from the Perspective of Voters and Supporters."
*Slovak Foreign Policy Affairs* 6 (1): 28--46.

Ulč, Otto. 1996. "Czechoslovakia's Velvet Divorce." *East European
Quarterly* 30 (3): 331--52.

Van Duin, Pieter, and Zuzana Poláč ková. 2000. "Democratic Renewal and
the Hungarian Minority Question in Slovakia." *European Societies* 2
(3): 335--60. https://doi.org/10.1080/146166900750036303.

Viera, Žúborová. 2015. "Newcomers in Politics? The Success of New
Political Parties in the Slovak and Czech Republic after 2010?" *Baltic
Journal of Law & Politics* 8 (2): 91--111.

Walter, Aaron T. 2017. "The Good, Bad, and Ugly of Populism: A
Comparative Analysis of the US and Slovakia." *Slovak Journal of
Political Sciences* 17 (2).

Weyland, Kurt. 2022. "How Populism Dies: Political Weaknesses of
Personalistic Plebiscitarian Leadership." *Political Science Quarterly*
137 (1): 9--42.

Wightman, Gordon, and Soňa Szomolänyi. 1995. "Parties and Society in
Slovakia." *Party Politics* 1 (4): 609--18.

Żarna, Krzysztof. 2018. "Towards Authoritarianism. Internal Situation in
the Slovak Republic (1994-1998)." *Przegląd Politologiczny*, no. 4:
103--15.

