---
title: Sweden
---


-   Date range: 1980-2020

-   Elections included:

    -   Legislative: 1982, 1985, 1988, 1991, 1994, 1998, 2002, 2006,
        2010, 2014, 2018.

## New Democracy

New Democracy (*Ny Demokrati*, ND) was founded in 1991 by author Ian
Wachtmeister and amusement park director Bernt Karlsson, both of whom
were established media personalities (Betz n.d., 7). ND's populism
originally had a festive, parody quality (A. Widfeldt 2000, 494) that
argued that "life must be more fun" (Betz n.d., 7). The party had a
strong opposition to the political class (built in part on
Wachmeister\'s books ridiculing politicians and bureaucrats) and its
anti-establishment credentials were evidently a significant part of its
appeal to voters (Rydgren 2008, 137) (OTH_POLCLASS = 3). It was quite
dependent on the leadership of Wachtmaister and Karlsson (Taggart 1995,
41; Wörlund 1992, 138) (CHARISMA = 3), and collapsed electorally after
their leadership splintered.

While ND's ideology was somewhat ambiguous (leading to splits in its
eventual caucus) it should generally be regarded as right wing during
campaigns (A. Widfeldt 2000, 495; Klein 2013, 116) (LR_POSITION = R).
This included campaigning against immigration and for liberal economic
reforms (Rydgren 2002, 34). Notably it was pro-Europe. Several of its
candidates gained media attention for saying racist things through the
campaign, and the party platform linked immigration to crime (A.
Widfeldt 2000, 495). However according to Betz, the party's immigration
rhetoric was both moderate (in terms of policy proposals) and
economically based (as opposed to culturally or racially based) (Betz
n.d., 121). We've coded it 2 on OTH_IMMIGRANTS and 1 on OTH_ETHNIC.
We've seen no evidence of anything on the OTH_FINANCIAL or OTH_ECONOMIC
variables (both = 1).

Neither leader had been involved in previous governments (INSIDER = 1),
and the party did not violate liberal democratic norms as far as we can
tell (LIBDEMNORMS = 1).

## Sweden Democrats 

Sweden Democrats (*Sverigedemokraterna*, SD) is a nativist
anti-immigration and anti-Islam party, founded in the late 1980s. The
party has a legacy in the neo-Nazi movement, with several of its
founders being previous members of far-right parties (Anders Widfeldt
2008; Klein 2013, 117). From the mid-1990s the SD sought to detoxify its
image and associate itself with other populist right parties in Europe
rather than the anti-democratic and violent fringe (Rydgren 2008, 146;
Anders Widfeldt 2008; Klein 2013, 117) -- although not to the degree
that is should be considered less than far-right on LRPOSITION. The
party first passed 5% of the vote in 2010 (5.7%) under the leadership of
Jimmie Åkesson. It's vote share has consistently increased, peaking at
17.5 in the 2017 election.

SD;s stated aim is to protect Sweden's culture and welfare state from
uncontrolled immigration, in particular from Muslim immigrants
(Hellström and Hervik 2014). The party has a history of advocating
repatriation of some immigrants (Anders Widfeldt 2008, 272), and in one
2010 election advertisement, the party showed a Swedish pensioner being
overtaken by women in Burqas in the line to get to the social security
office, with the tagline "Pensions or immigration: the choice is yours"
(Klein 2013, 121) (OTH_IMMIGRANT = 3, OTH_ETHNIC = 3). In this sense,
the party is a textbook case of welfare chauvinism (Norocel 2016),
claiming to be the ideological air of the original social democratic
tradition that Swedes are proud of (Hellström, Nilsson, and Stoltz 2012,
196). This nativist ideology has always been presented in an overtly
anti-establishment attitude (Rydgren 2008, 147), with the party claiming
to represent the views of common people over a privileged political
elite in which all other parties are essentially homogenous (Rydgren
2008, 148; Hellström, Nilsson, and Stoltz 2012, 201). In Hellström *et
al*'s words, "the SD portrays Swedish politics as an elite consensual
affair with a distorted link to the people, arguing that the democratic
system is bureaucratized and only serves the interests of the political
elite" (Hellström, Nilsson, and Stoltz 2012, 201) (OTH_POLCLASS = 3).
The SD is also hostile to the influence of the EU, and the cultural
influence of the USA (Rydgren 2008, 147), although not quite to the
point that these are principle 'others' of its populism (OTH_FOREIGN =
2).

Åkesson has led the party since 2005, and while he seems to have been an
effective re-brander of the party in its continued moderation (Anders
Widfeldt 2008, 271), his leadership does not seem to be relevant to the
point of our CHARISMA variable (= 1). According to Widfeldt the party
has always pledged its loyalty to the procedures of liberal democracy
(Anders Widfeldt 2008, 272--73). This could be debated given the party's
fascist pedigree (see Rydgren 2008, 148--49 for a sceptical view) but
for now we've left LIBDEMNORMS at 1. The party and its leaders have
never been in government (INSIDER = 1).

**References**

Betz, Hans-Georg. n.d. *Radical Right-Wing Populism in Western Europe*.
Palgrave Macmillan. Accessed 6 July 2019.
https://www.palgrave.com/gp/book/9780312083908.

Hellström, Anders, and Peter Hervik. 2014. 'Feeding the Beast:
Nourishing Nativist Appeals in Sweden and in Denmark'. *Journal of
International Migration and Integration* 15 (3): 449--67.
https://doi.org/10.1007/s12134-013-0293-5.

Hellström, Anders, Tom Nilsson, and Pauline Stoltz. 2012. 'Nationalism
vs. Nationalism: The Challenge of the Sweden Democrats in the Swedish
Public Debate'. *Government and Opposition* 47 (2): 186--205.
https://doi.org/10.1111/j.1477-7053.2011.01357.x.

Klein, Andreas. 2013. 'The End of Solidarity? On the Developement of
Right-Wing Populist Parties in Denmark and Sweden'. In *Exposing the
Demagogues: Right Wing and National Populist Parties in Europe.*, edited
by Karsten Grabow and Florian Hartleb, 105-131. Bruessels and Berlin,
Centre for European Studies and the Konrad Adenauer Stiftung.

Norocel, Ov Cristian. 2016. 'Populist Radical Right Protectors of the
Folkhem: Welfare Chauvinism in Sweden'. *Critical Social Policy* 36 (3):
371--90. https://doi.org/10.1177/0261018315621991.

Rydgren, Jens. 2002. 'Radical Right Populism in Sweden: Still a Failure,
But For How Long?' *Scandinavian Political Studies* 25 (December):
27--56. https://doi.org/10.1111/1467-9477.00062.

---------. 2008. 'Sweden: The Scandanavian Exception'. In *Twenty-First
Century Populism: The Spectre of Western European Democracy*, edited by
Daniele Albertazzi and Duncan McDonnell, 135--50. Basingstoke: Palgrave
Macmillan.

Taggart, Paul. 1995. 'New Populist Parties in Western Europe'. *West
European Politics* 18 (1): 34--51.
https://doi.org/10.1080/01402389508425056.

Widfeldt, A. 2000. 'Scandinavia: Mixed Success for the Populist Right'.
*Parliamentary Affairs* 53 (3): 486--500.
https://doi.org/10.1093/pa/53.3.486.

Widfeldt, Anders. 2008. 'Party Change as a Necessity -- the Case of the
Sweden Democrats'. *Representation* 44 (3): 265--76.
https://doi.org/10.1080/00344890802237031.

Wörlund, Ingemar. 1992. 'The Swedish Parliamentary Election of September
1991'. *Scandinavian Political Studies* 15 (2): 135--43.
https://doi.org/10.1111/j.1467-9477.1992.tb00135.x.

