---
title: Switzerland
---


-   Date range: 1980-2020

-   Elections included:

    -   Legislative: 1983, 1987, 1991, 1995, 1999, 2003, 2007, 2011,
        2015, 2019.

## Swiss Auto Party

The Swiss Auto Party (*Autopartei der Schweiz,* APS), was founded in
1985 by economic consultant and lawyer Michael Dreher to oppose
environmentally conscious state interventions in the ives of citizens
and the elite "do-gooders" who push them (Church 1989, 118). It soon
expanded beyond its narrow focus on the interests of motorists to
espouse a broad neo-liberalism and harsh opposition to immigration
(Skenderovic 2007, 165). It achieved its best result in in the 1991
national elections with 5.1% of the vote. Soon after this it changed its
name to the Freedom Party of Switzerland (*Freiheits-Partei der
Schweiz*), but most of its supporters migrated to the SVP after that
party's move to the right in the late 1990s. It did not pass 5% after
1991.

Further to opposing state intervention in the ideological sense, the APS
campaigned with "vehement and vocal hostility" towards established
parties (Betz 1994, 21), accusing the entire "political class" of being
"degenerate" and "wrecked" (cited in Skenderovic 2009, 110)
(OTH_POLCLASS = 3). In Skenderovic's words:

> The populist nature of the APS/FPS was clear to see in the party's
> consistent strategy of evoking resentment and mistrust towards
> government, state administration and the party system. It was clear
> that the party perceived an antagonistic relationship between the
> political establishment and 'the people', whom they saw as being
> betrayed by government, politicians and other political parties
> (Skenderovic 2009, 109).

Beyond its neo-liberal resistance to state intervention, the APS's
policy platform was its opposition to immigration (Kobach 1993, 356).
The party alleged that a "flood" of refugees were seeking asylum in
Switzerland for economic reasons rather than persecution, and that they
constituted a drain on state resources (Betz 1994, 121) (OTH_IMMIGRANTS
= 3). The nature of these attacks have been considered xenophobic by
many (Husbands 2000, 507; Skenderovic 2007, 170), as they particularly
targeted non-European migrants (Betz 1994, 121), who allegedly
threatened to "makes us Swiss strangers in our own country" (Skenderovic
2009, 111). We've coded APS 3 on OTH_ETHNIC, although there may be a
case to leave it at 2. We've seen no evidence for OTH_FINACIAL or
OTH_MILITARY (both = 1), and although the party opposed European
integration, the literature does not emphasise that any OTH_FOREIGN
rhetoric was a significant part of its discourse (= 1).

Although the party was programmatically thin (Betz 1994, 108), its
neo-liberalism and strong nativism make it clearly a part of the far
right (LRPOSITION = FR). Skenderovic claims that "The APS/FPS was not
characterised by strong leadership, nor was the party led by an
uncontested, charismatic leader" (Skenderovic 2009, 108) (CHARISMA = 1),
and we've seen no evidence that it was a fundamental threat to liberal
democratic norms in Switzerland (LIBDEMNORMS = 1). Neither Dreher nor
the party had served in government before the 1991 election (INSIDER =
1).

## Swiss People's Party

The Swiss People's Party (*Schweizerische Volkspartei*, SVP) traces its
roots to various agrarian and conservative movements in the twentieth
century. From the 1950s it and its predecessor have been one of the
parties included in the "magic formula" of power sharing on the Swiss
federal council (McGann and Kitschelt 2005, 153). Most scholarship
considers the party to be mainstream conservative and non-populist for
most of this time (Mazzoleni 2013, 237; Bernhard 2017, 514). The rise of
Christoph Blocher and his Zurich-based wing of the party changed this
(Marcus 2000, 36). Given the traditionally decentralised nature of Swiss
parties it is difficult to pinpoint the exact moment that the party
should be collectively characterised by Blocher's distinct populist
rhetoric, but the best option seems to be the 1999 federal election
(Rose 2000, 36), when Blocher's emergence as its undisputed figurehead
saw it's vote increase dramatically to 22.5% from 14.9% in the previous
election. The SVP has received approximately 25-30% in each subsequent
election. We've therefore included he SVP from 1999 -- 2019.

Under Blicher's leadership, the SVP adopted "virulent" rhetoric against
its rivals which converted it into a party of protest against the
broader political establishment (Church 1996b, 642; 2000, 224). Further
to it being incompetent, the political class was described by Blocher to
be untrustworthy (Church 2000, 217--18), and to have betrayed ordinary
Swiss voters (Bernhard, Kriesi, and Weber 2015, 131). This political
class was therefore portrayed as being fundamentally antagonistic to the
interests of the ordinary people (Mazzoleni and Skenderovic 2007, 93;
Skenderovic 2009, 160). In Favero's interpretation:

> In a true populist manner, he repeatedly criticised the political
> elites in Bern who allegedly cared more for their own benefits than
> for Swiss citizens. To convey these messages to his followers, Blocher
> regularly uses the Albisgüetli Convention to explain "what is going on
> behind the scenes in Bern to abolish Switzerland." The populist
> juxtaposition of 'us' (the good citizens) versus 'them' (the *classe
> politique*, the EU) clearly increased his charismatic appeal and the
> persuasiveness of his message. (Favero 2022, 489)

In contrast to these "power-loving system parties" (cited in Bernhard,
Kriesi, and Weber 2015, 133), Blocher claimed that it was the true and
sole representative of ordinary people's interests (Mazzoleni and
Skenderovic 2007, 93; Favero 2021, 254). As he put it: "We shall give
this people a voice, while others increasingly crowd out this voice!
Wherever a gap opens up between the interests of the citizens and the
'political class', we shall be the party of the citizen" (cited in
Bernhard, Kriesi, and Weber 2015, 134) (OTH_POLCLASS = 3). Notably,
Blocher managed to maintain this anti-establishment protest stance even
while the SVP was a member of the governing coalition (Mazzoleni 2013,
243).

The SVP's anti-immigration attitude has been one of the main
programmatic element of its success under Blocher (Antonuk 2000, 23). It
accused asylum seekers of abusing the system and threating the security
of citizens (Church 2000, 218; Mazzoleni 2013, 246) (OTH_IMMIGRANTS =
3). In a number of ways this opposition to immigration has included
xenophobic and racist components, as the party predominantly opposed
non-European immigrants (Mazzoleni and Skenderovic 2007, 94). In the
most notorious instance, the SVP's 2007 election campaign included
posters of white sheep kicking black sheep out of the country under the
slogan "For More Security" (Michel 2015, 410). The party has also
launched a popular initiative against the construction of Islamic
minarets in 2009, and included in its platform its stance against
"growing Islamisation" in 2011 (Mazzoleni 2013, 249). Blocher has also
been accused of trying to "harness Swiss resentment at Jewish
organizations" attempting to seek reparations for Swiss Banks'
activities during the Holocaust (Marcus 2000, 36). We've coded the party
3 on OTH_ETHNIC.

Opposition to European integration was the issue that initially brought
Blocher to prominence in the early 1990s (Church 1996a, 13; McGann and
Kitschelt 2005, 154), and under his leadership the SVP became strongly
anti-EU (Caramani 1996, 135). He presented the Swiss nation and its
sovereignty as being threated from abroad, against which the SVP was the
last line of defence (Mazzoleni and Skenderovic 2007, 93; Bernhard,
Kriesi, and Weber 2015, 125). This included an attack against domestic
*heimatmiide Parteien* (parties tired of their home country) (Caramani
1996, 132) (OTH_FOREIGN = 3). The party included no major economic
component in its anti-elitism (Bernhard 2017, 514) (OTH_FINANCIAL = 1),
nor any opposition to the military (OTH_MILITARY = 1).

Owing to its strong economic neo-liberalism (Afonso and Papadopoulos
2015, see; Church 2000, 218) and the salience of its cultural nativism
the party is generally considered far-right (Antonuk 2000, 24)
(LRPOSITION = FR). Blocher's charisma is routinely cited in the
literature as a critical part of the party's image and success under his
leadership (Church 1996b, 641; Popper 1999, 12; Favero 2022), and
coupled with the significant personal financial resources that he
brought to the party (Church 2000, 217), the SVP "was built in a
decisive way around its leader" (Mazzoleni 2013, 240). However, the
party has always had a strong base and numerous factions opposed to
Blocher (Favero 2021), meaning it doesn't' quite qualify for a 3 on
OTH_CHARISMA (= 2). Several scholars have emphasised that the party was
not a threat to liberal democratic norms -- and on the contrary that it
was extremely defensive of the Swiss political system and the
constitution (Church 2000, 227; McGann and Kitschelt 2005, 154). We have
coded the party 2 on INSIDER for its duration in the dataset given that
it had been in coalition governments since the 1950s.

**References**

Afonso, Alexandre, and Yannis Papadopoulos. 2015. 'How the Populist
Radical Right Transformed Swiss Welfare Politics: From Compromises to
Polarization'. *Swiss Political Science Review* 21 (4): 617--35.

Antonuk, Beth E. 2000. 'Immigration and the Political Shift to the Right
in Austria and Switzerland'. *Perspectives on Business and Economics*.

Bernhard, Laurent. 2017. 'Three Faces of Populism in Current
Switzerland: Comparing the Populist Communication of the Swiss People's
Party, the Ticino League, and the Geneva Citizens' Movement'. *Swiss
Political Science Review* 23 (4): 509--25.

Bernhard, Laurent, Hanspeter Kriesi, and Edward Weber. 2015. 'The
Populist Discourse of the Swiss People's Party'. In *European Populism
in the Shadow of the Great Recession*, edited by Hanspeter Kriesi and
Takis S. Pappas, 123--37. Colchester: ECPR Press.

Betz, Hans-Georg. 1994. *Radical Right-Wing Populism in Western Europe*.
Edited by Hans-Georg Betz. London: Palgrave Macmillan UK.
https://doi.org/10.1007/978-1-349-23547-6_1.

Caramani, Daniele. 1996. 'The Swiss Parliamentary Election of 1995'.
*Electoral Studies* 15 (1): 128--38.

Church, Clive H. 1989. 'The Swiss Way of Change: Politics since the 1987
Election'. *The World Today* 45 (7): 117--21.

---------. 1996a. 'The Paradoxical Europeanisation of Switzerland'.
*European Business Journal* 8 (2): 9--17.

---------. 1996b. 'The Swiss Elections of 1995: Real Victors and Real
Losers at Last?' *West European Politics* 19 (3): 641--48.

---------. 2000. 'The Swiss Elections of October 1999: Learning to Live
in More Interesting Times'. *West European Politics* 23 (3): 215--30.

Favero, Adrian. 2021. 'Rootedness, Activism, and Centralization: The
Case of the Swiss People's Party'. *Politics and Governance* 9 (4):
252--62.

---------. 2022. 'Charisma in Right-Wing Populism: Comparing the View of
the Leader and Followers within the Swiss People's Party'. *Swiss
Political Science Review* 28 (3): 477--95.

Husbands, Christopher T. 2000. 'Switzerland: Right-Wing and Xenophobic
Parties, from Margin to Mainstream?' *Parliamentary Affairs* 53 (3):
501--16.

Kobach, Kris W. 1993. 'Recent Developments in Swiss Direct Democracy'.
*Electoral Studies* 12 (4): 342--65.

Marcus, Jonathan. 2000. 'Exorcising Europe's Demons: A Far-Right
Resurgence?' *Washington Quarterly* 23 (4): 31--40.

Mazzoleni, Oscar. 2013. 'Between Opposition and Government: The Swiss
People's Party'. In *Exposing the Demagogues: Right-Wing and National
Populist Parties in Europe*, edited by Karsten Grabow and Florian
Hartleb, 237--59. Brussels: Konrad Adenauer Stiftung.

Mazzoleni, Oscar, and Damir Skenderovic. 2007. 'The Rise and Impact of
the Swiss People's Party: Challenging the Rules of Governance in
Switzerland'. In *The Extreme Right Parties and Power in Europe*, edited
by Pascal Delwit and Philippe Poirier, 85--116. Brussels: Editions de
l'Université de Bruxelles.

McGann, Anthony J., and Herbert Kitschelt. 2005. 'The Radical Right in
the Alps: Evolution of Support for the Swiss SVP and Austrian FPÖ'.
*Party Politics* 11 (2): 147--71.

Michel, Noémi. 2015. 'Sheepology: The Postcolonial Politics of Raceless
Racism in Switzerland'. *Postcolonial Studies* 18 (4): 410--26.

Popper, Nathaniel. 1999. 'Swiss Voice'. *Harvard International Review*
21 (4): 12--13.

Rose, Richard. 2000. 'The End of Consensus in Austria and Switzerland'.
*Journal of Democracy* 11 (2): 26--40.

Skenderovic, Damir. 2007. 'Immigration and the Radical Right in
Switzerland: Ideology, Discourse and Opportunities'. *Patterns of
Prejudice* 41 (2): 155--76.

---------. 2009. *The Radical Right in Switzerland: Continuity and
Change, 1945-2000*. New York: Berghahn Books.

