---
title: Türkiye
subtitle: |-
  Date range: 1983-2020
  <br>
  Since the foundation of the Turkish Republic in 1924 there has been a
  sharp political cleavage in Türkiye between Kemalist liberal secularists
  (including most of the civil service, military and judiciary) and the
  more religious bulk of the population in rural inland areas. That state
  institutions have so consistently sought to suppress Islamist politics
  has provided a context in which Islamist parties can easily paint
  populist "anti-system" narratives about themselves and the political
  class (Cizre and Çınar 2003, 310), and it often seems that Islamism is
  more relevant as a token of this social division than as a force of
  genuine religiosity or theocracy (M. H. Yavuz 1997, 74). This pattern
  can be traced in Türkiye through the Democrat Party, the National Order
  Party, the National Salvation Party and since 1980 through the Welfare
  Party, the Virtue Party, the Felicity Party and the Justice and
  Development Party -- each of which was linked in some way to its
  predecessor (often including leaders and structures).
title-block-banner: yes

---

# Case notes

## The Welfare Party

The Welfare Party (*Refah Partisi*, WP) was led by veteran Islamist
politician Necmettin Erbakan, who had previously led several other
Islamist parties which were banned by constitutional courts. The party
emerged in the late 1980s and won a plurality in the 1995 general
elections. According to Ayata, the narratives of the WP stressed the
role of western imperial powers in the humiliation and backwardness of
rural Turkish Muslims, and advocated Islamism as the only redemptive
path (Ayata 1996, 54). The party's "Just Order" platform actually
focused heavily on social justice and the plight of the poor -- even
more than leftist parties -- rather than on theocratic advocacy, and
built on the supposed contempt that the coastal and urban liberal elite
had for the masses (Ayata 1996, 54; White 1997, 26). That said, we have
seen no evidence that the wealthy themselves were a class of "other"
that the party countered, and it seems to have left some discursive
space for capitalist accumulation in its literature (Onis 1997, 753). It
also had significant connections to Islamic business elites (Onis 1997,
758; Gülalp 2001, 439) (OTH_ECONOMIC = 1). According to Onis (Onis 1997,
753) the party's rhetoric against the West was "relentless", and it
consistently accused the established parties of being "imitators of the
West" (OTH_FOREIGN = 3)

In the lead up to the 1995 election, Erbakan refused to share a debate
stage with the major party leaders on the grounds that they were all
imitators of the West (Onis 1997, 755), continuing its hard
anti-political class rhetoric that built a "WP vs the Rest" narrative
(OTH_POLCLASS = 3). While the party connected Islam with the homogenous
"people" (M. H. Yavuz 1997, 67), we've coded it 1 on OTH_ETHNIC as it
actually had a pan-ethnic identity and sought votes from Kurdish areas.
Despite the fact that the military has been so closely involved in the
secular liberal political establishment that WP opposed, we cannot see
any evidence that it constituted an "other" for the party (OTH_MILITARY
= 1). It should also be stressed that the combination of religious
identity and leftish economic platforms make the party very difficult to
characterise on a L-R scale (Onis 1997, 753) -- for now we've coded it
as R. The party had no prior position in power (INSIDER = 1) and there
is no evidence that the charisma of its leaders was particularly
relevant to its populist discourse (CHARISMA = 1).

## The Virtue Party

The Virtue Party (*Fazilet Partisi* VP) was created by the Welfare Party
leadership when it was banned by a constitutional court decision in
1997. While the Erbakan and several other leaders could not lead the new
party, they had a significant say over its direction and virtually
controlled it. However, the VP sharply shifted its tone from the WP,
most notably by enthusiastically embracing EU membership and removing
the anti-Western discourse from its ideology (OTH_FOREIGN = 1). This was
arguably because it saw EU legal protections as the only thing that
could curb the Turkish state's continual intervention against Islamist
political parties (Taniyici 2003, 476). As with WP, we've seen no
evidence of ethnocentric rhetoric (OTH_ETHNIC = 1). The party also
sought to soften its Islamist image, indicating a relaxing of various
platforms and promoting several women into its leadership to show its
more secular credentials (Mecham 2004, 348). It is not clear however
that there was any softening of its anti-political class rhetoric
(OTH_POLCLASS = 3). As Mecham puts it:

> Virtue found its new voice as an opposition party by shifting from the
> old claim that Turkey was not religious enough to the claim that
> Turkey was not democratic enough. Both charges attempted to frame the
> Turkish regime as illegitimate to some degree, but the charges of poor
> democracy sought to engage the secular democratic system on its own
> terms (Mecham 2004, 346).

That said, the variation in all of these variables is tricky to code
because many in Türkiye saw the party as a continuation of Welfare, and
considered its softening of rhetoric to be more strategic than genuine.
The party was split between Erbakan loyalists and reformers (including
Abdullah Gul and Recep Tayyip Erdogan), who became increasingly
antagonistic before the 1999 election (Mecham 2004, 347) and ended up
forming separate parties after Virtue was banned in 2001 (Felicity Party
and Truth and Justice respectively).

## Justice and Development Party

The Justice and Development Party (*Adalet ve Kalkınma Partisi*, AKP)
was founded in 2001 by former Istanbul mayor Recep Tayyip Erdogan, then
one of the most popular politicians in the country. The name "AK Party"
utilised the Turkish word *ak*, which means both "white" and "clean",
symbolising the party's commitment to renew the impure and corrupt
Turkish state (Mecham 2004, 349). It initially maintained Virtue's more
moderate expressions of Islamist identity (Dagi 2008, 29), but shed the
Welfare/Virtue Islamic logos in favour of a simple light bulb, and made
a point of recruiting more women into leadership positions (Mecham 2004,
353). Erdogan and the AKO have remained the dominant forces in Turkish
politics since it took power in the 2002 elections with 34.3% of the
vote.

Attempting to capture the more mainstream centre-right vote, AKP
campaigned against corruption in the Turkish state and advocated
religious liberty (maintaining the importance of Islam as a social
institution) while accepting the secular principles of the state and
shedding some its "anti-system" aura. However Erdogan's Welfare
background and several comments he made in the 2002 race meant that
anti-political class rhetoric was still a significant part of the
party's identity. In the party's 2002 election campaign, for example,
Erdogan said:

> My story is the story of this people. Either the people will win and
> come to power, or the pretentious and oppressive minority estranged
> from the reality of Anatolia and looking over it with disdain will
> remain in power. The authority to decide on this belongs to the
> people. Enough is enough, sovereignty belongs to the people (Aytaç and
> Öniş 2014, 45).

In its first election we have decided to code it 2 on the OTH_POLCLASS
variable (see Çarkoğlu 2002, 39; Gürsoy 2021, 166).

In its early days the party was stridently pro-EU membership -- more so
than Virtue. Despite this, various personal legacies of Erdogan and
Gül's time in Welfare/Virtue -- Erdogan is on record in 1994 saying that
one could either be a secularist or a Muslim, but not both (see Mecham
2004, 247) -- meant that the Islamist brand was still somewhat
established, and the party at this point was still essentially an
Islamist protest party in the Welfare tradition. Several scholars have
pointed out the nativist (Kaya, Robert, and Tecmen 2020, 363) and
ethnically exclusionary nature of this majoritarian narrative (Arat-Koç
2018; Gürsoy 2021). For this the party deserves a 2 for OTH_ETHNIC.
Opposition to immigrants, however, have not been an important component
of AKP's discourse (Gürsoy 2021, 161) (OTH_IMMIGRANTS =1). According to
Gürsoy "in the early years of AKP rule, 'the elite' meant most
fundamentally the secular military and judicial establishment."
(OTH_MILITARY = 3 from 2002), but after 2007 foreign enemies were
elevated to the primary enemies of the people. By the 2018 elections,
Erdogan and the AKP were characterising their domestic rivals as the
"domestic collaborators" of Türkiye's foreign enemies (Sözen 2019, 12;
see also Gürsoy 2021, 166) (OTH_FOREIGN = 1 in 2002, 3 from 2007).

It is difficult to pinpoint the time when AK started veering off into a
sharper populist tone with more defined denemies. We have settled on the
2007 snap election which followed the crisis of electing the president
(done by parliament). Here it seems that threats of intervention by the
military angered Erdogan who responded by leveraging his now
well-established base of popular support against them explicitly in a
"people/nation" vs. 'secularists/institutions" narrative during the
campaign (Dinçşahin 2012; Elçi 2019, 5). Note that some scholars
(Yabanci 2016, 599) suggest that the constitutional referendum in 2010
and the 2013 Gezi park protests as the key turning point. Whatever the
precise turning point, by the 2015 elections Erdogan had transitioned to
a clearer populist anti-elite discourse on a number fronts, criticising
all other politicians, media intellectuals as part of an elite tied to
previous corruption and maladministration, and sharply criticising the
western media, particularly over their criticism of the 2013 Gezi
protests (Erçetin and Erdoğan 2018) (OTH_POLCLASS = 3 2007-). This was
packaged in his rhetoric around the "New Turkey" (post constitutional
reforms) in which the Kemalist establishment was cast as remnants of the
"Old Turkey" (Selçuk 2016, 577). According to Selçuk political opponents
were increasingly portrayed as "traitors to the nation" or "coup
sympathisers" (the latter after the 2016 coup attempt) (Selçuk 2016; see
also Gürsoy 2021, 166--67).

Liberal democratic norms are also difficult to track with AK. We think
the best point to elevate LIBDEMNORMS to a 2 is the 2010 period, where
according to Yabanci attacks on the media in particular escalated
(Yabanci 2016). We have further elevated this to a 3 after the coup
attempt in 2016. Further research into AK should determine whether its
religious populist rhetoric has increased back to the scale of Welfare
in the 1990s. The literature suggest that Erdogan has always been the
charismatic central figure in the representation of the party (Elçi
2019, 5; Kaya, Robert, and Tecmen 2020, 370; Selçuk, Hekimci, and Erpul
2019; Sawae 2020, 261) (CHARISMA = 3). While the party has a complicated
policy profile, we agree with the general view of the literature that it
is a right-wing party to its cultural majoritarianism and nationalism
(LRPOSITION = R). We have coded AK 1 for INSIDER in 2002, and 3 for
every subsequent election after Erdogan became president.

## The Young Party

The Young Party (*Genç Parti*, GP), was a nationalist party built around
businessman and media mogul Cem Uzan, who railed against the
establishment and promised impossible benefits to voters (Çarkoğlu 2002,
39). He is generally considered populist (Robins 2003, 550) and
"Berlusconi-like" (Kaya 2003, 208) in the literature. GP only mustered
7.3% of the vote in 2002, below the 10% needed to enter parliament in a
race dominated by the ascendency of the AKP. He returned in 2007 but
only won 3% of the vote.

All sources suggest Uzan was extremely hostile to the political
establishment (Çarkoğlu 2002, 39), and is occasionally considered
"anti-system" (Kaya 2003, 208) (OTH_POLCLASS = 3). The party was also
considered "ultra-nationalist" (Başlevent, Ki̇rmanoğlu, and Şenatalar
2005, 548; Baykan 2018) and hostile to the IMF (in the context of
Türkiye's economic crisis) (Rubin 2005), which Uzan claimed was
colonizing Türkiye (Gökçen, Homer, and Oates 2006, 266). He was also
highly critical of the IMF, World Bank, the USA, and the EU (Kaya 2003,
208; Küçük 2018, 578), whom he considered opposed to the nation. For
this we have labelled the party 2 on OTH_FOREIGN, but further research
should determine the precise nature of this nationalist rhetoric. A
backstory here is Uzan's commercial dispute with Motorola, which
featured heavily in both the media and his campaign. We've seen no
evidence in the secondary literature that for GP to register on the
OTH_ETHNIC or OTH_IMMIGRANTS variables (both = 1).

GP was seen as a nationalist competitor to the Nationalist Action Party
(Robins 2003, 550), but also toward the centre of the spectrum due to
the something-for-everyone nature of its policies (Çarkoğlu 2002, 39;
Carcoglu 2006, 165). The literature variously considers it "right wing"
(Muftuler-Bac 2003, 428), "conservative nationalist" (Kaya 2003, 208)
and "centre right" (Küçük 2018, 577). We have labelled it centre-right
(LRPOSITION = CR). In place of any considered policy agenda, the GP is
universally considered a "one-man show" (Çarkoğlu 2002, 39) dominated by
Cem's flamboyant personality and reliant on his media organisation
(CHARISMA = 3). According to Çarkoğlu, Uzan's campaign violated several
electoral laws with impunity (Çarkoğlu 2002, 39), and although this
evidence could be corroborated we've coded it 2 on LIBDEMNORMS.

## Not included

The **Nationalist Action Party** (*Milliyetçi Hareket Partisi*, MHP) is
a very difficult party to code by our definitions. It is a radically
nationalist party, socially conservative, statist, anti-globalisation
and critical to both European and Russian threats to the Turkish
national interest. Its traditional enemies are foreigners and their
domestic collaborators, who include leftists, Kurds, Alevi Muslims, and
liberal intellectuals (M. Yavuz 2002, 206). The party has paramilitary
links, and has celebrated various former militia members (Cınar and
Arıkan 2002, 73). Its radical nationalism has a Manichean proportion as
it has discussed threats to the nation and the party's role in saving
it, and in doing so it has generally spoken for the true Turkish people
in a holistic sense (Erdoğan and Uyan-Semerci 2020). It has also used
acerbic rhetoric against opponents, whom it has accused of "treason"
among other things (Selçuk, Hekimci, and Erpul 2019, 556). However we
have not found enough evidence that the party was ever opposed to an
"elite" governing the country against the people's interests. Instead,
the party has considered itself an ally of the state. Erdoğan and
Uyan-Semerci, who have looked specifically into the potential populism
of the MHP under long-time leader Devlet Bahçeli, conclude simply that
"For Bahçeli, the elites of Türkiye are not among the usual enemies of
the nation" (Erdoğan and Uyan-Semerci 2020). On this basis we've elected
not to include the BHP in the dataset, as it appears to be far right but
not populist by our definition. Further research should clarify this.

**References**

Arat-Koç, Sedef. 2018. 'Culturalizing Politics, Hyper-Politicizing
"Culture":'White'vs."Black Turks" and the Making of Authoritarian
Populism in Turkey'. *Dialectical Anthropology* 42 (4): 391--408.

Arikan, E. Burak. 2002. 'Turkish Ultra--Nationalists under Review: A
Study of the Nationalist Action Party'. *Nations and Nationalism* 8 (3):
357--75. https://doi.org/10.1111/1469-8219.00055.

Ayata, Sencer. 1996. 'Patronage, Party, and State: The Politicization of
Islam in Turkey'. *Middle East Journal* 50 (1): 40--56.

Aytaç, S. Erdem, and Ziya Öniş. 2014. 'Varieties of Populism in a
Changing Global Context: The Divergent Paths of Erdoğan and
Kirchnerismo'. *Comparative Politics* 47 (1): 41--59.

Başlevent, Cem, Hasan Ki̇rmanoğlu, and Burhan Şenatalar. 2005. 'Empirical
Investigation of Party Preferences and Economic Voting in Turkey'.
*European Journal of Political Research* 44 (4): 547--62.
https://doi.org/10.1111/j.1475-6765.2005.00238.x.

Baykan, Toygar Sinan. 2018. *The Justice and Development Party in
Turkey: Populism, Personalism, Organization*. Cambridge University
Press.

Carcoglu, Ali. 2006. 'The New Generation Pro-Islamists in Turkey: Bases
of the Justice and Development Party in Changing Electoral Space'. In
*The Emergence of a New Turkey: Democracy and the AK Parti*, by Harkan
Yavuz, 19:160--80. Salt Lake City: University of Utah Press.
https://academic.oup.com/jis/article/19/1/128/681331.

Çarkoğlu, Ali. 2002. 'Turkey's November 2002 Elections: A New
Beginning?' *Middle East Review of International Affairs* 6 (4): 30--41.

Cizre, Ümit, and Menderes Çınar. 2003. 'Turkey 2002: Kemalism, Islamism,
and Politics in the Light of the February 28 Process'. *South Atlantic
Quarterly* 102 (2--3): 309--32.
https://doi.org/10.1215/00382876-102-2-3-309.

Cınar, Alev, and Burak Arıkan. 2002. 'The Nationalist Action Party:
Representing the State, the Nation or the Nationalists?' *Turkish
Studies* 3 (1): 25--40. https://doi.org/10.1080/714005706.

Dagi, Ihsan. 2008. 'Islamist Parties and Democracy: Turkey's AKP in
Power'. *Journal of Democracy* 19 (3): 25--30.
https://doi.org/10.1353/jod.0.0015.

Dinçşahin, Şakir. 2012. 'A Symptomatic Analysis of the Justice and
Development Party's Populism in Turkey, 2007--2010'. *Government and
Opposition* 47 (4): 618--40.
https://doi.org/10.1111/j.1477-7053.2012.01377.x.

Elçi, Ezgi. 2019. 'The Rise of Populism in Turkey: A Content Analysis'.
*Southeast European and Black Sea Studies* 19 (3): 387--408.

Erçetin, Tuğçe, and Emre Erdoğan. 2018. 'How Turkey's Repetitive
Elections Affected the Populist Tone in the Discourses of the Justice
and Development Party Leaders'. *Philosophy & Social Criticism* 44 (4):
382--98. https://doi.org/10.1177/0191453718755207.

Erdoğan, Emre, and P. Uyan-Semerci. 2020. 'Against All Winds: The
Populism--Nationalism Axis in the Rhetoric of the Nationalist Action
Party'. *Reflektif Journal of Social Science* 1 (1): 81--105.

Gökçen, M. Sinan, Sean Homer, and Caroline J. Oates. 2006. 'Consuming
Nationalism: Contemporary Nationalism in Turkish Popular Culture'. In
*Proceedings of the 1st Annual SEERC Doctoral Student Conference*,
261--73.

Gülalp, Haldun. 2001. 'Globalization and Political Islam: The Social
Bases of Turkey's Welfare Party'. *International Journal of Middle East
Studies* 33 (3): 433--48.

Gürsoy, Yaprak. 2021. 'Moving beyond European and Latin American
Typologies: The Peculiarities of AKP's Populism in Turkey'. *Journal of
Contemporary Asia* 51 (1): 157--78.

Kaya, Ayhan. 2003. '«Unity in Diversity»: Ethnic/Cultural Diversity in
Turkey and the European Union'. *CEMOTI, Cahiers d'Études Sur La
Méditerranée Orientale et Le Monde Turco-Iranien* 36 (1): 199--220.

Kaya, Ayhan, Max-Valentin Robert, and Ayşe Tecmen. 2020. 'Populism in
Turkey and France: Nativism, Multiculturalism and Euroskepticism'.
*Turkish Studies* 21 (3): 361--91.

Küçük, Mine Nur. 2018. 'Conceptions of 'the International'beyond the
Core: Turkey in the Post-Cold War Era'. *Turkish Studies* 19 (4):
571--92.

Mecham, R. Quinn. 2004. 'From the Ashes of Virtue, a Promise of Light:
The Transformation of Political Islam in Turkey'. *Third World
Quarterly* 25 (2): 339--58.

Muftuler-Bac, Meltem. 2003. 'The New Face of Turkey: The Domestic and
Foreign Policy Implications of November 2002 Elections'. *East European
Quarterly* 37 (4): 421--38.

Onis, Ziya. 1997. 'The Political Economy of Islamic Resurgence in
Turkey: The Rise of the Welfare Party in Perspective'. *Third World
Quarterly* 18 (4): 743--66. https://doi.org/10.1080/01436599714740.

Robins, Philip. 2003. 'Confusion at Home, Confusion Abroad: Turkey
between Copenhagen and Iraq'. *International Affairs* 79 (3): 547--66.

Rubin, Michael. 2005. 'Green Money, Islamist Politics in Turkey'.
*Middle East Quarterly*.

Sawae, Fumiko. 2020. 'Populism and the Politics of Belonging in
Erdoğan's Turkey'. *Middle East Critique* 29 (3): 259--73.
https://doi.org/10.1080/19436149.2020.1770443.

Selçuk, Orçun. 2016. 'Strong Presidents and Weak Institutions: Populism
in Turkey, Venezuela and Ecuador'. *Southeast European and Black Sea
Studies* 16 (4): 571--89. https://doi.org/10.1080/14683857.2016.1242893.

Selçuk, Orçun, Dilara Hekimci, and Onur Erpul. 2019. 'The Erdoğanization
of Turkish Politics and the Role of the Opposition'. *Southeast European
and Black Sea Studies* 19 (4): 541--64.

Sözen, Yunus. 2019. 'Competition in a Populist Authoritarian Regime: The
June 2018 Dual Elections in Turkey'. *South European Society and
Politics* 24 (3): 287--315.

Taniyici, Saban. 2003. 'Transformation of Political Islam in Turkey:
Islamist Welfare Party's Pro-EU Turn'. *Party Politics* 9 (4): 463--83.
https://doi.org/10.1177/135406880394003.

White, Jenny B. 1997. 'Pragmatists or Ideologues? Turkey's Welfare Party
in Power'. *Current History* 96 (606): 25--30.

Yabanci, Bilge. 2016. 'Populism as the Problem Child of Democracy: The
AKP's Enduring Appeal and the Use of Meso-Level Actors'. *Southeast
European and Black Sea Studies* 16 (4): 591--617.
https://doi.org/10.1080/14683857.2016.1242204.

Yavuz, M. 2002. 'The Politics of Fear: The Rise of the Nationalist
Action Party (MHP) in Turkey'. *The Middle East Journal* 56 (March):
200--221.

Yavuz, M. Hakan. 1997. 'Political Islam and the Welfare (Refah) Party in
Turkey'. *Comparative Politics* 30 (1): 63--82.
https://doi.org/10.2307/422193.
