---
title: Zambia
subtitle: |-
  Date range: 1991-2020
  <br>
title-block-banner: yes

---

# Case notes

## Patriotic Front

The Patriotic Front (PF) was created by veteran politician Michael Sata
in 2001 after he fell out with the governing Movement for Multi-Party
Democracy (MMD) party over presidential succession. Popularly known as
"King Cobra" for his venomous attacks on rival politicians (Resnick
2013, 62), Sata succeeded in rallying voters in urban and Bemba-speaking
regions who were frustrated with the effects of the MMD's economic
liberalisation (Larmer and Fraser 2007, 612). Sata and the PF stood in
presidential and legislative elections in 2001 without success, but
broke out in 2006 with 29.4% and 22.9% in the presidential and
legislative elections respectively, placing second in both. Sata
narrowly lost the election to succeed the Levy Mwanawasa in 2008 after
the latter died in office, but then won in 2011 and assumed the
presidency. Sata himself died in office in 2014, and the party chose
Edgar Lungu to succeed him. Lungu won re-election in 2015.

Sata and the PF are frequently considered populist in the Zambia
literature. While a lot of this relates to policy stances, there is
enough analysis to suggest that Sata's early elections (2001 and 2006)
practiced a version of populist discourse that is compatible with our
minimum definition. This revolved around linking the economic grievances
experienced by his target audience with the corruption of the government
(Paget 2014; Larmer and Fraser 2007, 613). In Sichuwa's words, he
"presented his political competitors, represented by the incumbents
Mwanawasa and subsequently Banda, as colluding with mining companies to
exploit ordinary workers" (Sishuwa 2021, 1064) (OTH_POLCLASS = 3). Sata
also employed a "highly emotional" (Hamusokwe and Mambwe 2021, 5) and
"confrontational" style (Cheeseman and Hinfelaar 2010, 64), that
deployed "sheer rudeness" towards people in power to construct a radical
and subversive counternarrative (Larmer and Fraser 2007, 613).

While this qualifies Sata and the PF for inclusion in 2006, subsequent
elections are more difficult. After Mwanawasa died in 2008, Sata
appeared to soften his rhetoric to the extent of selling himself as "a
member of the political establishment well-placed to offer continuity
and stability" (Cheeseman and Hinfelaar 2010, 67). His own deteriorating
health also reduced his ability to play the antagonistic "strongman"
figure of his earlier campaigns, and by 2011 "any idea that Sata
represented a radical threat depended on memories of his performance in
2006 rather than any repeat of it" (Fraser 2017, 464--65). The
literature also suggests that Lungu failed to emulate Sata's populist
narrative and performance (Hamusokwe and Mambwe 2021, 7; Fraser 2017,
457), and that by the time he took over the PF's populism had been
"watered down over time" (Hern 2020, 73). For these reasons we have not
included Sata, Lungu, or the PF in the dataset after the 2006 election.

Despite his role in the privatisation processes within the MMD, Sata's
narrative in 2006 championed the cause of poor workers (Larmer 2005,
42), the enemy of whom were, in Larmer and Fraser's words, a "corrupt
alliance between domestic political and business networks and a set of
international sponsors" (Larmer and Fraser 2007, 613). His hostility
towards foreign-owned mines and businesses has been considered
xenophobic and nationalistic by many scholars (see Simutanyi 2010, 11;
Larmer and Fraser 2007, 628; Cheeseman and Hinfelaar 2010, 67; Hess and
Aidoo 2014). He was particularly harsh against Chinese investors, whom
he called "infestors" (Hamusokwe and Mambwe 2021, 4) and agents of
"Chinese colonialism" (Uzar 2017, 297). Notably, this hostility related
to smaller scale Chinese and Indian shop owners in Lusaka (Resnick 2013,
79), claiming at one point that "The markets are for Zambians" (Larmer
and Fraser 2007, 628). We consider this enough to code Sata and the PF 3
on both OTH_ECONOMIC and OTH_ETHNIC. On the latter, there is also
evidence that Sata's rhetoric played into domestic ethnic divisions
relating to his Bemba-speaking base, claiming, for example, that
Mwanawasa's anti-corruption in initiatives were an attack on Bemba
speakers (Sishuwa 2023, 447). Given the centrality of international
financial institutions and foreign governments in his rhetoric (Larmer
and Fraser 2007, 613), we've also coded Sata and the PF 3 on
OTH_FOREIGN. We've seen no evidence to code above 1 for OTH_IMMIGRANTS
or OTH_MILITARY.

The literature frequently emphases the "charismatic" nature of Sata's
political appeal (Hamusokwe and Mambwe 2021, 1; Resnick 2013; Simutanyi
2010, 11), and that the PF was built around him and controlled by him
(Larmer and Fraser 2007, 627; Cheeseman and Hinfelaar 2010, 75; Fraser
2017, 458) (CHARISMA = 3). While Sata's tone was in many ways critical
of liberalisation and its effects, the PFs policy was only marginally
left leaning and its manifesto committed to "maintain an open, liberal
macro-economic environment" alongside its more progressive policies
around social services and the party's "anti-neo-liberal rhetoric,"
(Larmer and Fraser 2007, 626, 631). We've coded it CL on LRPPOSITION,
but this could be revisited. Despite his harsh criticism of those in
power, Sata was very much a member of the Zambian political
establishment, having served in high profile offices in multiple
governments since Independence (Burnell 2002, 1110; Larmer 2005, 42)
(INSIDER = 2).

Long before forming the PF, Sata had an established association with
vigilantes (Larmer and Fraser 2007, 624), and he threated to bring back
the "militancy" of the colonial past against contemporary rivals in the
2005 (Uzar 2017, 297). According to Larmer and Fraser, during the 2006
campaign pro-Sata minibuses in urban areas

> represented a threatening, lawless presence... When MMD cadres
> attempted to increase their visibility in cities they were soundly
> chased from the streets. Indeed, on one occasion the President was
> unable to travel through the capital as PF cadres blocked various
> routes with minibuses and threatened to stone his motorcade. (Larmer
> and Fraser 2007, 629)

Sata also rejected the results of elections (Sishuwa 2023, 432), and
threated to set up a "parallel government" that would make governance
impossible (Cheeseman and Hinfelaar 2010, 65). While more research could
confirm how much this differs from the common practices in Zambian
politics, but for now we have coded Sata and the PF as 3 on LIBDEMNORMS
on the basis of this evidence.

## Not included 

The **Movement for Multi-Party Democracy** (MMD) was a broad movement
that opposed the single party United National Independence Party (UNIP)
government and long-term president Kenneth Kaunda in the 1991 elections.
The MMD was initially led by the chairman of the Zambia Congress of
Trade Unions Frederick Chiluba, who defeated Kaunda in a landslide and
went on to win the 1996 election too. Chiluba's 1991 campaign has
occasionally been classified as populist in the literature (See for
example Makulilo 2013, 75; Vaughan 1999, 253; Larmer and Fraser 2007,
623). It is clear that the MMD campaigned heavily against the UNIP
*status quo* (Chikulo 1993, 91), and that Chiluba had a history of
broadly populist statements as a trade unionist (Bratton 1992, 85;
Baylies and Szeftel 1992, 86). However, we've not seen sufficient
evidence in the literature that this campaign or any other MMD campaign
was centred on a narrative that would fit our minimum definition of
populism. It seems instead that the MMD's 1992 campaign was a general
"change" campaign based on the slogan "the hour has come" (Ihonvbere
1995, 5; Helle and Rakner 2012, 9), driven by general discontent with
the outgoing UNIP government without a truly populist narrative against
it.

**References**

Baylies, Carolyn, and Morris Szeftel. 1992. 'The Fall and Rise of
Multi‐party Politics in Zambia'. *Review of African Political Economy*
19 (54): 75--91. https://doi.org/10.1080/03056249208703954.

Bratton, Michael. 1992. 'Zambia Starts Over'. *J. Democracy* 3: 81.

Burnell, Peter. 2002. 'Zambia's 2001 Elections: The Tyranny of Small
Decisions, "non-Decisions" and "Not Decisions"'. *Third World Quarterly*
23 (6): 1103--20. https://doi.org/10.1080/0143659022000036630.

Cheeseman, Nic, and Marja Hinfelaar. 2010. 'Parties, Platforms, and
Political Mobilization: The Zambian Presidential Election of 2008'.
*African Affairs* 109 (434): 51.

Chikulo, B.C. 1993. 'End of an Era: An Analysis of the 1991 Zambian
Presidential and Parliamentary Elections'. *Politikon* 20 (1): 87--104.
https://doi.org/10.1080/02589349308704989.

Fraser, Alastair. 2017. 'Post-Populism in Zambia: Michael Sata's Rise,
Demise and Legacy'. *International Political Science Review* 38 (4):
456--72. https://doi.org/10.1177/0192512117720809.

Hamusokwe, Basil, and Elastus Mambwe. 2021. 'Populism, Media and
Elections in Zambia: The Case of the Patriotic Front in the 2011 and
2016 Elections'. *RESEARCH REVIEW International Journal of
Multidisciplinary* 6 (12): 01--12.

Helle, Svein-Erik, and Lise Rakner. 2012. 'The Interplay between Poverty
and Electoral Authoritarianism: Poverty and Political Mobilization in
Zambia and Uganda'. *CMI Working Paper*.
https://open.cmi.no/cmi-xmlui/handle/11250/2474909.

Hern, Erin. 2020. 'Preferences without Platforms: How Voters Make
Choices in Zambia's Elections'. In *Democracy and Electoral Politics in
Zambia*, edited by Tinenenji Banda, O'Brien Kaaba, Marja Hinfelaar, and
Muna Ndulo, 69--93. Brill.
https://brill.com/display/book/edcoll/9789004430440/BP000003.xml?body=contentSummary-38296.

Hess, Steve, and Richard Aidoo. 2014. 'Charting the Roots of
Anti-Chinese Populism in Africa: A Comparison of Zambia and Ghana'.
*Journal of Asian and African Studies* 49 (2): 129--47.
https://doi.org/10.1177/0021909613479769.

Ihonvbere, Julius O. 1995. 'From Movement to Government: The Movement
for Multi-Party Democracy and the Crisis of Democratic Consolidation in
Zambia'. *Canadian Journal of African Studies / Revue Canadienne Des
Études Africaines* 29 (1): 1--25.
https://doi.org/10.1080/00083968.1995.10804370.

Larmer, Miles. 2005. 'Reaction & Resistance to Neo-Liberalism in
Zambia'. *Review of African Political Economy* 32 (103): 29--45.
https://doi.org/10.1080/03056240500120992.

Larmer, Miles, and Alastair Fraser. 2007. 'Of Cabbages and King Cobra:
Populist Politics and Zambia's 2006 Election'. *African Affairs* 106
(425): 611--37.

Makulilo, Alexander B. 2013. 'When\" Populists\" Become\" Unpopular\":
The Case of Three Presidents in Africa'. *The African Review: A Journal
of African Politics, Development and International Affairs*, 58--92.

Paget, Dan. 2014. 'Zambia: Dominance Won and Lost'. In *Party Systems
and Democracy in Africa*, edited by Renske Doorenspleet and Lia Nijzink,
148--67. London: Palgrave Macmillan UK.
https://doi.org/10.1057/9781137011718_8.

Resnick, Danielle. 2013. 'Urban Poverty and Party Populism in African
Democracies / Danielle Resnick, United Nations University, Helsinki.',
January.

Simutanyi, Neo. 2010. 'The 2008 Presidential Elections in Zambia:
Incumbency, Political Contestation and Failure of Political Opposition'.
In *IESE/CMI Conference on Election Processes, Liberation Movements and
Democratic Change in Africa, Maputo*, 9--11.
https://www.iese.ac.mz/lib/publication/proelit/Neo_Simutanyi.pdf.

Sishuwa, Sishuwa. 2020. '"Join Me to Get Rid of This President": The
Opposition, Civil Society and Zambia's 2011 Election'. In *Democracy and
Electoral Politics in Zambia*, edited by Tinenenji Banda, O'Brien Kaaba,
Marja Hinfelaar, and Muna Ndulo, 11--33. Brill.
https://brill.com/display/book/edcoll/9789004430440/BP000003.xml?body=contentSummary-38296.

---------. 2021. 'Roots of Contemporary Political Strategies:
Ethno-Populism in Zambia during the Late Colonial Era and Early 2000s'.
*Journal of Southern African Studies* 47 (6): 1061--81.
https://doi.org/10.1080/03057070.2021.1940602.

---------. 2023. 'Multi-Ethnic Vision or Ethnic Nationalism? The
Contested Legacies of Anderson Mazoka and Zambia's 2006 Election'.
*Canadian Journal of African Studies / Revue Canadienne Des Études
Africaines* 57 (2): 431--57.
https://doi.org/10.1080/00083968.2023.2196084.

Uzar, Esther. 2017. 'Contested Labour and Political Leadership: Three
Mineworkers' Unions after the Opposition Victory in Zambia'. *Review of
African Political Economy* 44 (152): 292--311.
https://doi.org/10.1080/03056244.2017.1345731.

Vaughan, Femi. 1999. 'Africa's Second Democratic Transition'. *Journal
